### ISSUE TITLE
Chat widget loses focus when opponent plays

### ISSUE THREAD

**Issue by massimiliano-leoni** [pychess/pychess#1000]
Since you are so good at fixing bugs, I'll post one more :D 

Well, more of a feature request: when I am playing online and I am chatting with my opponent, it he plays while I am typing the chat widget loses its focus and I have to click on it again to finish typing.

P.s. do I get a prize for the 1000th issue? :P :D

**Comment by gbtami** [comment]
I consider this as a bug.

P.s. of course!:smile: :beer:

**Comment by gbtami** [comment]
I can't reproduce this. Can you describe the case steps by step, and attach a screenshot, please?

**Comment by massimiliano-leoni** [comment]
Damn, I always forget to try it on the dev version before reporting XD
My bad, this only happens in a previous version.

Sorry for messing around :(
