### ISSUE TITLE
Animation is much slower now

### ISSUE THREAD

**Issue by Nakel** [pychess/pychess#1003]
I am absolutely in love with PyChess and have been using it for many months now, but there's something that I don't like in rc4. The animation is much slower and "realistic" now, and I just think it's bad.

The pieces moved around much better in rc3, and I'd like the developer to please replace the animation with the previous one. If you compare animation of pieces of rc3 and rc4, you'll realize that there's a difference; in rc3, pieces went to squares effortlessly and not fast and not slow either, but in rc4, the pieces feel somewhat "heavier" and move around slowly.

**Comment by gbtami** [comment]
Telling the truth I can't see the difference on my Linux boxes. What Linux distribution and DE are you using?
Can you create some short video captrures (maybe with your mobile) playing on rc3 and rc4 to let me show the difference, please?

**Comment by gbtami** [comment]
Ok, I have to revise my first comment. No need to create any video. rc4 drawing is about 2x - 2,5x slower than it was in rc3. Anyone can test this with uncommenting FPS measurement code in widgets/BoardView.py expose() method. Line 588-590 in rc3, 610-612 in rc4 (And turn print command into print function using () around the print message in rc4.)

Unfortunately I can't figure the reason. The drawing code is the same, except the minor changes needed by gtk2->gtk3 porting. If anyone has any ideas, please let as know!

**Comment by gbtami** [comment]
With latest commit it should be much better. Can you try it from git, please?

**Comment by Nakel** [comment]
After I pulled the newest git repo, I get the following error when I start pychess and it doesn't start at all;

Traceback (most recent call last):
  File "./pychess", line 157, in <module>
    chess_file, ics_host, ics_port)
  File "/home/gregor/pychess/lib/pychess/Main.py", line 501, in run
    pychess = PyChess(log_viewer, chess_file)
  File "/home/gregor/pychess/lib/pychess/Main.py", line 329, in **init**
    self.initGlade(log_viewer)
  File "/home/gregor/pychess/lib/pychess/Main.py", line 407, in initGlade
    label = subprocess.check_output(["git", "describe"])
  File "/usr/lib/python2.7/subprocess.py", line 544, in check_output
    raise CalledProcessError(retcode, cmd, output=output)
subprocess.CalledProcessError: Command '['git', 'describe']' returned non-zero exit status 128

The same error also comes on python3, what should I do?

**Comment by gbtami** [comment]
Fixed. Update your local git repo, please!

**Comment by Nakel** [comment]
After updating, now I get this;

  File "/home/gregor/pychess/lib/pychess/Main.py", line 409, in initGlade
    except CalledProcessError:
NameError: global name 'CalledProcessError' is not defined

Maybe it should be subprocess.CalledProcessError instead? I am still a beginner so I wouldn't know exactly.

**Comment by gbtami** [comment]
Yes, of course. Fixed.

**Comment by Nakel** [comment]
Rc4's animation is a little faster, only VERY little, and now very less "smooth". I still think rc3 is much better, by light years in animation. 

You should try to compare them yourselves.

**Comment by Nakel** [comment]
In rc4, after a few games, I notice that the pieces hang slightly or get somewhat interrupted in the middle when moving up the rank.

**Comment by gbtami** [comment]
@Nakel what distrib and package versions (listed in INSTALL) are you using?

**Comment by Nakel** [comment]
Ubuntu 12.04:

gnome-icon-theme: 3.4.0-0ubuntu1.1
python:  2.7.3-0ubuntu2.2
python-cairo: 1.8.8-1ubuntu3
python-gi: 3.2.2-1~precise
python-gi-cairo: 3.2.2-1~precise
gir1.2-glib-2.0: 1.32.0-1
gir1.2-gtk-3.0: 3.4.2-0ubuntu0.5

**Comment by gbtami** [comment]
@Nakel I have 12.04 (and 14.04 too) in VirtualBox, but I can't reproduce this :( What hardware RAM, CPU, VGA are you using? Are these problems the same with and without HINT/SPY analyzers?
Maybe you should consider upgrading to 14.04.
Btw. what FPS values you see with rc3 and git versions if you uncomment lines I mentioned before?

**Comment by gbtami** [comment]
In rc5 it should be better. FPS is better than with rc3 for me. Can you try it again, please?

**Comment by Nakel** [comment]
I can now confirm that the pieces move around much easily (in previewing a game and checking out the previous moves) and the animation is "somewhat" or much better than the previous one. However, another problem came out of this now; during a game, when I try to click a piece and then move it over to a square with my mouse, it is EXTREMELY slow and "staggered". For example, if I click a bishop and then use my mouse to move it to the g8 square, the bishop doesn't move easily to the square with my mouse, it moves extremely extremely slowly. Another example, when I click a queen and move the cursor to the e8 square from e1 quickly, the queen will take FOUR seconds to go to the e8 square.

**Comment by gbtami** [comment]
I can't reproduce this. Maybe this is the time to ask for creating some short video capture (maybe with your mobile) to demonstrate what happens on your screen. Can you try it, please?

**Comment by gbtami** [comment]
@Nakel Is this reproducible in local games or just playing on FICS? With analyzers on or off?
