### ISSUE TITLE
Taking back messes up the game

### ISSUE THREAD

**Issue by massimiliano-leoni** [pychess/pychess#1005]
Taking back a move messes up the graphics and the game synchronization, i.e. I can't go on playing after that and the pieces don't place properly on the chessboard.
If I try to move again it considers it as a "booked move", just like when I play while the opponent is thinking.

I understand the description is not the clearest piece of literature one could wish for :D

**Comment by gbtami** [comment]
A screenshot and a .log file definitely would be a big help :)

**Comment by gbtami** [comment]
@massimiliano-leoni with what version can you produce this? rc3, rc4, git ?

**Comment by massimiliano-leoni** [comment]
Hey, sorry for being late.
Here is the screenshot, it's the same as the other issue I had
![screenshot12](https://cloud.githubusercontent.com/assets/12351309/9699409/a8ba590c-53d9-11e5-8f93-9f383beda8c1.jpeg).

I played three moves and then took back, and then I couldn't play anymore...
Also, I can't see the opening name from the opening book, is this correct?

I'll email you the log now.

**Comment by gbtami** [comment]
Got it and was able to reproduce it, thx!

**Comment by massimiliano-leoni** [comment]
Wow, one of my bugs are reproducible! This is like a dream come true :D

**Comment by massimiliano-leoni** [comment]
Fixed with a oneliner, like a boss :D

**Comment by massimiliano-leoni** [comment]
I just played a game online and when my opponent accepted to takeback nothing happened in my gui, which kept waiting for him to move, whereas he was correctly seeing that it was my turn again.

**Comment by gbtami** [comment]
Hmm, seems this is another undo bug.

**Comment by massimiliano-leoni** [comment]
I have the log, do you want it?

**Comment by gbtami** [comment]
Yes please.

**Comment by gbtami** [comment]
Btw. at this moment in FICS games PyChess sends only takeback 1 offers independently of which players turn coming. I think it would be better to send takeback 2 when it's our turn, similar as we do in human-engine games.

**Comment by gbtami** [comment]
Done.
