### ISSUE TITLE
Package available for Slackware from SlackBuilds.org repository

### ISSUE THREAD

**Issue by ghost** [pychess/pychess#1007]
This is not an issue but inform for Slackware package

[pychess](http://slackbuilds.org/repository/14.1/games/pychess/)

Thank you for great job.
Dimitris Zlatanidis

**Comment by gbtami** [comment]
Great, thx!
Btw. notice that from 0.12rc4 PyChess dependencies have chaged. We migrated pychess to Gtk3 and Python3 (Python2 is supported too). See the INSTALL file!

**Comment by ghost** [comment]
Ok ...Thank you !

**Comment by gbtami** [comment]
@dslackw I'v added your link to http://pychess.org/download/ Is it OK in this form?
Update the slackware package to the just released 0.12 if you have time, please!

**Comment by ghost** [comment]
Slackware package for pychess updated for repository 14.2.
Please updated for the new url is https://slackbuilds.org/repository/14.2/games/pychess/

And next week Slackware package for pychess will updated for version 0.12.4

Thanks
Dimitris

**Comment by gbtami** [comment]
Done. Thank you!
