### ISSUE TITLE
Cannot see opening name/code

### ISSUE THREAD

**Issue by massimiliano-leoni** [pychess/pychess#1008]
As per title, when playing a game, even offline, I can't see the name of the opening in the "Annotations" tab.

**Comment by gbtami** [comment]
Do you see "Warning: eco.db not found, please run pgn2ecodb.sh" when starting PyChess in console?

**Comment by massimiliano-leoni** [comment]
Yes, I couldn't see it in the beginning because it was drown by loads of warnings like
`Warning: The property GtkSettings:gtk-button-images is deprecated and shouldn't be used anymore. It will be removed in a future version.`
I ran the script and now I can see the openings fine.

**Comment by gbtami** [comment]
Thx!
