### ISSUE TITLE
Move history and Score widgets not working when opening saved game

### ISSUE THREAD

**Issue by massimiliano-leoni** [pychess/pychess#1009]
When I open a saved game [the one pychess automatically saves at the end of the game, for example] the move history widget is blank and links to positions are not working, whereas the score widget only shows the initial [even] score and clicking in the below area triggers other positions.

**Comment by gbtami** [comment]
I can reproduce this (but not #1010), thx!

**Comment by massimiliano-leoni** [comment]
Yeah, I'm getting better at this :P

**Comment by massimiliano-leoni** [comment]
Fix works here too, good job!
