### ISSUE TITLE
Opening a saved game from first move messes up widgets

### ISSUE THREAD

**Issue by massimiliano-leoni** [pychess/pychess#1010]
This might be related to #1009 .
When I open a saved game and use the small "rewind" button to set the initial position to the first position, I can hear the "mate" sound, the blue status bar says "<winning player> won the game, the reason is unknown", move history and score widgets are like in #1009 and the annotations widget simply displays the result [e.g. 1-0] but no moves.
There seems to be no ways to navigate to other moves also.

**Comment by gbtami** [comment]
Can you send me a .pgn of this game and the .log with steps you described here, please?

**Comment by gbtami** [comment]
I think I'v just understand this issue now. You had used the "rewind" button in the mini game preview widget, aren't you? If you set a position in the preview widget, it will load moves from the initial position to the selected one and disregards moves after selection at all. So this is the intended behavior.

**Comment by massimiliano-leoni** [comment]
Yes, I think I did what you said.
Out of curiosity: can I have a rationale on why this is the intended behavior? I don't fully understand it :S

**Comment by gbtami** [comment]
Hmm. I'm thinking about what functionality we can lose if we change it not to disregard moves after the selected position in preview widget, but I can't remember anything :) I will change it. If someone will complain and can argue to revert it, we can discuss it and decide again.

p.s. I'm really appreciate for your testing and bugreports, thx!

**Comment by gbtami** [comment]
Done. Thx again!
