### ISSUE TITLE
bug : selecting pychess default engine causes traceback

### ISSUE THREAD

**Issue by bboutkov** [pychess/pychess#1020]
Traceback (most recent call last):
  File "/media/data/root/Documents/chess/pychess/pychess/lib/pychess/widgets/enginesDialog.py", line 325, in selection_changed
    engine = discoverer.getEngineByName(name)
  File "/media/data/root/Documents/chess/pychess/pychess/lib/pychess/Players/engineNest.py", line 355, in getEngineByName
    return self.getEngines()[names.index(name)]
ValueError: 'Pychess.py' is not in list

**Comment by gbtami** [comment]
Strange. I can't reproduce this. Telling the truth we have no Pychess.py at all. Our own engine is PyChess.py I can't imagine how you got this. Do you have any idea?

**Comment by bboutkov** [comment]
I think 'Pychess.py' might have been an error from part of my debugging on this issue. 

I can reproduce the main issue  with the value error of PyChess.py by:
start client
go to edit engines (in offline mode)
select via clicking engines on the left panel -> produces this error.

What I just noticed debugging further is that the traceback seems to only occur when theres more than 2 engines in the list. By default I only had PyChess and stockfish on my laptop and was getting no error, but when I additionally added fruit as an engine I started getting the same error by simply clicking on the PyChess engine. This makes me think that my 'fix' isnt quite appropriate :(

**Comment by gbtami** [comment]
Hmm. I have 16 engines installed, but wasn't able to reproduce this yet.
Please save your engines.json first, then try to reproduce this with deleting ~/.config/pychess/engines.json first.
If this solves the error, the saved engines.json is the reason. If not, we have to think another direction.

**Comment by bboutkov** [comment]
Ok. I think maybe this bug is related to the delete engine functionality in this engine edit window. I was still able to reproduce the error after clearing my engines.json.  to reproduce try : 

start client
go to edit engines (in offline mode)
delete an engine by selecting and clicking remove
now next selection of an engine should produce the error

**Comment by gbtami** [comment]
Ok, this helped to reproduce. Thx!
