### ISSUE TITLE
PyChess doesn't recognize sacrifice

### ISSUE THREAD

**Issue by Nakel** [pychess/pychess#1022]
1. d4 Nf6 2. c4 e6 3. Nc3 Bb4 4. a3 Bxc3+ 5. bxc3 O-O 6. Nf3 b6 7. Bg5 h6 8. Bxf6 Qxf6 9. e3 Nc6 10. Bd3 Na5 11. O-O Bb7 12. Re1 Bxf3 13. gxf3 e5 14. dxe5 Qxe5 15. Kh1 

The last move, Kh1, was clearly a sacrifice, allowing Black's queen to snatch White's pawn on c3 for nothing, but PyChess (in the comment section) doesn't say it is a sacrifice.

**Comment by gbtami** [comment]
Merged into #945
