### ISSUE TITLE
feature request : secondary sort on games list

### ISSUE THREAD

**Issue by bboutkov** [pychess/pychess#1026]
Currently if I sort by game type, the games list displays games alphabetically by type and that is all. I think it would be useful to automatically also sort by rating, as sorting by game type alone isn't very useful for selecting a good game to observe.

Perhaps eventually we could have a subsort system where we sort based on column a, and then subsort that based on column b where a user selects the two columns a & b. These might be big dreams for now though ...

**Comment by gbtami** [comment]
Changing our pixCompareFunction()  function in lib/pychess/ic/ICLounge.py to subsort on rating seems doable.
(If you like to experiment with it, it starts at line 599.)
https://python-gtk-3-tutorial.readthedocs.org/en/latest/treeview.html#setting-a-custom-sort-function

On the other side, Gtk.TreeView supports sorting by clicking on single columns only, so I can't imagine how can we implement two column selection at all.
https://python-gtk-3-tutorial.readthedocs.org/en/latest/treeview.html#sorting-by-clicking-on-columns

**Comment by gbtami** [comment]
Implemented a multi-column sort based on TreeModelSortUtil class from
https://github.com/metomi/rose/blob/master/lib/python/rose/gtk/util.py
It saves previous sort column and reuses it as secondary sort column on next column selection.
Try it please!

**Comment by cajone** [comment]
I believe this request has resolved I can use the column headers to sort on rating for white and then sort on rating for black and get back a list that shows the highest black rating versus white rating I can also sort by rating and then by type and this also seems to work
