### ISSUE TITLE
Create .svg pieces for Makruk/Ouk/Sittuyin

### ISSUE THREAD

**Issue by gbtami** [pychess/pychess#1028]
Unfortunately http://www.playok.com/en/makruk/ provides no free images.
Some images as inspiration:
http://www.veryspecial.us/pics/247a.jpg
http://1.bp.blogspot.com/_ha8LR1CowcU/TMGJ7WnwNdI/AAAAAAAABls/97HHioug_bA/s1600/makruk.jpg
https://plus.google.com/photos/112816884821337358713/albums/5515751575325418865/5515751674812970130?banner=pwa&pid=5515751674812970130&oid=112816884821337358713

**Comment by cajone** [comment]
Hi gbtami, could you assign this to me? I will create the svg's on a branch #1028 and send you a pull request when done, I think I should be able to turn this around fairly quickly

**Comment by gbtami** [comment]
@cajone as I see only members can be assignees, but you can work in your clone without being an assignee, so go for it! My only request is if you want it to be in PyChess publish it under some free license please! See https://wiki.debian.org/DFSGLicenses

**Comment by cajone** [comment]
hi gbtami, I have generated the svg files and a pull request https://github.com/pychess/pychess/pull/1033, 

if you need more info let me know

**Comment by gbtami** [comment]
Merged. It is awesome!
One thing I can notice. Pawns seems a little bit placed up from the center of fields. If you can move all pieces down with the same distance to center pawns then kings and queens will not stick to the  field above too. The best way to see this is to set View->Full screen and View->Show Sidepanels to off.

**Comment by cajone** [comment]
Ah, ok will do, one thing I did notice after I pushed it up onto github was that the Preference ->Themes -> Makruk.png file was a mashup of the FreeStaunton Set ( i used as a base ) an the set I was generating. Is the Theme png file auto generated or do I need to edit it also ?

**Comment by gbtami** [comment]
Btw. If you like to place your real name to ARTISTS file just create another pull request for it!

**Comment by gbtami** [comment]
create_theme_preview.sh will do it.

**Comment by gbtami** [comment]
Btw. if you like to add your real name to ARTISTS file just create another pull request for it.

**Comment by gbtami** [comment]
Just another little notice. As you can see in images linked above queen is a little bit shorter and thinner  then king and bishop in this variant to indicate the weakness of the queens.

**Comment by cajone** [comment]
ok I will change the Queens, I don't mind making minor changes. I pushed the alignment changes hopefully they are a little bit more centred, the pawns due to there shape against the sqares give of an optical illusion though :).

I had an issue with the create_theme_preview.sh  and removed the -3 from the python call you might want to put this back ( sorry for that )

**Comment by cajone** [comment]
OK modified the queens, let me know if the adjustment is enough

**Comment by gbtami** [comment]
Perfect! Thx again for this great contribution!

**Comment by cajone** [comment]
gbtami, Your more than welcome, thanks for the work you have put into this great interface so far. I can actually code in python, would you mind if I assisted in other areas of the project?

**Comment by gbtami** [comment]
I'v already sent you an invitation to join to PyChess :)
