### ISSUE TITLE
Observing games tag 

### ISSUE THREAD

**Issue by cajone** [pychess/pychess#1032]
When observing multiple games at the same time each game tag/tab contains the following information

"Player A (Rating) vs Player B (Ratiing) [Game Time Increment Time play mode ie blitz/standard]"

This seems to be a lot of information when traversing tags ( watching a competition ).

Would it be possible to move the "[Game Time Increment Time play mode ie blitz/standard]" part of the tag into the "annotation" header and just put the board number on that tag with the player identities ie

"[Board No.] Player A (Rating) vs Player B (Ratiing) "

**Comment by gbtami** [comment]
Sure! I think this issue is matching to #438 too.

**Comment by gbtami** [comment]
This needs modification in two place. Removing unneeded parts from lib/pychess/widgets/gamewidget.py game_info_label and adding missing time control info to sidepanels.annotationPanel.py insert_header(). The game_info label parts are coming from different display_text functions of GameWidget, GameModel, ICGameModel, FICSObjects.FICSGame

**Comment by cajone** [comment]
Ok this sounds like a good place to roll up my sleeves and get into the code base. I will pick this one up if you have not already implemented it ;)

**Comment by gbtami** [comment]
No I haven't. I just sniffed it around :)
