### ISSUE TITLE
pychess can't discover crafty

### ISSUE THREAD

**Issue by sterni1971** [pychess/pychess#1035]
Hello!

if I install in my Ubuntu 15.10 crafty (multiverse), afterwards pychess hangs in discovering
the crafty engine. If I remove crafty everything works fine again. I can manually start crafty

Pychess Version git 0.12-21-g8604323
OS: Ubuntu 15.10
python2.7 and python3.4

**Comment by sterni1971** [comment]
works. thank you

**Comment by gbtami** [comment]
Thx for reporting this!
