### ISSUE TITLE
Colorize Seek Graph rim of computer sought

### ISSUE THREAD

**Issue by cajone** [pychess/pychess#1037]
The seek graph used green ( unrated games ) and blue ( rated games ) both circles have a black rim.

Would it be possible to change this black rim to say red or another colour is the seek is for a computer match.

This would make it much quicker to tell if its a computer or human game ?

**Comment by gbtami** [comment]
Sure! Feel free to enhance it. It happens in ICLounge.py onAddSought() than in SpothGraph.py addSpot().
