### ISSUE TITLE
Can't use opening book other than PyChess own one

### ISSUE THREAD

**Issue by gbtami** [pychess/pychess#1042]
In Preferences->Hints I can select another book, but seems it's not used and not saved in config.

**Comment by massimiliano-leoni** [comment]
I can't actually use the default one either, same symptoms.

**Comment by gbtami** [comment]
You should look into .log file searching for "Could not find " with path of pychess_book.bin

**Comment by gbtami** [comment]
Latest commit fixed the issue for me. Try it please!

**Comment by massimiliano-leoni** [comment]
Fixed! Thank you.
