### ISSUE TITLE
primary variable not being set when a context switch takes place between 2 or more observed games

### ISSUE THREAD

**Issue by cajone** [pychess/pychess#1048]
The primary variable is used to direct whispers to the correct observed board.

If you have 2 or more observations on the go and you do a context switch between boards, the primary variable is not being reset to reflect this context switch hence you end up whispering to the wrong observed channel

( major bug request non critical )

The primary variable can be manually set using primary <board no>

**Comment by gbtami** [comment]
Docs to read: http://www.freechess.org/Help/HelpFiles/primary.html

**Comment by gbtami** [comment]
Works Ok, thx!
