### ISSUE TITLE
On signing out of  fics, a users presence in chat channels is not removed

### ISSUE THREAD

**Issue by cajone** [pychess/pychess#1049]
When a user leaves fics any channels that she/he was in maintains a ghost of there presence within the chat channel windows

(cosmetic bug)

**Comment by gbtami** [comment]
Yes, we should remove departed users from channels. Unfortunately FICS sends no notification info about new users joining to channels. So this list can't show actual present users. At least I don't know any way.

**Comment by cajone** [comment]
So FICS does send info about people leaving / logging out.

since we are only interested in channels that we are members of we can maintain a list of of channel tuples ie [(chan,user1),(chan1,user2)] and we get a leaving fics event then we might be able remove any tuples that have the leaving user in

this might seem heavy weight but I don't think guest users are allowed to join channels so we can short circuit the leaving event handle filtering out any guest users
