### ISSUE TITLE
Observe lectures on FICS

### ISSUE THREAD

**Issue by massimiliano-leoni** [pychess/pychess#1052]
I was trying to watch a lecture by LectureBot but in the Players list its status is set to Examining and the "Observe" button is grayed out.

I can see the lecture in the FICS console but it's unpractical to follow without a chessboard. Does Pychess support watching a lecture at the moment?
If not, this would be an important feature to add. Ideally, the LectureBot comments would appear in the "chat" widget.

**Comment by gbtami** [comment]
Examine is not supported yet. We maintain a list of implemented FICS feature herei:
https://github.com/pychess/pychess/wiki/FICSChecklist

**Comment by gbtami** [comment]
@massimiliano-leoni enabled observing examiners and piped kibitzing/whispers to chat widget. Please try it!

**Comment by massimiliano-leoni** [comment]
Looking forward to it! 
First thing tomorrow after work :D

There were people on the fics chat suggesting to just switch to a "better" client than pychess... Now I'll show them ;)

**Comment by massimiliano-leoni** [comment]
Browser = client, sorry XD

**Comment by massimiliano-leoni** [comment]
Yeah, it seems to be working pretty good!

**Comment by gbtami** [comment]
Ok, the next step is to support puzzlebot/endgamebot. It will be a bit harder because they change us from observer mode to examiner mode...

**Comment by gbtami** [comment]
You can start them from console now. See "tell puzzlebot help" and "tell endgamebot help".
