### ISSUE TITLE
Resizing problem

### ISSUE THREAD

**Issue by massimiliano-leoni** [pychess/pychess#1054]
A friend of mine reports that pychess resizes widgets in an uncomfortable way while going through the moves of a loaded game. See screenshot.
Notice how the window becomes too big for the screen.

She is running the latest dev version; I was not able to reproduce it with the same version, so apparently something system related? Anyway, probably an if carefully placed can workaround this.
![screen](https://cloud.githubusercontent.com/assets/12351309/11324696/bdf5b90c-9131-11e5-82cb-a2e50e90b48d.png)

**Comment by gbtami** [comment]
@massimiliano-leoni can _she_ reproduce this? If yes, ask she to describe the process a bit more detailed, please!

**Comment by massimiliano-leoni** [comment]
I have a _very_ low quality video of the bug in progress. I cannot upload it on github, though...

**Comment by gbtami** [comment]
Just upload it anywhere else and copy the link here. Or mail me.

**Comment by massimiliano-leoni** [comment]
https://www.dropbox.com/s/14jiou1qib62uw0/video_2015-11-24_22-23-44.mov?dl=0

Here! I will remove it in the far future.

**Comment by gbtami** [comment]
Got it, thx!

**Comment by gbtami** [comment]
Committed a possible fix, Try it please!

**Comment by massimiliano-leoni** [comment]
Now I have a new problem: the widget column on the right is now very wide and I can't reduce it to a normal size.

**Comment by gbtami** [comment]
I faced with it too :( Reverted.

**Comment by gbtami** [comment]
The root of the problem is our appendAutowrapColumn() in lib/pychess/System/uistuff.py we use to wrap analysis text column. It's based on http://www.islascruz.org/html/index.php?blog/show/Wrap-text-in-a-TreeView-column.html
Seems it sometimes doing crazy things. Unfortunately I don't know any better working solution for this auto wrap problem :(

**Comment by gbtami** [comment]
Committed a workaround. Instead of showing the whole analyzing line wrapped it only ellipsizes it. Try it please!

**Comment by massimiliano-leoni** [comment]
This solved the issue, wonderful!
