### ISSUE TITLE
Attempt to unlock mutex that was not locked Aborted (core dumped)

### ISSUE THREAD

**Issue by Ravanasura** [pychess/pychess#1055]
I am using elementary OS freya. I installed pychess with the command: `sudo apt-get install pychess`

When I executed `pychess` from terminal, I get:

```
Gtk-Message: Failed to load module "pantheon-filechooser-module"
Gtk-Message: Failed to load module "canberra-gtk-module"
Attempt to unlock mutex that was not locked
Aborted (core dumped)
```

When I tried to open from applications: Nothing. (Just open, within fraction of seconds closed)

```
apt-cache policy pychess
pychess:
         Installed: 0.12~beta3-1
        Candidate: 0.12~beta3-1
        Version table:
              *** 0.12~beta3-1 0
                        500 http://in.archive.ubuntu.com/ubuntu/ trusty/universe amd64 Packages
                        100 /var/lib/dpkg/status
```

**Comment by gbtami** [comment]
@Ravanasura beta3 is rather old, try to install the latest 0.12 .deb from http://pychess.org/download/ please!

**Comment by Ravanasura** [comment]
Well, thanks @gbtami. Problem solved. 

But why terminal installation gives beta version, even latest version is available?

**Comment by gbtami** [comment]
Unfortunately Linux distribution packagers sometimes follow upstream releases delayed.

**Comment by Light--** [comment]
> Unfortunately Linux distribution packagers sometimes follow upstream releases delayed.

what do you exactly mean ? my program also met this problem but i dont know how to fix that...

**Comment by gbtami** [comment]
Latest PyChess release: https://github.com/pychess/pychess/releases
Compare version with latest official Debian package: https://packages.debian.org/sid/pychess
