### ISSUE TITLE
Add context menu on player records

### ISSUE THREAD

**Issue by massimiliano-leoni** [pychess/pychess#1056]
Sometimes I feel it would be nice to right-click a seek and have some options popping up:
    [*] accept challenge [redundant]
    [*] send challenge [one of the three in the lower part]
    [*] view player profile [i.e. link to http://ficsgames.org/cgi-bin/search.cgi?player=playername].

How do you feel about that?

**Comment by gbtami** [comment]
First is redundant as you write.
Second seems little bit disrespectful for me. If one sent a concrete kind of seek that means he/she wants to play that kind if game not another.
I agree on third. Added it to #473.

**Comment by massimiliano-leoni** [comment]
Another useful option would be the assessment of the seek, i.e. the points to be won/lost in case of win, draw or loss. This is the output of the console command "assess playername /s" for standard game, etc...

**Comment by cajone** [comment]
wow did not even know that command existed, interesting

**Comment by gbtami** [comment]
Same here :)
I like the idea, just thinking about right click menu vs. push button above column headers.

**Comment by massimiliano-leoni** [comment]
I am for right click menu: quite often I do right click on a record expecting something to show up, only to later remember there's nothing implemented yet. I think it's natural to have it when asked for, instead of filling the gui with push buttons.

**Comment by gbtami** [comment]
Ok, thx for the input. I'm sold :)

**Comment by massimiliano-leoni** [comment]
For the best! Thanks!

**Comment by gbtami** [comment]
Started with "Accept" and "Archived" menu items.

**Comment by massimiliano-leoni** [comment]
Nice! What does the "Archived" option do?

**Comment by gbtami** [comment]
It updates Archived games (stored/journal/history) tab with seek owner games.

**Comment by gbtami** [comment]
Added assess. TODO: better tabular formatting with custom dialog.

**Comment by massimiliano-leoni** [comment]
Very nice, thanks!

For the player profile, I think it's fine if you simply open the link to the fics page in an external browser, no need for parsing the info in there in a new dialog.

Concerning my other request, the possibility to challenge that player with one of the user's predefined seeks, I would like to promote it again: I experienced a 15+0 clock is sometimes too short for me, whereas 20+0 or 15+15 is fine, and if I see someone seeking a game 15+0 it's likely that he or she would not mind playing 20+0 or 15+15 instead. I also saw the opposite happening: player P seeking a 15+0 and me seeking a 15+15, and player P accepts my seek because it is "close enough".
All this is to say that I think this feature is not an abuse, but rather a useful thing to have.

**Comment by gbtami** [comment]
I'm sold again :)
My only question is how can I chose what predefined seek (1, 2, or 3?) to use for challenging the selected player?

**Comment by massimiliano-leoni** [comment]
I never replied because we discussed this in chat.

I have a thing to note now: if I open the console and issue the "assess" command, the dialog pops up as if I used the right-click menu item.

This can be uncomfortable if a user uses the console more than the gui, as he might potentially end up having loads of dialogs popping up. Can you disable the dialog when the "assess" command is entered directly into the console?

**Comment by gbtami** [comment]
No popup fixed.

**Comment by massimiliano-leoni** [comment]
Fix confirmed, thanks!

**Comment by gbtami** [comment]
Added challenge.

**Comment by massimiliano-leoni** [comment]
Nicely done, thanks!

**Comment by gbtami** [comment]
Added finger.

**Comment by massimiliano-leoni** [comment]
I see you liked my idea in the end :)

**Comment by gbtami** [comment]
Absolutely! :)
