### ISSUE TITLE
Player names are "unknown" when observing a game

### ISSUE THREAD

**Issue by massimiliano-leoni** [pychess/pychess#1060]
I noticed than when observing a game on FICS  the names of the players are shown as "unknown".
I think this is a regression, if that matters.

**Comment by massimiliano-leoni** [comment]
The names are displayed correctly in the game tab when multiple tabs are open.

**Comment by cajone** [comment]
Hi 

Is this reproducible ( could you add a test process to reproduce) or just a random thing?

**Comment by massimiliano-leoni** [comment]
It always happens, just observe an ongoing match to reproduce.

**Comment by gbtami** [comment]
@massimiliano-leoni I can't reproduce it :(
Can you give me some more info and .log ?

**Comment by massimiliano-leoni** [comment]
I don't really have more info than what I just gave. I attach the log of a session in which I just logged onto FICS, started observing a game and then closed immediately.

[2015-11-28_18-17-40.txt](https://github.com/pychess/pychess/files/46389/2015-11-28_18-17-40.txt)

**Comment by gbtami** [comment]
Thx! You are using a version containing a regression. I think this was fixed later. Update your local git repo, please!

**Comment by massimiliano-leoni** [comment]
Confirmed, but now I can't observe examiners any more! Can you please re-enable that? I know support was incomplete, but I was still using it!

**Comment by gbtami** [comment]
@massimiliano-leoni I started to fix #1052 Stay tuned :)
