### ISSUE TITLE
Observed Game window not opening after typing 'ob <gnameno>' in console

### ISSUE THREAD

**Issue by cajone** [pychess/pychess#1067]
Can't get console command  observed game to open the chess board. I guess this is a regression as it was working yesterday'

**Comment by gbtami** [comment]
Same reason as in #1066. We should think about how to handle this guests disabled situation better.

**Comment by massimiliano-leoni** [comment]
I cannot reproduce this, mine works fine.

**Comment by gbtami** [comment]
This and #1066 error raises only when FICS disables guest logins for whatever reason (f.e. abusers).

**Comment by gbtami** [comment]
7f00587 fixes this too.
