### ISSUE TITLE
IClounge tab panel for stored/journal/history

### ISSUE THREAD

**Issue by cajone** [pychess/pychess#1070]
A quick way of seeing what games are stored , you history and journay entries.

This probably should be considered with #785 as a further enhancement  and also reducing the need to interact so much with the console window

**Comment by gbtami** [comment]
Stored and history part is ready.

**Comment by cajone** [comment]
Hi gbtami : ok so I had a quick test of this ( I guess this is the archived panel on the IClounge)

Clicking on a game and the preview button worked as expected.

The 2 things I found that I did not expect and it is very possible you have not looked at this yet

1) trying to sort by time/date column seemed to give back random results
2) trying to sort on time control also gave back random results

**Comment by gbtami** [comment]
Thx, fixed.

**Comment by gbtami** [comment]
Further plans:
Indicate online status of adjourned opponent with red/green "*" in result column (drop is_online)
Add white and black player columns (drop opponent and color) to support journal games.

**Comment by gbtami** [comment]
TODO: red/green "*"  online status handling for adjourned games
