### ISSUE TITLE
Other Chess Servers

### ISSUE THREAD

**Issue by thewhisperinyourears** [pychess/pychess#1079]
Is possible to add other chess servers that are FICS compatible? I tried join another chess server called www.uschessnetwork.com and it somehow worked it connected and even i saw myself online but it didn’t pass the logging message

**Comment by gbtami** [comment]
PyChess communicates to FICS in "block mode". Is USCN server supports this protocol?
Can this server work with xboard/winboard or with Jin or with any other client?

**Comment by thewhisperinyourears** [comment]
It works perfectly with x board and winboard. With Jin it works but the
board does not draw to the screen which is weird.

**Comment by gbtami** [comment]
I think they don't use "block mode". Do you have contact to USCN server admins to ask them about it?

**Comment by thewhisperinyourears** [comment]
I am an administrator in uscn but I don't know if the block mode is used.
But winboard works perfectly and x board also thief chess Interface and
arena chess

**Comment by gbtami** [comment]
@thewhisperinyourears can you join to #pychess on freenode.net IRC now?
If you don't have client installed, just use http://webchat.freenode.net/?channels=pychess&uio=d4

**Comment by thewhisperinyourears** [comment]
Yes I am logging

**Comment by gbtami** [comment]
Login fixed. Unfortunately USCN doesn't support block mode and interface variables, so parsing different output needs more work. For example pychess set "seekinfo" on startup, etc.

http://www.freechess.org/Help/HelpFiles/iv_block.html
http://www.freechess.org/Help/HelpFiles/ivariables.html
http://www.freechess.org/Help/HelpFiles/iv_seekinfo.html

**Comment by gbtami** [comment]
Match and observe started from console now works.

**Comment by thewhisperinyourears** [comment]
Did you checked the bug I told you

**Comment by gbtami** [comment]
@thewhisperinyourears unfortunately I can't remember anything :) File a new issue for all individual bug please!

**Comment by thewhisperinyourears** [comment]
You haven't logged in in a while

**Comment by gbtami** [comment]
@thewhisperinyourears when http://www.uschessnetwork.com will start?

**Comment by gbtami** [comment]
Seems this server doesn't work :(

**Comment by thewhisperinyourears** [comment]
Hey I have not see you in a while.

Are you okay?

**Comment by gbtami** [comment]
Hi!

I'm fine thx! Just working on https://github.com/gbtami/pychess-variants nowadays :)

**Comment by thewhisperinyourears** [comment]
Hey I started a tech company and I was wondering if you might be
interested.

You can visit https://televistar.com

If you think you wanna talk about it let me know
