### ISSUE TITLE
msi hard to download

### ISSUE THREAD

**Issue by Ivoz** [pychess/pychess#1080]
Hi there, I was trying to download the [12.1 msi](http://www.pychess.org/download/pychess-0.12.1-win32.msi) and it was constantly failing. I am using Windows 10 x64, Chrome 47 at the moment. The same is happening with Firefox 42. Fortunately Firefox is good at resuming failed downloads, so after 5-6 retries I managed to completely download it. However I assume many newer users, if this issue is not limited to something unique to me, might just give up straight away when their download fails the first time.

I was also unable to see any md5s / hashes to check the correctness of my eventual downloaded file.

I suggest you check the configuration of your webserver, whether it can handle long downloads / connections; I'd also suggest hosting the major downloads on Github releases as well as an alternate download location.

a hashes file for download verification would be nice as well. In case you were interested, https://letsencrypt.org/ also lets you host a free HTTPS server now if you'd like to enable that for visitors.

**Comment by gbtami** [comment]
Ivoz, thx for the feedback! Creating md5 is a good idea indeed.

**Comment by gbtami** [comment]
Uploaded released 0.12.1 packages to https://github.com/pychess/pychess/releases

**Comment by Ivoz** [comment]
Nice, thanks @gbtami :+1:
