### ISSUE TITLE
USCN Who command

### ISSUE THREAD

**Issue by thewhisperinyourears** [pychess/pychess#1083]
I don’t see all people listed in the player list.

**Comment by gbtami** [comment]
I see this. It seems OK for me. Can you describe the issue more detailed, please?
![uscn_who](https://cloud.githubusercontent.com/assets/479964/11804934/1016aad8-a308-11e5-92d3-9adee94c8074.png)

**Comment by cajone** [comment]
gbtami: Just as a small notification point on your screen shot above maybe set console title to reflect 'USCN console'

**Comment by gbtami** [comment]
This should be better now. Try it gain please!
