### ISSUE TITLE
Language is severely messed up on Windows

### ISSUE THREAD

**Issue by 727yubin** [pychess/pychess#1085]
I am using pychess on windows 7 ultimate. The problem is that the language is messed up. One option is shown in English, one in Korean, one in Japanese, one in Norsk(I think), one in a language I have never seen...
![bug](https://cloud.githubusercontent.com/assets/14364385/11820373/dc9a9894-a36c-11e5-8931-fc222ce22432.PNG)
Here's a screenshot.
Is there any way I can change the language from the program?
By the way, the system language is English, but I have set some text (such as the clock) to display in Korean.

**Comment by gbtami** [comment]
You can try to set LANG environment variable to C to dismiss translations. If this doesn't work we can try to add a command line argument to select translation language. Btw. can you copy here the .log file of a short pychess session, please? (Just start pychess and quit.) It's in youre home dir under .locale/share/pychess/

**Comment by gbtami** [comment]
It's rather strange to see more than one language translation beside English in one app. Especially "Szerkesztés" which is Hungarian :) Can you take a look at https://www.transifex.com/gbtami/pychess/language/ko/ please?

**Comment by 727yubin** [comment]
The log is here:

20:44:48.104 Default DEBUG: Resizing window to width=1280 height=738
20:44:48.105 Default DEBUG: Moving window to x=-8 y=-8
20:44:48.284 Default INFO: PyChess Anderssen 0.12.1 git 
20:44:48.285 Default INFO: Command line args: 'None'
20:44:48.287 Default INFO: Platform: Windows-7-6.1.7601-SP1
20:44:48.287 Default INFO: Python version: 3.4.3
20:44:48.287 Default INFO: Pyglib version: 3.14.0
20:44:48.950 Default DEBUG: Resizing window to width=1280 height=738
20:44:48.951 Default DEBUG: Moving window to x=-8 y=-8
20:44:52.986 Default DEBUG: ionest.closeAllGames
20:44:52.986 Default DEBUG: keepWindowSize.savePosition: ಸುಸ್ವಾಗತ - PyChess
20:44:52.986 Default DEBUG: Saving window position width=1280 height=738 x=-8 y=-8

**Comment by 727yubin** [comment]
Trying to log in to transifex keeps on giving me an ssl error.

**Comment by gbtami** [comment]
Try to start pychess from command line with:
set LANG=C
pychess.exe

**Comment by 727yubin** [comment]
Nope. That changed nothing.

**Comment by gbtami** [comment]
@727yubin can you join to as on IRC please?
http://webchat.freenode.net/?channels=pychess&uio=d4

**Comment by gbtami** [comment]
Added --no-gettext command line option. I think this is the most we can do to handle this on Windows.

**Comment by gbtami** [comment]
Maybe this can help: https://github.com/mypaint/mypaint/blob/master/mypaint.py#L226
