### ISSUE TITLE
Player rating appended to name in chat

### ISSUE THREAD

**Issue by massimiliano-leoni** [pychess/pychess#1103]
Today a player asked me why my rating is appended to my name [handle] in the chat.

Is this not supposed to happen? Should pychess provide an option to disable that?

**Comment by cajone** [comment]
Hmm, IMHO I like my rating added to my handle and also the handle of my friends, First up it lets me see at a glance there progress without me having to go round all my friends and checking there stats to see how there doing. Second if someone jumps into a chat with me that I don't know and start rattling on about some chess line or something, it lets me know at a glance if they have any idea of what they are talking about ( not bullet proof, but a reasonable guide ).

So I would suggest we leave it alone unless it really is bothering you, but again this is only my opinion.

**Comment by massimiliano-leoni** [comment]
I actually like it too, I was just notifying that at least someone found it unusual/awkward.

**Comment by gbtami** [comment]
I like it too :)
