### ISSUE TITLE
Following a game while playing issue

### ISSUE THREAD

**Issue by cajone** [pychess/pychess#1105]
Not sure how we address this but if you are following someone and start a new game yourself, you can run into an issue that the followed player finishes there game and you are still playing and the followed person then starts a new game. At this point the  focus jumps from your game to the person you are following.

This can be very bad if you have very little time on your clock when this event happens

**Comment by gbtami** [comment]
Maybe we should send "follow" before we start to play a new game as babaschess is doing. Funny thing is that on observed game finish Babaschess pops up an endgame dialog while I played another game.
