### ISSUE TITLE
Piece Promotion ?

### ISSUE THREAD

**Issue by cajone** [pychess/pychess#1106]
The attached png ( although I had to upload it as a txt file) shows a game I played  recently. If you load this into pychess there seems to be a timing issue at move 29.. c1=Q

The board at this point shows both the prompted pawn -> Queen and also the pawn on c2. It's not until 30. Bxc1 that this pawn disappears. Although there is nothing logically wrong with this I would have thought the pawn would have disappeared the second the Queen appeared ?

( possible bug )

[smoozer (1340) vs. pgg (1286).txt](https://github.com/pychess/pychess/files/76761/smoozer.1340.vs.pgg.1286.txt)

**Comment by gbtami** [comment]
Nice catch! :)

**Comment by cajone** [comment]
:) finding the bug was good also !!

**Comment by massimiliano-leoni** [comment]
I cannot reproduce this with current version [or I misunderstood the description of the bug]: I see the pawn disappearing when the newly created queen appears.

**Comment by massimiliano-leoni** [comment]
I've seen a match in which both Black and White promote in consecutive moves, the first promotion goes fine and the second one exhibits the bug.
