### ISSUE TITLE
Conversation info not diplaying correctly

### ISSUE THREAD

**Issue by massimiliano-leoni** [pychess/pychess#1108]
The "conversation info" panel in the chat window does not put proper line breaks in the text. As a result, some of the text cannot be read even if the window is maximized.

![screenshot19](https://cloud.githubusercontent.com/assets/12351309/12117555/d720d8fa-b3c1-11e5-8f05-8513ebed36b3.jpeg)

**Comment by cajone** [comment]
Strange I thought we had word wrap turned on in that panel, obviously not or its not working correctly

**Comment by cajone** [comment]
massimilliano-leoni, I have been looking at this over the last couple of days and unfortunately because of the widget used in the design (treeview) the cells in the view are not easily wrapped, I tried a work around but could not get it to function correctly, so we will either have to redesign this or possibly another Developer may have a solution of this ( apologies for not being able to take this further)

**Comment by cajone** [comment]
massimilliano-leoni, gbtami and I had a conversation about this issue and we decided to try and change the chat interface slightly and move the Notes you see above ( Conversation Info Panel) into a separate textview panel that will be above the middle message area and we will hide the 'Conversation Info' Panel if the focus is not a Channel but a Player.

This work is going to be included with the re-structuring of the 'Conversation' List you see on the left hand side of the chat window. So watch this space ..

**Comment by massimiliano-leoni** [comment]
@cajone thanks for the effort and the support :)
Just a clarification: the "Conversation info" panel should also be visible for players. That is the most important case, I'd say, just like the situation in the screenshot above.

**Comment by cajone** [comment]
gbtami:

I have an issue that I cannot get the chat panels to resize after trying to hide the info panel when a player and not a channel has been selected Gist snippet below. I just need to be able to expand the viewpanel to take up the rest of the space freed by hiding the infopanel

Any ideas ?

https://gist.github.com/cajone/246587b6fd1667e00884

**Comment by massimiliano-leoni** [comment]
Very well, now it's much better.
Just one last detail: now the line numbers are displayed as part of the text, which makes it slightly awkward. Can you remove them?

**Comment by gbtami** [comment]
Removed. Thx!
I was thinking about to add new lines to divide messages. Is it can help to make it a bit readable or  is this ok as is now? What do you think?

**Comment by massimiliano-leoni** [comment]
I think it's ok the way it is at the moment.
We'll see with some usage if it needs any improvement.

**Comment by gbtami** [comment]
OK, thx.
