### ISSUE TITLE
Whisper sent to observed game went to my played game opponent

### ISSUE THREAD

**Issue by gbtami** [pychess/pychess#1128]

**Comment by gbtami** [comment]
OK, from the .log it seems my observer game whisper was not sent to played game opponent just was shown in played game chat panel too.

**Comment by cajone** [comment]
Hmm so you had focus on the observed game made a whisper within that game and it turned up as a whisper in the game you were playing?

**Comment by cajone** [comment]
so whispers don't take gameno arguements, they just go the the primary game, could it be you context switched to quickly and by the time the whisper did the round trip from you  -> fics -> you the primary number had changed ?

Possibly a race condition between fics getting the new primary gameno and fics processing the whisper

Might be worth checking the log to see if the primary gameno changed before it processed the whisper?

**Comment by gbtami** [comment]
From http://www.freechess.org/Help/HelpFiles/whisper.html
If you are playing a game, the message will be sent to observers of your
game.  If you are not playing a game, the message will be sent to observers of
the 'primary' game in your observation queue.  (For details on the primary
queue, read "help primary".)
As I understand this if I play a game, any chat I type in any other observation game chat panels will be sent to my played game observers. So if I want to whisper in my observation games, I should stop playing game first. So this is not a PyChess bug, but a feature :) We can send whispers to our played game observers from any other ob game chat panel :)

**Comment by cajone** [comment]
Agreed, Think you should just close this, this is a fics facility nothing we can do about it

**Comment by gbtami** [comment]
Maybe we can disable observation games chat as long as a played game is in progress.

**Comment by cajone** [comment]
I don't really have an opinion on this, but if you feel its beneficial / less confusing then yes

**Comment by gbtami** [comment]
I think I leave this as is for now.
