### ISSUE TITLE
Tournament Calendar

### ISSUE THREAD

**Issue by cajone** [pychess/pychess#1129]
One thing I have not seen in any other FICS client which I think might be of interest to end users is a tournament calendar ( This not to say it does not exist, just I have never seen it)

Might be nice to be able to have a visualisation (via  a calendar) of events that happen on FICS ( possible with alarm notifications) a list of events are kept here although we might be able to extract this information directly via a FICS connection 

http://www.freechess.org/Events/Scheduled/

Possible Enhancement , Comments please ?

**Comment by gbtami** [comment]
Good idea!

**Comment by massimiliano-leoni** [comment]
I like it too!

**Comment by gbtami** [comment]
Maybe we should use info from fics mamer too. Just have to parse its output:

11:29:09) tell mamer listtourneys
(11:29:09) (told mamer)
(11:29:09) :mamer's tourney list:
(11:29:09) :
(11:29:09) :+----------------------------------------------------------------------------+
(11:29:09) :| ID   | Status    | Manager           | Type               | Start Date     |
(11:29:09) :|------|-----------|-------------------|--------------------|----------------|
(11:29:09) :| 1    |  done*    | fridayknights     | 15 0 r SS\4        | 2017.0618.2345 |
(11:29:09) :| 2    |  done*    | fridayknights     | 15 0 r SS\4        | 2017.0620.1800 |
(11:29:09) :| 3    |  done*    | fridayknights     | 5 0 r SS\5         | 2017.0617.2204 |
(11:29:09) :| 4    |  done*    | fridayknights     | 5 0 r SS\5         | 2017.0618.0740 |
(11:29:09) :| 5    |  done*    | fridayknights     | 5 0 r SS\5         | 2017.0620.2215 |
(11:29:09) :| 6    |  done*    | fridayknights     | 5 0 r SS\5         | 2017.0622.2201 |
(11:29:09) :| 7    |  done*    | knubbel           | 15 0 r SS\4        | 2017.0619.0532 |
(11:29:09) :| 8    |  done*    | knubbel           | 15 0 r SS\4        | 2017.0621.1800 |
(11:29:09) :| 9    |  done*    | fridayknights     | 15 0 r SS\4        | 2017.0622.2307 |
(11:29:09) :| 10   | +open<    | knubbel           | 15 0 r SS\4        | -------------- |
(11:29:09) :| 11   |  done*    | fridayknights     | 5 0 r SS\5         | 2017.0615.2200 |
(11:29:09) :| 12   |  done*    | fridayknights     | 5 0 r SS\5         | 2017.0616.2208 |
(11:29:09) :| 13   |  done*    | fridayknights     | 3 0 r los RR       | 2017.0618.1101 |
(11:29:09) :| 16   |  done*    | LightKnight       | 3 0 r SS\3         | 2017.0616.1711 |
(11:29:10) :| 17   |  done*    | Headbanger        | 1 0 r SS\5         | 2017.0619.1429 |
(11:29:10) :| 18   |  done*    | Headbanger        | 1 0 r SS\5         | 2017.0619.1454 |
(11:29:10) :| 19   |  done*    | Headbanger        | 1 0 r SS\5         | 2017.0619.1513 |
(11:29:10) :| 20   |  done*    | fridayknights     | 5 0 r SS\5         | 2017.0619.2202 |
(11:29:10) :+----------------------------------------------------------------------------+
(11:29:10) :
(11:29:10) :Use "td next" to see the next page.
