### ISSUE TITLE
History of a player

### ISSUE THREAD

**Issue by cajone** [pychess/pychess#1130]
I don't know if this is an issue or a designed function, but if I select the archived tab from the chat window it shows me a list of games I have played recently.

If I then go to the console and type 'history some_other_player' the archive window shows me a list of there recent games.

Is this intentional ?

Update: I guess its a bug since if I then click on examine one of the other players games I get back a message in the console 'There is no history game <gameno> for pgg

**Comment by gbtami** [comment]
At the same time  fixing the bug maybe we should turn this into a feature adding a "History "button to players tab, and "My archived" games button to archive panel. What do you think?

**Comment by cajone** [comment]
Yes sure agreed

**Comment by gbtami** [comment]
Bug fixed.
