### ISSUE TITLE
Load recent game feature not working

### ISSUE THREAD

**Issue by massimiliano-leoni** [pychess/pychess#1134]
I have this weird problem with the feature: I have the "auto save game" option enabled, so that every game of mines gets saved as "/tmp/P1 vs P2.pgn".
Now after I finish a game if I go to "load recent game" I correctly see it in the list [and the path is correct], but if I try to open it it just gives me a blank game, starting position.
If I open the game with "Load game" it works as expected.

**Comment by gbtami** [comment]
Added a new --purge-recent command line argument to get rid of old pychess entries in ./local/share/recently-used.xbel too.

**Comment by massimiliano-leoni** [comment]
Fix confirmed, thanks!
