### ISSUE TITLE
Add confirmation dialog to log off

### ISSUE THREAD

**Issue by massimiliano-leoni** [pychess/pychess#1135]
The "log off" button is dangerously close and similar to the "show chat" and "show console" ones.
It still hasn't happened but I think it's just a matter of time before I accidentally click that instead of one of the others.

In that case, it would be nice to have a confirmation dialog window asking me if I really want to log off, especially if I am playing a game.

**Comment by gbtami** [comment]
I'v moved it to main app toolbar in "perspectives". Do we need confirmation dialog after this change?

**Comment by massimiliano-leoni** [comment]
Of course not!
