### ISSUE TITLE
My seeks are no more visible in the Seeks tab

### ISSUE THREAD

**Issue by massimiliano-leoni** [pychess/pychess#1136]
As per title, commit 81399ae974bfbcabe4c5f0027ae3df36b278fbe7 introduced this regression: I can no longer see my seeks in the relative tab, even though they are being posted as someone accepted them.

I also would like to point out that before that commit I could check in the console how many players could see the seek, looking for the relative "(4 player(s) saw the seek.)" message, which is now filtered out but I found useful.

In general, I do like the filter on the console text, but I would not filter this particular piece of information.

**Comment by gbtami** [comment]
Reproduced, thx!
