### ISSUE TITLE
Sounds are messed up when moving in a variation

### ISSUE THREAD

**Issue by massimiliano-leoni** [pychess/pychess#1137]
1. Open a game
2. Go back to a move in the middlegame and explore a variation by clicking on the piece you want to move and then on the destination square: no sound is played [should play a move sound?]
3. Explore the variation by dragging a piece from its position to the destination square: the invalid move sound is played [this should not happen].

**Comment by gbtami** [comment]
In variations we never play sounds, just in main line, so fixed 3. only.
