### ISSUE TITLE
Variable number of seeks

### ISSUE THREAD

**Issue by massimiliano-leoni** [pychess/pychess#1139]
Main use case: I am currently issuing always the same two seeks, which I have stored in number 1 and 2 of the default seeks. Number 3 is unused, but is still issued when I press "Send all seeks".

Any means to have me send the first two seeks with one button is acceptable: I was thinking of making the number of default seeks a variable, fine if bounded; another possibility is to let the user disable a default seek so that it is not issued with the "send all seeks" button. This latest option sounds a little bit confusing though, so I would go for the first one.

Other suggestions are welcome. I know I am lazy person, but clicking once is better than thrice :D

**Comment by cajone** [comment]
may replace the send all seek button with a set of 3 on/off toggles next to each seek, or for the one you don't want ( if this a regular thing) just change its setting to match one of the others?

So you still issue 3 seeks but they look like 2

**Comment by gbtami** [comment]
Ok, the 3 check boxes over radio button wins.
