### ISSUE TITLE
Console auto-opening

### ISSUE THREAD

**Issue by massimiliano-leoni** [pychess/pychess#1153]
Can we have an option [disabled by default] to have the console automatically open on fics login?

**Comment by cajone** [comment]
Can't see why not as long as its a preference setting to toggle on / off

**Comment by gbtami** [comment]
Console is panelized and dockable in FICS perspective now.

**Comment by massimiliano-leoni** [comment]
This way it's fine! I haven't played for a while, the new GUI is nice!

[OT]What is the "Database" button for?[/OT]

**Comment by gbtami** [comment]
It's for database "perspective". I'v just started it. It will handle .pgn and .pdb(pychess own sqlite format) databases. I plan to add some dockable panels to it, like board preview,  databases list panel, filter panel. Later an opening tree too. The main app tollbar will give import/export toolbuttons etc. And preferences->autosave->toDatabase option.

**Comment by massimiliano-leoni** [comment]
Sounds good! Looking forward to it!
