### ISSUE TITLE
Observers panel closed by default

### ISSUE THREAD

**Issue by massimiliano-leoni** [pychess/pychess#1154]
Now that there is an "Observers" panel inside the chat widget, I noticed it is usually at zero height by default. Is it possible to have this behaviour changed? [Provided it is intended]

Maybe an option to have it by default high enough to accommodate for a line of names?

**Comment by cajone** [comment]
hmm this is not my experience, my observer panel is 2-3 line high by default

( but it is very possible I configured it this way and it was saved as part of my preferences)

**Comment by massimiliano-leoni** [comment]
I just tried again, maybe it doesn't keep the setting?

**Comment by cajone** [comment]
This what I have and it persists between sessions 

![screenshot at 2016-01-28 16 20 33](https://cloud.githubusercontent.com/assets/6152957/12650631/6a1e024c-c5db-11e5-9420-221a5a472077.png)

**Comment by massimiliano-leoni** [comment]
I _did_ get it. Here's mine
![screenshot23](https://cloud.githubusercontent.com/assets/12351309/12650775/6143d792-c5e4-11e5-9637-a8f04631211f.jpeg)

**Comment by cajone** [comment]
if you pull the line between the chat and the observer panel does it not stay there next time you start?

or try pulling it up so the annotation panel is smaller?

**Comment by massimiliano-leoni** [comment]
No, that's what I've been trying to say.

**Comment by cajone** [comment]
Ok we need to find a way to better proportion the chat window so we get at least one line for the observer panel

**Comment by massimiliano-leoni** [comment]
Very nice, now it is self-resizing :)
