### ISSUE TITLE
Use "pylichess" and "pylichess_cheat"

### ISSUE THREAD

**Issue by ghost** [pychess/pychess#1156]
I discover that for now there are two Python-based projects, that use lichess.org HTTP API:
1) https://github.com/CamdenClark/pylichess
2) https://github.com/NikolaiT/lichess_cheat
So, is it possible implement them to "pychess"?
Or maybe there is some simpler way to make desktop client app for Lichess using Python?

**Comment by gbtami** [comment]
See #893

**Comment by cajone** [comment]
Can't see a use for this type of interface unless you wanted to run an engine in the background and front end it like a human player. Hence dragging Pychess into the muddy waters or cheatware, no thanks !

What was the reason for your request?

**Comment by gbtami** [comment]
@Symbian9 as @JoeIMon mentioned in #1332 there are more API exist to play on lichess.org, so this is possible. (I don't reopen this issue and #893, #1332 will be open to further discussion. )
