### ISSUE TITLE
Analyzer evaluation visible when playing online

### ISSUE THREAD

**Issue by massimiliano-leoni** [pychess/pychess#1158]
1. Observe a game with analyzer turned on [Hints]
2. Start a new game meanwhile
3. "Annotation" panel shows evaluation values
4. Disable by Ctrl+H or use it to beat Magnus Carlsen :D 

![screenshot24](https://cloud.githubusercontent.com/assets/12351309/12661571/aa2aa3f6-c61a-11e5-9abb-a56207900f30.jpeg)

**Comment by gbtami** [comment]
I can't reproduce this. Strange.

**Comment by gbtami** [comment]
I can reproduce something similar with starting analyze menu or changing hint settings while playing.
Have you disabled/enabled/changed hint analyzer settings while playing/observing this two game?
