### ISSUE TITLE
Endgame table not working on move before promotion

### ISSUE THREAD

**Issue by massimiliano-leoni** [pychess/pychess#1161]
When there are less than seven pieces on the board, the endgame table shows up in the Hints panel to show endings of the game. However, I experienced that the table won't show up if the possible moves include a promotion. It comes back at the following move though. See screenshot [but don't look at how stupid I was to draw a won position :'( ]

![screenshot25](https://cloud.githubusercontent.com/assets/12351309/12679001/f85f51d4-c6a1-11e5-8705-69557c22f47f.jpeg)

Curiously enough, this doesn't happen all the time: if I setup a position manually, the table shows up even before a promotion.

**Comment by gbtami** [comment]
Nice catch, thx!
