### ISSUE TITLE
desired functions in pychess

### ISSUE THREAD

**Issue by chessobbo** [pychess/pychess#1183]
1. Be able to ignore players in the listings of games offered.
2. Added new chess version where one can take one's own material. Like in war you can sacrifice your own men to achieve the goal. Call it Holmberg.

**Comment by gbtami** [comment]
1. is same as #785 
2. Is this an existing chess variant? Can you provide a link where the rules are described, please?

**Comment by chessobbo** [comment]
It is not a chess variant I know of, but I invented it. Take your own material as if it is the opponent's.

**Comment by chessobbo** [comment]
If you decide to include it in PyChess, call the version Holmberg, or Chess Holmberg, or Holmberg Tactical, or Tactical Holmberg. Keep it simple and descriptive.

**Comment by gbtami** [comment]
If you like to accept any new chess variant in pychess you should provide a detailed consistent description of rules somewhere. I suggest you to start a discussion on talkchess.com forum about it first.

**Comment by gbtami** [comment]
Thinking more about it I have to say this needs nearly total rewrite of pychess core functions (move generation, validation, evaluation, etc.), so it will never go to pychess unless you send a working patch :)
