### ISSUE TITLE
Support for chess engine opening books

### ISSUE THREAD

**Issue by pychess** [pychess/pychess#123]
Original [issue 123](https://code.google.com/p/pychess/issues/detail?id=123) reported by [wouterstomp](https://code.google.com/u/102934909087409897177/) 2006-12-24

I don't know if pychess supports this already or not, but for several chess
engines, including gnuchess and crafty, you can install opening books which
pychess could take advantage of.

**Comment by pychess** [comment]
Original [comment 1.](https://code.google.com/p/pychess/issues/detail?id=123#c1) posted by [lobais](https://code.google.com/u/lobais/) 2006-12-26

It would be nice to have converters for the different engines opening books.
I've been looking at the crafty source code, and it might be doable.
Gennerelly a better openingbook, with more than 2000 kasparov games, would be nice.
- changed status to: Accepted
- removed label: Defect
- removed label: Medium
- added label: Enhancement
- added label: Low

**Comment by pychess** [comment]
Original [comment 2.](https://code.google.com/p/pychess/issues/detail?id=123#c2) posted by [gbtami](https://code.google.com/u/gbtami/) 2010-04-29

Maybe we can add support for "OwnBook" and "Book File" options for UCI engines.

Another enhancement can be adding polyglot format book support:
http://alpha.uhasselt.be/Research/Algebra/Toga/book\_format.html

**Comment by pychess** [comment]
Original [comment 3.](https://code.google.com/p/pychess/issues/detail?id=123#c3) posted by [UncombedCoconut](https://code.google.com/u/101407884191342298754/) 2011-04-14

I just saw this CTG book reader code:
https://github.com/AaronBecker/daydreamer/blob/release/book\_ctg.c
(An older unofficial spec http://rybkaforum.net/cgi-bin/rybkaforum/topic\_show.pl?pid=26942 may clarify.)

PolyGlot is the most popular open format, used by SCID and many engines. It has good FOSS book-generation tools.
CTG ChessBase's closed format. It's the most popular among book-makers; many offer free (gratis) high-quality books.

If we support these two formats and let the user pick a book file, I think we can close the issue.
I'm also in favor of killing the existing SQLite book format and book-making code.

**Comment by pychess** [comment]
Original [comment 4.](https://code.google.com/p/pychess/issues/detail?id=123#c4) posted by [lobais](https://code.google.com/u/lobais/) 2011-04-15

Yup, let's support PolyGlot first.
If the api good enough, people may contribute code for the rest.
Adding CTG as well is a good test, that the api isn't PolyGlot centric.

**Comment by pychess** [comment]
Original [comment 5.](https://code.google.com/p/pychess/issues/detail?id=123#c5) posted by [gbtami](https://code.google.com/u/gbtami/) 2011-12-06
- changed status to: Started

**Comment by pychess** [comment]
Original [comment 6.](https://code.google.com/p/pychess/issues/detail?id=123#c6) posted by [gbtami](https://code.google.com/u/gbtami/) 2012-09-13

There is a new topic on TalkChess: Polyglot keys for chess variants.
http://talkchess.com/forum/viewtopic.php?topic\_view=threads&p=482216&t=45121

And the new extension suggested by H.G.Muller(author of Winboard):
http://hgm.nubati.net/book\_format.html

This can be interesting when PyChess will support more variants.

**Comment by gbtami** [comment]
https://github.com/niklasf/lila-openingexplorer has public API
