### ISSUE TITLE
Problem with some of the themes

### ISSUE THREAD

**Issue by JoelMon** [pychess/pychess#1331]
Some of the themes turns the pieces and pawns to gray instead of black and white. For example the Alpha theme. Other themes affected: Alfonso, Leipzig, Magnetic, Maya, etc. (PyChess Anderssen 0.12beta3)

![screenshot_2016-03-01_13-14-28](https://cloud.githubusercontent.com/assets/6587811/13437027/3227ed32-dfb0-11e5-9a0a-69acfdc6cb01.png)

**Comment by gbtami** [comment]
Install the latest PyChess from here: https://github.com/pychess/pychess/releases
You can find package dependencies here: https://github.com/pychess/pychess/blob/master/INSTALL

**Comment by JoelMon** [comment]
I'll give that a shot
