### ISSUE TITLE
PyChess with Tkinter GUI

### ISSUE THREAD

**Issue by ghost** [pychess/pychess#1335]
Is it possible replace default Py-Gtk GUI with Tkinter GUI?

Here is demo video where author sad that it's a PyChess with Tkinter
https://youtube.com/watch?v=CjFFnuTBUoM

If Tkinter is default python GUI library, then it would be better remove dependency to many external dependency such as Pango, python-cairo and other non-standart python library.

**Comment by cajone** [comment]
If that is a Tkinter gui api, it would seem the author has already done a large amount of work to port it.

Maybe if the author made his clone available and came over to #pychess on freenode irc  we could talk about it. I personally would like to see the project support QT4/5 as a gui api interface, but that's just my 2 cents worth. 

We are a very small team currently only 2 people really active in development with the odd piece of very welcome code coming from others, so any assistance from others is welcome ( I think I speak for btami here also )

Do you know the author at all ?

**Comment by gbtami** [comment]
Porting PyChess to any other GUI toolkit is really _huge_ amount of work. Gtk3 is just an upgrade from Gtk2 , but porting to it took several months! We have so many plans and feature requests enough work for long years :)
