### ISSUE TITLE
CPU full usage when connecting to FICS lounge

### ISSUE THREAD

**Issue by massimiliano-leoni** [pychess/pychess#1336]
I noticed this today for the first time: when I connect to the FICS lounge, the python process that runs pychess starts using a whole core continuously, while it is doing nothing apparently.

Maybe some part of pychess does not get along with some package I recently upgrade? How can I find out?

**Comment by gbtami** [comment]
This is too few info to tell anything :(

**Comment by massimiliano-leoni** [comment]
I was expecting this. What more information can I give?

**Comment by gbtami** [comment]
You can try to run pychess with: pychess --idle-add-debug --thread-debug --log-viewer
and look into View->Log Viewer or .log file.

**Comment by massimiliano-leoni** [comment]
I run it, I attach the log file for a session in which I simply connected to FICS and waited a bit, while the CPU was going at full speed.

[2016-03-10_12-32-39.txt](https://github.com/pychess/pychess/files/167034/2016-03-10_12-32-39.txt)

**Comment by gbtami** [comment]
As I see from .log the guest login of helper connection is stucked somehow. Added some more debug log. git pull, try and attach the .log again please!

**Comment by massimiliano-leoni** [comment]
Done, now it takes much longer to open, and the log file is about 400 MB for just connecting to FICS and closing pychess immediately.

I also got a backtrace:
`/opt/pychess/lib/pychess/ic/ICLogon.py:164: Warning: Source ID 148 was not found when attempting to remove it
  GObject.source_remove(self.pulser)
Exception in thread FICSHelperConnection.run:281:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/opt/pychess/lib/pychess/ic/FICSConnection.py", line 285, in run
    self._connect()
  File "/opt/pychess/lib/pychess/ic/FICSConnection.py", line 207, in _connect
    "guest connections have been prevented")
  File "/opt/pychess/lib/pychess/ic/TimeSeal.py", line 215, in read_until
    log.debug(not_find, extra={"task": (self.name, "raw")})
AttributeError: 'NoneType' object has no attribute 'debug'
`

And here is the zipped log 
[2016-03-10_14-58-53.log.zip](https://github.com/pychess/pychess/files/167241/2016-03-10_14-58-53.log.zip)

**Comment by gbtami** [comment]
The reason (from .log) is:
"Due to abusive behavior, nobody from your site may login without an account.
If you wish to use this server, please register at http://www.freechess.org"

**Comment by massimiliano-leoni** [comment]
Curious, I do have an account...

**Comment by massimiliano-leoni** [comment]
Wooohooo! Wonderful! Thanks.

**Comment by gbtami** [comment]
@massimiliano-leoni pychess uses 2 connection to fics. 1. a normal with your accont  and 2. a helper with a guest account. The latter is for track games/players with gin/pin/availinfo set on without scrambling users own variables. see #608 and #1066 
Committed a fix to let you connect to fics without helper(guest) connection, but this has the consequence players/games panels are not updated at all.
Anyhow it would be good to know who/when/why was abusive from your site. Ask fics admins please!

**Comment by massimiliano-leoni** [comment]
Yes, I see the consequences... It is still barely usable, how do I do without the gui updating?

I will try to find out what the abuse was, but I play from home so I don't know what to think...

**Comment by gbtami** [comment]
Fixed #1066 , so players/games will be updated if you enable gin, availinfo, open  variables to set on by pychess.
