### ISSUE TITLE
Playing a perfect endgame

### ISSUE THREAD

**Issue by massimiliano-leoni** [pychess/pychess#1337]
When six or less pieces are on the board, all possible outcomes are known via endgame tables. In such a situation, the endgame list shows all possible moves with the associated result and needed plys.

What would be nice to have is an option to select a move from this list and play that line until the checkmate, having both sides play the best move from there on, where of course we call "the best move" the one that leads the winning side to mate in fewer moves and the the one that leads the losing side the be mated in as many moves as possible.
The line should be added as a variation to the Annotations panel.

**Comment by massimiliano-leoni** [comment]
How do you trigger that? I can't see it!

**Comment by gbtami** [comment]
Just double click on egtb move. Same way you can add analyzing (hint/spy) engine PV lines as variations.

**Comment by massimiliano-leoni** [comment]
Double-clicking only adds the first move on my machine, not the whole variation.

**Comment by gbtami** [comment]
Exactly. Egtbs are not engines. They doesn't provide whole variations just
DTM info per one move. You have to double click again and again to see
different variations.

**Comment by massimiliano-leoni** [comment]
Yes, I got it. Nevertheless, I would like the double-click action to insert the whole endgame "as if" I double-clicked on the first table-base entry until checkmate.

**Comment by gbtami** [comment]
You are right. I was too happy when I was implementing my one move
"solution" and stopped to fix the whole issue :) My bad. I will implement
the rest of course.

**Comment by massimiliano-leoni** [comment]
Very nice! Now that it's implemented, do you like it like I do? :)

**Comment by gbtami** [comment]
Absolutely! :)
