### ISSUE TITLE
pychess-0.12.3-1.py27.noarch.rpm installation failure 

### ISSUE THREAD

**Issue by mattgatto** [pychess/pychess#1340]
[gatto@fedora-20 Downloads]$ sudo yum install pychess-0.12.3-1.py27.noarch.rpm 
Loaded plugins: langpacks, refresh-packagekit
Examining pychess-0.12.3-1.py27.noarch.rpm: pychess-0.12.3-1.py27.noarch
Marking pychess-0.12.3-1.py27.noarch.rpm as an update to pychess-0.12-1.py27.noarch
Resolving Dependencies
--> Running transaction check
---> Package pychess.noarch 0:0.12-1.py27 will be updated
---> Package pychess.noarch 0:0.12.3-1.py27 will be an update
--> Finished Dependency Resolution

Dependencies Resolved
# 
#  Package          Arch            Version                Repository                              Size

Updating:
 pychess          noarch          0.12.3-1.py27          /pychess-0.12.3-1.py27.noarch           13 M
# Transaction Summary

Upgrade  1 Package

Total size: 13 M
Is this ok [y/d/N]: y
Downloading packages:
Running transaction check
Running transaction test
Transaction test succeeded
Running transaction (shutdown inhibited)
  Updating   : pychess-0.12.3-1.py27.noarch                                                       1/2 
Error unpacking rpm package pychess-0.12.3-1.py27.noarch
error: unpacking of archive failed on file /usr/share/pychess/flags/pl.png;56ec5692: cpio: read
  Verifying  : pychess-0.12.3-1.py27.noarch                                                       1/2 
pychess-0.12-1.py27.noarch was supposed to be removed but is not!
  Verifying  : pychess-0.12-1.py27.noarch                                                         2/2 

Failed:
  pychess.noarch 0:0.12-1.py27                     pychess.noarch 0:0.12.3-1.py27                    

Complete!
[gatto@fedora-20 Downloads]$

**Comment by gbtami** [comment]
Works for me with package downloaded from pychess.org. Maybe your download is demaged.

[tamas@localhost Letöltések]$ sudo yum install pychess-0.12.3-1.py27.noarch.rpm  
[sudo] password for tamas: 
Betöltött bővítmények: langpacks
Repodata is over 2 weeks old. Install yum-cron? Or run: yum makecache fast
pychess-0.12.3-1.py27.noarch.rpm felülvizsgálata: pychess-0.12.3-1.py27.noarch
pychess-0.12.3-1.py27.noarch.rpm megjelölése, mint pychess-0.12rc4-1.py27.noarch frissítése
Függőségek megállapítása
--> Tranzakció ellenőrzés futtatása
---> A(z) pychess.noarch 0:0.12rc4-1.py27 csomaggal a következő történik: frissítve
---> A(z) pychess.noarch 0:0.12.3-1.py27 csomaggal a következő történik: egy frissítés
--> A függőségvizsgálat véget ért
fedora/20/x86_64/metalink                                | 3.5 kB     00:00  
updates/20/x86_64/metalink                               | 3.3 kB     00:00     

Függőségek Megtalálva

# 

#  Package    Arch      Verzió             Tároló                           Méret

Frissítés:
 pychess    noarch    0.12.3-1.py27      /pychess-0.12.3-1.py27.noarch     13 M

# Tranzakció Összegzés

Frissítés  1 Package

Teljes méret: 13 M
Is this ok [y/d/N]: y
Downloading packages:
Running transaction check
Running transaction test
Transaction test succeeded
Running transaction
  Frissítés     : pychess-0.12.3-1.py27.noarch                              1/2 
  Tisztítás     : pychess-0.12rc4-1.py27.noarch                             2/2 
  Ellenőrzés    : pychess-0.12.3-1.py27.noarch                              1/2 
  Ellenőrzés    : pychess-0.12rc4-1.py27.noarch                             2/2 

Frissítve:
  pychess.noarch 0:0.12.3-1.py27                                                

Kész!
[tamas@localhost Letöltések]$

**Comment by mattgatto** [comment]
I guess it was a corrupted download, because I deleted the old copy, downloaded a new one, and it installed fine.
