### ISSUE TITLE
Backtrace when closing pychess with FICS lounge open

### ISSUE THREAD

**Issue by massimiliano-leoni** [pychess/pychess#1344]
A recent commit introduced a bug causing this backtrace to appear at some point while I use pychess.
I have seen this after closing pychess in the console, so I am not sure what is causing it, but will pay more attention.

```
Traceback (most recent call last):
  File "/opt/pychess/lib/pychess/ic/ICLounge.py", line 1794, in onGameAdd
    game.display_text, game.display_rated)
  File "/opt/pychess/lib/pychess/ic/FICSObjects.py", line 554, in display_rated
    return _("Unrated")
TypeError: 'NoneType' object is not callable
```

**Comment by massimiliano-leoni** [comment]
More info: the backtrace appears when closing pychess.

**Comment by massimiliano-leoni** [comment]
Here's how to reproduce:
1. Launch pychess
2. Connect to FICS
3. Close pychess from the main window, which triggers the closing of the FICS lounge as well

Curiously enough, if I separately close the FICS lounge and then close pychess the backtrace does not show up.

**Comment by gbtami** [comment]
I think this is a cleanup on quit process weakness of pychess. Fics games and players are (start/stop in/out) are handled from a secondary (guest) connection started from another thread. If you don't close fics before quit it may happen that some games are started to add to the GUI in helper thread. And while main python thread finishing it's cleaning up builtins module where _() belongs to. It's a function alias of gettext() placed into builtins on pychess start.

Committed a possible fix. Can you try it please?

**Comment by massimiliano-leoni** [comment]
Looks like you did it again: fix confirmed!
