### ISSUE TITLE
Dialogs don't have title

### ISSUE THREAD

**Issue by massimiliano-leoni** [pychess/pychess#1346]
Dialogs opened by the "finger" or "assess" buttons do not have a label in the windows toolbar just like other pychess windows.
This means that if they go to the background it becomes difficult to find and close them. It would be better if these dialogs had a window label for themselves, and even more so since they do block the rest of pychess until they are closed.

See screenshot for more clarity. 
![schermata1](https://cloud.githubusercontent.com/assets/12351309/14148133/9d374a78-f69e-11e5-8242-e1afb0d278b1.png)

**Comment by massimiliano-leoni** [comment]
Mmm, adding the title did not solve the issue for me...

**Comment by gbtami** [comment]
Are you sure you are on latest git version?

**Comment by massimiliano-leoni** [comment]
Yes, git log gives me 772a04a0db489bc24f2ec5f275b299db094bd0c8 as the first commit, and the dialogs do have a title now.
