### ISSUE TITLE
Annotation panel broken

### ISSUE THREAD

**Issue by massimiliano-leoni** [pychess/pychess#1353]
When I hover the mouse on one of the moves in the annotation panel I get a lot of

```
  File "/opt/pychess/sidepanel/annotationPanel.py", line 214, in motion_notify_event
    offset = it.get_offset()
AttributeError: '_ResultTuple' object has no attribute 'get_offset'`
```

in the console and navigation is unusable.

**Comment by gbtami** [comment]
I can't reproduce this. Can you give some more info please?

**Comment by massimiliano-leoni** [comment]
It's even more general than I thought. Here are the steps:
1. Run `pychess` from a terminal
2. Start a new game
3. Move the mouse to the Annotation panel, even without doing any move.

Backtraces like the one I posted above come out in great number.

**Comment by gbtami** [comment]
Strange, all OK here with above steps.

**Comment by gbtami** [comment]
Seems return type of get_iter_at_location() changed in newer Gtk version. See the same issue in gramps https://gramps-project.org/bugs/view.php?id=9335

**Comment by gbtami** [comment]
Committed a fix. Test it please!

**Comment by massimiliano-leoni** [comment]
Almost there, now the backtrace appears only when clicking, not when hovering.

**Comment by gbtami** [comment]
Can you paste the new Traceback here please?

**Comment by massimiliano-leoni** [comment]
Similar to the other, just in another function

```
Traceback (most recent call last):
  File "/opt/pychess/sidepanel/annotationPanel.py", line 235, in button_press_event
    offset = it.get_offset()
AttributeError: '_ResultTuple' object has no attribute 'get_offset'
```

**Comment by gbtami** [comment]
Fixed, thx!

**Comment by massimiliano-leoni** [comment]
Fix confirmed, good job!
