### ISSUE TITLE
Segfault on second match

### ISSUE THREAD

**Issue by massimiliano-leoni** [pychess/pychess#1354]
Just found a critical one:
1. Run `pychess`
2. Start new game, even against computer
3. Play or close the game, even without a single move
4. Start a new game once again

Result: `pychess` crashes with a segfault.

**Comment by gbtami** [comment]
Du you got any Traceback in console?
I can't reproduce this. Is this reproducible for you?

**Comment by massimiliano-leoni** [comment]
It is reproducible, always.
Here is the full backtrace of gdb when running python2 with debugging symbols
http://pastebin.com/j2QSUVUw

And this is what I get in the terminal when running with python3

```
$ cd /opt/pychess/ && python3 pychess

(pychess:3577): Gtk-CRITICAL **: gtk_css_gadget_get_border_allocation: assertion 'GTK_IS_CSS_GADGET (gadget)' failed

(pychess:3577): Gtk-CRITICAL **: gtk_css_gadget_get_border_allocation: assertion 'GTK_IS_CSS_GADGET (gadget)' failed

(pychess:3577): Gtk-CRITICAL **: gtk_css_gadget_get_border_allocation: assertion 'GTK_IS_CSS_GADGET (gadget)' failed

(pychess:3577): Gtk-CRITICAL **: gtk_css_gadget_get_border_allocation: assertion 'GTK_IS_CSS_GADGET (gadget)' failed

(pychess:3577): Gtk-CRITICAL **: gtk_css_gadget_get_border_allocation: assertion 'GTK_IS_CSS_GADGET (gadget)' failed

(pychess:3577): Gtk-CRITICAL **: gtk_css_gadget_get_border_allocation: assertion 'GTK_IS_CSS_GADGET (gadget)' failed
Fatal Python error: Segmentation fault

Thread 0x00007fd8f58f1700 (most recent call first):
  File "/usr/lib/python3.5/threading.py", line 293 in wait
  File "/usr/lib/python3.5/queue.py", line 164 in get
  File "/opt/pychess/sidepanel/bookPanel.py", line 356 in run
  File "/usr/lib/python3.5/threading.py", line 914 in _bootstrap_inner
  File "/usr/lib/python3.5/threading.py", line 882 in _bootstrap

Current thread 0x00007fd931849700 (most recent call first):
  File "/opt/pychess/lib/pychess/widgets/gamewidget.py", line 1089 in attachGameWidget
  File "/opt/pychess/lib/pychess/widgets/ionest.py", line 42 in generalStart
  File "/opt/pychess/lib/pychess/widgets/TaskerManager.py", line 222 in startClicked
  File "/opt/pychess/lib/pychess/Main.py", line 543 in run
  File "pychess", line 179 in <module>
Errore di segmentazione

```

**Comment by gbtami** [comment]
Maybe this is caused by another Gtk change like #1353 Maybe not.
Can you try to downgrad your gtk to 3.18.x please? I have no other idea.

**Comment by massimiliano-leoni** [comment]
Downgrading is a bit of a pain, but I could try that later. In any case the problem will show up again as soon as more conservative distributions upgrade their versions as well.

**Comment by gbtami** [comment]
I'm not sure this is the case. I'm just guessing here :(

**Comment by gbtami** [comment]
The Gtk-CRITICAL lines are scary too. I never see those here.

**Comment by massimiliano-leoni** [comment]
Yes, those lines appear when `pychess` crashes.

**Comment by gbtami** [comment]
Is this the same on FICS opening any second game?

**Comment by massimiliano-leoni** [comment]
Yes, and also mixing.

**Comment by gbtami** [comment]
Another idea. As the Traceback shows only 2 threads running and the second is checking for egtb. Can you try to turn off analyzers, opening book and tablebase(!) hints too please? Just let us see if this is a threading issue or not.

**Comment by massimiliano-leoni** [comment]
I will try and I will get back to you in ten days :)

**Comment by massimiliano-leoni** [comment]
This is still in my TODO list, will get back sooner or later :D

**Comment by gbtami** [comment]
Np. thx!

**Comment by massimiliano-leoni** [comment]
Here I am! Interesting stuff, it crashes even without all those things.
Even more, and this is the piece of news, it crashes even if I
1. start `pychess`
2. open `Preferences`
3. go to `Sidepanels` [this loads the chessboard in the other window, and counts as starting the first game
4. change tab
5. go back to `Sidepanels`

So the bug seems to be related to loading the chessboard a second time.

**Comment by gbtami** [comment]
I can't reproduce this in 16.04 and I feel this is gtk/pygobject version related. What package versions are you using?

**Comment by massimiliano-leoni** [comment]
My gtk version is 3.20.4-1 and my python-gobject version is 3.20.1-1.

I am using debian testing, so versions are updated according to https://packages.debian.org/search?keywords=python-gobject&searchon=names&suite=testing&section=all [use the top-right corner search line to search other packages in testing distribution].

**Comment by gbtami** [comment]
OK, finally I managed to install debian testing in virtualbox. I tried it several times in last months, but it always failed on tasksel step. Today daily ISO was Ok, and the bug was reproducible! \o/

**Comment by massimiliano-leoni** [comment]
That's a known bug of the installer, you could have asked me for the trick! Good to know its solved now and you can reproduce my bugs.

**Comment by massimiliano-leoni** [comment]
Fix confirmed, thanks!
