### ISSUE TITLE
Pychess failed to understand checkmate

### ISSUE THREAD

**Issue by ghost** [pychess/pychess#1355]
Hi,

I am running Debian Jessie with Pychess 0.12beta3 (installed via aptitude). While logged in at FICS and playing and unrated blitz game against a guest, Pychess did not understand that I checkmated my opponent:

![selection_009e](https://cloud.githubusercontent.com/assets/15808443/15155023/edb91c6c-16e0-11e6-8ab0-2923e2a9a4d5.jpg)

You can see in the bottom right that Pychess thinks that this is just check, while in the notation the checkmate is understood (as hinted by #). Also, there was no big yellow bar that usually appears after a game ends.

Pychess kept counting down his time and did not stop, even though I have the option auto call flag enabled (I guess this is just a result that the FICS server already ended that game as I won it).

As I am fairly new to both Pychess and FICS I don't know what more additional information I can provide you with - feel free to ask.

**Comment by gbtami** [comment]
This is rather old version of PyChess. Please install the latest version from https://github.com/pychess/pychess/releases where this is fixed.
Dependencies are listed here: https://github.com/pychess/pychess/blob/master/INSTALL
