### ISSUE TITLE
Limiting number of lines searched and min/max search depth of pychess.py

### ISSUE THREAD

**Issue by SchachMaster** [pychess/pychess#1356]
I want to change these values, but cannot find the appropriate section of the source code. I find this a more realistic way of limiting strength than the common method of making the engine randomly choose a move it knows is inferior.

**Comment by gbtami** [comment]
PyChess own engine is a CECP(Xboard) protocol engine so it uses "sd N" command to limit the nominal search depth to N ply.
See setOptionStrength() and __setDepth() in lib/pychess/Players/CECPEngine.py
No "number of lines searched" command exist in CECP protocol.
