### ISSUE TITLE
Hints off by default.

### ISSUE THREAD

**Issue by gbtami** [pychess/pychess#1359]
My son and hes girlfriend played a human-human game using PyChess. (This was the very first time they used PyChess.) After the game he suggested all hints should be off by default on book panel.

**Comment by bboutkov** [comment]
Hmm default = off I think is safer for most situations.

Really though, I think the the hints should really be on or off depending on the game mode.
For example when you observe a game, it makes sense to have them on, yet If I play vs puzzlebot on FICS, hints should certainly be off to not ruin the puzzle. Also playing most game types would certainly make sense to be off by default as you pointed out.

**Comment by gbtami** [comment]
Ok, I think i will change initial defaults to be off. Thx for the answer!

**Comment by bboutkov** [comment]
I dont think this is properly implemented. For example, if I do:
"tell puzzlebot gm" in console, a new game is started and hints are still on.

**Comment by gbtami** [comment]
Agreed.

**Comment by gbtami** [comment]
The "fix" is a little bit excessive. It disables hints not just on puzzlebot/endgamebot/etc but on all examined games. Creating correct fix is not easy because puzzle games created as observation games first by server and just later turned into examined.
