### ISSUE TITLE
Ics window, not closed, when rated game is playing and when main window is closed. (no abort, no resign).

### ISSUE THREAD

**Issue by kapitanf** [pychess/pychess#1361]
1, FatICS:

![bez nazvu 1](https://cloud.githubusercontent.com/assets/19979955/16227909/e7cc36a6-37b3-11e6-9876-b1d21921096a.png)

2, Seeking

![bez nazvu 2](https://cloud.githubusercontent.com/assets/19979955/16227934/18020b98-37b4-11e6-9456-14c0c0c0a17c.png)

3, First (linux) connected well, on windows (connected as user?). This work (seeking rated and unrated)

![bez nazvu3](https://cloud.githubusercontent.com/assets/19979955/16227991/7ad974e0-37b4-11e6-8cf5-1431c5b01ce6.png)

4, Last fail!!! (registered user vs. registered user)

![bez nazvu4](https://cloud.githubusercontent.com/assets/19979955/16228031/b6dae726-37b4-11e6-8080-d9214b93e126.png)

ics window cloased, when i close main window.

**Comment by kapitanf** [comment]
1, start application "python pychess"
2, Game/ Play Internet Chess
3, Name "mirrorring" Password "pass" Host: "freechess.org" Ports: "5000,23"
4, button "Connect"
5, Internet Chess: FICS , blitz, 5min, Rated
6, button "Send Seek", wait
7, Main Window, button "Close Without Saving"
8, your image 4

**Comment by kapitanf** [comment]
console window: cmd.exe , cd c:\pychess-master\ , python pychess
![bez nazvu 1](https://cloud.githubusercontent.com/assets/19979955/16229380/b99bf416-37bc-11e6-8423-ce81a0efc2bc.png)

**Comment by gbtami** [comment]
What is the problem in image 4.? You say "ics window cloased, when i close main window." This is the expected behavior, isn't it?

**Comment by kapitanf** [comment]
gbtami solved the problem. thanks
