### ISSUE TITLE
Dependency list updated on debian testing

### ISSUE THREAD

**Issue by massimiliano-leoni** [pychess/pychess#1362]
On a freshly installed Debian testing with KDE package `gir1.2-gtksource-3.0` is a dependency to run `pychess` but is not listed in the `INSTALL` file.

**Comment by gbtami** [comment]
I think it's there:
https://github.com/pychess/pychess/blob/master/INSTALL#L39

**Comment by massimiliano-leoni** [comment]
Mmm, sorry for missing that, my brain somehow skipped that line :D 
Never mind!

**Comment by gbtami** [comment]
Np.
By the way, i plan to release 0.12.4 this week. Do you know/like anything i should fix before release?

**Comment by massimiliano-leoni** [comment]
Not off top of my head, go for it!

**Comment by gbtami** [comment]
OK, thx!
