### ISSUE TITLE
News Items expanding ICLounge but not resizing when closed

### ISSUE THREAD

**Issue by cajone** [pychess/pychess#1363]
The News Items expand ( vertically) the size of the ICLounge when each item is opened, if the item is then closed the ICLounge does not shrink back to its original size

![image](https://cloud.githubusercontent.com/assets/6152957/16357901/9b596104-3afb-11e6-8d76-805042596bff.png)

**Comment by gbtami** [comment]
I'v put news into scrolled window in FICS perspective.
