### ISSUE TITLE
Problem with saving game and closing save dialog on Windows.

### ISSUE THREAD

**Issue by kapitanf** [pychess/pychess#1366]
first test save game:

http://kapitanf.czweb.org/001.png

next try exit game:

http://kapitanf.czweb.org/002.png

**Comment by gbtami** [comment]
Reproduced it on windows7 with .msi installer. Seems this is a .msi problem because runninig pychess from sources it works OK. As a workaround I suggest to set autosave on in preferences until this bug will get fixed.

**Comment by gbtami** [comment]
@kapitanf  can you try if this still reproducible with 0.99.0 from https://github.com/pychess/pychess/releases please?
