### ISSUE TITLE
Move History Misalignment

### ISSUE THREAD

**Issue by NoSuck** [pychess/pychess#1386]
Hello.  I currently use PyChess 0.12.4.  A new issue has appeared with move history display.  I am not sure which version of PyChess introduced the issue, though I do not recall it existing 18 months ago:

![Move History Misalignment](https://nosuckdotorg.files.wordpress.com/2016/10/pychess-move-history-alignment-issues.png)

**Comment by gbtami** [comment]
Can you reproduce this regularly? (Unfortunately I can't at all.)

**Comment by NoSuck** [comment]
I noticed today that I see the problem with `LANG=ja_JP.utf8` but not `LANG=en_US.utf8`.

**Comment by gbtami** [comment]
Can you try the latest git version, please?

**Comment by gbtami** [comment]
@NoSuck can you try if this still reproducible with 0.99.0 from https://github.com/pychess/pychess/releases please?

**Comment by NoSuck** [comment]
Thanks for following up.  I apologize for not responding earlier but can confirm the alignment issue is fixed in 0.99.0.  I tried taking a screenshot but was unable to figure out how to load PGN files into the game window (and not the database organizer, which looks nice, by the way).  There seems to be a lot of new functionality.

**Comment by gbtami** [comment]
You can load games from .pgn by double clicking on Database gamelist rows. (Or select with simple click then press Enter.)
