### ISSUE TITLE
Implementation of Ghost 3 beta (WB) into PyChess (latest version) for Windows

### ISSUE THREAD

**Issue by ChessGUI** [pychess/pychess#1387]
Where can I find an explanation (step-by-step)   concerning the following topics?
1) In which way can be embedded Ghost 3 beta (WB) http://www.ghostchess.de/ghost3-beta/Ghost3_Beta_20160913_64bit.zip into the current PyChess application for Windows?
2) Will be a release for Windows x64 systems only?

**Comment by gbtami** [comment]
1) Edit->Engines->New (wait some sec to let pychess discover the engine)
2) 32bit Python can run 64bit engines with subprocess.Popen(), so providing only 32bit .msi seems OK. But maybe I'm wrong.
