### ISSUE TITLE
Can't add engines not marked executable on Linux

### ISSUE THREAD

**Issue by CarbonFixer** [pychess/pychess#1388]
Trying to add another engine only replaces PyChess.py, and only the executable path at that. Renaming the engine fails. Cannot add options. Terminal output attached.

[AddEngine.txt](https://github.com/pychess/pychess/files/535690/AddEngine.txt)

[ChangeToUCI.txt](https://github.com/pychess/pychess/files/535697/ChangeToUCI.txt)

**Comment by CarbonFixer** [comment]
Update: the cause was not having the chess engine file marked executable in the filesystem (+x). There should probably be some error message for idiots like me instead of the inexplicit behavior described in the original report.

**Comment by gbtami** [comment]
Good idea, and thx for the update!
