### ISSUE TITLE
I have had issue with permissions for installing engines in both Pychess or Scid.

### ISSUE THREAD

**Issue by pdvossen** [pychess/pychess#1391]
I have Pinguy and Cub Linux both Debian based. When I went to their latest updates on both computers, all of a sudden I can't get permission to install engines in Pychess or Scid. I have tried my old tried to Linux commands. Still not able. I am trying to troubleshoot.

**Comment by gbtami** [comment]
What version of PyChess do you use?
What error message you get?

**Comment by pdvossen** [comment]
Thanks for contacting me.

I downloaded beta 12.3. It installed stockfish 8. First time that has
worked. If there is a better version let me know, but now I am happy. I
like pychess's interface. I have Shredder for linux to.

Patrick

**Comment by gbtami** [comment]
The latest release is 0.12.4
You can download it from https://github.com/pychess/pychess/releases
Is the problem still exists?
