### ISSUE TITLE
Bug PyChess.py engine

### ISSUE THREAD

**Issue by gitHubAccoun7** [pychess/pychess#1399]
[Moves.pdf](https://github.com/pychess/pychess/files/643118/Moves.pdf)
Hello PyChess-developers,

I'm frequently bugged by an impossible move from the PyChess.py-engine. See attached file.

Is this a known problem? How could it be fixed?

Cheers

**Comment by gbtami** [comment]
What pychess version are you using?
Can you attach the game in .pgn saved format here please?

**Comment by gitHubAccoun7** [comment]
[blackPawnBug.zip](https://github.com/pychess/pychess/files/644378/blackPawnBug.zip)
I just updated to "Anderssen 0.12.4", hoping the bug has already been fixed in this version. Prior to that I played in 0.12.3 beta version.

Find attached two different games with the same bug in the last move of the black pawn as zipped 
png-files. By the way the PyChess.py level is 2, if that matters...

**Comment by gbtami** [comment]
This is the so called en passant move in chess.
See https://en.wikipedia.org/wiki/En_passant
