### ISSUE TITLE
Pychess 0.12.4 crashes when starting new game on FICS

### ISSUE THREAD

**Issue by Peedlerofpawn** [pychess/pychess#1400]
Like it says in the title, Pychess 0.12.4 crashes when starting a new game on FICS. It seems to happen when you try to start a game by double clicking on one of the games that are being advertised in the game list in the lobby (not the seek graph, but the list). I think it might also be happening when other people click on a seek I have sent since I frequently notice the program freezes shortly after I have issued a seek, presumably because somebody was trying to accept my game. I am on Linux Mint 17.3. The version 0.12.3 didn't have this problem and I have gone back to that one for now.

**Comment by gbtami** [comment]
Unfortunately I can't reproduce this. What the "crash" exactly means? Is pychess quits, or hangs infinitely not responding to anything? Can you see any treceback messages if you start pychess from console? Can you attach a .log file of a "crashed" session please? .log files are stored in ~/.local/share/pychess

**Comment by Peedlerofpawn** [comment]
By crash I mean "hangs indefinitely". Also some of the elements on the 
screen are greyed out, such as the games in the list and the accept 
button for games. Since I uninstalled that version and reinstalled the 
old one I think all those files have been deleted, I will have to 
install the new version again and see if I can recreate the crash and 
then send you the log files. By the way, the crash doesn't happen 
consistently, only sometimes. It's not something that you will be able 
to recreate 100% every time.

**Comment by Peedlerofpawn** [comment]
Also, autopromote to queen is not working on version 0.12..3. Not only does it ask you which piece you want to promote to but once you have chosen the piece you want, you then have to move the piece to the 8th rank again! Just lost a game that way because I only had 3 seconds left and was about to mate but after I got the pawn to 8th rank the little selection box came up and after I chose queen I still had to move the pawn to 8th rank again.

**Comment by gbtami** [comment]
Fixed autopromote to queen on premove.
Can you reproduce the crash bug with latest git version too?

**Comment by gbtami** [comment]
@Peedlerofpawn  try latest git version if you can please!
It needs Python3. See the INSTALL file for packages needed.

**Comment by Peedlerofpawn** [comment]
Where do I download it? The version on the website is still 12.4, no? Where's the new one?

**Comment by gbtami** [comment]
You can
``
git clone https://github.com/pychess/pychess.git 
``
or on https://github.com/pychess/pychess page there is a big green button "Clone or download"
If you click on it it shows "Download ZIP"

**Comment by Peedlerofpawn** [comment]
Sorry, it's too technical for me, if it can't be installed from a repository I don't think I'll be able to. As far as I can see I already have Python 3 and 3.4 installed but it keeps refusing to install without them (but they are already there!)

**Comment by gbtami** [comment]
What "keeps refusing" exactly means? What error message you get?

**Comment by Peedlerofpawn** [comment]
It keeps telling me that I need python 3.4 installed in order for it to install pychess, but I already have python 3.4 installed.

**Comment by gbtami** [comment]
You have to start (git version of) pychess with python3 instead of python!
Ok, I'v changed the pychess starting script shebang line to #!/usr/bin/python3
so after "git pull" you can start it with ./pychess only now.

**Comment by Peedlerofpawn** [comment]
Sorry, I really have no idea what that means. I just need a program I can install in Terminal and then open. I I think it's just too complicated for me to be honest.

**Comment by mattgatto** [comment]
Shouldn't the startup script do that automatically?

**Comment by gbtami** [comment]
Ok, no problem. I hope I can create the first alpha version of 1.0 soon.

**Comment by gbtami** [comment]
@Peedlerofpawn can you try if you can still reproduce this with 0.99.0 from https://github.com/pychess/pychess/releases please?
