### ISSUE TITLE
Three fold repetition does not draw

### ISSUE THREAD

**Issue by gennaro-tedesco** [pychess/pychess#1401]
**Version**: 0.12.4 Anderssen
**System**: Ubuntu 16.04

**Description**: Three fold repetition of moves and position does not imply draw, as it should. The engine continues playing on instead. Likewise for any other draw offer: the engine does not accept draws even in theoretically draw positions and continues performing random moves. It seems the entire draw concept needs to be enhanced.

**Comment by gbtami** [comment]
Can you attach a .pgn demonstrating the issue please?

**Comment by gennaro-tedesco** [comment]
Start from the following position, given in FEN notation: `7k/3B4/7K/7P/8/8/8/8 w - - 0 1`. Set up the position and play human vs engine (I have tried many engines, from the starting pychess to stockfish through maxqi and shamax); in particular repeat the below sequence of moves

```
[FEN "7k/3B4/7K/7P/8/8/8/8 w - - 0 1"]

1. Kg6 Kg8 2. Kh6 Kh8 3. Kg6 Kg8 4. Kh6 Kh8 5. Kg6 Kg8 6. Kh6 Kh8 7. Kg6 Kg8 8.
Kh6 Kh8 *
```
where you can actually go on forever. The system should 
- recognise the three fold repetitions and draw the game;
- understand that the position is draw and accept a draw offer when sent (currently I have never seen any draw offer being accepted, ever).

Moreover the system should itself propose a draw when theoretically so, at least, without continuing moving ad libitum.

**Comment by gbtami** [comment]
Strange. "Actions"->"Offer draw" was accepted by PyChess and "Claim draw" works for me after 3 repetition too.

**Comment by gennaro-tedesco** [comment]
The thing is, one needs not "claim draw" to draw after the three fold repetitions: it must draw automatically; if one does not claim then the system continues playing, which should not be the expected behaviour. Moreover the offer draw must be accepted already before the three fold repetitions, as the position is theoretically draw itself: has it worked for you before or after the moves repetitions?

**Comment by gbtami** [comment]
Draw offer is accepted by PyChess engine in above positioan at _any_ time (before first move or after moves you pasted). After 3 repetition the menu changes from "Offer draw" to "Claim draw" and GUI accepts it for me too.

New automatic draws by FIDE rules 9.2 (5 repetition and 75 moves) http://www.fide.com/fide/handbook.html?id=171&view=article are not implemented yet. See #882 

In other cases we stick to FIDE rules so 3 repetition should be claimed by players for example.
(The only exception is engine-engine games where GUI adjudication stops endless playing instead of human claims.)

**Comment by gennaro-tedesco** [comment]
Could this behaviour depend on particular settings, i. e. timing or other parameter? In untimed or long-timed games I still cannot get the engine to accept the draw offer (in the above-mentioned setup).

What settings have you used to achieve it?

**Comment by gbtami** [comment]
Are you playing with PyChess own engine or with some other one? If the former it should always accept draw offers. If the latter it depends on that engine.
I use default settings.

**Comment by gennaro-tedesco** [comment]
I see: it might probably depend on the fact that I have been using sometimes different engines (although in principle I used to know that engines always playing till the end, whereas the GUI/interface can be set to end a draw game). 

Thanks for the assistance anyway!
