### ISSUE TITLE
Protocol detection with parameters

### ISSUE THREAD

**Issue by ecrucru** [pychess/pychess#1409]
Hello,

In the dialog to configure the engines, xboard is selected by default. When switching to "uci", pyChess executes the command of the engine to check if it replies "uciok" and then it gets all the available options.

I would like to know if it is normal that the parameters of the command are not used at this moment ?

Example:
- "engine.exe -uci" may return the options A and B
- "engine.exe -xboard" may return the single option C
- "engine.exe" alone cannot provide any option, so the engine is not properly configured

Thank you.

**Comment by gbtami** [comment]
I can add the parameters to command on protocol detection run of course. Telling the truth I know only one engine (sjaakII) supporting both uci and xboard but it doesn't need parameters to switch. I can imagine there are engines supporting 1) and 2) but don't think 3) is needed. Can you give me engine links to test this issue please?

**Comment by ecrucru** [comment]
Hello,

I simplified a bit the initial question to illustrate the basic logic and the flexibility it may add.

More in details, my engine is written in JavaScript, so it needs an host to run. This is Node.js (node.exe) and the parameters activate the engine (name of the JS file + some parameters for the optimization).

When I select the protocol to configure the engine for the first time, pyChess executes "node.exe" with no parameter and there is necessarily no output. The workaround is to modify the configuration file directly :
https://github.com/ecrucru/anticrux/blob/dev/README.md#procedure-for-pychess

Once installed, everything is fine. pyChess has a good detection of the variants and the gameplay is nice.

Thanks.

**Comment by gbtami** [comment]
Added node.js runtime support to engines dialog so you can select anticrux-engine.js on adding a new engine. Test it please!

**Comment by ecrucru** [comment]
Hello,

I have installed pyChess in a VM and I tested your latest commit.

It is OK.

Thank you very much.
