### ISSUE TITLE
pyChess not shown on startup

### ISSUE THREAD

**Issue by ecrucru** [pychess/pychess#1410]
Hello,

Tested configuration :

| System | pyChess | Impacted |
|--------|---------|----------|
| Win32  | 0.12.4  | Yes      |
| Debian | latest  | No       |

Steps :
- Minimize pyChess
- Close pyChess with a right click in the taskbar
- Run pyChess

pyChess is now out of the screen. Precisely, it is located at X=-32000 and Y=-32000 according to the properties of the top window. The window has certainly the right size yet.

I don't know on Win32 if you already have corrected this issue.

Thanks.

**Comment by gbtami** [comment]
Fixed. Thx!
