### ISSUE TITLE
Predefined positions

### ISSUE THREAD

**Issue by ecrucru** [pychess/pychess#1411]
Hello,

This is a feature request.

What about adding a button in the board editor to set up the classical position ? Another one to clear the board ? Possibly amother one to set up Chess960 ?

For now, we have to start a new game before going to the board editor for the first time, then we get the default position.

Thanks

**Comment by gbtami** [comment]
One remaining enhancement is to add button to set up Chess960 start positions.

**Comment by gbtami** [comment]
I think adding another button to set up Chess960 is just clutters the GUI without real need.

**Comment by ecrucru** [comment]
On this topic, let's generate the 960 positions in `eco.db`, then the position can be called by name through the existing button.
