### ISSUE TITLE
pychess_0.12.4-1_all.deb hangs on close with Linux Mint 17.3 KDE 64-bit

### ISSUE THREAD

**Issue by BriCra17gh** [pychess/pychess#1413]
pychess frequently hangs on exit with the error shown below in the xterm where I started pychess.

Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/pychess/Main.py", line 232, in on_quit1_activate
    game_handler.closeGame(gmwidg, gmwidg.gamemodel)
TypeError: closeGame() takes exactly 2 arguments (3 given)

BriCra

**Comment by gbtami** [comment]
@BriCra17gh try latest git version if you can please!
It needs Python3. See the INSTALL file for packages needed.

**Comment by gbtami** [comment]
@BriCra17gh can you try if this still reproducible with 0.99.0 from https://github.com/pychess/pychess/releases please?
