### ISSUE TITLE
ELO level equivalence

### ISSUE THREAD

**Issue by yomguy** [pychess/pychess#1417]
Hi,
I wonder what are the ELO equivalent values versus the PyChess level numbers.
Thanks for the info and this great game!

**Comment by gbtami** [comment]
I had never measured PyChess engine for ELO. I "feel" it's playing around 1400 on max level and this goes down to 0 if you set lower levels (probably not linear).

**Comment by yomguy** [comment]
Thanks a lot @gbtami for these explanations forwarded to my 9 year old son who asked the question ;)
