### ISSUE TITLE
preserve user settings / preferences across versions - feature request

### ISSUE THREAD

**Issue by BriCra17gh** [pychess/pychess#1426]
Using per-user config files across pychess versions results in failed execution as shown in #1412.

It would be nice to be able to keep user-defined settings between versions. 

What do you think of devising a way to do that automatically?

Meanwhile, what can I (and what must I not) cut and paste between config files so I don't have to reenter everything via the GUI?

Thanks.

BriCra

**Comment by gbtami** [comment]
I'v fixed this in my latest commit as mentioned in https://github.com/pychess/pychess/issues/1412#issuecomment-304617106

If you have your old (0.12.4) config files saved you can simply copy them back to ~/.config/pychess
The latest pychess git version will use them without any problem. 

The problem/bug was that pychess own python engine was python2/python3 compatible but in engines.json contained lines:
```
  "vm_command": "/usr/bin/python", 
  "vm_name": "python"
```

Now all pychess code is python3 only so when it wanted to start hes own engine it used /usr/bin/python to run it and eventually failed. Now pychess automatically changes these lines to python3 on startup.
Sorry for inconvenience!
