### ISSUE TITLE
Pychess sometimes hangs when FICS games are finished

### ISSUE THREAD

**Issue by bboutkov** [pychess/pychess#1436]
This is kind of hard to reproduce but has occured when sending a flag call, or when checkmating opponent - sometimes pychess hangs and must be forcekilled once a game finishes on FICS.  No errors are logged while this happens. 

The working theory is that gbulb is being flooded by FICS server communication, engine starting, file saving and sending the game over status notification all at the same time.
 
One possible way to fix this was discussed in irc - to introduced forced delays between actions to make life easier for the asyncio event loop - Im not sure if this is the proper fix, but it might be the easiest.

**Comment by gbtami** [comment]
Reproduced it yesterday. Log attached.
[pychess_fics_game_end_freeze.log.gz](https://github.com/pychess/pychess/files/1104291/pychess_fics_game_end_freeze.log.gz)

**Comment by gbtami** [comment]
@bboutkov try latest git please! Changed the default event loop to one that asyncio provides instead of gbulb. The latter still available starting pychess with --gbulb-loop.

**Comment by bboutkov** [comment]
After the changes in https://github.com/pychess/pychess/commit/005a6c29f1ff49b0758deed93b58d8b235290550 and its parent I cant say I have seen any more issues related to any kind of hanging. Since it was elsewhere mentioned that this also fixes some issues on the Windows side I think its safe to close this issue.
