### ISSUE TITLE
[Solved] time control hidden when time setting is 0-...

### ISSUE THREAD

**Issue by xav01** [pychess/pychess#1438]
Hi,

I use pychess Anderssen 0.12.2, in linux mint 18 cinnnamon 64-bit v3.0.7, up to date.
When playing on fics, if I accept a game with time set to 0 for the beginning and some more time for each move, the time control is hidden, so I can't know how much time I have left, neither for my opponent . 
Has this issue already been reported? And is there a solution I missed.
Best regards.
Xavier.

**Comment by bboutkov** [comment]
Hey @xav01 I'd just like to mention that this doesnt appear to be happening in the latest git version. I think theres a pre-release being planned soon that you could wait for, or feel free to try and clone the repo and see for yourself if things are working as expected.

**Comment by gbtami** [comment]
@xav01 it was fixed in 0.12.4. You can download .deb from https://github.com/pychess/pychess/releases

**Comment by xav01** [comment]
Thanks a lot for your answers, it's true it works fine with the 0.12.4 version.
