### ISSUE TITLE
Options not refreshed correctly in enginesDialog.py

### ISSUE THREAD

**Issue by ecrucru** [pychess/pychess#1441]
Hello,

In the dialog to configure the engines, if I select an engine which has at least one option, the list of the options is updated.

But if I click on another engine which has no option (like LozzaJS), the list of options is not refreshed. So it gives the impression that this new engine has some options (this is false). Moreover, changing the displayed options modifies the settings of the previously selected engine.

This is not critical but confusing. I refer to this method :
https://github.com/pychess/pychess/blob/master/lib/pychess/widgets/enginesDialog.py#L104

Thank you

**Comment by gbtami** [comment]
Nice catch. Thx!
