### ISSUE TITLE
Unsupported variant on the home screen

### ISSUE THREAD

**Issue by ecrucru** [pychess/pychess#1444]
Hello,

The home screen of pyChess should only display the engines which can play the normal variant of chess, as it seems to be hardcoded in TaskerManager.py.

Or should it take the default variant set in the configuration (engine dialog) ?

Thank you.

**Comment by gbtami** [comment]
The bug is that PyChess assumes all engine support standard chess. See https://github.com/pychess/pychess/blob/master/lib/pychess/Players/engineNest.py#L475

Another thing is that PyChess TaskerManager always start 5 min standard game and never uses saved config items from the more detailed newGameDialog. Changing this may be an enhancement, but has no priority before 1.0.

**Comment by ecrucru** [comment]
I have retested from the freshest master but this commit causes too much regressions. I have locally reverted your changes to make sure of that. Schematically, if `engines.json` is made of `[{variant_engine},{stockfish}]` because it is my minimal configuration, then :

- impossibility to manage the settings of all the engines (blank view)
- wrong engine started from the home screen when a normal game against stockfish is chosen
- impossibility to start a variant game from the dedicated menu item (see newGameDialog.py:431)

I guess that the exclusion of the non-standard engines from the list causes a shift in the internal identifiers. I strongly suggest to revert the commit. Sorry for that.

**Comment by gbtami** [comment]
Thx for testing! You are absolutely right. Unfortunately pychess has some inner assumptions I'v forgot about, so to correctly fix this issue more changes needed than just exclusion of the non-standard engines from the list.

**Comment by gbtami** [comment]
@ecrucru may I ask you to test this fix please?

**Comment by ecrucru** [comment]
Good for me, nice ! Thanks.
