### ISSUE TITLE
Using i3wm some popup style windows appear in background when playing fullscreen

### ISSUE THREAD

**Issue by bboutkov** [pychess/pychess#1449]
It seems like some windows appear in the background when playing fullscreen, while others (such as New Game) work as expected.

When they show up in the background it "feels" like pychess freezes because some of these windows are still Active but in the background.  I think all of the below windows should be made to behave like New Game does when using fullscreen mode (make them floating active windows on top of main interface)

Problem Popup Windows: Analyze Game, Tip of the Day, Finger User, Externals Dialog, New Database

**Comment by gbtami** [comment]
The Analyze Game, Tip of the Day, Externals Dialog produced empty windows on second run for me and if I clicked on them pychess crashed. I changed them to create new instances on each call. But I can't reproduce the problem with Finger Dialog and New Database yet.

**Comment by gbtami** [comment]
Ok, I reproduced this issue with i3wm. Thx for the pointer! (My prev commit solved another issue.)
