### ISSUE TITLE
Flat score

### ISSUE THREAD

**Issue by ecrucru** [pychess/pychess#1453]
Hello,

I use ddugovic/Stockfish and pyChess 0.99 for that question.

Let's suppose that I play the variant "racingkings", we have the score in the panel :

![racing](https://user-images.githubusercontent.com/24614488/30506428-3800efbe-9a7c-11e7-8af9-e48254434573.png)

```
uci
setoption name UCI_Variant value racingkings
isready
ucinewgame
position fen 8/1r6/6K1/q5b1/2kB4/8/4N3/1r2N3 w - -
go depth 5

info depth 1 seldepth 1 multipv 1 score cp -917 nodes 102 nps 395 tbhits 0 time 258 pv d4g7
info depth 2 seldepth 2 multipv 1 score cp -814 nodes 153 nps 332 tbhits 0 time 460 pv d4g7 c4c5 g6h7
info depth 3 seldepth 3 multipv 1 score cp -814 nodes 212 nps 414 tbhits 0 time 511 pv d4g7 c4c5 g6h7
info depth 4 seldepth 4 multipv 1 score cp -1227 nodes 352 nps 603 tbhits 0 time 583 pv d4g7 c4c5 g6h7 b7b8
info depth 5 seldepth 5 multipv 1 score cp -1696 nodes 1902 nps 1129 hashfull 0 tbhits 0 time 1684 pv e1d3 c4b5 d4g7 b7b8 g6g5
bestmove e1d3 ponder c4b5
```

If I play the variant "suicide", the score is not displayed in the score panel and the score is not equal to zero.

![suicide](https://user-images.githubusercontent.com/24614488/30506450-4dbf7e74-9a7c-11e7-8bcd-2abaa1a1fed1.png)

```
uci
setoption name UCI_Variant value suicide
isready
ucinewgame
position fen r1bqkb1r/pppn1pp1/8/7p/8/8/PPPPPP1P/RNBQK1NR w - -
go depth 5

info depth 1 seldepth 1 multipv 1 score cp 611 nodes 19 nps 50 tbhits 0 time 375 pv b1a3
info depth 2 seldepth 4 multipv 1 score cp 1233 nodes 71 nps 99 tbhits 0 time 713 pv b2b4 f8b4 d2d3
info depth 3 seldepth 6 multipv 1 score cp 692 nodes 137 nps 163 tbhits 0 time 836 pv b2b4 f8b4 c1a3 b4d2
info depth 4 seldepth 7 multipv 1 score cp 745 nodes 194 nps 184 hashfull 0 tbhits 0 time 1052 pv b2b4 f8b4 c1b2 b4d2 b2g7 d2e1 d1 d7
info depth 5 seldepth 8 multipv 1 score cp 530 nodes 566 nps 385 hashfull 0 tbhits 0 time 1468 pv b2b4 f8b4 e2e4 b4d2 d1h5 d2c1 h5 f7
bestmove b2b4 ponder f8b4
```

The UCI output is really the same, so why is the score not displayed ?

Please note that the sample UCI outputs are not in line with the screenshots.

Thanks

**Comment by gbtami** [comment]
I can't play suicide with variant stockfish from https://github.com/niklasf/Stockfish at all. It lists 'giveaway' but not 'suicide'. Seems I'm missing something here.

```tamas@tami:~/bin/stockfish_lichess$ ./stockfish-x86_64 
Stockfish 140917 64 by T. Romstad, M. Costalba, J. Kiiski, G. Linscott
uci
id name Stockfish 140917 64
id author T. Romstad, M. Costalba, J. Kiiski, G. Linscott

option name Debug Log File type string default 
option name Contempt type spin default 0 min -100 max 100
option name Threads type spin default 1 min 1 max 512
option name Hash type spin default 16 min 1 max 1048576
option name Clear Hash type button
option name Ponder type check default false
option name MultiPV type spin default 1 min 1 max 500
option name Skill Level type spin default 20 min 0 max 20
option name Move Overhead type spin default 100 min 0 max 5000
option name nodestime type spin default 0 min 0 max 10000
option name UCI_Chess960 type check default false
option name UCI_Variant type combo default chess var chess var giveaway var atomic var crazyhouse var horde var kingofthehill var racingkings var 3check
option name SyzygyPath type string default <empty>
option name SyzygyProbeDepth type spin default 1 min 1 max 100
option name Syzygy50MoveRule type check default true
option name SyzygyProbeLimit type spin default 6 min 0 max 6
uciok
```

**Comment by ecrucru** [comment]
Hello,

Oh well, they have done some changes in the code during the last 6 months.

Some tips target the use of "giveaway" now :
https://github.com/niklasf/Stockfish/blob/fishnet/src/Makefile#L275
https://github.com/ornicar/lila/blob/master/ui/ceval/src/stockfishProtocol.ts#L29

However, that variant name is not supported by pyChess (?) and I can't use the new stockfish multi variants :
```
setoption name UCI_Variant value giveaway
terminate called after throwing an instance of 'std::length_error'
  what():  basic_string::_M_create
```

In the short term with the variant "suicide", you may encounter the described case with my little engine or pychess-engine too.

To be sure, I also unchecked the analyzers in the configuration.

Thanks.

**Comment by gbtami** [comment]
The score panel values (while playing) are computed by pychess engine eval function and for antichess variants it uses only material eval. But it was not normalized to 1 pawn value. Fixed it.
(If hint analyzer engine is set, on finished games they will be used to refresh the scores.)

Added giveaway support to pychess also.

**Comment by ecrucru** [comment]
Hello,

First, thank you for the support of "giveaway" which was not part of the initial question. That feature will help to play with the recent release of Stockfish with variants.

For the flat score, it is better than before and based on your clear explanation, I would suggest a little improvement for the calculation of the score. Let's take a graph issued from a sample game :

![score](https://user-images.githubusercontent.com/24614488/30564071-156e6d56-9cc4-11e7-8a72-4aa9bb6b8403.png)

- Dashed blue line = Number of pieces for White
- Dashed red line = Number of pieces for Black
- Green line = The current score in pyChess
- Purple line = The new suggestion

If you calculate the score by material difference, the strength is not «nice» at end of the game because of the «proportion of the material difference». IMHO, a better rule would be to take the material difference as you currently do now, divide by the maximal number of pieces between White and Black, then multiply by the maximal score to maximize the view of the score in the panel. This is the purple line which ends with the highest score.

| Move | White | Black | Current diff | New diff |
|:----:|:-----:|:-----:|:------------:|:--------:|
| g3   | 16    | 16    | 0            | 0,0      |
| b6   | 16    | 16    | 0            | 0,0      |
| b3   | 16    | 16    | 0            | 0,0      |
| e6   | 16    | 16    | 0            | 0,0      |
| h4   | 16    | 16    | 0            | 0,0      |
| Qxh4 | 15    | 16    | 1            | 0,6      |
| gxh4 | 15    | 15    | 0            | 0,0      |
| Ba3  | 15    | 15    | 0            | 0,0      |
| Bxa3 | 15    | 14    | -1           | -0,7     |
| g5   | 15    | 14    | -1           | -0,7     |
| hxg5 | 15    | 13    | -2           | -1,3     |
| Nf6  | 15    | 13    | -2           | -1,3     |
| gxf6 | 15    | 12    | -3           | -2,0     |
| Rf8  | 15    | 12    | -3           | -2,0     |
| Bxf8 | 15    | 11    | -4           | -2,7     |
| Kxf8 | 14    | 11    | -3           | -2,1     |
| Rxh7 | 14    | 10    | -4           | -2,9     |
| Kg7  | 14    | 10    | -4           | -2,9     |
| fxg7 | 14    | 9     | -5           | -3,6     |
| a5   | 14    | 9     | -5           | -3,6     |
| b4   | 14    | 9     | -5           | -3,6     |
| axb4 | 13    | 9     | -4           | -3,1     |
| Na3  | 13    | 9     | -4           | -3,1     |
| bxa3 | 12    | 9     | -3           | -2,5     |
| Bh3  | 12    | 9     | -3           | -2,5     |
| Ra4  | 12    | 9     | -3           | -2,5     |
| Bxe6 | 12    | 8     | -4           | -3,3     |
| fxe6 | 11    | 8     | -3           | -2,7     |
| Rh4  | 11    | 8     | -3           | -2,7     |
| Rxh4 | 10    | 8     | -2           | -2,0     |
| f4   | 10    | 8     | -2           | -2,0     |
| Rxf4 | 9     | 8     | -1           | -1,1     |
| c4   | 9     | 8     | -1           | -1,1     |
| Rxc4 | 8     | 8     | 0            | 0,0      |
| Qa4  | 8     | 8     | 0            | 0,0      |
| Rxa4 | 7     | 8     | 1            | 1,3      |
| d4   | 7     | 8     | 1            | 1,3      |
| Rxd4 | 6     | 8     | 2            | 2,5      |
| Kd2  | 6     | 8     | 2            | 2,5      |
| Rxd2 | 5     | 8     | 3            | 3,8      |
| Rb1  | 5     | 8     | 3            | 3,8      |
| Rxe2 | 4     | 8     | 4            | 5,0      |
| Rxb6 | 4     | 7     | 3            | 4,3      |
| Rxa2 | 3     | 7     | 4            | 5,7      |
| Rxe6 | 3     | 6     | 3            | 5,0      |
| dxe6 | 2     | 6     | 4            | 6,7      |
| Ne2  | 2     | 6     | 4            | 6,7      |
| Rxe2 | 1     | 6     | 5            | 8,3      |
| g8=R | 1     | 6     | 5            | 8,3      |
| Rg2  | 1     | 6     | 5            | 8,3      |
| Rxg2 | 1     | 5     | 4            | 8,0      |
| a2   | 1     | 5     | 4            | 8,0      |
| Rxa2 | 1     | 4     | 3            | 7,5      |
| Ba6  | 1     | 4     | 3            | 7,5      |
| Rxa6 | 1     | 3     | 2            | 6,7      |
| Nxa6 | 0     | 3     | 3            | 10,0     |

HTH

**Comment by gbtami** [comment]
Good idea!
@ecrucru may I ask you to create a pull request? The affected code is at https://github.com/pychess/pychess/blob/master/lib/pychess/Utils/lutils/leval.py#L114
