### ISSUE TITLE
Change the country from the UI

### ISSUE THREAD

**Issue by ecrucru** [pychess/pychess#1454]
Hello,

The country is part of `engines.json` but it has no corresponding changeable field in engineDialog.

For user-friendliness, is it possible to add that manual field ?

Thanks

**Comment by ecrucru** [comment]
Hello,

I made an attempt to add the change of the country from the UI :

![image](https://user-images.githubusercontent.com/24614488/31576927-d0da0262-b105-11e7-8e8e-48ba8ab7a779.png)

That proposal has one issue : the combobox of the country doesn't reflect the current flag of the configuration when the selection is changed.

I need your help to finalize that feature.

Thanks.

**Comment by gbtami** [comment]
Merged your updated PR. Thx!
It would be nice to have selection with keyboard from the combobox also. Unfortunately this is one of the oldest Gtk+ feature request, not addressed to date :( See https://bugzilla.gnome.org/show_bug.cgi?id=567141
