### ISSUE TITLE
Connect without timeseal

### ISSUE THREAD

**Issue by ecrucru** [pychess/pychess#1455]
Hello,

This is a feature request.

Like in Arena Chess, is it possible to add a checkbox to connect to a chess server with/without timeseal ?

Thanks

**Comment by gbtami** [comment]
Is there any benefit connecting without timeseal to FICS?

**Comment by ecrucru** [comment]
Hello,

The benefit is through the ability to turn it off. Telnet of course, Arena and WinBoard have this ability. I assume they found an interest in not requesting timeseal absolutely to connect.

For testing purposes, I modified unconfidently your timeseal.py and it allowed pyChess to go through the barrier of the timeseal at the time of the connection.

It gave me the impression that the feature is feasible but I deliberately rely on your expertise to know if it is expectable even with a low priority. It is an enhancement, not a bug indeed.

Thanks.

**Comment by gbtami** [comment]
It's feasible of course, but telling the truth I don't see any benefit turning it off. Timeaseal is developed to detect and compensate lag. Don't using it just add some handicap to the player with worst internet connection.
You can try this "feature" if you don't enable pychess to download ICC timestamp (or remove it from ~/.locale/share/pychess/engines/timestamp_linux_2.6.8) and try to play some quick game with pychess on ICC.

**Comment by gbtami** [comment]
@ecrucru if you (or anyone else) see any benefit of adding this feature to PyChess, PR is welcome.

**Comment by ecrucru** [comment]
A working change is available [here](https://github.com/ecrucru/pychess/tree/dev_timeseal). My impression is that it is already complete.

However, PyChess exposes the error `ICSTelnet has no attribute transport` [here](https://github.com/ecrucru/pychess/blob/master/lib/pychess/ic/TimeSeal.py#L225) when it connects to my [local chess server](https://github.com/ecrucru/anticrux/blob/master/README.md#anticrux-server) when you run `./pychess --log-debug`. I know that a game cannot be started yet with PyChess, so I need to view the communication to understand how the commands are parsed when the server sends the required `<pf>`, `<pr>`, etc... This error makes this analysis impossible and it doesn't occur for freechess. Very confusing.

If this potential PR is interesting for you, I would appreciate your help to fix this error.

Thanks.

**Comment by gbtami** [comment]
Wow! Finally I understand your motivation :) @ecrucru @ddugovic sorry for my poor imagination! I forgot that people may want to use PyChess to other servers (not just for FICS/ICC).

@ecrucru your changes seems OK. I tried your `dev_timestamp` branch and was able to connect to AntiCrux server and got no error you described. Strange.

Anyhow, send PR please!

**Comment by ecrucru** [comment]
I retested in another VM : the issue doesn't arise, so I assume there is an updated package there.

PyChess is OK and the initial topic is solved. That's the most important !

Thanks for the merge.

**Comment by gbtami** [comment]
@ecrucru if you need any help regarding FICS protocol usage in anticrux server feel free to ask on IRC freenode.net  on #pychess channel.
