### ISSUE TITLE
Strange, but seemingly by design, tab behaviour

### ISSUE THREAD

**Issue by ghost** [pychess/pychess#1456]
As far as I can tell, when one ends a game in Pychess, and starts a new game, the old one remains in a tab, unless one closes that tab. This can lead to multiple tabs, for which I have no use. Surely there should be an option to disable this behaviour, and indeed I feel it should be disabled by default.

PyChess 0.12.2

**Comment by gbtami** [comment]
Auto close game tab after game end can be an option in preferences dialog, but I disagree it should be on by default. People I know like to analyze their games post-mortem.
