### ISSUE TITLE
Strange, but seemingly intended, time behaviour

### ISSUE THREAD

**Issue by ghost** [pychess/pychess#1457]
If I start a game against a computer opponent, and I am white and play my first move, the computer's clock doesn't start ticking down until it has made it's first move - as *black*. Is this right?

PyChess 0.12.2

**Comment by gbtami** [comment]
Yes, this is bug #688

**Comment by gbtami** [comment]
This behaviour was implemented because FICS works this way. But for local games this was a long standing bug. Fixed it now.
Thx for reporting!

**Comment by gbtami** [comment]
Btw. 0.12.2 is rather old. Try 0.99.0 from https://github.com/pychess/pychess/releases please!

**Comment by ghost** [comment]
I might do that (try the new version). Thanks. By the way, you might want to get a version newer that 0.12 into Linux Mint's repositories. Linux Mint 17.3 will be coming out in some months (3? 6? I'm unsure) time.

**Comment by gbtami** [comment]
@CottonEaster I used to email about new versions to Debian and Fedora pychess package maintainers, but unfortunately I know none of the package maintainers of Linux Mint.

**Comment by ghost** [comment]
Perhaps [this webpage](https://linuxmint.com/teams.php) will help you to get in contact with someone relevant within Mint. PyChess seems a significant Linux project (albeit one that is still at a 0.X version number) and - am I right in saying this? - a version is in the Mint repositories already.

**Comment by gbtami** [comment]
From https://www.linuxmint.com/documentation/user-guide/Cinnamon/english_18.0.pdf
"Linux Mint uses Ubuntu repositories (more on what this means later) and is fully
compatible with it so most of the resources, articles, tutorials, and software made for
Ubuntu also work for Linux Mint."
As I see Linux Mint uses Ubuntu packages. Ubuntu uses Debian packages (to start from). So the root of PyChess .deb packages are stucked at 0.12.2 is here:  https://tracker.debian.org/pkg/pychess
