### ISSUE TITLE
Incorrect detection of an engine

### ISSUE THREAD

**Issue by ecrucru** [pychess/pychess#1463]
Hello,

I use the latest pyChess and I have installed the package «stockfish» and configured it into pyChess. OK

Now I compile ddugovic/stockfish on Linux in a personnal folder. The output file is «stockfish». I add it to pyChess.

pyChess detects stockfish of the package manager, doesn't add a new entry for my compiled engine, and a corrupted entry `stockfish(1)` is configured unsuccessfully at every run of pyChess.

The workaround is to edit `engines.json` to repair the file (impossible from the UI) or add an engine from a personal folder which is not already named like an existing application in `/usr/bin/*`.

Regards.

**Comment by gbtami** [comment]
@ecrucru this commit works for me. Can you confirm the committed fix works for you also?

**Comment by ecrucru** [comment]
Yes, it looks fine.

Thanks.
