### ISSUE TITLE
Use MultiPV from Engines as default on Hints panel

### ISSUE THREAD

**Issue by ecrucru** [pychess/pychess#1467]
Hello,

The analyzer is defined in the options and it takes the configuration done in engineDialog.

If the engine supports MultiPV, it would be nice that the widget "Hints" displays the found multiple principal variations (not just one in any case).

The ticket #862 seems to refer to the way the value is updated from the UI, but I have the impression that the value is ignored and this is in contradiction with #747 as far as I understand.

Thanks for any tip on that question.

**Comment by gbtami** [comment]
Works for me:
![multipv1](https://user-images.githubusercontent.com/479964/31317495-4e2e467e-ac42-11e7-92dc-25e44284e8e6.png)
![multipv2](https://user-images.githubusercontent.com/479964/31317497-5271030c-ac42-11e7-9726-b42fda12ba1d.png)
![multipv3](https://user-images.githubusercontent.com/479964/31317498-55c8bde2-ac42-11e7-8d09-ef367598261d.png)
Unfortunately #862 is still valid.

**Comment by ecrucru** [comment]
OK thanks, I better understand what the player meant in the other issue. My question looks a bit duplicate and I am sorry for that.

Finally, in other words, is it possible to reuse the default value of MultiPV from the options ? This will avoid the manual change you did above (this is for me the workaround). The issue 862 is about the controls and the layout.

Regards.
