### ISSUE TITLE
Start the analyzers with a low priority

### ISSUE THREAD

**Issue by ecrucru** [pychess/pychess#1471]
Hello,

This is a feature request.

Playing against the AI with 2 analyzers is CPU intensive.

What about setting a low priority for the processes of the analyzers ? They are not essential for the game and the priority should be given to the opponent (AI) in order to not affect its thinking time. Yes, it depends of the number of CPU.

Regards

**Comment by gbtami** [comment]
We use os.nice(15) as you can see at https://github.com/pychess/pychess/blob/master/lib/pychess/System/SubProcess.py#L51

Unfortunately os.nice is Unix only. Maybe we should apply http://code.activestate.com/recipes/496767/ or just use psutil if it's available.

If you have any other idea to get better user experience regarding CPU usage feel free to implement it. PR is always welcome!

**Comment by ecrucru** [comment]
Hello,

Before asking, I had a look at that file yesterday.

**1)** It came first to the fact that `dwCreationFlag` is not supported :
https://docs.python.org/3/library/subprocess.html#subprocess.STARTUPINFO

**2)** The tool `psutil` seems to have that possibility. So we could write something like that :
```python
import psutil
if sys.platform == "win32"
    psutil.Process(self.pid).nice(psutil.IDLE_PRIORITY_CLASS)
else
    psutil.Process(self.pid).nice(20) #The higher, the lower the priority
```

**3)** `win32api` is probably not the best way to port pyChess to every platform.

**4)** A piece of code relying on `os.setPriority()` (Linux only ?) reduced the priority of the current thread in order to give the same priority for the sub-processes. This is not the expected solution.

psutil seems to be a good way to achieve the expected result, but I don't know which policy you will provide to that package not used yet.

Thanks.

**Comment by gbtami** [comment]
I'm fine with 2) if it's OK on Ubuntu 14.04 (we are on Trusty on Travis CI).

**Comment by ecrucru** [comment]
Hello,

I made an attempt to change the logic through a PR.

It has been tested on a virtual Linux only :
![image](https://user-images.githubusercontent.com/24614488/31466553-e7022464-aed7-11e7-84bf-9f0ab91ada94.png)

We might also verify that the build scripts are not broken.

HTH

**Comment by gbtami** [comment]
Cool, thx!
