### ISSUE TITLE
[linux] can't see executable files when adding engine

### ISSUE THREAD

**Issue by andersfylling** [pychess/pychess#1474]
I've been using pychess before to test my own engine, but as i downloaded pychess today from AUR (fresh install of linux) I wasn't able to see any executable files. Is this an issue with others as well?

Does pychess need a specific filetype or ending on the filename?

Edit: just added a empty .exe file in the folder. and it can see that. Weird.
Edit2: did a git clone and install python dependencies. Still the same behavior.

**Comment by gbtami** [comment]
Works for me. Pychess engine add dialog needs files to be executable only.
See https://github.com/pychess/pychess/blob/master/lib/pychess/widgets/enginesDialog.py#L171

**Comment by andersfylling** [comment]
Are you on linux?
Cause this worked before. So I don't understand why it only supports .exe combined with wine on linux now. Seems counterintuitive.

**Comment by gbtami** [comment]
I'm on XUbuntu 16.04. Pychess supports linux binaries **and** windows .exe engines (using wine) on linux. 
Btw. can you run your engine from command line without any problem? Can you paste the output of `ls -l` from a directory containing your engine please?

**Comment by gbtami** [comment]
@andersfylling is this issue still exists for you?

**Comment by andersfylling** [comment]
So when I compile my engines I simply save them as `NAME` (someEngine.cpp => someEngine) and no file type suffix. Unlike windows which stores them as `.exe`.

Can Pychess look for files that are marked as executable?

@gbtami I assumed you cloned the latest version for testing right?

**Comment by andersfylling** [comment]
Kinda looks like it only sees `.exe` files on my end.
```python
filter = Gtk.FileFilter()
        filter.set_name(_("Executable files"))
        filter.add_mime_type("application/x-executable")
        filter.add_mime_type("application/x-ms-dos-executable")
        filter.add_mime_type("application/x-msdownload")
        filter.add_pattern("*.exe")
```

**Comment by gbtami** [comment]
@andersfylling what is the mime type of your engine reported by file command?
Here is an example output on my Ubuntu 16.04 box:
```
tamas@tami:~/bin/komodo-8_2d3f23/Linux$ file --mime komodo-8-linux
komodo-8-linux: application/x-executable; charset=binary
```

**Comment by andersfylling** [comment]
It's a different type from those already given in the filter:

`application/x-sharedlib; charset=binary`
Seems like you just found the issue @gbtami

**Comment by gbtami** [comment]
@andersfylling maybe this can help:
https://stackoverflow.com/questions/41398444/gcc-creates-mime-type-application-x-sharedlib-instead-of-application-x-applicati

**Comment by gbtami** [comment]
Ahh, just seen you sent a PR also. Thx!
