### ISSUE TITLE
Tag TimeControl + Unloadable game

### ISSUE THREAD

**Issue by ecrucru** [pychess/pychess#1479]
Hello,

I have several problems with the following game that I lost against my little engine. I wanted to analyze it with pyChess for the first time.

```
[Event "Fun"]
[Site "Home"]
[Date "2017-10-17"]
[Round "?"]
[White "Me"]
[Black "AntiCrux 0.3.0 - Level 8"]
[Result "0-1"]
[PlyCount "63"]
[Variant "suicide"]
[TimeControl "-"]
[Termination "normal"]

1. b3 d5 2. g4 Bcxg4 3. e4 dxe4 4. Qxg4 Qxd2 5. Qxg7 Bxg7
6. Bcxd2 Bxa1 7. Ngf3 e4xf3 8. Bfg2 f3xg2 9. Bc1 gxh1=N
10. Kd1 Nhxf2 11. h3 Nfxd1 12. Nc3 Bxc3 13. Bb2 Ndxb2
14. b4 Bxb4 15. a3 Bxa3 16. c4 Nb2xc4 17. h4 Kf8 18. h5 Ngf6
19. h6 Kg7 20. hxg7 Nfh5 21. gxh8=K Bb2 22. Kxh7 Bh8
23. Kxh8 Nhg7 24. Kxg7 Nbd7 25. Kxf7 Rd8 26. Kxe7 Ndb8
27. Kxd8 Ncd6 28. Kxc7 Ndb5 29. Kxb7 Nb5d6 30. Kxa7 Ndc8
31. Kxb8 Na7 32. Kxa7# 0-1
```

The tag `TimeControl` is correct according to the specification :

```
There are six kinds of TimeControl fields.
(...)
The second kind is a single hyphen ("-") which means that there was no time
control mode in use. When used, it is usually the only descriptor present.
```

This game cannot be opened by pyChess latest-git because the TimeControl `-` is not handled correctly :

```
Traceback (most recent call last):
  File "/home/ecrucru/pychess/lib/pychess/perspectives/database/PreviewPanel.py", line 98, in on_selection_changed
    self.persp.chessfile.loadToModel(rec, -1, self.gamemodel)
  File "/home/ecrucru/pychess/lib/pychess/Savers/pgn.py", line 662, in loadToModel
    secs, gain = parseTimeControlTag(model.tags['TimeControl'])
TypeError: 'NoneType' object is not iterable
```

I face different cases :

- pyChess Linux latest-git :
	- Tag '-' : error in console=**yes**, openable=**no**, preview=no
	- Tag '5' : error in console=no, openable=**no**, preview=yes
	- No tag  : error in console=no, openable=**no**, preview=yes
- pyChess Windows 0.99.0 :
	- Tag '-' : error in console=??, openable=**no**, preview=no
	- Tag '5' : error in console=??, openable=yes, preview=yes
	- No tag  : error in console=??, openable=yes, preview=yes

"Openable" means double-clicking on the file from the database.

The problem is not only fixing [pgn.py@parseTimeControlTag](https://github.com/pychess/pychess/blob/master/lib/pychess/Savers/pgn.py#L123) or not processing the tag if it contains `?` or `-`. The PGN game is principally not loadable in the latest release (regression ?).

Thanks.

**Comment by ecrucru** [comment]
OK, on Linux you can't double click on the game to load it : we should press the key *Enter*. That's what I wanted to write for "openable" previously.

Your commit is fine, thank you.

**Comment by gbtami** [comment]
Strange. Loading games with double click works for me on Ubuntu16.04 (xfce,gnome,w3m) and on Linux Mint 17.3 KDE also. If it still exist can you open a new issue about this please?

**Comment by ecrucru** [comment]
The double-click still doesn't work for me, but if it is OK for you on Linux, I assume that the reason is out of pyChess.

- Your code is in line with the [documentation](https://developer.gnome.org/gtk3/stable/GtkTreeView.html#gtk-tree-view-row-activated)
- No effect of `self.set_activate_on_single_click(False)`
- No effect of `gtk-double-click-time=500`
- My mouse works

I will note that for later and will come back to you if necessary.

**Comment by gbtami** [comment]
@ecrucru if you have time may I ask you to join #pychess channell on IRC freenode.net (or http://webchat.freenode.net/?channels=pychess&uio=d4) please?
