### ISSUE TITLE
Inapplicable opening book

### ISSUE THREAD

**Issue by ecrucru** [pychess/pychess#1481]
Hello,

If you start a new suicide game, the opening book is correctly deactivated.

If you load a suicide game from a PGN file (you may reuse the file from the ticket 1479), the opening book is showing entries for the first move to go. This is inapplicable : d4 or e4 are losing moves.

Regards.

**Comment by gbtami** [comment]
Pychess has one opening book entry on preferences dialog and the default is for standard chess only. There is an Xboard extension to polyglot book spec for variants. It would be cool to implement it in pychess :)
See http://hgm.nubati.net/book_format.html and later discussion about this issue http://talkchess.com/forum/viewtopic.php?t=58806&highlight=variant+book

Anyhow, until pychess doesn't support variant books it should disable book info on hints panel.
