### ISSUE TITLE
Online opening book and egtb support

### ISSUE THREAD

**Issue by gbtami** [pychess/pychess#1482]
It would be nice to ad add support for https://github.com/niklasf/lila-openingexplorer and https://github.com/niklasf/tbserve

**Comment by sshivaji** [comment]
Is it necessary to add support to lila-openingexplorer as well as
chess_db/scoutfish?

**Comment by gbtami** [comment]
chess_db/scoutfish are both offline programs not supporting variants while lila-openingexplorer and tbserve are online services supporting variants.

Pychess has offline opening book support (polyglot) and offline egtb support (gaviota) and online (nalimov via http://www.k4it.de/index.php?topic=egtb&lang=en), but they are not support variants.
