### ISSUE TITLE
Incorrect update for the renamed engines

### ISSUE THREAD

**Issue by ecrucru** [pychess/pychess#1505]
Hello,

When you add an engine, it takes by default the name of the executable file. If this executable file is physically updated, its MD5 hash will change and pyChess will load the new options correctly. Everything is OK.

Now, rename the engine in the tree view in pyChess. It will cause several problems :
- the engine is duplicated in the tree view (both old and new names)
- the engine is redetected at every launch of pyChess even if it didn't changed
- the options are not refreshed correctly : they remain in the state of the last update, generally when the engine was added for the first time

The workaround is to never change the name of the engine.

Thanks

**Comment by gbtami** [comment]
Agreed. We have to change the tree view read only.

**Comment by gbtami** [comment]
Maybe we should consider to add a new "name" field to engine properties to enable adding same engine (with different names) several times. It can be useful if one like to use an engine with different pre set options for different tasks, or for self play different versions of an engine.
