### ISSUE TITLE
Widget Move history

### ISSUE THREAD

**Issue by ecrucru** [pychess/pychess#1511]
Hello,

I have 2 feature requests about the widget "Move history" :

![image](https://user-images.githubusercontent.com/24614488/33099940-f4ad6a64-cf12-11e7-9699-826072891bd9.png)

1) The font of the pieces is a too small

2) The moves for Black never take 50% of the visible width of the widget. The width is calculated based on the width taken by the tabs of the dock view. When you resize the widgets to make the board bigger, the active width to draw the moves is not updated and the moves for black may go out of the window. This is very unfriendly and it affects also the annotation panel which truncates the visible text and moves. On the screenshot, Black is say 15% while White is 75% of the visible width.

Regards

**Comment by gbtami** [comment]
I think 2. is OK after commit https://github.com/pychess/pychess/commit/30b84fa80f6b091ca9969d18128c3844f0748c57 
Changing fonts needs new config option in Preferences, but doable.
