### ISSUE TITLE
GUI freezes after taking back a move vs endgamebot

### ISSUE THREAD

**Issue by massimiliano-leoni** [pychess/pychess#1514]
When challenging endgamebot on FICS a key functionality is to take back one move if you don't play the correct mating sequence. Recently I have experienced that after taking back a move the user interface does actually go back to the previous position, but freezes if I try to play another move afterwards.

**Comment by gbtami** [comment]
Confirmed. Seems 0.99.0 has some regression regarding examined and observed examined games. This affects using lecturebot, puzzlebot and endgamebot also.

**Comment by gbtami** [comment]
@massimiliano-leoni can you test it, please?

**Comment by massimiliano-leoni** [comment]
You have my seal of approval! :D
