### ISSUE TITLE
Residual arrows

### ISSUE THREAD

**Issue by ecrucru** [pychess/pychess#1515]
Hello,

There are 2 cases for which strange residual arrows are displayed like this :

![image](https://user-images.githubusercontent.com/24614488/33287689-cf1a5720-d3b9-11e7-9b00-127dd8be62d4.png)

- If you suspend the analyzer with the red circle in the analysis view
- If you change the position from the annotation panel because the active analyzer is not parsed immediately

Thanks

**Comment by gbtami** [comment]
Can you give me some more info (the game pgn movelist and analyzer engine settings) to reproduce this please?

**Comment by ecrucru** [comment]
Hello,

For the case **n°1**, it works with any game. Let's take this stupid one :

```
[White "Someone"]
[Black "Else"]
[Result "1/2-1/2"]

1. e4 Nc6 2. f4 Nf6 3. Nc3 Nd4 4. Nf3 c5 5. Nb5 Nxb5
6. Bxb5 Nxe4 7. O-O e6 8. Ne5 Qh4 9. g3 Qh3 10. d3 Nxg3
11. hxg3 Qxg3+ 12. Kh1 Qh3+ 13. Kg1 Qg3+ 14. Kh1 Qh3+
15. Kg1 Qg3+ 16. Kh1 Qh3+ 1/2-1/2
```

For the latest position, Stockfish will suggest `Kh1` and there is a green arrow for that. Now suspend the engine with the little red button and change the position : you will see the residual green arrow.

For the case **n°2**, changing the position should hide the arrow (because no more analysis is available at that exact moment unless it is cached) and any parsed line from the analyzer should update the arrow if it corresponds to the right position.

I don't use so much the red arrow but it is the same concern.

![image](https://user-images.githubusercontent.com/24614488/33338351-23d598b2-d476-11e7-8e6b-933926d044d3.png)

Regards

**Comment by gbtami** [comment]
Ok I understand the problem now. Thx!
