### ISSUE TITLE
No name for the human players for a game started from a notation

### ISSUE THREAD

**Issue by ecrucru** [pychess/pychess#1520]
Hello,

- Launch pyChess
- Menu Game, Enter game notation
- Human vs. Human/Stockfish, d4 e5 d5

The human players never have names, so it is strange "visually speaking".

![image](https://user-images.githubusercontent.com/24614488/33735126-ad1c5ce0-db8e-11e7-94c5-b653cca24757.png)

Regards

**Comment by gbtami** [comment]
Do you have first/second player names set in preferences?

**Comment by ecrucru** [comment]
Indeed, tested with the last commit
