### ISSUE TITLE
Paused analyzer restarts after undo

### ISSUE THREAD

**Issue by ecrucru** [pychess/pychess#1521]
Hello,

- Play a game with the assistance of the analyzer
- After some moves, suspend it with the red button in the bookPanel
- Play some other moves and undo

The engine is restarted but we don't have the red button to pause it. We see the analyzer running because the score in the annotation panel is updated and the green arrow is changing on the board.

It may be required to set a bigger number of seconds to see the effect (ex: 45 seconds of analysis)

Regards

**Comment by gbtami** [comment]
I can't reproduce this. Give some more info to reproduce, please!

**Comment by ecrucru** [comment]
The procedure above is correct. But if you have a fast computer, the right move will be raised quickly and you will probably not see the score or the arrow changing. I suggest that you monitor the CPU activity to highlight the fact that the analyzer is running despite it was asked to be paused. This was tested with the latest commit.

**Comment by gbtami** [comment]
With 5 min human-human standard chess game and glaurung/stockfis as infinite analyzer seems OK for me. CPU activity doesn't raises after undoing moves. What game type/players/analyzers should I use to reproduce this?

**Comment by ecrucru** [comment]
Oh well, one should undo several moves in a row as fast as possible (Ctrl+ZZZZ...). The animation is activated. Then we get something like that :

![image](https://user-images.githubusercontent.com/24614488/34074656-25fd04b2-e2b4-11e7-92f4-c2c982773b5f.png)

HTH

**Comment by gbtami** [comment]
Reproduced it. Thx!
