### ISSUE TITLE
Board set back to the initial position

### ISSUE THREAD

**Issue by ecrucru** [pychess/pychess#1522]
Hello,

- Start a new game
- Define the tabs "Annotation" and "Move history" exactly like this : we see that the move history is blank here

![image](https://user-images.githubusercontent.com/24614488/33735596-075ee6a4-db90-11e7-8826-994649a558e5.png)

- Switch to the tab "Annotation"

![image](https://user-images.githubusercontent.com/24614488/33735471-b11a2f6a-db8f-11e7-8d78-592ee7b5fdb3.png)

- Play few moves
- Switch to the tab "Move history"

The cursor has not followed the moves, so we are set back to the initial position. This effect happens quite often. The workaround is to set the right position back to normal with the navigational buttons in the bottom left corner of pyChess.

Regards

**Comment by gbtami** [comment]
I can't reproduce this. Is this always happening for you?

**Comment by ecrucru** [comment]
Indeed and tested with the last commit. It is important that you access the tab Move history first then switch to Annotation before you start to move.

By default for a new game, pyChess defines as visible the last visible tab. So if you start a new game and are in the tab Annotation already, if you don't show first Move history then switch to Annotation, you will not have the issue.

**Comment by ecrucru** [comment]
Hello,

The initial issue is still happening.

Here is another way to reproduce it with the latest commit :
- Start a game and be in that situation :
![image](https://user-images.githubusercontent.com/24614488/34643789-e6242a0a-f32a-11e7-9aa8-beb2999e20c7.png)
- Leave the game
- Start from a game notation : e4 e5
- You are set to the second ply
- Click on the tab «Move history»

The board is set back to the initial position.

Thanks.

**Comment by gbtami** [comment]
@ecrucru can you test it again, please?

**Comment by ecrucru** [comment]
It is ok after a quick test. Thanks.
