### ISSUE TITLE
Negative time in the clock control

### ISSUE THREAD

**Issue by ecrucru** [pychess/pychess#1526]
Hello,

If you are in the foreground and your time is over, the game is stopped (time forfeiture).

But if you are in another tab (multiple games in parallel) or if pyChess' window is reduced, then the clock may become negative. There is no check for a negative time, so the game never ends.

![image](https://user-images.githubusercontent.com/24614488/33806411-0529c3f6-ddc8-11e7-9abf-488bce394352.png)

It is tested with the latest commit.

Regards,

**Comment by gbtami** [comment]
Not exactly. There is a checkbox "Auto Call Flag" in "Actions" menu. But it used by engine players only now (and for set v_autoflag on FICS http://www.freechess.org/Help/HelpFiles/v_autoflag.html).

See https://github.com/pychess/pychess/blob/master/lib/pychess/Utils/GameModel.py#L176

Human players should use "Call flag" in "actions" menu. I'm not sure this is reasonable at all. Especially because it seems to be disabled all the time in local games :)

**Comment by ecrucru** [comment]
Thanks to your explanation, I have to revise the initial diagnostic. It is simply due to the players, not the tabs. This table is a local human vs human by simplification :

| Bottom player | Current player | Autocall | Tab            | Result        |
|:-------------:|:--------------:|:--------:|:--------------:|:-------------:|
| White         | Black          | On       | Active tab     | Game stopped  |
| White         | Black          | On       | Inactive tab   | Game stopped  |
| White         | Black          | On       | Reduced window | Game stopped  |
| Black         | Black          | On       | Active tab     | Game stopped  |
| Black         | Black          | On       | Inactive tab   | Game stopped  |
| Black         | Black          | On       | Reduced window | Game stopped  |
| White         | White          | On       | Active tab     | Negative time |
| White         | White          | On       | Inactive tab   | Negative time |
| White         | White          | On       | Reduced window | Negative time |
| Black         | White          | On       | Active tab     | Negative time |
| Black         | White          | On       | Inactive tab   | Negative time |
| Black         | White          | On       | Reduced window | Negative time |
| White         | Black          | Off      | Active tab     | Negative time |
| White         | Black          | Off      | Inactive tab   | Negative time |
| White         | Black          | Off      | Reduced window | Negative time |
| Black         | Black          | Off      | Active tab     | Negative time |
| Black         | Black          | Off      | Inactive tab   | Negative time |
| Black         | Black          | Off      | Reduced window | Negative time |
| White         | White          | Off      | Active tab     | Negative time |
| White         | White          | Off      | Inactive tab   | Negative time |
| White         | White          | Off      | Reduced window | Negative time |
| Black         | White          | Off      | Active tab     | Negative time |
| Black         | White          | Off      | Inactive tab   | Negative time |
| Black         | White          | Off      | Reduced window | Negative time |

From this table, we can conclude that autoflag `off` doesn't check the clock, but we can't say that autoflag `on` checks the clock (the behavior is not the same for Black and White if autocall is `on`). Is it a problem from your point of view ?

Regards

**Comment by gbtami** [comment]
This is rather interesting. How GameModel can stop a human-human game when zero_reached() first line is 
`if conf.get('autoCallFlag', True) and self.players[1 - color].__type__ == ARTIFICIAL:`

Btw the code in TimeModel.py seems a complete mess for me, and autoCallFlag doesn't work for me even if I remove the `and self.players[1 - color].__type__ == ARTIFICIAL` part from that conditional statement. Telling the truth I'm not against to use autoCallFlag for human players, so if you like to work on this issue just go for it!
