### ISSUE TITLE
Highlight the variation lines

### ISSUE THREAD

**Issue by ecrucru** [pychess/pychess#1529]
Hello,

This is a feature request.

The mode human vs human is practical to create studies. For example, in the following position, there are several possible moves :

- `7. Bd2`
- `7. Nc3`
- `7. Kf1`

The request is the ability to show a blue arrow on the board when at least one variation line has been created. It is more user-friendly than checking the annotation panel, and it may serve for quizzes/trainings. Schematically, the output looks like this :

![image](https://user-images.githubusercontent.com/24614488/34079275-0c807b50-e32b-11e7-9cec-4c73c4ac7695.png)

It is similar to #131, but it relies on the variation lines, not on the ouput of the analyzer.

Regards

**Comment by ecrucru** [comment]
Hello,

As a possible alternative, I was thinking about the following design :

![image](https://user-images.githubusercontent.com/24614488/34653187-fa1834e8-f3e8-11e7-8ee6-e998868d198e.png)

- Add moves in little boxes in the header of annotationPanel.
    - If sorted alphabetically, then we can try to guess the best move without assuming that it is always the first one.
    - The layout would be similar to the app «Analyze this» and better that the drop-down list on lichess's studies.

- When the mouse is over the move, an arrow is drawn on the board for a quick read.
    - It will avoid to have N arrows drawn at the same time on the board, as stated in the initial message.

- When you click on the move, you branch to the corresponding main move or sub-move.
    - It will improve the exploration of a multi-level PGN file. That's why the blue boxes of «analyze this» are very practical despite it runs on a mobile phone only and doesn't have sorted moves (guesses are mechanically limited).

- An orange box to go up or to the previous move, not to the main line (aka top level).
    - If you didn't guessed correctly, it will allow to retry.

My naive impression is that driving all the moves from the annotationPanel makes the best sense. Of course, the work _just_ needs to be done and it is not easy.

For educational purposes when reviewing an analyzed PGN file, this feature would be awesome.

Thanks.

**Comment by gbtami** [comment]
Very nice idea! We absolutely need something like this in Learn perspective Lessons panel. Telling the truth the annotation panel code base is rather spaghetti like and needs some refactoring also. First its TextView widget have to be split to header and move text parts because now it scrolls the game header out of visible view if game text is long.

**Comment by gbtami** [comment]
I have started to work on this.

**Comment by gbtami** [comment]
With commit https://github.com/pychess/pychess/commit/1ff48155da4a8dadbd7eb51549ac7a267a45c8f0 point 1. and 3. is ready for testing.

**Comment by ecrucru** [comment]
I have started to test the feature on a fully analyzed game. The expected effect is really interesting and the navigation is easier !

For now, I noticed the following things :

- display the moves with the unicode symbol if it is activated in the preferences
- set the sort of the moves as an option : sorted/shuffled=guess the best move, unsorted=quick navigation (the first move is the main line)
- when we click on the round button, we go to the subline but if it only has 0 or 1 move, the choices are not updated
- the buttons are slightly big, so when the bar of the moves is hidden when it is empty, the current position of the annotation panel may become out of the visible area
- eventually propose a sound or a colored button when there is a variation line to catch the attention more effectively

**Comment by gbtami** [comment]
1. Ready,  except reacting to change notification.
2. I postpone this. I use choices in interactive lessons unsorted now, just to let chose from opponent moves if there are many. The concept is to implement how lichess interactive lessons work now, to let users practice them in PyChess offline. We can add other kind of "guess the move" style panel later.
3. Is this still exist after my latest commit? Give a short example showing it, please!
4. Will investigate this. Telling the truth I'm just learning how Gtk theming with css works.
5. Good idea! If you can suggest any free sound (something not too intrusive, and short, similar to "success.wav I'v added lately"), please do!

**Comment by gbtami** [comment]
1., 3. and 4. should be fixed after latest commit.

**Comment by ecrucru** [comment]
**1)** OK

**2)** OK, we will try later.

**3)** The update is more correct, but this stupid case is strange :

```
1. Nf3 c5
    (1... d5 2. Ne5 f6 3. Nc4
        (3. Ng4 h5 4. Ne3 d4 5. Nd5 c6 6. Nb4 a5 7. Nd3
            (7. e3)
        )
    3... dxc4)
2. e4 e5
    (2... f6)
3. d4
    (3. c3)
3... g6
    (3... Nf6)
```

- If you browse from the beginning with the left and right arrows of the keyboard **(OK)**
- Click on `7. e3`, press the left arrow on your keyboard, there is no choice **(KO)**
- Then click `7. Nd3`, press the left arrow, there is a choice **(OK)**
- Click on `3... g6`, strange moves are proposed while it should return no choice **(KO)**

**4)** OK. This is slightly connected to #906 too.

**5)** [_choice.zip](https://github.com/pychess/pychess/files/1657893/_choice.zip) may do the job without much originality. Else there are plenty of beeps on freesound.org, and [this one](https://freesound.org/s/379419/) (after cut) could be friendly and CC0 is compatible with GPL.

**Comment by gbtami** [comment]
3. and 5. should be OK now.

**Comment by ecrucru** [comment]
Thanks for the provided feature.
It is very good, once again !
