### ISSUE TITLE
Christmas about

### ISSUE THREAD

**Issue by ecrucru** [pychess/pychess#1532]
Hello,

It seems that `glade\christmas_about.png` is not used. I assume that there is something to do at the current period with this nice winter-compatible artwork.

Regards

**Comment by gbtami** [comment]
Absolutely :) I'm just preparing 0.99.1 right now!

**Comment by ecrucru** [comment]
Oh OK, very nice release ! I didn't know that you would use the picture for the "christmas' release" :-)

It answers the question : there is no plan to have the artwork in the about dialog to be displayed time-dependently.

Thank you.
