### ISSUE TITLE
Wrong animated piece

### ISSUE THREAD

**Issue by ecrucru** [pychess/pychess#1547]
Hello,

- Activate the animations
- Consider this position : `4K3/6k1/1N6/3q4/8/2p5/8/8 w - -`
- Play `Nxd5`, `Kg6` and `Nxc3` in that order

The animation shows a queen excluded from the board while we took a pawn.

Regards

**Comment by gbtami** [comment]
It animates nothing unusual for me. Can you create a screenshot or if this is not a static thing a short video capture with your mobile phone, please?

**Comment by ecrucru** [comment]
This is very fast but here it is :
![image](https://user-images.githubusercontent.com/24614488/34499613-218f23a0-f007-11e7-8293-2dbc013c71d0.png)

**Comment by gbtami** [comment]
Wow, nice catch :) Thx!
