### ISSUE TITLE
Scoutfish 32 bits on Windows

### ISSUE THREAD

**Issue by ecrucru** [pychess/pychess#1548]
Hello,

PyChess downloads Scoutfish from Github when you tick the relevant checkbox in the external modules.

**1)** The x32 copy seems to be a 64 bits version, so it doesn't run. The workaround is to recompile `mcostalba/scoutfish` oneself and replace the executable located at `%HOMEPATH%\.local\share\pychess\engines\scoutfish_x32.exe`.

**2)** Scoutfish fails if the PGN file contains a space in its path. The workaround is to put the file in a path without any space.

**3)** Lets's open the following PGN file. It is 4 bullet games between 2 engines. A scout file is now generated :-)

```
[Event "PyChess"]
[Site "PyChess"]
[Date "2018.01.04"]
[Round "1"]
[White "Gull"]
[Black "Rybka"]
[Result "1-0"]
[TimeControl "60+1"]
[PlyCount "45"]
[Termination "normal"]

1. Nc3 Nc6 2. Nf3 Nf6 3. d4 d6 4. e4 Be6 5. d5 Bd7 6. dxc6 Bxc6 7. Bd3 d5 8.
Ne5 Qd6 9. Nxc6 Qxc6 10. Bb5 dxe4 11. Bxc6+ bxc6 12. Qd4 Rd8 13. Qxa7 Kd7 14.
Bf4 Ke8 15. Qxc7 c5 16. Qc6+ Rd7 17. Rd1 e5 18. Bxe5 Bd6 19. Rxd6 e3 20. Qc8+
Ke7 21. Nd5+ Nxd5 22. Qxd7+ Kf8 23. Qd8# 1-0 


[Event "PyChess"]
[Site "PyChess"]
[Date "2018.01.04"]
[Round "1"]
[White "Rybka"]
[Black "Gull"]
[Result "0-1"]
[PlyCount "88"]
[Termination "normal"]

1. Nc3 Nc6 2. Nf3 d5 3. d3 Nf6 4. Bf4 a6 5. Ne5 Nxe5 6. Bxe5 c6 7. Qd2 Ng4 8.
Bd4 e5 9. Be3 d4 10. Bg5 dxc3 11. bxc3 Qb6 12. d4 exd4 13. cxd4 h6 14. Bf4 Qb2
15. Rd1 Bb4 16. c3 Bxc3 17. h3 Bxd2+ 18. Bxd2 Nf6 19. e3 Qxa2 20. Bd3 a5 21.
O-O Qb3 22. Bc1 a4 23. e4 a3 24. Bf4 a2 25. e5 Nd5 26. Be3 Nxe3 27. fxe3 Qc3
28. e6 Bxe6 29. d5 Bxd5 30. e4 a1=Q 31. Rxa1 Rxa1 32. exd5 Qxd3 33. Rxa1 Qd4+
34. Kh2 Qe5+ 35. g3 Qb2+ 36. Kg1 Qxa1+ 37. Kf2 cxd5 38. h4 Qh1 39. Ke3 Qe4+ 40.
Kf2 d4 41. Kg1 d3 42. Kf1 Qe2+ 43. Kg1 d2 44. h5 d1=Q# 0-1 


[Event "PyChess"]
[Site "PyChess"]
[Date "2018.01.04"]
[Round "1"]
[White "Rybka"]
[Black "Gull"]
[Result "0-1"]
[TimeControl "60+1"]
[PlyCount "36"]
[Termination "normal"]

1. Nc3 Nf6 2. Nf3 d5 3. Ne5 d4 4. Nb5 c6 5. Na3 Bf5 6. Nac4 b5 7. g4 Nxg4 8.
f3 e6 9. h4 Be7 10. Nxg4 Bxg4 11. e3 Bxh4+ 12. Ke2 d3+ 13. cxd3 Bxf3+ 14. Kxf3
Qf6+ 15. Kg4 Qg5+ 16. Kf3 Qf5+ 17. Kg2 Qf2+ 18. Kh3 Qg3# 0-1 


[Event "PyChess"]
[Site "PyChess"]
[Date "2018.01.04"]
[Round "1"]
[White "Gull"]
[Black "Rybka"]
[Result "1-0"]
[TimeControl "60+1"]
[PlyCount "67"]
[Termination "normal"]

1. c4 Nc6 2. Nf3 Nf6 3. d4 d5 4. cxd5 Qxd5 5. Nc3 Qd6 6. e4 Be6 7. e5 Qb4 8.
a3 Qa5 9. exf6 O-O-O 10. Bb5 exf6 11. O-O Bd6 12. Be3 Kb8 13. b4 Qb6 14. d5 Nd4
15. Bxd4 c5 16. dxc6 Qc7 17. cxb7 Qxb7 18. Qa4 Rc8 19. Ba6 Qd7 20. Nb5 Rc6 21.
Bxa7+ Ka8 22. Be3 Bb3 23. Qa5 Qd8 24. Bb7+ Kxb7 25. Qa7+ Kc8 26. Nxd6+ Qxd6 27.
Qa8+ Kd7 28. Qxh8 Rc2 29. Rad1 Bd5 30. Bc5 Qe6 31. Rfe1 Qg4 32. Re7+ Kc6 33.
Qe8+ Qd7 34. Qxd7# 1-0
```

If I add a filter for `8/8/8/5q2/7b/8/8/8` (=`qf5`+`bh4`), then I get no result in PyChess. If I query the scout file directly, then I get a result. This is indeed the right result from the third game (`16... Qf5+`) but there is no message to explain why the game is not found by PyChess.

```
C:\>scoutfish.exe
scout ai.scout {"sub-fen":"8/8/8/5q2/7b/8/8/8"}
{
    "moves": 236,
    "match count": 1,
    "moves/second": 0,
    "processing time (ms)": 0,
    "matches":
    [
        { "ofs": 1171, "ply": [32] }
    ]
}
```

Thanks for your help of these issues.

Regards

**Comment by sshivaji** [comment]
Glad you guys are integrating scoutfish. I helped with some of the
scoutfish stuff before. I apologize for lack of contributions to pychess,
unfortunately, I dont have Ubuntu anymore and am using only Mac for dev,
can we run pychess on Mac?

We can change scoutfish code at https://github.com/gbtami/scoutfish or
https://github.com/sshivaji/scoutfish. We should change the C++ code for
issues 1 and 2. The reason why its failing on a space in a PGN file is that
it assumes that the next argument is sent. This is not hard to handle, but
needs to be done..

**Comment by gbtami** [comment]
@ecrucru sub-fen queryes definitely worked at some point before. Seems this regression is exist in 0.99.0 also :(

@sshivaji unfortunately I never had any Mac so I can't help too much. I think it definitely should work with minor system specific patches. As I know the directory structure is a little different so https://github.com/pychess/pychess/blob/master/lib/pychess/System/prefix.py may need some changes. Regarding dependencies Quodlibet is a pygobject project with similar dependencies to PyChess so https://github.com/quodlibet/quodlibet/tree/master/osx_bundle can help to start with.

**Comment by gbtami** [comment]
Filed 2) as #1549
and 3) as #1550 
See my comments there.

**Comment by gbtami** [comment]
@sshivaji seems 3) needs fix in scoutfish code also :(

**Comment by sshivaji** [comment]
I can do the fixes to the scoutfish module, but I need a new environment to
test out pychess. Hopefully I can find something that works on Mac, or is
there a way to test out pychess without the GUI?

**Comment by gbtami** [comment]
Moved to https://github.com/pychess/scoutfish/issues

**Comment by gbtami** [comment]
@sshivaji btw all these issues are scoutfish only so you can work on them without installing PyChess.
Of course if you can make PyChess work on Mac it would be a huge win 😉
