### ISSUE TITLE
Recent files in the menu on Windows

### ISSUE THREAD

**Issue by ecrucru** [pychess/pychess#1552]
Hello,

On Windows, does the menu «Load recent game» work for you ?

Mine is deseperately blank :
![image](https://user-images.githubusercontent.com/24614488/34643908-19611b1a-f32d-11e7-95b5-c7c2c8858b2c.png)

It is OK on Linux with the latest commit, so it may be an OS-specific issue.

Thanks

**Comment by gbtami** [comment]
Same here.
