### ISSUE TITLE
Support not 8x8 chess variants like Shogi and XiangQi

### ISSUE THREAD

**Issue by gbtami** [pychess/pychess#1561]

**Comment by gbtami** [comment]
https://www.chessbase.in/news/peter-heine-nielsen-on-shogi/
http://georgiachessnews.com/2018/01/09/why-you-need-to-learn-xiangqi-for-playing-better-chess/

**Comment by gbtami** [comment]
This needs complete rewrite.

**Comment by LouisGariepy** [comment]
Is this still being worked on?

**Comment by gbtami** [comment]
No.
