### ISSUE TITLE
Better wildcard to filter a PGN file

### ISSUE THREAD

**Issue by ecrucru** [pychess/pychess#1566]
Hello,

This is a feature request.

Let's suppose that you want to filter by the name of a chess player in the filter view, you have to type something like `%parov%` because of sqlite.

What about doing something more usual like `*parov*` ? Or eventually `parov` directly searches for `%parov%`, and `as*ov` for `%as%ov%` ?

`Kasparov` is just a simple example, but the issue is more common when a complex name has variants like `-`, `- `, ` -` or ` - ` (dash and spaces around).

Regards

**Comment by gbtami** [comment]
In commit https://github.com/pychess/pychess/commit/b0d864cf3434b69d3d3d20d60c6745b397930daa I changed .pgn filtering from startswith('text') to like('%text%')
Feel free to enhance it further if you want to add more flexibility.

**Comment by ecrucru** [comment]
Thanks for the change.
