### ISSUE TITLE
eco.db in latest MSI release

### ISSUE THREAD

**Issue by ecrucru** [pychess/pychess#1569]
Hello,

This is an information.

The MSI package of PyChess 0.99.1 has an incomplete file `pychess/share/pychess/eco.db`, so there are some issues related to the determination of the openings.

The regenerated file from the latest commit is compatible (refer to pgn2ecodb).

Regards

**Comment by gbtami** [comment]
You are right :( Fortunately eco.db is available in https://github.com/pychess/pychess/releases/download/0.99.1/pychess-0.99.1.tar.gz
