### ISSUE TITLE
Estimated duration of a game

### ISSUE THREAD

**Issue by ecrucru** [pychess/pychess#1575]
Hello,

This is a feature request.

If you play a game X'+Y", its duration is generally equal to ceil(2*(X+Y*40/60)) minutes. For example, 15+15 looks low but it may represent 50 minutes. On the other hand, 15+0 is limited to 30 minutes whatever the number of moves.

In the new game dialog, the idea is to show the estimated duration of the game before the game starts. The value is updated each time you change a clock or select a new radio button. The calculation depends on the chosen clock type indeed.

Regards

**Comment by gbtami** [comment]
On fics this called etime (http://www.freechess.org/Help/HelpFiles/etime.html).
We use this formula to sort games on FICS perspective seek panel if you click on Clock column header.

Telling the truth I'm not convinced that showing etime on new game dialog (or anyone else) can interest average user. All chess players has favourite time controls they like to play. I'v never met any of them in my life who was thinking in term of game duration time when they choose a particular time control. Maybe I'm wrong.

**Comment by ecrucru** [comment]
When you are not familiar with the clocks, it may be informative for an offline use. For example, to accelerate the beginning of the game, you may accept a shorter fixed time at the benefit of a higher increment within a limited time frame (after 40 moves, 3+10 and 10+0 are unobviously quite the same). Another example, you may run out of time at the end with no increment, so may want to use one without exceeding a given duration. Another example, you may want to play blitz (5+3) or standard (5+4) at the limit. Yes, the examples are probably a bit exagerated... until you have your own habits.

The request is opened for comments because there are 4 possible implementations :

1. A dedicated gtk label : takes some space
2. A simple bracket in the caption of the option : not intrusive
3. A tooltip
4. Reject the idea

![image](https://user-images.githubusercontent.com/24614488/35642403-4e5ed826-06c3-11e8-9dd6-27455939546e.png)
(* fictitious figures)

**Comment by ddugovic** [comment]
I like the simple bracket idea, and if there's space display a range `(5 - 10 minutes)` for an estimated 20 - 60 moves.

**Comment by gbtami** [comment]
Ok, I'm sold. My vote is on combined 2. and 3. :)
