### ISSUE TITLE
Filter games by month in database

### ISSUE THREAD

**Issue by ecrucru** [pychess/pychess#1594]
![image](https://user-images.githubusercontent.com/24614488/36357864-7bdeabf6-1504-11e8-81e0-4319a1bf2bb9.png)

Eventually by day also

**Comment by gbtami** [comment]
I can't remember why I added year only but I think it should be Date (from-to) instead.

**Comment by ecrucru** [comment]
May it be linked to the partial dates ?

To use the date as a whole, I don't measure yet the impact and regression. So I will not help much on that topic.

**Comment by ecrucru** [comment]
About the field Year, if you want to search for games of a given year, one should set that year **both** in `year_from` and `year_to`. That's for an higher user friendliness.

**Comment by gbtami** [comment]
I think https://github.com/pychess/pychess/commit/0755b86cfa26a53cdb354a52072387cefcbde925 fixed this.
