### ISSUE TITLE
Export the position as text

### ISSUE THREAD

**Issue by ecrucru** [pychess/pychess#1599]
Hello,

Following #678, the idea is to copy the board in the following format :

```
A""""""""S
çtMvWlVmT%
æOoOoOoOo%
å*+*+*+*+%
ä+*+*+*+*%
ã*+*+*+*+%
â+*+*+*+*%
ápPpPpPpP%
àRnBqKbNr%
DèéêëìíîïF
```

This text can be rendered with a special TTF font.

Regards

**Comment by gbtami** [comment]
PyChess logging uses `__repr__()` the board to .log file. See https://github.com/pychess/pychess/blob/master/lib/pychess/Utils/lutils/LBoard.py#L831
You can use `print()` the board to .txt file also. Feel free to enhance its layout if you need it.
