### ISSUE TITLE
Update Wiki/ChessEngines

### ISSUE THREAD

**Issue by ecrucru** [pychess/pychess#1600]
https://github.com/pychess/pychess/wiki/ChessEngines

- Generic information about few recommended engines
- Possible concerns/limitations when used in PyChess
- Engines for Windows too
- Variant engines
- Matrix of features
- Updated download links
- Online anti-virus recheck

The purpose is to offer PyChess' players a quick guide to play against a suitable and reliable AI.

**Comment by gbtami** [comment]
Only one thing I ask, don't add Windows only engines to list, please!

**Comment by gbtami** [comment]
@ecrucru great update, thx!
One thing I noticed, you use "no more supported" and "unsupported" in some places. Shouldn't be it "no more developed" instead?

**Comment by ecrucru** [comment]
Oh yes, sorry for the wording! That's corrected now.
Thanks
