### ISSUE TITLE
Deeper annotationPanel

### ISSUE THREAD

**Issue by ecrucru** [pychess/pychess#1610]
Example to illustrate the idea :
![image](https://user-images.githubusercontent.com/24614488/36863640-939bc0d8-1d8a-11e8-98b6-f446461a06bb.png)

**Comment by gbtami** [comment]
Can you explain this a bit more detailed please?

**Comment by ecrucru** [comment]
The levels are not well indented because of a limit given by the red style.

I have some PGN studies with a lot of levels and I just realized that a deeper level may be less indented than the parent level. With wrapped text when the subline is long and/or commented, it becomes very complicated to handle.

The idea is to see if adding new styles may help to limit that effect. It will not change anything until 3 sublevels.
