### ISSUE TITLE
Provide pychess as a Snap package

### ISSUE THREAD

**Issue by rhersel** [pychess/pychess#1611]
As you know, Snap is a universal package format that gives developers and maintainers less work than building packages for each and every Linux package format. Snap serves it all and provides instant updates to your users.

**Please provide Pychess as a Snap package.**

The reason for this request is that I'm using the Solus Distro and Pychess is neither available as an eopkg package nor as a Snap package.

**Comment by MariusQuabeck** [comment]
At https://docs.snapcraft.io/ you can find information on how to package your app as a snap. If you need any help, please ask at https://forum.snapcraft.io/ and the awesome Snapcraft team & community devs will happily provide help :)

**Comment by gbtami** [comment]
@rhersel I myself don't want to maintain additional package formats other than .rpm .deb and .msi
If your Linux distribution doesn't provide PyChess packages yet you always can use it from sources. If all dependencies are installed, you can run pychess in place! See https://github.com/pychess/pychess/blob/master/INSTALL for dependencies.

**Comment by rhersel** [comment]
Ok, maybe you will change your mind in the future as Snap becomes a more universal package format. Thanks for taking it into account.

**Comment by gbtami** [comment]
I'v asked solus devs on IRC about packaging pychess and they said they create solus packages only for stable releases. So after we release pychess 1.0 there is hope it will go into solus. See updated https://dev.solus-project.com/T5448
