### ISSUE TITLE
Pychess complains of not all dependencies installed - rsvg

### ISSUE THREAD

**Issue by walterjwhite** [pychess/pychess#1614]
I am attempting to launch pychess and upon doing so get:

```
ERROR: Not all dependencies installed! You can find them in INSTALL
Namespace Rsvg not available
```

I tried both my distribution's package as well as the source and then manually installing the deps using python3 setup.py install.  Both yielded the same results.  My distribution has 0.12.4, the source I tried is 0.99.1.

**Comment by gbtami** [comment]
What distribution are you using? What packages (listed in INSTALL) do you have installed?

**Comment by walterjwhite** [comment]
I am using Funtoo Linux.  An older version was working fine.

python3.4.6-r1
x11-libs/cairo-1.14.8
dev-python/pycairo-1.15.1
x11-libs/pango-1.40.3
dev-libs/glib-2.48.2
x11-libs/gtksourceview-2.10.5-r3
x11-libs/gtksourceview-3.20.4
media-libs/gstreamer-0.10.36-r2
media-libs/gstreamer-1.12.3
dev-python/pygobject-3.20.1
gnome-base/librsvg-2.40.16

So, the rsvg error from above leads me to believe something is awry with rsvg, but it is installed.  Maybe it is in the wrong place?

**Comment by gbtami** [comment]
PyChess is a Python3 project and it needs python binding packages of rsvg also.

**Comment by walterjwhite** [comment]
Ok, I see the issue, upstream gentoo only supports dev-python/librsvg-python in python 2.
