### ISSUE TITLE
Enhanced load of the local engines

### ISSUE THREAD

**Issue by ecrucru** [pychess/pychess#1629]
Hello,

The concept is to get more information about the engines based on matching names, not based on hard-coded names.

The work in progress includes :
- a reworked list of engines (to be extended later)
- insentiveness to exact file name, including :
    - software version
    - operating system
    - bitness
    - instruction set
- a new field ELO

Regards

**Comment by gbtami** [comment]
Can you explain a bit more what is the goal of this issue please?
Or we can discuss it on http://webchat.freenode.net/?channels=pychess&uio=d4 if you have time.

**Comment by ecrucru** [comment]
It is just minor things to investigate to get a proposed flag and ELO estimate against an engine whatever the exact name of the executable file. In the same way, it should fix little things I saw like hard-coded values, clean up or duplicate engines.

It should help me also to qualify upcoming harder issues for 6 engines of various strength and quality (Andscacs, Gull, µMax, Phalanx, Vanilla and AnMon).
