### ISSUE TITLE
not counting wins just losses 

### ISSUE THREAD

**Issue by CyberXess** [pychess/pychess#1631]
Hello all, I hope anyone could help me with this problem:
For about a month my pychess program stop counting wins and losses and I thought I'd report the problem, but kept postponing that issue, because I did not feel hurt on this problem.
Know suddenly the problem was partially resolved they start to count only losses!!! If then I was not being harmed, know I am, because my rating is decreasing radically because of this issue! If I win the rating maintains equal, if I lose they naturally decrease my rating - this is extremely annoying!  If someone could help me on this very unfair issue that gets me very furious, I would be grateful.

Many many thanks,
bye

**Comment by gbtami** [comment]
@CyberXess pychess itself doesn't counts wins/losses and never calculates any ratings. It simply reports your finger data from freeechess.org while you are logged in and when it's changing after you finish a rated game. Maybe you are talking about something different and I just misunderstand your problem?

**Comment by CyberXess** [comment]
Sure,

forgive if I mis-explained myself I am not a programmer (yet) and I don't know how this things work and english is not my first language. I'll assume I made myself unclear...

The thing is in the top right corner of the pychess application (when one is logged in) there is a your user name and then, the type of game (Blitz and Standard in my case), and next to it the rating, the wins the Draws and the losses. So far I think it is clear! What happens is that if I lose a game it almost instantly appears as a lost in that table, on the contrary if I win a game it don't appears as a win now. It use to work well but for some time as I said the wins, Draws and Losses, remained unchanged. For about some days till now the Wins and the Draws remain unchainged, even if I win and Draw some game, but then if i lost a game it counts... What is that  this deviation makes happen? That makes my rating seriously damaged!

I hope now I maid myself clear and that you or someone could help me on this.

Many many thanks in advance.

Cheers

**Comment by gbtami** [comment]
Ok, seems at least we are saying about the same thing :)
Anyhow I'v never noticed this behaviour in pychess. Are you sure you play rated games when this happens?
Btw. what version of pychess are you  using and on what OS?
