### ISSUE TITLE
wrong french translation for "A player checks"

### ISSUE THREAD

**Issue by herverenault** [pychess/pychess#1637]
```
#: glade/PyChess.glade:3365
msgid "A player _checks:"
msgstr "Vérification _Joueur"
```
Should be "Un joueur fait échec"

**Comment by gbtami** [comment]
@herverenault you can help to translate pychess on https://www.transifex.com/projects/p/pychess/ Yuo just have to register and can use its web interface to work on translations.

**Comment by herverenault** [comment]
OK done: https://www.transifex.com/gbtami/pychess/translate/#fr/pychess/4826458?q=text%3A'A+player+_checks%3A'

**Comment by gbtami** [comment]
Thx!
Btw. next release is coming soon, so I will update the translations template on transifex also.
