### ISSUE TITLE
When anonymous FICS game is saved to PGN file, user name should be tagged

### ISSUE THREAD

**Issue by herverenault** [pychess/pychess#1638]
Because when you open the PGN later on, you can't remember which player you were :)

Mobialia Chess for Android tags the user as "GuestWXYZ (Player)" vs opponent "GuestABCD". I think this a good way of doing it.

I've had a look at lib/pychess/Utils/GameModel.py, is it the right place to do this? I'd like to try and make a patch.

**Comment by gbtami** [comment]
Good idea!
I think lib/pychess/ic/ICGameModel.py is the place you are looking for. It contains some helper function also, like  remote_player(), remote_ficsplayer(), hasGuestPlayers(), etc. you may find useful.
