### ISSUE TITLE
ValueError: invalid literal for int() with base 10: ''

### ISSUE THREAD

**Issue by lrodriguez15** [pychess/pychess#1640]
Hello, I'm getting these error in UBUNTU 17.10. Something crashes and a new instance of Pychess is opened.  Any thoughts?   

File "/usr/lib/python3/dist-packages/pychess/Utils/GameModel.py", line 308, in on_analyze
    if (ply not in self.spy_scores) or (int(self.spy_scores[ply][2]) <= int(depth)):
ValueError: invalid literal for int() with base 10: ''
Traceback (most recent call last):

**Comment by gbtami** [comment]
What version of pychess are you using?

**Comment by lrodriguez15** [comment]
Morphy 0.99.1

**Comment by gbtami** [comment]
Seems your spy (inverted) analysis engine is sending something unusual output to pychess.
Try to disable it in Edit->Preferences->Hints or install stockfish and choose it for both analyzer and for inverted analyzer.

**Comment by ecrucru** [comment]
In UCIEngine, under certain circumstances, the parsed depth may be returned as a blank string. Later converted to int, it fails because `int("") = ValueError` instead of `0`.

Or it is an issue with the score returned by the engine, but we need more information about the engine and the position.

**Comment by gbtami** [comment]
@lrodriguez15 it would good to know what engine are you using as inverted analyzer and what chess position produces this error.

**Comment by lrodriguez15** [comment]
I'm using stockfish and the most recent time when the error ocurred was in
this position: r5k1/pppq1ppp/3b1n2/3p4/3n2P1/1B1Pr1P1/PPPN3P/R2Q1KNR b - -
3 13
