### ISSUE TITLE
Assume queen when the promotion mark is missing from the engine

### ISSUE THREAD

**Issue by ecrucru** [pychess/pychess#1641]
Hello,

With PyChess 0.99.1 (not latest git), UsurpatorII fails on `8/6pp/1K6/3P1p2/2P2P1k/8/p7/8 b - - 0 44`. It sends `a2a1` without the mark of the queen, so PyChess tells that it is incorrect and ends the game.

Is it regular to assume that a move can be promoted to queen in that condition ? The option to auto-promote to queen has no effect here.

As a comparison, in the Arena GUI, there is no issue and it promotes to queen by default.

Regards

**Comment by gbtami** [comment]
I think this happens at https://github.com/pychess/pychess/blob/master/lib/pychess/Utils/lutils/lmove.py#L636
Instead of
`raise ParsingError`
try
`flag = QUEEN_PROMOTION`
