### ISSUE TITLE
Add the engines in mass

### ISSUE THREAD

**Issue by ecrucru** [pychess/pychess#1642]
Hello,

In the current state, the engines are found automatically by looping on a preconfigured set of engines, then the run data are found in the path. An engine can be later added manually from the dialog window.

The feature request is about adding the engines by selecting a folder. Indeed, they are generally stored in the same parent folder.

So the idea is :

- Add a function(path, depth)
	- If path is none, consider the envpath
	- Scans the folders to match the depth
	- Return a list of folders
- At startup, we call the function for the envpath and depth 0
- In engineDialog, add a button
	- The button selects a folder from the dialog
	- A list a subfolders is returned : it should not be part of envpath
- For both, find an executable file in each folder : `*.exe` or `+x`
- If the file matches against a pattern like `uninstall|reset|remove|delete|purge`, skip
- If the file is already loaded (same name), skip to not add it twice
	- If you add again the same folder, it will do a delta load
- If the file is not in the list of preconf engine list, skip (else we could trigger an executable file not related to chess)
	- It is still possible to add it manually
- If the file name contains `32`, `64`, etc... we verify that the bitness matches with the operating system
	- The engines are often shipped in multiple copies
- Add the engine in a to-be-checked state (like today)
- Once the loop is finished, PyChess will use the existing feature to load the options
- We need then to clean the engines for which nothing was read

Regards

**Comment by gbtami** [comment]
Good idea! I always hate to re add my test engines after deleting engines.json for any reason.
