### ISSUE TITLE
create_rpm_py36.sh run failure

### ISSUE THREAD

**Issue by mattgatto** [pychess/pychess#1644]
It would seem that the tar ball that's created, dist/PyChess-0.99.1.tar.gz, doesn't have "pgn2ecodb.py" in it.

[mgatto@maggie pychess-git]$ ./create_rpm_py36.sh 

[ ... ]

+ STATUS=0
+ '[' 0 -ne 0 ']'
+ cd PyChess-0.99.1
+ /usr/bin/chmod -Rf a+rX,u+w,g-w,o-w .
+ exit 0
Executing(%build): /bin/sh -e /var/tmp/rpm-tmp.KGBvF9
+ umask 022
+ cd /home/mgatto/code/pychess-git/build/bdist.linux-x86_64/rpm/BUILD
+ cd PyChess-0.99.1
+ /usr/bin/python3.6 setup.py build
Traceback (most recent call last):
  File "setup.py", line 130, in <module>
    exec(open("pgn2ecodb.py").read())
FileNotFoundError: [Errno 2] No such file or directory: 'pgn2ecodb.py'
error: Bad exit status from /var/tmp/rpm-tmp.KGBvF9 (%build)

RPM build errors:
    Bad exit status from /var/tmp/rpm-tmp.KGBvF9 (%build)
error: command 'rpmbuild' failed with exit status 1

**Comment by gbtami** [comment]
Released packages are not created from .tar.gz but from sources.
1. git clone https://github.com/pychess/pychess.git
2. cd pychess
3. git checkout 0.99.1
4. ./create_rpm_py36.sh

Btw. don't you want to try current pychess from git instead? :)

**Comment by mattgatto** [comment]
ok, that worked.
