### ISSUE TITLE
Undo (Ctrl-Z) deletes all analysis

### ISSUE THREAD

**Issue by mattgatto** [pychess/pychess#1647]
I was using pychess git (from a self-built rpm) to do some analysis, i.e, create a bunch of variations, and I was trying to delete one of the moves from one of the variations, so I hit Ctrl Z, and it deleted all of the variations, which seems to me to be a major bug.

**Comment by gbtami** [comment]
Matt, how can I reproduce this? Can you give me step-by-step instructions please?
