### ISSUE TITLE
Pychess doesn't load analysis variations from PGN files into analysis panel as moves

### ISSUE THREAD

**Issue by mattgatto** [pychess/pychess#1648]
Pychess doesn't load analysis variations from PGN files into analysis panel as moves, but only as a comment.

**Comment by gbtami** [comment]
Unfortunately I can't reproduce this. Matt, can you paste that .pgn here please?

**Comment by mattgatto** [comment]
[Event "Local Event"]
[Site "Local Site"]
[Date "2018.05.17"]
[Round "1"]
[White "Matthew Gatto"]
[Black "Guest"]
[Result "*"]
[Variant "Fischerandom"]
[SetUp "1"]
[FEN "nbqrnkbr/pppppppp/8/8/8/8/PPPPPPPP/NBQRNKBR w HDhd - 0 1"]
[PlyCount "17"]
[Termination "normal"]

1. d4 d5 2. c4 c6 3. cxd5 cxd5 4. Nb3 Bd6 5. f3 h6 6. e4 Bh7 7. Be3 e6 8. e5
Bxb1 9. Qxb1 {Analyzer's primary variation: 9... Be7 10. Rc1 Qd7 } *

**Comment by gbtami** [comment]
Wait! This variation line is a comment regarding PGN spec. It should be inside () to be variation line for the PGN parser. Matt can you remember how you created this? If you added it in annotation panel by had (in a little comment dialog/editor) then this is OK.

**Comment by mattgatto** [comment]
I added them just by making moves at the end of the game to create
variations, not by using a comment editor.

**Comment by gbtami** [comment]
Ok thx! Finally I was able to reproduce this.
