### ISSUE TITLE
logo

### ISSUE THREAD

**Issue by ahmeterbay** [pychess/pychess#1649]
hi
can i help u to design a new logo for your application?
it will be free :)

**Comment by gbtami** [comment]
@ahmeterbay first of all thx for the offer!
Telling the truth I like the PyChess logo we have now, but there is another area where we need some help. If you want to help pychess take a look at https://github.com/pychess/pychess/issues/1368 please! (Docker icons are the small .svg images at the upper left corner of each sidepanel.)

Btw. the original PyChess logo was designed by @mimooh

**Comment by ahmeterbay** [comment]
thanx for offer but ı just lıke to desıgn logo..
