### ISSUE TITLE
Smoother score

### ISSUE THREAD

**Issue by ecrucru** [pychess/pychess#1656]
Hello,

When a game is loaded, the score is shown with a depth of 1. When the queens are exchanged for example, you have unreliable peeks.

A smoother score may be obtained with depth 3.

HaGN

**Comment by gbtami** [comment]
This happens only when no analyzer engine was enabled in preferences. In this case we use leval.evaluateComplete() and this gives us a "static" evaluation of the current position only. See https://github.com/pychess/pychess/blob/master/lib/pychess/perspectives/games/scorePanel.py#L79
Maybe it would be more correct not to draw anything at all in score panel if analyzer is not enabled.

**Comment by ecrucru** [comment]
You must always display a quick score by default that will be refined by an engine. The current logic is the good one.

My point is, instead of that :
![image](https://user-images.githubusercontent.com/24614488/42906523-ad65791e-8adb-11e8-871b-7b633a67e2f7.png)

Just get something smoother by default like that with less peaks :
![image](https://user-images.githubusercontent.com/24614488/42906537-b1366daa-8adb-11e8-984e-75281b4b3bb6.png)

The trick is to invoke a low depth evaluation with your pyengine instead of a static evaluation that ignores easy tactical tricks (like piece exchange). It should not consume so much time, at least really much less than a full call to stockfish.

**Comment by gbtami** [comment]
The reason of introducing static evaluation (when no analyzer was enabled) was exactly that pychess own python engine is extremely slow and resource hungry compared to "real" engines like stockfish.

**Comment by ecrucru** [comment]
OK, I see your point. Thanks.
