### ISSUE TITLE
Undo causing pychess endless loop

### ISSUE THREAD

**Issue by jule009** [pychess/pychess#1657]
Hi, should this problem be solved in ...99.2? It appears also in my ...99.2 installation. I have made a log again, is this log of interest?  Then I will publish it. So far the error occured when Pychess has to make a decision, where it can loose the game. Also a redraw has been done some draws before. Level 15. Kind regards
![pychessendlessloop180720](https://user-images.githubusercontent.com/40624880/42986330-69347874-8bf5-11e8-8b0c-25f63d3da70d.png)

**Comment by gbtami** [comment]
Yes, attach the .log file please! Maybe if you rename it from .log to .txt github will enable to directly attach it instead of copy-paste.

**Comment by jule009** [comment]
[2018-07-20_07-05-37.txt](https://github.com/pychess/pychess/files/2212979/2018-07-20_07-05-37.txt)

Here the log, I think one condition except redraw is a "big" thinking phase of Pychess and possibly the Pychess internal question, how to win in an difficult situation.

**Comment by gbtami** [comment]
Thx! Seems my fix not covered all possible cases of #1652

**Comment by jule009** [comment]
Here an occurrence of this error again, don't know if this is the same location in the code.
![pychessendlessloop180722](https://user-images.githubusercontent.com/40624880/43045429-f41b033a-8db8-11e8-8e0b-b841b4b7b35e.png) .

Here the logfile
[2018-07-22_12-55-27.txt](https://github.com/pychess/pychess/files/2216991/2018-07-22_12-55-27.txt)

**Comment by jule009** [comment]
There is an occurrence again, I don't know, if it's the same as the previous occurrences, therefore I mention it.
![pychessendlessloop180803](https://user-images.githubusercontent.com/40624880/43641197-f8227a80-9722-11e8-9675-bab2f4de56f5.png)

here the log file:
[2018-08-03_11-22-31.txt](https://github.com/pychess/pychess/files/2257219/2018-08-03_11-22-31.txt)

Kind regards

**Comment by jule009** [comment]
again this error occured. I present the log, hope it's helpful
[2018-08-03_17-50-56.txt](https://github.com/pychess/pychess/files/2258191/2018-08-03_17-50-56.txt)

![pychessendlessloop180803-2](https://user-images.githubusercontent.com/40624880/43656494-dfbeef0c-9752-11e8-9a3d-2e4984df1ed4.png)

Kind regards

**Comment by gbtami** [comment]
Thx @jule009 ! I can reproduce this issue now so no more examples needed :)
Unfortunately I didn't find the correct fix yet :(

**Comment by gbtami** [comment]
@jule009 may I ask you to test https://github.com/pychess/pychess/releases/download/0.99.2/PyChess-0.99.2-2018.08.17-mingw.msi regarding this issue, please?
It's a new installer built with latest versions of Python3.7, Gtk3, etc. using http://www.msys2.org/ instead of outdated https://sourceforge.net/projects/pygobjectwin32/
If you find anything not working with this installer but worked with the old one, please report it also. Thx!

**Comment by jule009** [comment]
First try: Cannot start this "try out" Pychess with "pychess --log-debug", don't know why, my fault? Clicking onto the Pychess icon starts Pychess. So currently, I can not produce a logfile.
Kind regards

**Comment by jule009** [comment]
works now only giving the full path, i.e. C:\Users\***\Appdata\Local\Programs\pychess\pychess.exe --log-debug
Kind regards

**Comment by gbtami** [comment]
You can start PyChess with --log-debug using the icon also. Just use the icons right click properties(?) menu item to change the command it starts.

**Comment by jule009** [comment]
![pychesserror180817](https://user-images.githubusercontent.com/40624880/44266546-39b11480-a22b-11e8-8465-dc3828a6004b.png)
In this position I can not move the queen, would like to move to H1. I find no reason why, but possibly I don`t see all. Could be an error in https://github.com/pychess/pychess/releases/download/0.99.2/PyChess-0.99.2-2018.08.17-mingw.msi
[2018-08-17_13-47-03.txt](https://github.com/pychess/pychess/files/2297212/2018-08-17_13-47-03.txt)

**Comment by jule009** [comment]
sorry, too much chess, my error in the last comment

**Comment by jule009** [comment]
Intermediary result: In the last 15 chess plays with the updated version https://github.com/pychess/pychess/releases/download/0.99.2/PyChess-0.99.2-2018.08.17-mingw.msi this error "endless loop" didn't occur, tests were done in the way, where normally this error occured. In my feeling this version seems to be ok. I will do further tests, one or two times per day. And in case of error report.

**Comment by gbtami** [comment]
Had you you made "undo move"s in these games? I'm asking this because the original issue was caused by incorrect undo logic in pychess code.
@jule009 thx for the feedback!

**Comment by jule009** [comment]
There are always "undo's", when I am playing chess with Pychess, because otherwise I would loose the game. There are also always situations, where Pychess might feel to loose the game. Therefore I incorporated all, what I know, about forcing this error to appear. Anyway currently I have about 2 games a day and sofar this error didn't occur.

**Comment by gbtami** [comment]
OK, I close this issue now. If it occurs again feel free to reopen it.

**Comment by jule009** [comment]
After about 100 error free games this error occured again.
![pychessendlessloop181110](https://user-images.githubusercontent.com/40624880/48301119-b1b86f00-e4e8-11e8-811e-696032befe2c.png)
[2018-11-10_11-18-58.txt](https://github.com/pychess/pychess/files/2568366/2018-11-10_11-18-58.txt)

**Comment by gbtami** [comment]
Was there any "undo" in this game?

**Comment by jule009** [comment]
I think it was one undo, but I don`t remember exactly, it didn't expect, what happened.

**Comment by jule009** [comment]
Another situation, I don't remember if there was 1 undo or not.
Game ok, saved middle of playing. After resume of game, no move of Pychess again - seems to be now in an endless loop.
[2018-11-15_14-47-28.txt](https://github.com/pychess/pychess/files/2586387/2018-11-15_14-47-28.txt)
Now log after resume:
[2018-11-15_15-27-02.txt](https://github.com/pychess/pychess/files/2586392/2018-11-15_15-27-02.txt)
Saved file(txt instead of pgn):
[pychess-engine-gegen-brig..txt](https://github.com/pychess/pychess/files/2586409/pychess-engine-gegen-brig.txt)
![pychessnomove181115](https://user-images.githubusercontent.com/40624880/48570794-77463c00-e905-11e8-9f00-41988046fac2.png)
Kind regards

**Comment by gbtami** [comment]
May I ask you to start pychess using --log-debug command line argument added until this issue fixed, please. Without that it is really hard to tell anything about why the pychess engine doesn't respond.

**Comment by jule009** [comment]
Hi, since Your first request to log the plays, I always start  pychess using --log-debug command line argument added.
Kind regards

 

 

-----Ursprüngliche Mitteilung-----
Von: gbtami <notifications@github.com>
An: pychess/pychess <pychess@noreply.github.com>
Cc: jule009 <julechner@aol.com>; Mention <mention@noreply.github.com>
Verschickt: Sa, 17. Nov. 2018 9:25
Betreff: Re: [pychess/pychess] pychess probaly endless loop #1652 - still valid in ...99.2 ? (#1657)



May I ask you to start pychess using --log-debug command line argument added until this issue fixed, please. Without that it is really hard to tell anything why the pychess engine doesn't respond.

**Comment by jule009** [comment]
Sorry, I just saw that the --log-debug has got lost, I have added it again

**Comment by jule009** [comment]
New test, start of game, no undo, save, resume -> endless loop, reproducable.
saved pgn file:
[pychess-enginegegenbrig-test.txt](https://github.com/pychess/pychess/files/2591888/pychess-enginegegenbrig-test.txt)
Log files:
Part before save:
[2018-11-17_13-16-57.txt](https://github.com/pychess/pychess/files/2591892/2018-11-17_13-16-57.txt)
Part after resume:
[2018-11-17_13-23-38.txt](https://github.com/pychess/pychess/files/2591893/2018-11-17_13-23-38.txt)
ScreenShot before save:
![afterinteruption](https://user-images.githubusercontent.com/40624880/48662131-beefd380-ea7d-11e8-9ce1-9105ad85ceff.png)
End of game:
![endofgame](https://user-images.githubusercontent.com/40624880/48662136-d929b180-ea7d-11e8-8e21-cfdf5ffe7a7d.png)

Hope this helps, sorry that I didn't see, that in the last previous log the debug function was off.
I think this procedure is reproducable.
Kind regards

**Comment by gbtami** [comment]
Seems this is another issue. See https://github.com/pychess/pychess/issues/1707

The remaining question is the case in https://github.com/pychess/pychess/issues/1657#issuecomment-437579213 was the same as this latest one (load previously saved game)?

**Comment by jule009** [comment]
There was no undo, in this game.

**Comment by gbtami** [comment]
But was that a saved and loaded game also?

**Comment by jule009** [comment]
Yes, I did only 2 or 3 do's to make the logfiles not too big. If neccessary I can repeat a similar game with more do's and report. It was the saved and loaded game.

**Comment by gbtami** [comment]
Ok, the save-load problem is an unrelated issue here. See #1707 
May I close this now, or do you experience undo related engine stallings yet?

**Comment by jule009** [comment]
So far not, I will report again, if an additional undo related case occurs.
