### ISSUE TITLE
Usage of MultiPV

### ISSUE THREAD

**Issue by ecrucru** [pychess/pychess#1661]
Hello,

I have a question about MultiPV.

This option is meaningful when the engine is used as an analyzer. But in a match Engine vs Human/Engine, it doesn't make real sense to request alternate lines that will not be processed. It consumes CPU and divides the strength of the engine.

Is it possible to forward the manual value of MultiPV from the options when the engine is used as an analyzer only ?

I have verified with my little engine and it receives a value >1 for MultiPV when it acts as a player (=3 in the options). It should affect the other engines as well.

Thanks for your feedback.

**Comment by gbtami** [comment]
Now all engine options are set in initEngine() at https://github.com/pychess/pychess/blob/master/lib/pychess/Players/engineNest.py#L523 and this is independent from what engine role is or what option is designed for by engine authors.

To save/load MultiPV for analyzing engines (on hints panel) we shouldn't use engines options dialog at all. I suggest to save a new config option for analyzing MultiPV on hints panel only instead in https://github.com/pychess/pychess/blob/master/lib/pychess/perspectives/games/bookPanel.py#L289 and load it in https://github.com/pychess/pychess/blob/master/lib/pychess/perspectives/games/bookPanel.py#L203 instead.
What do you think?

**Comment by ecrucru** [comment]
We made the change in the past to inherit the MultiPV from the engine. To me, it looks logic to comply with an engine-dependent setting and because you may have a different behavior.

Let's suppose that FooFish handles a lot of MultiPV without much problem, but BarFish crashes when the MultiPV is high, I would give them a different value for MultiPV. If we have a common value for MultiPV, we have also to do validations with the engine. Should we then exclude the option from the manual maintenance ? In all the cases, the MultiPV can be changed in the panel.

Forcing MultiPV=1 for the players is for me the simpliest option that will keep the current logic which doesn't appear to be wrong.

Please note that MultiPV in panel is limited to 9.

I let you decide what is better to make the engines stronger/faster/deeper in pyChess GUI.

**Comment by gbtami** [comment]
You are right.
Test my fix please!

**Comment by ecrucru** [comment]
It looks fine. Thanks
