### ISSUE TITLE
pychess 0.99.2 does not work with python 3.7

### ISSUE THREAD

**Issue by xyproto** [pychess/pychess#1666]
Python 3.7 has added `async` and `await` as reserved keywords ([changelog](https://docs.python.org/3/whatsnew/3.7.html)).

This breaks calls like `asyncio.async(start(gtk_app))`.

Error message when running pychess after packaging and installing pychess 0.99.2:

```
pychess
  File "/usr/bin/pychess", line 260
    asyncio.async(start(gtk_app))
                ^
SyntaxError: invalid syntax
```

**Comment by gbtami** [comment]
I'v fixed it in https://github.com/pychess/pychess/commit/6179d56d18e4391c0af3475d23a374b43aad5c22
0.99.3 is coming soon.

**Comment by xyproto** [comment]
Great, I'll use 6179d56 for the Arch Linux pychess package in the mean time.
