### ISSUE TITLE
(setup.py:1487): Gtk-CRITICAL **: 10:16:04.817: gtk_icon_theme_get_for_screen: assertion 'GDK_IS_SCREEN (screen)' failed

### ISSUE THREAD

**Issue by xyproto** [pychess/pychess#1667]
I'm trying to package pychess 6179d56 for Arch Linux, as suggested in #1666.

Building the package in a chroot, as is done with all official packages, makes `setup.py` segfault, since it seems to want to do things related to GDK/GTK+. Building the package with full access to the host system (using `makepkg` works fine).

Here is the error message:

```sh
(setup.py:1487): Gtk-CRITICAL **: 10:16:04.817: gtk_icon_theme_get_for_screen: assertion 'GDK_IS_SCREEN (screen)' failed
/startdir/PKGBUILD: line 21:  1487 Segmentation fault      (core dumped) python setup.py install --prefix=/usr --root="$pkgdir"
```

Here is the PKGBUILD I'm currently using:

```bash
# $Id: PKGBUILD 371341 2018-08-13 23:15:27Z arodseth $
# Maintainer: Alexander F. Rødseth <xyproto@archlinux.org>
# Contributor: Allan McRae <allan@archlinux.org>
# Contributor: Alexander Fehr <pizzapunk@gmail.com>

pkgname=pychess
pkgver=0.99.2
pkgrel=1
pkgdesc='Chess client'
arch=('any')
url='http://pychess.org/'
license=('GPL')
depends=(gst-plugins-base gtksourceview3 python-cairo python-gobject
         python-ptyprocess python-psutil python-sqlalchemy)
makedepends=(git python-pexpect)
# commit 6179d56 contains a fix for Python 3.7. 0.99.3 will be out soon.
source=("git+https://github.com/$pkgname/$pkgname#commit=6179d56")
#source=("https://github.com/$pkgname/$pkgname/releases/download/$pkgver/$pkgname-$pkgver.tar.gz")
sha256sums=('SKIP')

package() {
  #cd "pychess-$pkgver"
  cd pychess

  python setup.py install --prefix=/usr --root="$pkgdir"
}

# getver: raw.githubusercontent.com/pychess/pychess/master/lib/pychess/__init__.py
# vim: ts=2 sw=2 et:
```

Here are the steps to reproduce the segfault:

1. Install `devtools` (or `devtools-git`)
2. Be in the same directory as the `PKGBUILD`
3. Run `sudo extra-x86_64-build`

**Comment by gbtami** [comment]
I'm not familiar with arch packaging so my ideas may be completely wrong.
1. Maybe add more packages to depends from https://github.com/pychess/pychess/blob/master/INSTALL
2. If package build process is happening on a GUI-less system xvfb is needed as you can see in https://github.com/pychess/pychess/blob/master/.travis.yml

**Comment by xyproto** [comment]
Thanks! I'll look into packaging it by using xvfb.

**Comment by xyproto** [comment]
Works now. The updated pychess package will appear in [community] shortly: https://www.archlinux.org/packages/community/any/pychess/
