### ISSUE TITLE
Export to PNG with Black on the bottom

### ISSUE THREAD

**Issue by ecrucru** [pychess/pychess#1670]
Hello,

Following #1531, is it possible to export the position to PNG (picture) with the consideration of the current rotation of the board ?

If you see what I mean :-)

![image](https://user-images.githubusercontent.com/24614488/44554462-5bc9fb80-a731-11e8-8c07-1025c4af0499.png)

Thanks.

**Comment by gbtami** [comment]
What is the use case of this picture?
Btw. rotating images is basic stuff in any picture viewer utility.

**Comment by ecrucru** [comment]
The picture is a little joke to say that we can't have black pieces correctly positionned at the bottom of the board if pychess' PNG generator doesn't do it for us. It makes sense when it is black's turn, unless we want to export the board with white at the bottom.

In other words, the question is how it is possible to consider the rotation of the main board in `png.py`.

Another solution is to use symmetric pieces, but they are less common for the users to illustrate a website for example.
https://github.com/veloce/lichobile/tree/master/www/images/pieces/symmetric

**Comment by gbtami** [comment]
Maybe passing the rotation of boardview to save() at https://github.com/pychess/pychess/blob/master/lib/pychess/perspectives/games/__init__.py#L330 ?
