### ISSUE TITLE
Stockfish eats 100% CPU during FICS game

### ISSUE THREAD

**Issue by mirao** [pychess/pychess#1676]
**Steps to reproduce:**

- Seeks/Challenges -> Send Seek
- Suppose some player on FICS (http://www.freechess.org) will accept it
- A game starts

**Expected result:**

- no CPU overloading by Stockfish. IMHO Stockfish engine shouldn't start at all during a FICS game

**Actual result:**

- Stockfish starts and eats 100% CPU during the game. It affects performance of PyChess UI.

**Used SW:**

- PyChess 0.99.2
- Ubuntu 18.04
- Stockfish 8 64 BMI2

**Comment by gbtami** [comment]
You can turn off analyzers before start playing in Edit->Preferences->Hints

**Comment by mirao** [comment]
Thanks. Yes, it can be turned off this way, by disabling of both options in "Analyzing".

Manual analysis behaves strangely to me: If I start analysis using Games -> Analyze Games -> O.K., then **I'm not able to stop it**. I tried Cancel or Edit -> Preferences -> Hints -> Analyzing -> Disable, but without success. Only way how to get rid of running chess engine is closing of PyChess. Any idea? Or is there other element in UI for it?

**Comment by gbtami** [comment]
@mirao Thx for reporting this! There is a "Do you want to abort it?" message and "Abort" button at the bottom. It works for me, unless "Infinite analysis" checked on preferences hints panel. Which seems a bug, so I filed it as https://github.com/pychess/pychess/issues/1677

**Comment by mirao** [comment]
Exactly, thanks.
