### ISSUE TITLE
Preview of the sounds

### ISSUE THREAD

**Issue by ecrucru** [pychess/pychess#1679]
Hello,

When you set a sound by selecting the sound file, you cannot preview it immediately after with the corresponding button in preference dialog.

I also have the impression that they are effective only when pyChess is restarted.

You can reproduce the issue by clearing the filename in the config file, then set the sound from the GUI.

Also, it would be nice the set the default folder pychess/sounds instead of showing the recent tab of the gtk file dialog. When we add a sound, it cannot be a recent file.

Btw this dialog doesn't offer direct access to a given folder by pasting a path in an edit box. With GIMP, there is no issue, so is it possible to allow that feature in pychess too ?

Thanks

**Comment by gbtami** [comment]
Regarding default folder it works OK when I want to choose first time, but it offers recent tab next time. I have no idea how to change this behavior.
