### ISSUE TITLE
Engine written in Python not loaded

### ISSUE THREAD

**Issue by ecrucru** [pychess/pychess#1683]
Hello,

When you add an engine written in Python (like `xboard.py` of SunFish), it is not loaded correctly. My impression is that `vm_command` is not detected and no MD5 is calculated. If you close the window, save and then restart PyChess, the engine is not detected and the GUI is a bit messed up until you remove the added engine from engineDialog.

With NodeJS, there is no issue. The runtime env command is detected. That's why it is strange.

The case is applicable to Windows, not tested under Linux.

Once the error with the MD5 key is solved in `engines.json`, that engine plays well. Loading it is the issue.

Thanks

**Comment by gbtami** [comment]
This was #1680 and #1681
I tested the committed fixes  on Linux only :(
