### ISSUE TITLE
pychess-engine wants to play invalid move Na2

### ISSUE THREAD

**Issue by jule009** [pychess/pychess#1694]
Play ran in way I didn't want, about 10 redraws - strange Error Na2.
[2018-10-15_07-35-31.txt](https://github.com/pychess/pychess/files/2477572/2018-10-15_07-35-31.txt)
![pychesserror181015](https://user-images.githubusercontent.com/40624880/46932974-5fec0880-d052-11e8-947c-7c348543efc6.png)

**Comment by gbtami** [comment]
"about 10 redraws" = about  undo ten times ?

**Comment by jule009** [comment]
Yes, about 10 time undo in one step, to get the previous situation, where I dis a bad do. So far I could not reproduce this error, I tried so far once.

**Comment by gbtami** [comment]
Undo bug fix fixed this also IMO.
