### ISSUE TITLE
Chess960 and castling - multiple bugs

### ISSUE THREAD

**Issue by ms2048** [pychess/pychess#1697]
Win7 Pro SP2, Pychess 0.99.3 here. I've recently played a (very amateurish) game of Chess960 with Stockfish under PyChess.

[ms vs. Stockfish 9 64.pgn.txt](https://github.com/pychess/pychess/files/2503889/ms.vs.Stockfish.9.64.pgn.txt)

After some time I've realized three problems, probably interconnected:
1. that PyChess didn't allow me to castle (moving the king over to the rook didn't work) - so - just in case - I've saved the ongoing game to a pgn file (attached above)
2. that PyChess crashes when I want to reload the game from the attached file (after 'Load Game', selecting the attached pgn file and clicking 'Open', 'scoutfish_x64.exe' crash occurs)
3. that PyChess refuses to even set up an initial position from this game:  after entering the 'Setup Position' window, copying FEN from the starting position of this game: `rqnknrbb/pppppppp/8/8/8/8/PPPPPPPP/RQNKNRBB w FAfa - 0 1` and clicking on 'Paste FEN' the following error message appears: 'Castling availability field is not legal'.

Also:

4. this PGN file (created by PyChess 0.99.3) has mixed line endings (both CRLF and LF are there) but correcting these didn't help.

I've only recently started using PyChess, so maybe I'm missing something, please advise.

**Comment by gbtami** [comment]
Regarding reload, avoid using spaces in saved .pgn file names, please! Seems scoutfish doesn't like it.

**Comment by ms2048** [comment]
Ok but it is the default name chosen by PyChess itself, I didn't change it (I only added .txt suffix to be able to attach it here).

Btw any chance for a fix in scoutfish? Not using spaces is going to be mighty inconvenient...

**Comment by gbtami** [comment]
Removed spaces from default .pgn filename in https://github.com/pychess/pychess/commit/002388f854de5260a4152e526e9ce80f4cbb7645

**Comment by gbtami** [comment]
Regarding scoutfish, any help is welcome. See https://github.com/pychess/scoutfish/issues/1
