### ISSUE TITLE
Sittuyin promotion bugs

### ISSUE THREAD

**Issue by ianfab** [pychess/pychess#1702]
After the bugfixes in https://github.com/pychess/pychess/commit/c808a4e5de230207322896736914a0801db51a71 there still seem to be two issues with promotions in Sittuyin:
- To my knowledge (implementations in cutechess, Sjaak II, and Fairy-Stockfish; "How to Play Myanmar Traditional Chess" by Maung Maung Lwin), when a player has only one pawn left, the remaining pawn may be promoted from any square of the board and not only on the main diagonals. This rule does not seem to be reflected in PyChess. Example FEN: 6k1/3s4/6PS/5N2/pP6/P7/2S2F2/2K1R3 b - - 0 49
- When a pawn promotes while staying on the same square, a pawn of opposite color is added to the captured pieces (next to the board). E.g., when black promotes b2b2f/b2=F, a white pawn is added to the captured pieces. This does not happen when the pawn promotes with a general move.

**Comment by gbtami** [comment]
The first is fixed after https://github.com/pychess/pychess/commit/7d6cd3ed1cfabaea14ab70137741aa962471eee0
The second needs some more work.

**Comment by gbtami** [comment]
https://github.com/ianfab/Fairy-Stockfish/issues/14
