### ISSUE TITLE
Missing ECO

### ISSUE THREAD

**Issue by gbtami** [pychess/pychess#1703]
Nikos Panagogiannopoulos:
"Hi all! is there a way so far to show the ECO notations at the comments? Thanks in advance"

me:
ECO and opening name is shown in annotation panel header. Isn't it there for you?
Btw what version of PyChess are you using?

"ununtu-studio"

**Comment by gbtami** [comment]
Do you have /usr/share/pychess/eco.db ?

**Comment by NikosPg** [comment]
hi, yes I do.

**Comment by NikosPg** [comment]
can I have a screenshot of how should it be?

**Comment by gbtami** [comment]
![eco](https://user-images.githubusercontent.com/479964/48008490-16a34c00-e11a-11e8-8ffd-0c468e880169.png)

**Comment by NikosPg** [comment]
oh! I need it!

**Comment by NikosPg** [comment]
![pychess](https://user-images.githubusercontent.com/6053933/48009790-0e9cd980-e125-11e8-8132-6decbfed4389.png)
i'm in greek
