### ISSUE TITLE
FICS challenge button doesn't work

### ISSUE THREAD

**Issue by jule009** [pychess/pychess#1710]
Tried to play over internet. No success even, when both are standard - tried this with my neighbour. But here is the last trial with someone from the web. I think both players have the same requirements on a game.
[2018-11-30_14-31-03.txt](https://github.com/pychess/pychess/files/2633398/2018-11-30_14-31-03.txt)
![ficcs-1](https://user-images.githubusercontent.com/40624880/49292966-fb282880-f4ae-11e8-8d76-50c90eaa9b04.png)
![ficcs-2](https://user-images.githubusercontent.com/40624880/49292986-0bd89e80-f4af-11e8-9d82-55b228b3290d.png)

If this description is not understandable, I can easily comment more.
Kind regards

**Comment by gbtami** [comment]
Reproduced it. Challenge button doesn't work at all :( But you can use the local right click menu :)
```
Traceback (most recent call last):
  File "/home/tamas/pychess/lib/pychess/perspectives/fics/SeekChallenge.py", line 228, in onChallengeButtonClicked
    player = self.lounge.players_tab.getSelectedPlayer()
AttributeError: 'FICS' object has no attribute 'players_tab'
```

Regarding the screenshots, I think lagBOT will never accept any challenges. I think it's just a program to measure network lag, just the server running it as a user.

**Comment by jule009** [comment]
Hi,
can try it next Tuesday, my neighbour will meet me then, and we will have 2 Computers on the same desk. I will report.
Thank You!
Kind regards

 

 

-----Ursprüngliche Mitteilung-----
Von: gbtami <notifications@github.com>
An: pychess/pychess <pychess@noreply.github.com>
Cc: jule009 <julechner@aol.com>; Author <author@noreply.github.com>
Verschickt: Fr, 30. Nov. 2018 15:53
Betreff: Re: [pychess/pychess] Problem with FICCS don't understand (#1710)



Reproduced it. Challenge button doesn't work at all :( But you can use the local right click menu :)
Traceback (most recent call last):
  File "/home/tamas/pychess/lib/pychess/perspectives/fics/SeekChallenge.py", line 228, in onChallengeButtonClicked
    player = self.lounge.players_tab.getSelectedPlayer()
AttributeError: 'FICS' object has no attribute 'players_tab'

Regarding the screenshots, I think lagBOT will never accept any challenges. I think it's just a program to measure network lag, just the server running it as a user.

**Comment by jule009** [comment]
Played again over FICS with my neighbour, 2 computers we had on one desk. I still (Win 8.1) could not start the internet game, even right klicking (same error message as told previously). My neighbour could start (Win 10). I was jojule (white), my neighbour rurudi (black). At the end of the game pychess didn't see, that black was checkmate. We will try again next monday, that's our chess day. If this problem (not recognizing "chessmate" or other errors will occur), I will report. If of interest here the log of jojule (Win 8.1). If neccessary in the next try I will give again screenshots and logs from both players.
Kind regards

[2018-12-04_16-15-10.txt](https://github.com/pychess/pychess/files/2647409/2018-12-04_16-15-10.txt)

**Comment by gbtami** [comment]
From log file I see you challenged rurudi for an untimed game but rurudi's formula (blitz || standard) && !abuser doesn't match your challenge:
```
16:17:52.995 Default DEBUG: OfferManager.challenge: rurudi <GameType fics_name='untimed', display_text='Ohne Zeitlimit'> 0 0 False None
16:17:52.995 ('jojule', 'run_command') DEBUG: match rurudi 0 0 u 
16:17:52.996 ('jojule', 'raw') INFO: 52 match rurudi 0 0 u 
16:17:53.340 unknown WARNING: Executing <TimerHandle when=430.775 glib_update(<GLib.MainCon...t 0x004bc660)>, <ProactorEven...se debug=True>) at pychess:235 created at pychess:238> took 0.344 seconds
16:17:53.340 ('freechess.org', 'raw') DEBUG: bytearray(b"\x1552\x1673\x16Match request does not fit formula for rurudi:\nrurudi\'s formula: (blitz || standard) && !abuser\n\x17\nfics% ")
16:17:53.341 ('jojule', 'command_reply') DEBUG: 52 73 Match request does not fit formula for rurudi:
rurudi's formula: (blitz || standard) && !abuser
16:17:53.346 ('jojule', 'req_not_fit_formula') DEBUG: Match request does not fit formula for rurudi:
rurudi's formula: (blitz || standard) && !abuser
```
About FICS formulas see https://www.freechess.org/Help/HelpFiles/formula.html

The missing game end issue seems a bug. Filed it at https://github.com/pychess/pychess/issues/1713
Investigating it...

**Comment by jule009** [comment]
We have still a problem syncronizing our play time adjustments (rurudi - jojule), Rurudi shows "15 minutes play time", jojule shows "no time limit" (see sreenshot from jojule).
![pychess-fics-problem](https://user-images.githubusercontent.com/40624880/49781602-b05eaa00-fd13-11e8-98ba-51fa2f2b7755.png)

rurudi is on Win 10, jojule on Win 8.1, sorry I don't have currently a screenshot from rurudi's situation. But we can not change rurudi's "15 minutes" to "no time limit". How to do this? Both are on the last update of Pychess. BTW the chessmate error didn't occur so far with the newest version of Pychess.
Thanks in advance!
Kind regards

**Comment by gbtami** [comment]
I think there is a misunderstanding regarding "syncronizing our play time adjustments".

On FICS/ICC there are some concept exist you have to know:

seek: you send an advertise for everyone that you want to play a game with given conditions (time 
control, rated/unrated, color, rating range, etc.)

challenge: similar, but addressed to a particular player only

clock: minutes+gain (0+0=untimed)

formula: everyone can set some predefined expression to filter out seeks/challenges he/she (don't)want to see/accept.

As I noticed before rurudi's formula is `(blitz || standard) && !abuser` meaning he will be not seeing any seeks and will decline all challenges which are not blitz or standard automatically. (Also everything coming from users labelled as 'abuser'.) And `untimed` is NOT `blitz`, and `untimed` is NOT `standard`!

See:
https://www.freechess.org/Help/HelpFiles/match.html
https://www.freechess.org/Help/HelpFiles/clocks.html
https://www.freechess.org/Help/HelpFiles/blitz.html
https://www.freechess.org/Help/HelpFiles/standard.html
https://www.freechess.org/Help/HelpFiles/formula.html

**Comment by jule009** [comment]
Thank You for the info !
I have solved our problem. On the screenshot sent in my last post You see in the head line the field "Ansicht". Don't know how it's called in the English version. In "Ansicht" You can hide/display different "options", don't know how to call. In the German version, if You scroll down, the last option is "Suchen/Herausforderungen", there one can choose i.e. "15 min or no time limit", this option is hidden on rurudis PC, now I know how to display. This is quite silly, but if one doesn't see this, one "runs" in an endless loop while searching. 
BTW is in Morphy 0.99.4 the problem, You called it "The missing game end issue seems a bug. Filed it at #1713", solved? If not, we will have an eye on it.

**Comment by gbtami** [comment]
Just some other info that may help.
If you want to use lichess with english user interface (to let see how something called in english in pychess) just start it with --no-gettext added to the end of starting command. Something like `pychess --no-gettext`
You can experiment with FICS play while you are alone. Just start pychess twice. First log in to FICS with your regular username/password. Second click on the big globe icon and check "as guest" on extended FICS login dialog. This way you can challenge yourself for play unrated games. (Guest players a bit limited, as everywhere used to be.) It seems crazy, but very useful for testing purpose :)

Regarding #1713 I hop it fixed. But if it raises again reopen it, please!
