### ISSUE TITLE
Missing variant name in FEN conversion

### ISSUE THREAD

**Issue by ecrucru** [pychess/pychess#1714]
Hello,

You get this error when you try to filter a database by pasting a subfen with the button paste :

```
Traceback (most recent call last):
  File "/pychess/lib/pychess/perspectives/database/FilterPanel.py", line 629, in fen_changed
    self.widgets["sub_fen"].set_text(self.get_fen())
  File "/pychess/lib/pychess/perspectives/database/FilterPanel.py", line 647, in get_fen
    return self.setupmodel.boards[-1].as_fen()
TypeError: as_fen() missing 1 required positional argument: 'variant'
```

There is potentially another error of that kind in `Variants/setupposition.py`.

I am not sure if forcing `NORMALCHESS` is the proper way to fix. So I prefer to ask.

Thanks.

**Comment by gbtami** [comment]
Yes that will fix it. Unfortunately scoutfish doesn't support variants so we have no chance to use anything else here.
