### ISSUE TITLE
Open PGN from clipboard

### ISSUE THREAD

**Issue by sallyx** [pychess/pychess#1719]
Hi,
first thank you for Pychess, its a great software and I love it :)

It would be very helpful, I it was possible to open PGN from clipboard, as I often
analyze games  which I  do not want to save fo file (my own games from chess.com, games from chessgames.com etc.).

I.e. something like Database -> Create new from clipboard.

 Or, If you create new database, you should not be asked immediately to save it to file and there should by possibility to add game to the database from clipboard.

**Comment by gbtami** [comment]
Is this something you can do now with Game -> Enter game notation, then pasting to the text entry, just with less steps? Or something like an "in memory database" (living only in memory while PyChess is running)? Or something like https://github.com/pychess/pychess/issues/1690 ?

**Comment by sallyx** [comment]
Yes, the first is like Game -> Enter game notation (except it will create "in memory database" from which you can open the game), the second is "in memory database" to which you can add games from clipboard (and maybe save later).

**Comment by gbtami** [comment]
Thx! I'v opened https://github.com/pychess/pychess/issues/1720 for the second one.
