### ISSUE TITLE
Cannot open pgn file on Ubuntu 16.04

### ISSUE THREAD

**Issue by hwbell** [pychess/pychess#1722]
I can't seem to open a pgn file at all? I go to Game > Load Game, and select the file, but then the Open Game dialog opens, appearing like I just clicked Game > New Game, but with the option for 'Initial Position', which it is also worth noting, doesn't work. So all you can do from this dialog is start  a new game vs a human or comp. 

Also, there is the option of Game > Load Recent Game, which doesn't do anything when clicked.

Am I just missing something?

**Comment by gbtami** [comment]
Works for me with latest 0.99.4 from https://github.com/pychess/pychess/releases
What version are you trying to use?

**Comment by hwbell** [comment]
It looks like I am using an older version because I had installed using apt-get install pychess, which hasn't been updated. I tried downloading the newer .zip and running from souce by running ./pychess from the folder, but it didn't work. Any suggestions?

**Comment by gbtami** [comment]
You have to install dependencies first. See https://github.com/pychess/pychess/blob/master/INSTALL

**Comment by hwbell** [comment]
Ah, good to scroll down all the way  : )
Thanks
