### ISSUE TITLE
Double click doesn't start games from pgn files

### ISSUE THREAD

**Issue by loug42** [pychess/pychess#1726]
pgn files load but do not open in the large left-side screen when double-clicked.  This works properly in 99.3.  Occurs with any pgn file.

**Comment by gbtami** [comment]
Unfortunately https://github.com/pychess/pychess/commit/c4efbcd8f0343d032f9e29ce20af7d7f581d6ab7 caused this regression I didn't noticed :(
Until I fix it you can use pressing Enter (after selecting a row).

**Comment by loug42** [comment]
Thanks for your incredibly prompt reply and the simple solution.

Happy Holidays,

Lou
