### ISSUE TITLE
Reduced captured pieces

### ISSUE THREAD

**Issue by ecrucru** [pychess/pychess#1728]
Hello,

This is a feature request which consists in displaying the uncommon captured pieces of the players, so that we can see better the advantage by type of piece.

![image](https://user-images.githubusercontent.com/24614488/50374856-bc404b00-05f4-11e9-989d-e40263013b27.png)

When there are many pieces already captured, it takes a lot of space and it lacks a bit of readability :

![image](https://user-images.githubusercontent.com/24614488/50374905-51dbda80-05f5-11e9-97ed-b28687f51b8f.png)

Thanks

**Comment by gbtami** [comment]
Isn't this the same as #1607 ?

**Comment by ecrucru** [comment]
Oh yes, I missed that issue. I used the keywords "material" and "difference" instead of "capture" or "advantage". Sorry for that, thanks.
