### ISSUE TITLE
undo not transmitted (FICS)

### ISSUE THREAD

**Issue by jule009** [pychess/pychess#1732]
My neighbour and I play chess via FICS Server (Pychess). An undo wish of my neighbour is displayed to me, I accept, the undo is done on my neighbours desk but not on my desk. Is this a known issue? My neighbour is not very firm on computers. His OS is Win10, my OS is Win8.1. Sofar I could not find the path to Pychess in Win10 (it's a hided folder), therefore we have no log for the undo. If this issue is new, I will investigate how to make a log in Win10 and then present a log, after the next occurrence of this error.
Kind regards

**Comment by gbtami** [comment]
Unfortunately yes, it's a known bug https://github.com/pychess/pychess/issues/1392
