### ISSUE TITLE
Fairymax on Pychess uses 25% of cpu

### ISSUE THREAD

**Issue by loug42** [pychess/pychess#1733]
While I understand that this may be a fairymax issue (rather than a pychess one) I felt is was worth reporting here because it does not occur with other engines.  A game played by a human against fairymax 5.01b (from ubuntu repos) maxes out at 25% of cpu after 3-4 moves.  This does not happen with stockfish, fruit or crafty.

**Comment by loug42** [comment]
Sorry, that should read "fairymax 5.0b"...

**Comment by gbtami** [comment]
Works for me OK on Ubuntu 18.04. Haven't you set ponder on in engine settings accidentally?

**Comment by loug42** [comment]
No, ponder is not checked.

**Comment by gbtami** [comment]
Try to start pychess like this:
./pychess --log-debug --log-view
While playing against fairymax you can try to figure out what's happening in "Log" -> "Log viewer" menu.

**Comment by loug42** [comment]
message in red "executing timer handle" followed by numbers I don't understand.  same message keeps repeating with a longer time between each occurrence.  I can try to copy the message if it will help...

**Comment by loug42** [comment]
I played around and found the bug.  Pychess plays correctly when the game is timed.  When "untimed" is selected (which I use when studying a game, and I do this a lot) Pychess malfunctions.  Why this only occurs with fairymax and not with other engines is beyond my pay grade :)

**Comment by loug42** [comment]
Or the bug could be in fairymax...I've looked at the variables that can be set in pychess and nothing shouts out to me.

**Comment by gbtami** [comment]
What version of Ubuntu are you using?

**Comment by loug42** [comment]
xubuntu 18.04

**Comment by gbtami** [comment]
I'm unable to reproduce this issue :( Can you create a short video on it please?

**Comment by loug42** [comment]
I don't know how to make a video but here are the steps to re-create the issue:
1. select /game/new game/human being/fairymax/untimed/normal chess/start game
2. begin play as white
3. after 3-4 moves play stops
4. start ubuntu task manager/select cpu
5. on my system cpu is at 25%

if I then start over with a timed game pychess runs normally.
if I play against another engine in untimed mode pychess runs normally

no need to waste a lot of time on this - I can get around it by playing only timed game against fairymax... 

thanks for your time

**Comment by loug42** [comment]
as I continue to work with this I have discovered that using the classical 3 minute setting is the only way to make fairymax play normally. other time settings cause 25% cpu usage.  I will have to find another linux compatible engine that plays at 1400 elo

thanks again for your help
