### ISSUE TITLE
set formula, FICS, how to put the "set" command in the command line of Windows

### ISSUE THREAD

**Issue by jule009** [pychess/pychess#1734]
Hi, there is no direct login into the FICS server possible (Java problems). Where and how to put a command like "set formula" in the Windows command line, tried it with no success when logged in to FICS via Pychess (internet chess). Sorry for the silly question.
Kind regards

**Comment by gbtami** [comment]
![formula](https://user-images.githubusercontent.com/479964/51253372-5c905200-199e-11e9-8c16-588aa27606fd.png)

See https://www.freechess.org/Help/HelpFiles/formula.html
If you need further assistance, just join to http://webchat.freenode.net/?channels=pychess&uio=d4

**Comment by jule009** [comment]
Sorry for my possibly silly continuation. Is that, what You show, the console after logging in to FICS server? I can not login to FICS server because of Java problems and sofar I have no solution for this problem. This can not be the Windows own console. My communication to FICS server runs only via Pychess.I have a help mail from FICS help team, saying general Java problems, use Babaschess, but I think this will be the same as using Pychess.Kind regards
 
 
-----Ursprüngliche Mitteilung-----
Von: Bajusz Tamás <notifications@github.com>
An: pychess/pychess <pychess@noreply.github.com>
Cc: jule009 <julechner@aol.com>; Author <author@noreply.github.com>
Verschickt: Mi, 16. Jan. 2019 14:53
Betreff: Re: [pychess/pychess] set formula, FICS, how to put the "set" command in the command line of Windows (#1734)

See https://www.freechess.org/Help/HelpFiles/formula.html—

**Comment by gbtami** [comment]
The above screenshot is showing PyChess own FICS console window. When you use FICS via PyChess you are logging in to FICS server, and in PyChess console window you can set/query your variables as my above example shows. FICS console window in PyChess is a full featured command line interface to FICS. You can send any command using it, even can play a full game from console. Of course it's a silly idea, but any FICS GUI like babaschess or pychess just send/receive commands in the background. You can read about all available FICS commands starting from here http://freechess.org/Help/AllFiles.html

**Comment by gbtami** [comment]
@jule009 I'm sorry to say (and talking against pychess) but I highly suggest to try https://lichess.org instead of FICS. FICS is nearly dead. Lichess is the present and the future. It has everything you can get from FICS but in a browser with the best GUI ever created!

**Comment by jule009** [comment]
Thank You very much, I got it now, the console was hidden in my environment.Kind regards
