### ISSUE TITLE
Accessibility for PyChess

### ISSUE THREAD

**Issue by ghost** [pychess/pychess#1736]
Hi,

I just met Pychess.

### Can we make Pychess accessible?
Yes, I would like to ask. Visually impaired chess players cannot use any chess program on the market. There is a version of xboard that has stopped developing. very old and lacking space.

Python offers an environment in which we can develop very fast projects.
### Can the Pychess team add support for screen readers?
I can tell you what to do. But I can't help a lot of code. I have no knowledge to develop this project.
### what we need to do
1. We will include the [AccessibleOutput2 module](https://bitbucket.org/qsoft/accessible_output2). Thanks to this lib, we can send the status to the screen readers.
* In this case, the presence of the screen reader is checked. Activates if active.
2. We should add support and shortcuts for the keyboard. A screen reader will be able to play pieces with arrows.
3. Unfortunately, no screen reader is compatible with GTK. It could have been much better if the project used WX or PyQt.
* In this case, we must introduce all objects created with gtk to AccessibleOutput2 (I have no idea). If this can be done, I can ask [NVDA's team](https://github.com/nvaccess/nvda) how we can do it. They can help us a lot.
### Say what?
Do you have the Pychess team more "accessible" and more "undisabled" technology?

I live in Turkey. I know hundreds of blind chessmen. Thousands of people in the world are waiting for this development. This is a great improvement on a global scale.
The blinds cannot benefit from the technology of chess. Because programs are not accessible.

### note
If there is something we can do, I can write a more detailed article.
This was the "Can we do it" question 😊 .

This issue was written with half my English and Translate. I'm sorry about my grammar mistakes.

**Comment by gbtami** [comment]
I don't think this should be closed.
