### ISSUE TITLE
GNUchess from the Ubuntu 18.04 repos won't run in PyChess 99.3

### ISSUE THREAD

**Issue by loug42** [pychess/pychess#1737]
This is no longer an issue in 99.4 - gnuchess works properly regardless of time constraints.

**Comment by gbtami** [comment]
For me sometimes it starts sometimes not. Strange.

**Comment by loug42** [comment]
I just now discovered inadvertently that GNUChess runs on timed games but refuses to run on untimed.  I play mostly untimed games because I use PyChess to study openings, tactics, etc.

**Comment by gbtami** [comment]
@loug42 can you still reproduce this?
