### ISSUE TITLE
pychess.org lacks SSL, serves downloads without SSL, vulnerable to BDFProxy

### ISSUE THREAD

**Issue by hartwork** [pychess/pychess#1738]
Hi!

The advent of [BDFProxy](https://github.com/secretsquirrel/BDFProxy) changed how I think about binary downloads from a website without SSL, or at least raised awareness with me a lot. pychess.org lacks SSL and does serve compiled code for execution, e.g. http://www.pychess.org/download/pychess_0.10.1-1_all.deb. Please fix that, SSL matters, not just for passwords but for authentication of content.

```console
# wget -O- https://pychess.org/
--2019-02-11 00:19:51--  https://pychess.org/
Resolving pychess.org... 188.121.55.128
Connecting to pychess.org|188.121.55.128|:443... connected.
OpenSSL: error:140770FC:SSL routines:SSL23_GET_SERVER_HELLO:unknown protocol
Unable to establish SSL connection.
```

Many thanks!

**Comment by hartwork** [comment]
PS: I guess I should have reported to https://github.com/pychess/pychess.website, instead? How do we proceed?

**Comment by gbtami** [comment]
@hartwork thx for reporting this!
@thomasahle can you fix this somehow, please?

**Comment by gbtami** [comment]
pychess releases now served from github only.
