### ISSUE TITLE
Register "pychess-org" or so at PyPI?

### ISSUE THREAD

**Issue by hartwork** [pychess/pychess#1739]
Hi!

If https://pypi.org/project/PyChess/ is something else, have you considered registering a package "pychess-org" or so to be able to point that and save people "the research", wondering and searching? Just an idea. What do you think?

Best, Sebastian

**Comment by gbtami** [comment]
It's some completely different unmaintained old stuff. I tried to contact its owner before without any luck :(
https://pypi.org/project/PyChess-Anderssen/ was uploaded years ago. Unfortunately I forgot to update it on pypi from long time.
