### ISSUE TITLE
Strength slider in PyChess

### ISSUE THREAD

**Issue by loug42** [pychess/pychess#1744]
Please pardon me if this is the wrong place to ask questions - I'm wondering how much the strength slider reduces the ELO of engines.  What would the reduction be for the entire slider (from 20 to 1) and/or what would it be per point?  Or does it vary depending on the engine?

Thank you...

**Comment by gbtami** [comment]
This is protocol and engine dependent.
See https://github.com/pychess/pychess/blob/master/lib/pychess/Players/CECPEngine.py#L411 and https://github.com/pychess/pychess/blob/master/lib/pychess/Players/UCIEngine.py#L309
Exact ELO can't be estimated because it is hardware dependent anyhow.

**Comment by loug42** [comment]
Thanks for replying.
