### ISSUE TITLE
Selected colors not saved

### ISSUE THREAD

**Issue by loug42** [pychess/pychess#1746]
In edit/preferences/themes I choose 'colors only' then dark squares 'light blue' then 'reset colors' - colors are changed.  On restart of pychess chosen colors are gone and back to default shades of gray.  Not a fatal error but a minor annoyance...

**Comment by loug42** [comment]
Pychess 99.4 - I checked the config file - the selected colors are being saved but are ignored on the next run of pychess and replaced with the default gray-on-gray.

**Comment by loug42** [comment]
Pychess 99.4 - the texture setting are remembered correctly.  I'm going with Brazilwood until the custom colors are available.

**Comment by gbtami** [comment]
Thx for the additional info!
