### ISSUE TITLE
Castling produces a queen

### ISSUE THREAD

**Issue by ecrucru** [pychess/pychess#1747]
Hello,

For the purpose of the issue 1690 in progress, I have the following concern.

When a king is moved from its initial position to the target position of a rook, it is not interpreted as a castling move and it produces a queen, which is very strange.

```
[SetUp "1"]
[FEN "k7/8/8/8/8/8/8/4K2R w K - 0 1"]
e1h1
```

```
[SetUp "1"]
[FEN "7k/8/8/8/8/8/8/R3K3 w Q - 0 1"]
e1a1
```

```
[SetUp "1"]
[FEN "4k2r/8/8/8/8/8/8/4K3 b k - 0 1"]
e8h8
```

```
[SetUp "1"]
[FEN "r3k3/8/8/8/8/8/8/4K3 b q - 0 1"]
e8a8
```

Can you help me to make it work at `lutils` level ? From what I understood, this manner to write such a move is a generic disambiguation for Chess960, knowing that the usual chess position is a particular Chess960 position.

Thanks

**Comment by gbtami** [comment]
The reason of this behavior is that these moves are not valid SAN moves, and parseSAN() itself doesn't sanitize input. Fortunately we have parseAny() for this purpose, so we can relax more our .pgn parser to accept UCI moves also.
