### ISSUE TITLE
Make PyChess work on OSX

### ISSUE THREAD

**Issue by gbtami** [pychess/pychess#1757]
Unfortunately i never had any Mac myself but this is definitely doable. See https://github.com/quodlibet/quodlibet

**Comment by aleien** [comment]
Hello!)
I happen to have mac and some time and interest to make pychess work on OSX. Unfortunately I have no experience in converting games/apps to different platforms (except for ios/android, but I guess that's a different stories, because languages are different between those two platforms)

Can I ask you for some directions? (: What is needed to be done, so that PyChess can work on different OS?

I.e. I see that when I try to run setup.py I do miss some dependencies. If I understand correctly, if we want to let users run pychess on macos we first need to check if all dependencies are available (which most likely is true), and then write correct script to download them?

**Comment by gbtami** [comment]
PyChess is pure Python3 code, so in theory you just have to install all dependencies somehow on OSX. https://pygobject.readthedocs.io/en/latest/index.html can help I think.
If all dependencies are there I can imagine that you have to add some platform dependent changes here and there. Maybe https://github.com/pychess/pychess/blob/master/lib/pychess/System/prefix.py will not find data files because of different layout of file system.

**Comment by ibrahimcherni2018** [comment]
I'm using mac to contribute to this project, I decided to put the project in DOCKER to see if it is possible to run it from a container in my MAC, but i'm facing some issues, Like "RuntimeError: Gtk couldn't be initialized. Use Gtk.init_check() if you want to handle this case". I'm still blocked, i searched everywhere to resolve this. Is there anyone here happens to know how to resolve this issue. I'm at some steps to finish creating the Docker image for pychess. thank you

**Comment by gbtami** [comment]
I think you should try to install pychess without docker first.
Can you run hello.py fro https://pygobject.readthedocs.io/en/latest/getting_started.html ?

**Comment by yao-eastside** [comment]
I was able to make it work with a small code change

https://gist.github.com/zhaoshaojun/1de3be9bc807ec3b33c20103544c743b

**Comment by zhaoshaojun** [comment]
#1827

**Comment by gbtami** [comment]
Awesome news!
Seems you commented out some stuff to let it start.
1. Importing Gst (gstreamer) is needed to make sound.
2. Importing GtkSource is needed for .pgn text colorization in new game dialog.
3. locale.bindtextdomain() is related to translations.

It would be nice to solve 1. and 2. (maybe 3. is not needed on Darwin systems), but not essential.
Main issue is how users can install manually  pychess on OSX. It would be enough to add the steps needed to INSTALL file.
Another one is how to create OSX distributable for pychess. Maybe using py2app or using pyinstaller. (Unfortunately I can't help to try these without OSX box.)

**Comment by yao-eastside** [comment]
Aha, so it is because I commented out Gst. That will be on the top of my todo list.

The current Mac version is already usable, although not very pleasant. But without sound, I really do not want to use it as I do not know when my opponent has moved. 

Progress will be reported here. Pull request will be created later when the diff is in a better shape. Right now, I only tries to make it work on Mac, which breaks other OSes.

**Comment by zhaoshaojun** [comment]
take

**Comment by yao-eastside** [comment]
Hi all, I was able to make pychess run on macos, and reduced the code changes to one places at pychess:194.

The only issue is, I am seeing a lot of gtk-warinings like the following:

(pychess:20628): Gtk-WARNING **: 20:00:49.493: Error loading theme icon 'go-top' for stock: Icon 'go-top' not present in theme Adwaita

Do you see that on Windows and Linux as well?
Thanks.
-Shaojun

**Comment by yao-eastside** [comment]
The "good" thing is that unittest gives warning or errors:

test3 (dialogs.DialogTests)
Start a new game from enter notation dialog ...
(run_tests.py:20857): Gtk-WARNING **: 20:16:31.287: Can't set a parent on widget which has a parent

**Comment by yao-eastside** [comment]
warnings/errors in unit test:

pychess/lib/pychess/Players/CECPEngine.py:289: RuntimeWarning: coroutine 'sleep' was never awaited
Coroutine created at (most recent call last)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/unittest/suite.py", line 84, in __call__
    return self.run(*args, **kwds)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/unittest/suite.py", line 122, in run
    test(result)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/unittest/case.py", line 663, in __call__
    return self.run(*args, **kwds)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/unittest/case.py", line 615, in run
    testMethod()
  File "/Users/shaojun/open-source/pychess/testing/ficspuzzlebot.py", line 151, in test1
    self.loop.run_until_complete(coro())
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/asyncio/base_events.py", line 571, in run_until_complete
    self.run_forever()
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/asyncio/base_events.py", line 539, in run_forever
    self._run_once()
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/asyncio/base_events.py", line 1767, in _run_once
    handle._run()
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/asyncio/events.py", line 88, in _run
    self._context.run(self._callback, *self._args)
  File "/Users/shaojun/open-source/pychess/lib/pychess/Players/CECPEngine.py", line 289, in coro
    yield from asyncio.sleep(0.1)
  yield from asyncio.sleep(0.1)
RuntimeWarning: Enable tracemalloc to get the object allocation traceback

**Comment by gbtami** [comment]
If there are no missing icons in PyChess GUI then Warnings like "Icon 'go-top' not present in theme Adwaita" are harmless.

Some of the unit tests are using asyncio and exit/cleanup may be not clean. This is also harmless if unit tests itself are all Ok.

**Comment by yao-eastside** [comment]
Thanks @gbtami . There are missing icons in PyChess GUI when I am using it. Other than the missing icons, it is usable now. Still working on it ^_^

**Comment by zhaoshaojun** [comment]
#1831

**Comment by zhaoshaojun** [comment]
#1831

**Comment by gbtami** [comment]
If you can attach some screenshots where icons are missing, I can try to find a fix also.

**Comment by yao-eastside** [comment]
Sure. It is interesting that at least one of the icon (on the top left of "Start Game") is not missing :)
So it would be interesting to see why others are missing. 

![Screen Shot 2020-05-16 at 2 28 59 AM](https://user-images.githubusercontent.com/8732068/82116222-03b10500-971d-11ea-935f-cec17ae04277.png)
![Screen Shot 2020-05-16 at 2 29 53 AM](https://user-images.githubusercontent.com/8732068/82116237-22af9700-971d-11ea-936b-fccf751e2dfc.png)

**Comment by gbtami** [comment]
I think the root of all missing icon issues is here https://developer.gnome.org/gtk3/stable/gtk3-Stock-Items.html
"Since GTK+ 3.10, stock items are deprecated. You should instead set up whatever labels and/or icons you need using normal widget API, rather than relying on GTK+ providing ready-made combinations of these."

And the difference on the top left of "Start Game" shows us the solution also. We have to replace all stock icon usage in pychess code base to icons saved from old releases of icon themes (Adwaiata?) as we already did it with weather icons. See https://github.com/pychess/pychess/tree/master/glade
 and https://github.com/pychess/pychess/blob/master/lib/pychess/widgets/TaskerManager.py#L185

**Comment by yao-eastside** [comment]
@gbtami Great to know that you already know the root cause and also had solutions. Any plan (issues opened on github) to replace those icons soon? I can help testing on the macOS platform.

**Comment by gbtami** [comment]
I will try to fix this soon, but don't ask me exact dates :)

**Comment by gbtami** [comment]
Btw. if you find other places where icons are missing, paste here please! Thx.

**Comment by yao-eastside** [comment]
sure, thanks @gbtami

**Comment by gbtami** [comment]
Committed some missing icons. Can you test it please?

**Comment by yao-eastside** [comment]
Some issues have definitely been fixed. See the screenshot. Let me check for others.

![Screen Shot 2020-05-16 at 8 17 54 PM](https://user-images.githubusercontent.com/8732068/82134955-58528f80-97b2-11ea-8f7c-4233b7a00ab7.png)

**Comment by yao-eastside** [comment]
Some icons are missing when starting a new game
![Screen Shot 2020-05-17 at 3 35 01 PM](https://user-images.githubusercontent.com/8732068/82161730-fd717480-9853-11ea-8fbb-15896f065e8d.png)

messages in the terminal that might be helpful
![Screen Shot 2020-05-17 at 3 35 17 PM](https://user-images.githubusercontent.com/8732068/82161736-09f5cd00-9854-11ea-95b7-07ab43e72183.png)

**Comment by yao-eastside** [comment]
![Screen Shot 2020-05-17 at 3 36 53 PM](https://user-images.githubusercontent.com/8732068/82161757-44f80080-9854-11ea-9ca4-6bb757a1f18e.png)

**Comment by yao-eastside** [comment]
@gbtami  Take your time. Let me know when you have made progress.

**Comment by gbtami** [comment]
Updated. Try all perspectives like FICS, Database and Learn also, please!

**Comment by yao-eastside** [comment]
@gbtami I need some more time. Busy with my work currently. Sorry for the delay.

**Comment by gbtami** [comment]
No problem. Same here :)

**Comment by yao-eastside** [comment]
![Screen Shot 2020-06-11 at 12 22 06 AM](https://user-images.githubusercontent.com/8732068/84356827-99ec1580-ab79-11ea-87bf-7a6973554207.png)

missing 6 icons in this attachment.  
menu > game > new game

**Comment by yao-eastside** [comment]
![Screen Shot 2020-06-11 at 12 25 04 AM](https://user-images.githubusercontent.com/8732068/84357135-06671480-ab7a-11ea-85af-87f1b2e2f64a.png)

missing 10 icons in this attachment. (6 of them are the same as above)
menu > game > new game

**Comment by yao-eastside** [comment]
![Screen Shot 2020-06-11 at 12 26 59 AM](https://user-images.githubusercontent.com/8732068/84357302-475f2900-ab7a-11ea-992a-e38caa8b010c.png)

missing a few icons in this attachment. (nice to have)
menu > game > load game

![Screen Shot 2020-06-11 at 12 28 26 AM](https://user-images.githubusercontent.com/8732068/84357425-7d9ca880-ab7a-11ea-8592-b607f310bbdc.png)

missing 1 icons in this attachment.
menu > game > load recent game

**Comment by yao-eastside** [comment]
![Screen Shot 2020-06-11 at 12 29 53 AM](https://user-images.githubusercontent.com/8732068/84357540-ade44700-ab7a-11ea-8f18-8ef8d4a26b3b.png)

missing a few icons
menu > preference

**Comment by yao-eastside** [comment]
![Screen Shot 2020-06-11 at 12 30 30 AM](https://user-images.githubusercontent.com/8732068/84357592-c48a9e00-ab7a-11ea-81b9-892287c0efbc.png)

similar to above

**Comment by yao-eastside** [comment]
![Screen Shot 2020-06-11 at 12 31 46 AM](https://user-images.githubusercontent.com/8732068/84357691-f26fe280-ab7a-11ea-8397-4a70f44f660d.png)

other screens look nice. For example, the above one.

**Comment by yao-eastside** [comment]
The above are the ones I can find. Thanks
@gbtami

**Comment by yao-eastside** [comment]
![Screen Shot 2020-06-11 at 12 38 08 AM](https://user-images.githubusercontent.com/8732068/84358335-d9b3fc80-ab7b-11ea-8662-e4a5efddf493.png)

adding one more. One is missing at the top, 3 are missing at the bottom, and 3 on the right.

**Comment by gbtami** [comment]
Thx a lot! 
Have you tried Learn and ICS also? Are they Ok?

**Comment by yao-eastside** [comment]
I tried a few ICS, but none of them worked for me, so I was not able to check if there is anything missing there if I connected.

**Comment by yao-eastside** [comment]
![Screen Shot 2020-06-11 at 4 27 00 PM](https://user-images.githubusercontent.com/8732068/84448746-630d1280-ac00-11ea-9d13-0a2144763253.png)

"learn" misses one icon on the top.

**Comment by gbtami** [comment]
"none of them worked"
Is this means you was not able to connect to FICS at all? 
Btw. if you start pychess from console (command line) with arguments:
```
python3 ./pychess --log-debug --log-view
```
then you can see pychess logs in "View"->"Log Viewer" menu. That can help to figure out what is the problem.

**Comment by yao-eastside** [comment]
This is nothing pychess related. I cannot find a valid FICS server. Also if I do, I only play anonymously.

**Comment by gbtami** [comment]
Is freechess.org blocked in your country?

**Comment by yao-eastside** [comment]
Not blocked. I am in the US.

**Comment by yao-eastside** [comment]
Note: I would not try any of this if it requires a registration, as I don't play on it often.

**Comment by gbtami** [comment]
You can log in as anonymous. It will be more than enough to see how it works.

**Comment by yao-eastside** [comment]
Looks like my company blocked those sites.

**Comment by mattwaltbriggs** [comment]
Looks like there is some work to do to get PyChess to work on M1 Macs (and yes, I installed libpango):
`$ ./pychess

** (process:27818): WARNING **: 12:42:25.157: Failed to load shared library 'libpango-1.0.0.dylib' referenced by the typelib: dlopen(libpango-1.0.0.dylib, 9): image not found
Failed to create splash screen
Traceback (most recent call last):
  File "/Users/matthewbriggs/Downloads/pychess-1.0.0/./pychess", line 193, in <module>
    locale.bindtextdomain(domain, locale_dir)
AttributeError: module 'locale' has no attribute 'bindtextdomain'`

**Comment by gbtami** [comment]
As I mentioned in the opening post I have no apple device.
Any PR related to this issue is more than welcome.

**Comment by mattwaltbriggs** [comment]
My initial thought is it's not finding the dylib file because homebrew has moved it's stuff from /usr/local to /opt/homebrew

**Comment by nicogab34** [comment]
I am currently struggling to launch the GUI on MAC OS, what is the command/script to do that? @zhaoshaojun?

Thanks for helping

**Comment by sblackstone** [comment]
Able to get everything installed with:

```
brew install gtk+3 pygobject3 gtksourceview3 librsvg

python3 setup.py install
```

I then had to modify the source and change 

```
-        libintl = ctypes.cdll.LoadLibrary('libintl.dylib')
+        libintl = ctypes.cdll.LoadLibrary('/usr/local/lib/libintl.dylib')
```

In theory, you should be able to use `DYLD_FALLBACK_LIBRARY_PATH` but this may be thwarted due to Apple's runtime protection:

https://developer.apple.com/library/archive/documentation/Security/Conceptual/System_Integrity_Protection_Guide/RuntimeProtections/RuntimeProtections.html

Perhaps we could just add a manual attempt to use `/usr/local/lib` on OSX since the majority of people will be installing these libraries using brew and thats where they will be put.
