### ISSUE TITLE
CrazyAra 0.4.0 Crazyhouse UCI running on PyChess current GUI

### ISSUE THREAD

**Issue by yellow-panther** [pychess/pychess#1760]
Hello gbtami,

did you have success now to run  https://github.com/QueensGambit/CrazyAra/releases on your graphical interface? C:\Benutzer\NRL\AppData\Local\Programs\Python\Python37 contains the following directories DLLs, Doc, include,Lib,libs,Scripts,tcl,Tools and the data LICENSE,NEWS,python (applicatiom), pythob3.dll,python37.dll,pythonw (application),vcruntime140.dll I have installed  https://www.python.org/ftp/python/3.7.3/python-3.7.3-amd64.exe , pip install python-chess (v0.28.0), pip-install cython(v0.29.10), pip install virtualenv,(v16.6.0) pip install mxnet-mkl==1.4.1 und py -m pip install --upgrade pip (v19.1.1) Intel i5 Quad IvyBridge-micro-architecture

Regards,

**Comment by gbtami** [comment]
See https://github.com/QueensGambit/CrazyAra/issues/28
