### ISSUE TITLE
About opening book

### ISSUE THREAD

**Issue by ecrucru** [pychess/pychess#1771]
Hello,

For further enhancements, would you have some technical info about `pychess_book.bin` ?

This file has not been updated since 2014. So I wonder if it has some restrictions, like particular depth, particular source of data, particular usage for its content, etc... ?

Thanks for your guidance.

**Comment by gbtami** [comment]
It's a standard Polyglot opening book file. Originally it was a custom Sqlite db created from .pgn
https://bitbucket.org/gbtami/pychess/src/0.6/lib/pychess/Utils/book.py
The source .pgn is unknown for me. Maybe @thomasahle can remember.

It would be better not to store this in binary format in the repo and just re create it in setup.py from any .pgn we like to use instead.

**Comment by thomasahle** [comment]
I think I just found a pgn with all recorded Kasparov games :-D

**Comment by ecrucru** [comment]
Thanks for your clarifications. So I will check few ideas for the opening book in the next weeks.

Also, do you think it is relevant to use `niklasf/eco` as the default `en/eco.pgn` ? It is one of the ideas because the original source is down.

Have a good week !

**Comment by gbtami** [comment]
Yes. I think it is the most up to date.
