### ISSUE TITLE
PyChess version 1.0 (Missing Chess Sets in the UI) stops at letter "K"

### ISSUE THREAD

**Issue by lexterror** [pychess/pychess#1781]
On both Windows and Linux version 1.0. Missing Chess sets. No Chess sets after letter "K"

**Comment by gbtami** [comment]
Reproduced. Thx for reporting this!

**Comment by gbtami** [comment]
For some unknown reason /user/share/pychess/pieces/Kosal.png preview image file is missing from .deb and .msi (This is causing the break in for cycle filling the preview panel with all images.)
As a workaround you can download and unpack sources from https://github.com/pychess/pychess/archive/1.0.0.tar.gz then regenerate it with running ./create_theme_preview.sh

**Comment by ghost** [comment]
~I'm not seeing any chess sets at all. Not sure if this is the same issue. In an older version from the Fedora repos (Anderssen 0.12.4) the chess sets are displayed.~

After running `./create_theme_preview.sh`, they are indeed shown. Perhaps it would make sense for the theme previews to be created automatically if they are not already there?

**Comment by gbtami** [comment]
They are created when you run setup.py build/install
