### ISSUE TITLE
Introducing our group to the PyChess community

### ISSUE THREAD

**Issue by Bracewind** [pychess/pychess#1782]
Hello everyone,

We are a group of 5 students in software engineering. We were tasked with contributing to an open source project. We chose pychess for its internal documentation and its programming language.

I am in charge of communicating on behalf of the group with the pychess community (i.e. mainly @gbtami). If any problem arises or you want to talk with the whole group, please at-mention me, @Bracewind.

Here are the github accounts of the five students :

- https://github.com/Bracewind
- https://github.com/habichou
- https://github.com/ibrahimcherni2018
- https://github.com/mathieucaroff
- https://github.com/youba28

We're also interested in hearing about the conventions used in the PyChess code, as we may have missed some of them.

Thanks for reading this issue, 

Grégoire Pichereau

**Comment by gbtami** [comment]
Hi @Bracewind !
Good to hear you choose PyChess :)
Just let you know that we can chat on IRC https://webchat.freenode.net/#pychess or
on discord https://discord.gg/aPs8RKr also.

**Comment by gbtami** [comment]
Finally I find the SwCaseStudy what I was talking about before:
https://docs.google.com/document/d/1og1-_Rw5eZcXqH80HpEapZ0dYJg11P-RLzTqTB1Faus/edit?usp=sharing
