### ISSUE TITLE
AdaChess

### ISSUE THREAD

**Issue by iandoug** [pychess/pychess#1783]
Hi

Trying to add AdaChess engine. Following suggestion in another ticket, I put this in engines.json:

{
  "command": "/home/ian/chess/AdaChess-v3.6/adachess.exe", 
  "country": "be", 
  "name": "AdaChess", 
  "protocol": "xboard", 
  "vm_command": "/usr/bin/wine", 
  "vm_name": "wine"
 }, 

PyChess then detects and lists the engine, but attempting to play games does not work. It says there are no engines in the game.

Is above correct, or am I doing something wrong?

The engine works fine in CuteChess.

System is Gentoo Linux, AMD64.

~/.config/pychess $ which wine
/usr/bin/wine

Thanks, Ian

**Comment by gbtami** [comment]
Can you run it from console?
I can't on Ubuntu 1804.
I get this:
```
tamas@tami:~/bin/AdaChess-v3.6$ LANG=C wine adachess.exe 
0009:err:process:create_process L"Z:\\home\\tamas\\bin\\AdaChess-v3.6\\adachess.exe" not supported on this installation (x86_64 binary)
wine: Bad EXE format for Z:\home\tamas\bin\AdaChess-v3.6\adachess.exe.
```

**Comment by iandoug** [comment]
Don't know how to force monospace text here.

~/chess/AdaChess-v3.6 $ wine adachess.exe 
Number of CPU detected: 8
Hash size is 32768000
          
 r n b q k b n r    8
 p p p p p p p p    7
 . . . . . . . .    6
 . . . . . . . .    5
 . . . . . . . .    4
 . . . . . . . .    3
 P P P P P P P P    2
 R N B Q K B N R    1
          
          
  a b c d e f g h

**Comment by gbtami** [comment]
Try to start pychess with --log-debug --log-viewer command line args.
This way you can watch all logs in "View" -> "Log viewer" menu.

**Comment by iandoug** [comment]
While testing with Cute Chess I noticed this message, which may be the cause of the problem. Don't worry too much about this because AdaChess is not very strong as modern engines go, so I won't be testing with it going forward.

"Adachess does not support the setboard command, using the edit command now"

Thanks, Ian
