### ISSUE TITLE
Checkmate being "not the best move" in a puzzle?

### ISSUE THREAD

**Issue by ghost** [pychess/pychess#1788]
Trying out the new puzzles and lessons, and they're amazing! Great work.

Often in those puzzles, when I make a move that achieves checkmate, in the annotation window I am informed that it is **"Not the best move"** and I see a button with the option to **"Retry"**.

I get that perhaps one mate may perhaps *look cooler* than another but surely any checkmate should be considered equally *good*, in terms of winning the game, or am I missing something?

Perhaps the issue is that there was a *quicker* forced mate, but the **"Retry"** button just retracts one move, and so doesn't give you the option of playing out that quicker mate.

Slightly different issue, but also relating to the puzzles: Sometimes PyChess gives plainly wrong advice, e.g. in **Lichess Practice: Greek Gift: Greek Gift Challenge #3**, it will *insist* that `BxH7` is **"Not the best move"** (although it clearly is), and it is only possible to "win" that puzzle by playing a line that *doesn't involve the Greek Gift*.

**Comment by gbtami** [comment]
Can you remember which puzzle was that?

**Comment by ghost** [comment]
I've had at happen in **Checkmate patterns i** and in **Discovered attacks** so far, in perhaps 3 or 4 different puzzles.

I imagine it might be something that would make more sense to fix in how puzzles are handled in general rather than tweaking individual puzzles though.

**Comment by gbtami** [comment]
Agreed. As I remember puzzles are pgn driven expecting you to play exactly the same moves.
Any better solution (regarding to accept longer mate) PR is welcome!

**Comment by ghost** [comment]
It's interesting because it would look like the code in `lib/pychess/Utils/LearnModel.py` already accounts for this. As a comment in the `check_failed_playing_best` function definition says,

> No need to check in best moves (and let add more time to analyzer) in trivial cases

and the code below *appears* to have a check for mate.

**Comment by gbtami** [comment]
It would help to debug this issue if you can remember which exact puzzle and moves should I take to reproduce this.

**Comment by ghost** [comment]
Don't worry; I'm on it.

I'm looking at the puzzles in `learn/puzzles/lichess_study_lichess-practice-discovered-attacks_by_arex_2017.01.30.pgn` now. Some of the termination conditions are about score, not about *mate in X*.

Then, if we look at `check_failed_playing_best` again, this bit smells a bit to me:
```
             if self.goal.result in (MATE, MATE_IN) and (
                 (status == BLACKWON and self.starting_color == BLACK) or
                     (status == WHITEWON and self.starting_color == WHITE)):
                 return False
```

Surely, *regardless of termination condition*, if you achieve a check mate, you can't have *failed to play the best move*, right? (In normal chess, that is. I'm assuming there are not puzzles for chess variants.)

I'd change it to this, to make sure that regardless of the termination condition specified in the puzzle, a mate would always qualify as the best move,

```
             if ((status == BLACKWON and self.starting_color == BLACK) or
                     (status == WHITEWON and self.starting_color == WHITE)):
                 return False
```

I don't know if that's what caused the issue though. I should have noted the puzzle and exact position but was just expecting to play chess; not hack.

**Comment by ghost** [comment]
I'll play some more puzzles and see if the issue still after the change above.

Haven't been able to get Lucas Chess to run because I wanted to play chess puzzles. Had no idea until today that it had been added to PyChess.

(That thing with the Greek Gift is a different issue, and perhaps it just isn't the best move in that particular position. But if it isn't, then that puzzle doesn't belong in that category. Although the puzzles are from LiChess, so that's not really the responsibility of PyChess devs to sort out.)

**Comment by gbtami** [comment]
"Surely, regardless of termination condition, if you achieve a check mate, you can't have failed to play the best move, right?"
This is definitely not the case in MATE_IN x goal puzzles if you win using more move than x.
This is the meaning of MATE_IN x :)

**Comment by ghost** [comment]
> This is definitely not the case in MATE_IN x goal puzzles if you win using more move than x.
This is the meaning of MATE_IN x :)

Yes, you're right that you can fail a mate in 1, e.g. by taking 10 moves to achieve mate. (Of course..!)

However, this check (in `check_failed_playing_best`) is for each individual move, and an individual move that achieves a checkmate is by definition the **best** move available (unless you're playing suicide chess or something weird).

If a move achieves check mate but there was an opportunity to have achieved an earlier check mate, then it must be the fault of **a previous move** which wasn't good enough, and not **the individual move which achieved the check mate**, right?

The **"Retry"** button, which appears when the best move is not played, just undoes the very last move.

**Comment by ghost** [comment]
I applied the change above and played through the same puzzles again and I didn't experience the bug. It could have been because I played some different lines, of course.

**Comment by gbtami** [comment]
You are right. Waiting for a PR :)

**Comment by ghost** [comment]
Another issue with the puzzles is that what the engine can change it's mind about what the best move is. This keeps happening in a puzzle I'm playing now:

* I make a move and I'm told that it's **"not the best move"**
* I click on the **Best move** button, and I am shown the exact move I just did
* I make the move again and again told it's **"not the best move"**
* I click on the **Best move** button, and it shows me a completely different move

I wanted to paste the move history in here, but it's not copyable. So I tried to save the game as a PGN but it doesn't work because of another bug. (See #1790. Have submitted PR.)

OK, I'll just type it in here, because the moves that the engine "want" me to play out are just plain weird. Puzzle is **Lichess Practice: Key Squares: Pawn on the 2nd rank**

1. Kd3 Kc5 2. Kc3 Kd6 3. Kc4 Kc6 4. c3 Kd7 5. Kc5 Ke8 6. c4 Kd7 7. Kd5 Kc7 8. Kc5 Kd7 9. Kd5 Kc7 10. Kd4 Kc6 11. c5 Kd7 12. Kd5 Kc7 13. c6 Kc8 14. Kc5 Kc7 15. Kb5 Kc8 16. Kb6
Kb8 17. Kb5 Kc7 18. Kc5 Kc8 19. Kb5 Kc7 20. Kc5 Kc8 21. Kb6 Kb8 22. Ka5 Kc8 23.
Ka6 Kc7 24. Kb5 Kc8 25. Kc5 Kc7 26. Kd5 Kc8 27. Ke4 Kc7 ... (and it's not finished yet)

I think that either PyChess should be a bit more chilled with what moves it will consider **"best"**, or it should be more consistent.

(Perhaps this should have been a different bug report, but I don't want to just spam puzzle issues.)

**Comment by ghost** [comment]
> You are right. Waiting for a PR :)

Cool :-)

**Comment by ghost** [comment]
I think this issue is fixed then, once the PR goes through.

**Comment by ghost** [comment]
**Nope!** Didn't work. The issue is still there.

```
[Event "Lichess Practice: Checkmate Patterns II: Morphy's Mate #3"]
[Site "https://lichess.org/study/8yadFPpU"]
[Date "????.??.??"]
[Round "?"]
[White "Pelle"]
[Black "stockfish"]
[Result "1-0"]
[SetUp "1"]
[FEN "2r1nrk1/pp1q1p1p/3bpp2/5P2/1P1Q4/P3P3/1BP2P1P/R3K2R w KQ - 0 1"]
[PlyCount "23"]
[Termination "normal"]
[Annotator "https://lichess.org/@/arex"]
[UTCDate "2017.01.28"]
[UTCTime "13:50:33"]

{ From John Owen - Amos Burn, 1887. }  1. Rg1+ Bg3 2. Rxg3+ Ng7 3. Qxf6 Qd2+ 4.
Kxd2 Rfd8+ 5. Ke2 Kf8 6. Rxg7 Rxc2+ 7. Kf3 Rxf2+ 8. Kxf2 Rd2+ 9. Kg3 Rg2+ 10.
Kxg2 Ke8 11. Qxf7+ Kd8 12. Qd7# 1-0
```

With the move `Qd7#` I am told again that it's **"Not the best move"**, even with my suggested patch applied! PyChess *insists* it has to be `Rg8#` when clicking on the **Best move** button. But when actually doing `Rg8#`, I am again told that that's **"Not the best move"** either.

Very strange.

**Comment by gbtami** [comment]
This latest mate in 6 puzzle is OK for me (without your patch!).

```
[Event` "Lichess Practice: Checkmate Patterns II: Morphy's Mate #3"]
[Site "https://lichess.org/study/8yadFPpU"]
[Date "????.??.??"]
[Round "?"]
[White "tamas"]
[Black "stockfish-x86_64-modern"]
[Result "1-0"]
[SetUp "1"]
[FEN "2r1nrk1/pp1q1p1p/3bpp2/5P2/1P1Q4/P3P3/1BP2P1P/R3K2R w KQ - 0 1"]
[PlyCount "11"]
[Termination "normal"]
[ECO "?"]
[Annotator "https://lichess.org/@/arex"]
[UTCDate "2017.01.28"]
[UTCTime "13:50:33"]
[Opening "?"]

{ From John Owen - Amos Burn, 1887. }  1. Rg1+ Bg3 2. Rxg3+ Ng7 3. Rxg7+ Kh8 4.
Rg8+ Rxg8 5. Qxf6+ Rg7 6. Qxg7# 1-0
```
