### ISSUE TITLE
Can't save PGN of puzzles

### ISSUE THREAD

**Issue by ghost** [pychess/pychess#1790]
To reproduce:
* Open a puzzle, e.g. **Key Squares: Pawn on the 2nd rank**
* Go to **Game** -> **Save Game As ...**
* Click **Save**

What happens:
* The save dialog remains open
* An empty PGN file is created

What was expected:
* The save dialog should close
* The game should be saved as PGN

**Comment by ghost** [comment]
Getting this error in the console:
```
Traceback (most recent call last):
  File "/home/pelle/pychess/lib/pychess/Main.py", line 338, in on_save_game_as1_activate
    perspective.saveGameAs(gmwidg.gamemodel, position)
  File "/home/pelle/pychess/lib/pychess/perspectives/games/__init__.py", line 331, in saveGameAs
    game.save(uri, saver, append, position, flip)
  File "/home/pelle/pychess/lib/pychess/Utils/GameModel.py", line 667, in save
    saver.save(fileobj, self, position, flip)
  File "/home/pelle/pychess/lib/pychess/Savers/pgn.py", line 249, in save
    print(buffer, status, file=handle)
UnicodeEncodeError: 'latin-1' codec can't encode character '\u2013' in position 83: ordinal not in range(256)
```

**Comment by ghost** [comment]
Looks like it happens with *any* game that has a comment that contains a non-ASCI character.

**Comment by gbtami** [comment]
This is a little bit more complicated. PGN spec expects latin-1 see http://www.saremba.de/chessgml/standards/pgn/pgn-complete.htm#c4.1
Non standard encoded UTF-8 PGN should be saved to UTF-8 of course, but don't forget that most of the PGN files out there are in latin-1 so just changing PGN_ENCODING is definitely NOT the solution.
