### ISSUE TITLE
PyChess being picky and inconsistent about best move in puzzles

### ISSUE THREAD

**Issue by ghost** [pychess/pychess#1791]
When playing puzzles, PyChess can change it's mind about what the best move is. This keeps happening in a puzzle I'm playing now:

* I make a move and I'm told that it's **"not the best move"**
* I click on the **Best move** button, and I am shown the exact move I just did
* I make the move again and again told it's **"not the best move"**
* I click on the **Best move** button, and it shows me a completely different move

The moves that the engine "want" me to play out are sometimes just plain weird. The puzzle **Lichess Practice: Key Squares: Pawn on the 2nd rank** is almost unplayable and the issue is very easy to reproduce in it. These are the moves that PyChess "wanted" me to make:

1. Kd3 Kc5 2. Kc3 Kd6 3. Kc4 Kc6 4. c3 Kd7 5. Kc5 Ke8 6. c4 Kd7 7. Kd5 Kc7 8. Kc5 Kd7 9. Kd5 Kc7 10. Kd4 Kc6 11. c5 Kd7 12. Kd5 Kc7 13. c6 Kc8 14. Kc5 Kc7 15. Kb5 Kc8 16. Kb6
Kb8 17. Kb5 Kc7 18. Kc5 Kc8 19. Kb5 Kc7 20. Kc5 Kc8 21. Kb6 Kb8 22. Ka5 Kc8 23.
Ka6 Kc7 24. Kb5 Kc8 25. Kc5 Kc7 26. Kd5 Kc8 27. Ke4 Kc7 ... (and it's not finished yet)

I think that either PyChess should be a bit more chilled with what moves it will consider **"best"**, or it should be more consistent.

_Originally posted by @hjek in https://github.com/pychess/pychess/issues/1788#issuecomment-552233803_

**Comment by gbtami** [comment]
Why you opened new issue for this?
