### ISSUE TITLE
Lectures lec8.txt and lec26.txt contains errors

### ISSUE THREAD

**Issue by firewall1110** [pychess/pychess#1795]
I think, that I fix this errors.
I could not send this files to tmfreita@uiuc.edu - may be e-mail not exist any more.
So I send them to PyChess team .

 (changes : back 999 replace to revert , change some move notation, so pychess understand)
[lec8.txt](https://github.com/pychess/pychess/files/3842844/lec8.txt)

 (changes: remove one line break)
[lec26.txt](https://github.com/pychess/pychess/files/3842852/lec26.txt)

If my this problem solution is good, than issue may be closed!

/Valters Brouns/

**Comment by gbtami** [comment]
Committed, thx!
