### ISSUE TITLE
Cannot install on Manjaro - python-sqlalchemy dependency 404

### ISSUE THREAD

**Issue by Zireael07** [pychess/pychess#1810]
I used pacman -S pychess.

**Comment by gbtami** [comment]
I'm sorry but I have no Manjaro. I suggest to ask on Manjaro forum.

**Comment by Zireael07** [comment]
Since that dependency seems required in other distros (I checked the package lists in INSTALL in the tar.gz), too, I strongly suspect the problem is more universal.
