### ISSUE TITLE
Attempt to start a custom FEN fails in Sittuyin

### ISSUE THREAD

**Issue by notruck** [pychess/pychess#1812]
I tried to load up some basic endgames for training against the engine. They were all fairly innocuous positions, and work alright for Makruk and ASEAN. But for some reason, it always says under the board, "The game ended in a draw Because [my username] stalemated" when I choose Sittuyin. 

After a while, I switched to Human vs Human mode. Same result. :(

Steps to reproduce:

1. Using the latest Pychess downloaded from github, please try
Game > New Game > From Custom Position

2.  Choose Sittuyin Chess under Chess Variant and paste this FEN
4k3/8/8/8/8/8/8/4K2R w - - 0 1   (very basic KR vs K endgame)

3. The same FEN works if the variant is changed to Makruk or ASEAN.

**Comment by gbtami** [comment]
Sittuyin FEN needs fullmove number to be greater than 8 to enable playing real moves. First 8 move pair is reserved for initial drop moves!
You need latest git commit also. (Fixed IndexError)
