### ISSUE TITLE
Max number of moves recorded is not unlimited.

### ISSUE THREAD

**Issue by lkjell** [pychess/pychess#1826]
Version Steinitz 1.0.0
The max number of moves in history is 488. 489 from pgn. Everything above 489 will result in an error when loading.

**Comment by gbtami** [comment]
I think that is more than enough. See https://en.wikipedia.org/wiki/List_of_world_records_in_chess#Longest_game

**Comment by lkjell** [comment]
Unfortunately it is not enough.

**Comment by gbtami** [comment]
PR is welcome.

**Comment by gbtami** [comment]
Fixed via https://github.com/pychess/pychess/pull/1828/commits/1b7bb8d4a84e503135058c1682ff283661cdc1e7
Thx a lot!
