### ISSUE TITLE
does it have sound when move?

### ISSUE THREAD

**Issue by yao-eastside** [pychess/pychess#1827]
Hi all,

I was able to get it to work on Mac (and I do not have other machines). Does it have sound when I or my opponent make a move (I was playing with stockfish)?

Thanks.

**Comment by yao-eastside** [comment]
#1757

**Comment by gbtami** [comment]
Yes of course pychess has sounds. See ![https://i.imgur.com/RELmj8C.png](https://i.imgur.com/RELmj8C.png)

But you commented out gstreamer import in your patch linked in #1757
