### ISSUE TITLE
Engine stops playing mid game

### ISSUE THREAD

**Issue by andyjd70** [pychess/pychess#1833]
I am using pychess on ubuntu 18.04LTS, I have a constant issue of the engine i'm playing against randomly stopping playing , it's almost as if it thinks i've made 2 moves . I can then play the opposing peices but only my clock keeps counting down. I thought it was me at first maybe trying to make an illegal move but if I use the back buttons I can see my move and the the engine hasn't responded, I can then play it's peices. It's happened on every engine i've played.

**Comment by gbtami** [comment]
What is your pychess package version?
What engine are you playing with?

**Comment by andyjd70** [comment]
Hi,
It's version 0.12.2.  It's the version available with the Ubuntu 18.04
LTS.
I have used Stockfish, pychess and fairymax and noticed the issue with
all 3 engines
Cheers
Andrew
-----Original Message-----From: Bajusz Tamás <notifications@github.com>
Reply-To: pychess/pychess <
reply@reply.github.com>To:
pychess/pychess <pychess@noreply.github.com>CC: andyjd70 <
andrew.deacon70@gmail.com>, Author <author@noreply.github.com>Subject:
Re: [pychess/pychess] Engine stops playing mid game (#1833)Date: Tue,
26 May 2020 16:16:25 -0700

What is your pychess package version?

What engine are you playing with?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "
https://github.com/pychess/pychess/issues/1833#issuecomment-634329567",
"url": "
https://github.com/pychess/pychess/issues/1833#issuecomment-634329567",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by gbtami** [comment]
Use the latest release from https://github.com/pychess/pychess/releases please!

**Comment by andyjd70** [comment]
I have now upgraded to the latest version and  haven't had the issue anymore, it would be nice to see the latest version available in Ubuntu 18.04LTS, I'm sure people will try it and just move onto something else not realising iit;s not the current version.
In the last game I just played i mean't to castle but mistakingly just moved the king one space, I used the arrow at the bottom to go back a move but the engine then just stops playing and I can move peices for both sides, I realise now this is a feature and there is an undo option in the menus but it would be helpful to have a clearly labelled undo button on the screen.
