### ISSUE TITLE
Sittuyin PGN parsing error

### ISSUE THREAD

**Issue by gbtami** [pychess/pychess#1834]
PyChess parsed the move c3=F as d4c3=F instead of b4c3=F
[whole-game.txt](https://github.com/pychess/pychess/files/4739647/whole-game.txt)
![sittuyin](https://user-images.githubusercontent.com/479964/83939608-a0c40280-a7de-11ea-9ab5-bbac62b90704.png)

**Comment by notruck** [comment]
I encountered a slightly different issue, again while parsing a PGN generated by cutechess-cli. 

In this game at move 58, only the pawn on d5 was eligible for a promotion on the e6-square. 

The Ferz eventually moved to d7, and no further "invalid move" problems arose. :smile: 

![d5e6F](https://user-images.githubusercontent.com/56622488/84222309-1a344d00-aa8c-11ea-8be3-4fc7ac46afea.png)

[Move_58_promotion_ambiguity.pgn.txt](https://github.com/pychess/pychess/files/4755980/Move_58_promotion_ambiguity.pgn.txt)

**Comment by gbtami** [comment]
Fixed via https://github.com/pychess/pychess/commit/3135c90c19f9f864bb432d49b92f95cf121e90a8
Thx again!
