### ISSUE TITLE
"Janggi" move notation problem and game save&load error.

### ISSUE THREAD

**Issue by cjssh1002** [pychess/pychess#1837]

**Comment by gbtami** [comment]
This project supports 8x8 board variants only.

**Comment by gbtami** [comment]
The correct places where you should ask are:
https://github.com/cutechess/cutechess/issues
https://github.com/ianfab/Fairy-Stockfish/issues
http://www.open-aurec.com/wbforum/viewforum.php?f=19
janggidosa ?
