### ISSUE TITLE
Puzzle mode

### ISSUE THREAD

**Issue by pychess** [pychess/pychess#184]
Original [issue 184](https://code.google.com/p/pychess/issues/detail?id=184) reported by [nunomiguelmota](https://code.google.com/u/100123020538576358086/) 2007-06-30

This is just a feature request. Sometimes i don't have much time to play a
full game and it would be great just to solve some chess puzzles

**Comment by pychess** [comment]
Original [comment 1.](https://code.google.com/p/pychess/issues/detail?id=184#c1) posted by [lobais](https://code.google.com/u/lobais/) 2007-07-03

Sounds very reasonable.
However we will need some pussels to add.
I can see three solutions:
We get some good chessplayers to do it.
We go for a wiki, rated approach, in which everybody can contribute.
We steal some elsewhere.

Do you know if there are any freely available?
- changed status to: Accepted
- removed label: Defect
- added label: Enhancement
- added label: Release1.0

**Comment by pychess** [comment]
Original [comment 2.](https://code.google.com/p/pychess/issues/detail?id=184#c2) posted by [nunomiguelmota](https://code.google.com/u/100123020538576358086/) 2007-07-03

I like the second solution, i think it is a great idea and we could do something new
with a chess game. Imagine that we have a little button that  would allow anyone to
submit puzzles from the game they have just ended. And that combined with a rating
system....we would have every day new puzzles to solve! it is a very community
oriented approach.

**Comment by pychess** [comment]
Original [comment 3.](https://code.google.com/p/pychess/issues/detail?id=184#c3) posted by [berado88](https://code.google.com/u/108250154226472549192/) 2007-07-04

I don't think these are free, but my favorite link is:
http://www.chessbase.com/puzzle/index.htm

**Comment by pychess** [comment]
Original [comment 4.](https://code.google.com/p/pychess/issues/detail?id=184#c4) posted by [lobais](https://code.google.com/u/lobais/) 2007-08-13

Ok, so we'll need serverhosting. I'm thinking that we can perhaps ask google, which
have already sponsored this page, or perhaps some other free software vendor like
Canonical or Red Hat..

I'm also thinking if the page should be a independent "Chess Puzzles" page, or
perhaps a part of a PyChess resources page, which would also contain opening books
and themes.
The advantage of having it independent would be to access a broader puzzle community.
The advantage of having it together with other resources would be in consistency.

Another task will be to create a (probably xml) format for the puzzles. If they are
to be machine checkable, we'll need to think about what criterias should be
supported: Mates/Draws in x moves, Castles in x moves, Promotes a pawn... etc.
- removed label: Release1.0
- added label: Release2.0

**Comment by pychess** [comment]
Original [comment 5.](https://code.google.com/p/pychess/issues/detail?id=184#c5) posted by [wouterstomp](https://code.google.com/u/102934909087409897177/) 2007-08-13

There is no lack of freely available chess problems. Here are a few public domain
books with chess problems:

http://www.anders.thulin.name/SUBJECTS/CHESS\_PROBLEMS/
http://www.bobby-fischer.net/chess\_books.htm

The only problem would be getting them in a pychess compatible format.

**Comment by pychess** [comment]
Original [comment 6.](https://code.google.com/p/pychess/issues/detail?id=184#c6) posted by [wouterstomp](https://code.google.com/u/102934909087409897177/) 2007-08-13

Someone converted the problems of some of these books to pgn format:

http://uglx.org/misc-chess

**Comment by pychess** [comment]
Original [comment 7.](https://code.google.com/p/pychess/issues/detail?id=184#c7) posted by [lobais](https://code.google.com/u/lobais/) 2007-08-13

Well that does of cource make things quite a lot easier, but it is still not as nifty
as the community based approach :)
Perhaps if we ever get an online chess puzzles page, those could be added from the
beginning to give more volume to the page.

But we also have to think about the implementation in PyChess. What do people need
when solving, and do we need any abstraction layers from just opening a pgn with a
"White wins in four moves" comment?

**Comment by pychess** [comment]
Original [comment 8.](https://code.google.com/p/pychess/issues/detail?id=184#c8) posted by [jokoveltman](https://code.google.com/u/113868825465409293678/) 2009-09-30

CTS (www.emrald.net) also has an enormous db of puzzles, and is a free/open service.
 Not sure how to get them from the site to PyChess, though.

Things I would be very happy to see in this area are:
- timing (ie., how long it took to find the correct move)
- success/failure tracking
- side to move indicator
- option to hide hints (in real games, there's no sign that says "Mate in 2")
- puzzle lists
- ability to add/create/insert own puzzles/positions
- ability to continue playing the position as in a game - either as both sides or
  with an engine as opponent, and possibly even with the engine playing both sides

**Comment by pychess** [comment]
Original [comment 9.](https://code.google.com/p/pychess/issues/detail?id=184#c9) posted by [gbtami](https://code.google.com/u/gbtami/) 2013-03-27

http://www.yacpdb.org

**Comment by bboutkov** [comment]
Just want to mention that FICS provides its own puzzlebot ("tell puzzlebot help" in console for more info). Perhaps integrating with that would be an easier task. There also exists endgamebot on FICS as well

**Comment by gbtami** [comment]
Good idea! Thx.
