### ISSUE TITLE
after setup install , pychess - No module named 'websockets'

### ISSUE THREAD

**Issue by g1ra** [pychess/pychess#1845]
$ pychess
Traceback (most recent call last):
  File "/usr/local/bin/pychess", line 209, in <module>
    from pychess.Main import PyChess
  File "/usr/local/lib/python3.8/dist-packages/pychess/Main.py", line 27, in <module>
    from pychess.widgets.tipOfTheDay import TipOfTheDay
  File "/usr/local/lib/python3.8/dist-packages/pychess/widgets/tipOfTheDay.py", line 6, in <module>
    from pychess.Savers.remotegame import get_internet_game_providers
  File "/usr/local/lib/python3.8/dist-packages/pychess/Savers/remotegame.py", line 10, in <module>
    import websockets
ModuleNotFoundError: No module named 'websockets'

`
$Downloads/pychess/pychess-master# python3 ./setup.py install`
....
`$Downloads/pychess/pychess-master# pip3 install websocket `
....
Same result

**Comment by g1ra** [comment]
```
~$ python
Python 2.7.18rc1 (default, Apr  7 2020, 12:05:55) 
[GCC 9.3.0] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import websocket
>>>
```

```
> ~$ python3
> Python 3.8.2 (default, Apr 27 2020, 15:53:34) 
> [GCC 9.3.0] on linux
> Type "help", "copyright", "credits" or "license" for more information.
> >>> import websocket
```

```
# apt-cache show pychess                                                                             
Package: pychess                                                                                                                                                
Architecture: all                                                                                                                                               
Version: 0.12.2-1build1                                                                                                                                         
Priority: optional                                                                                                                                              
Section: universe/python                                                                                                                                        
Origin: Ubuntu                   
```                      
ubuntu build is very old

**Comment by gbtami** [comment]
Try our latest release instead from https://github.com/pychess/pychess/releases
Don't forget to install all dependencies listed in https://github.com/pychess/pychess/blob/master/INSTALL

**Comment by ecrucru** [comment]
There are 2 packages for the websockets, but the right one to use for PyChess is `websockets` whose name ends with the character `s`.

`pip install websockets` or `apt-get install python3-websockets` should fix your issue.

**Comment by g1ra** [comment]
Thank you ecrucru,
install python3-websockets solved the problem !
