### ISSUE TITLE
Windows MSI download?

### ISSUE THREAD

**Issue by yuribudilov** [pychess/pychess#1847]
Hello
This is just a question/query, not an issue.

where can I get the Windows-10 MSI file download for the latest PyChess version (1.0.2) ?
I am not in position to built it myself, I need something 100% pre-built and ready to run.

I use PyChess 1.0.0 on Windows 10 and it works to play games but it crashes when I use the analyse game result to view from the database, after period of time (crash time varies but it always crashes after short period of time, after a few minutes of viewing the game). I use Stockfish 10 engine (BMI2 exe) with PyChess.

many thanks in advance

**Comment by gbtami** [comment]
There is no .msi for 1.0.2 because MSYS2 build system was broken before, but you can try to install our daily build from https://ci.appveyor.com/api/buildjobs/4ogpyaeak7559its/artifacts/dist%2FPyChess-1.0.3-mingw.msi

**Comment by yuribudilov** [comment]
thank you, i can wait for the next version with a pre-built Windows-10 MSI file, 
many thanks, 
I am not a developer, just a user of PyChess.
