### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by xero-lib** [pychess/pychess#1851]
> I'm closing this now, because I don't want to waste more time to fix users broken Python3 install. Sry.

That was never the error causing the app to be unusable.

The persistent error is still:
```py
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/pychess/Main.py", line 251, in on_new_game1_activate
    newGameDialog.NewGameMode.run()
  File "/usr/lib/python3.8/site-packages/pychess/widgets/newGameDialog.py", line 562, in run
    cls._ensureReady()
  File "/usr/lib/python3.8/site-packages/pychess/widgets/newGameDialog.py", line 120, in _ensureReady
    _GameInitializationMode._init()
  File "/usr/lib/python3.8/site-packages/pychess/widgets/newGameDialog.py", line 206, in _init
    updateCombos(discoverer)
  File "/usr/lib/python3.8/site-packages/pychess/widgets/newGameDialog.py", line 201, in updateCombos
    data = [(item[0], item[1]) for item in playerItems[variant]]
IndexError: list index out of range
```

Which to my knowledge isn't caused by a 3rd party python package. Please reopen this.

_Originally posted by @xero-lib in https://github.com/pychess/pychess/issues/1846#issuecomment-653930772_

**Comment by gbtami** [comment]
Paste your ~/.config/pychess/engines.json content here please.

And one more question. If you create a fresh local pychess git clone, what is the output of the following command running from pychess source dir?
`PYTHONPATH=lib/ python3 lib/pychess/Players/PyChess.py`

**Comment by xero-lib** [comment]
> Paste your ~/.config/pychess/engines.json content here please.
> 
> And one more question. If you create a fresh local pychess git clone, what is the output of the following command running from pychess source dir?
> `PYTHONPATH=lib/ python3 lib/pychess/Players/PyChess.py`

There is nothing in ~/.config/pychess besides `config` since I uninstalled it globally. I just have the git install until I can figure out why it's not working. 
![image](https://user-images.githubusercontent.com/54485853/86553792-55059580-bf11-11ea-96af-90d90c71e19c.png)
The contents of `config` are: 
```sh
[General]
soundcombo0 = 3
soundcombo1 = 3
soundcombo2 = 3
soundcombo3 = 3
soundcombo4 = 3
soundcombo5 = 3
soundcombo6 = 3
soundcombo7 = 3
soundcombo8 = 3
soundcombo9 = 3
soundcombo10 = 3
soundcombo11 = 3
soundcombo12 = 3
sounduri0 = file:/home/helix/Scripts/pychess/sounds/move1.ogg
sounduri1 = file:/home/helix/Scripts/pychess/sounds/check1.ogg
sounduri2 = file:/home/helix/Scripts/pychess/sounds/capture1.ogg
sounduri3 = file:/home/helix/Scripts/pychess/sounds/start1.ogg
sounduri4 = file:/home/helix/Scripts/pychess/sounds/win1.ogg
sounduri5 = file:/home/helix/Scripts/pychess/sounds/lose1.ogg
sounduri6 = file:/home/helix/Scripts/pychess/sounds/draw1.ogg
sounduri7 = file:/home/helix/Scripts/pychess/sounds/obs_mov.ogg
sounduri8 = file:/home/helix/Scripts/pychess/sounds/obs_end.ogg
sounduri9 = file:/home/helix/Scripts/pychess/sounds/alarm.ogg
sounduri10 = file:/home/helix/Scripts/pychess/sounds/invalid.ogg
sounduri11 = file:/home/helix/Scripts/pychess/sounds/success.ogg
sounduri12 = file:/home/helix/Scripts/pychess/sounds/choice.ogg
ics_combo = 0
autologin = False
categorycombo = 0
max_log_files = 10
hint_mode = False
spy_mode = False
show_sidepanels = True
autocallflag = True
tips_seed = 202511739
tips_index = 1
firstname = Helix
secondname = Guest
showemt = False
showeval = False
showblunder = True
hidetabs = False
closeall = False
facetoface = False
scorelinearscale = False
showcaptured = False
figuresinnotation = False
moveanimation = False
noanimation = False
autopromote = False
autorotate = False
showficsgameno = False
fullanimation = True
showcords = True
drawgrid = True
activatesupportalgorithm = False
autosave = True
autosaveformat = pychess
saveemt = False
saveeval = False
saveratingchange = False
indentpgn = False
saveowngames = True
max_analysis_spin = 3
infinite_analysis = False
opening_check = False
book_depth_max = 13
endgame_check = False
online_egtb_check = True
analyzer_check = True
inv_analyzer_check = False
alarm_spin = 15
usesounds = True
show_tip_at_startup = False
tipofthedaywindow_width = 320
tipofthedaywindow_height = 240
tipofthedaywindow_x = 2480
tipofthedaywindow_y = 420
download_timestamp = True
download_chess_db = True
download_scoutfish = True
externalsdialogwindow_width = 595
externalsdialogwindow_height = 240
externalsdialogwindow_x = 2480
externalsdialogwindow_y = 420
ngblitz min = 5
ngblitz moves = 0
ngblitz gain = 0
ngrapid min = 15
ngrapid moves = 0
ngrapid gain = 5
ngnormal min = 45
ngnormal moves = 0
ngnormal gain = 15
ngclassical min = 3
ngclassical moves = 40
ngclassical gain = 0
ngvariant1 = 3
ngvariant2 = 21
mainwindow_width = 960
mainwindow_height = 810
mainwindow_x = 2160
mainwindow_y = 27

[FICS]
asguestcheck = True
timesealcheck = True

[ICC]
```

The output of the command you specified is: 
![image](https://user-images.githubusercontent.com/54485853/86553849-7f575300-bf11-11ea-8ca4-7201af4e05c6.png)

**Comment by gbtami** [comment]
Update your local git clone (git pull) please, then paste here the output of:
`PYTHONPATH=lib/ python3 lib/pychess/Players/engineNest.py`

**Comment by xero-lib** [comment]
```py
/home/helix/Scripts/pychess/lib/pychess/Players/CECPEngine.py:6: PyGIWarning: Gtk was imported without specifying a version first. Use gi.require_version('Gtk', '3.0') before import to ensure that the right version gets loaded.
  from gi.repository import Gtk, GObject
discovering_started odict_keys(['PyChess.py', 'gnuchess', 'stockfish', 'tiger'])
..count() not went well on engine gnuchess
```

> Update your local git clone (git pull) please, then paste here the output of:
> `PYTHONPATH=lib/ python3 lib/pychess/Players/engineNest.py`

**Comment by gbtami** [comment]
And after this what is the content of  ~/.config/pychess/engines.json ?

**Comment by gbtami** [comment]
Btw. seems engine discovery failed in your system.
Here is my output:
```
tamas@tami:~/pychess$ PYTHONPATH=lib/ python3 lib/pychess/Players/engineNest.py
/home/tamas/pychess/lib/pychess/Players/CECPEngine.py:6: PyGIWarning: Gtk was imported without specifying a version first. Use gi.require_version('Gtk', '3.0') before import to ensure that the right version gets loaded.
  from gi.repository import Gtk, GObject
discovering_started odict_keys(['PyChess.py', 'crafty', 'critter', 'fairymax', 'fruit', 'glaurung', 'gnuchess', 'shamax', 'sjaakii', 'sjeng', 'spike', 'stockfish', 'toga2'])
Failed to open file: No such file or directory
UnicodeError while decoding: b'id author Ralf Sch\xe4fer und Volker B\xf6hm\n'
.............all_engines_discovered
['crafty', 'critter', 'fairymax', 'fruit', 'glaurung', 'gnuchess', 'PyChess.py', 'shamax', 'sjaakii', 'sjeng', 'spike', 'stockfish', 'toga2']
tamas@tami:~/pychess$ 
```

Notice the list of discovered engines at the end. Try to uninstall gnuchess please.

**Comment by xero-lib** [comment]
> Btw. seems engine discovery failed in your system.
> Here is my output:
> ```
> tamas@tami:~/pychess$ PYTHONPATH=lib/ python3 lib/pychess/Players/engineNest.py
> /home/tamas/pychess/lib/pychess/Players/CECPEngine.py:6: PyGIWarning: Gtk was imported without specifying a version first. Use gi.require_version('Gtk', '3.0') before import to ensure that the right version gets loaded.
>   from gi.repository import Gtk, GObject
> discovering_started odict_keys(['PyChess.py', 'crafty', 'critter', 'fairymax', 'fruit', 'glaurung', 'gnuchess', 'shamax', 'sjaakii', 'sjeng', 'spike', 'stockfish', 'toga2'])
> Failed to open file: No such file or directory
> UnicodeError while decoding: b'id author Ralf Sch\xe4fer und Volker B\xf6hm\n'
> .............all_engines_discovered
> ['crafty', 'critter', 'fairymax', 'fruit', 'glaurung', 'gnuchess', 'PyChess.py', 'shamax', 'sjaakii', 'sjeng', 'spike', 'stockfish', 'toga2']
> tamas@tami:~/pychess$ 
> ```
> 
> Notice the list of discovered engines at the end. Try to uninstall gnuchess please.

The gnuchess output only came out after about 5 minutes, but I'll try it anyway.

**Comment by xero-lib** [comment]
> Btw. seems engine discovery failed in your system.
> Here is my output:
> 
> ```
> tamas@tami:~/pychess$ PYTHONPATH=lib/ python3 lib/pychess/Players/engineNest.py
> /home/tamas/pychess/lib/pychess/Players/CECPEngine.py:6: PyGIWarning: Gtk was imported without specifying a version first. Use gi.require_version('Gtk', '3.0') before import to ensure that the right version gets loaded.
>   from gi.repository import Gtk, GObject
> discovering_started odict_keys(['PyChess.py', 'crafty', 'critter', 'fairymax', 'fruit', 'glaurung', 'gnuchess', 'shamax', 'sjaakii', 'sjeng', 'spike', 'stockfish', 'toga2'])
> Failed to open file: No such file or directory
> UnicodeError while decoding: b'id author Ralf Sch\xe4fer und Volker B\xf6hm\n'
> .............all_engines_discovered
> ['crafty', 'critter', 'fairymax', 'fruit', 'glaurung', 'gnuchess', 'PyChess.py', 'shamax', 'sjaakii', 'sjeng', 'spike', 'stockfish', 'toga2']
> tamas@tami:~/pychess$ 
> ```
> 
> Notice the list of discovered engines at the end. Try to uninstall gnuchess please.

I removed gnuchess, no change.

Also, no change to `~/.config/pychess`. Still just config.

![image](https://user-images.githubusercontent.com/54485853/86616543-9af74380-bf7b-11ea-85d5-95a59b23a709.png)
It just sits there, does nothing.
![image](https://user-images.githubusercontent.com/54485853/86616590-ae0a1380-bf7b-11ea-98df-6f27bd35a838.png)

**Comment by gbtami** [comment]
Ok, try to uninstall stockfish and tiger also. Let see if it can discover pychess engine itself!

**Comment by xero-lib** [comment]
> Ok, try to uninstall stockfish and tiger also. Let see if it can discover pychess engine itself!

Yes, it did:

```py
PYTHONPATH=lib/ python3 lib/pychess/Players/engineNest.py
/home/helix/Scripts/pychess/lib/pychess/Players/CECPEngine.py:6: PyGIWarning: Gtk was imported without specifying a version first. Use gi.require_version('Gtk', '3.0') before import to ensure that the right version gets loaded.
  from gi.repository import Gtk, GObject
discovering_started odict_keys(['PyChess.py'])
.all_engines_discovered
['PyChess.py']
```

**Comment by xero-lib** [comment]
> Ok, try to uninstall stockfish and tiger also. Let see if it can discover pychess engine itself!

Tiger seems to have been the problem. Now that I'm looking at the error, I think it was detecting Tiger but not finding it, so when I tried to open the new game context menu, it tried to enumerate Tiger but couldn't find it.

**Comment by xero-lib** [comment]
Thank you for all your help!

**Comment by gbtami** [comment]
Seems tiger is some security related stuff.
`tiger - Report system security vulnerabilities`
I marked it as NO_AUTO_DETECT in https://github.com/pychess/pychess/commit/24fa59e8fa9896234492bfe6d79d3b71ce31a17b

Thx for your patience also!
