### ISSUE TITLE
No Audio after OS upgrade

### ISSUE THREAD

**Issue by g3k0** [pychess/pychess#1855]
Hello, 

I upgraded my OS Mint from version 19.3 to version 20. 
After the upgrade the audio of the application is not working anymore. 

I installed all the packages listed in the INSTALL file. gstreamer1.0-pulseaudio is installed.

I run the application with the ./pychess command. 

Are there some other packages I need to install?

**Comment by gbtami** [comment]
Try to `git pull` first, then run
`PYTHONPATH=lib python3 lib/pychess/System/gst_player.py `
pychess uses [this](https://github.com/pychess/pychess/blob/master/lib/pychess/System/gst_player.py) tiny gst server subprocess for sounds which accepts sound files in stdin as absolute path.
For example
`/home/tamas/pychess/sounds/start1.ogg`

**Comment by g3k0** [comment]
Unfortunately it is not working, when I run `PYTHONPATH=lib python3 lib/pychess/System/gst_player.py`  the process remains hanging. 

curiously only puzzle success and variation choices sounds are working.
I attach a  screenshot: 
![screen](https://user-images.githubusercontent.com/4429186/87334839-96182e00-c53f-11ea-9e0a-f0ab497a8825.png)

**Comment by gbtami** [comment]
"Unfortunately it is not working, when I run PYTHONPATH=lib python3 lib/pychess/System/gst_player.py the process remains hanging."
What this exactly means? Can you paste the console output here please?

**Comment by gbtami** [comment]
Btw if puzzle success and variation choices sounds are working that means the problem is not gst and dependencies related at all but sound config settings instead.
Can you try to change "No sound" to something else clicking on above dropdowns?

**Comment by g3k0** [comment]
I selected an audio file from the dropdown and I pressed the play button but there is no audio

The log of the application is this one:

```
christian@christian-H87M-HD3:~/Studio/pychess$ ./pychess 

(pychess:62210): Gtk-WARNING **: 19:02:13.785: Can't set a parent on widget which has a parent
```

I attach a screenshot of the audio settings:
![screen](https://user-images.githubusercontent.com/4429186/87454915-f02ef700-c604-11ea-8c2a-0de8771b17ae.png)


Maybe there is some package missing in my OS, the application was working fine before the upgrade of the OS.

**Comment by gbtami** [comment]
What "puzzle success and variation choices sounds are working" means then?

**Comment by g3k0** [comment]
If I press the play button I hear the sound

**Comment by gbtami** [comment]
Ok, that means packages required by pychess are Ok.
Maybe some of your pychess audio files are corrupted or has file access issues.
Can you play .ogg files shipped by pychess with other audio player apps?

**Comment by g3k0** [comment]
I ran the audio files under ./sounds, both .ogg and .wav with VLC media player and I can hear the sounds.

I gave 755 permissions to all files in the folder.

Then from sound preferences windows I selected the sounds. I press play and there was no sound.

I turn off the application and turn on again. Then from sound preferences I press play buttons again, and now I can hear sounds
