### ISSUE TITLE
Puzzle Troicki.OLV

### ISSUE THREAD

**Issue by Arunachala-Ramana** [pychess/pychess#1860]
After playing 4 or 5 puzzles it says Puzzles completed. I checked the Olv file and it contains a lot of puzzles not just 4. 
![a](https://user-images.githubusercontent.com/68316708/87955176-ff151e00-caca-11ea-8419-866b8ea7c92d.png)
 Not sure, what the problem is :(

**Comment by gbtami** [comment]
Pychess uses mate in #n puzzles only from .olv files because in .olv solutions can be in several (sometimes rather unusual) form (because its input is a wiki page). Writing a parser for a not clearly defined file format is hopeless.
