### ISSUE TITLE
Add "Skip puzzle" putton

### ISSUE THREAD

**Issue by gbtami** [pychess/pychess#1863]
Splitted from https://github.com/pychess/pychess/issues/1862
Now, when the engine gives a false hint to a puzzle and even if i make the correct move it says retry. That means i can't move to the next puzzle. Perhaps can you consider adding a skip puzzle option? What i am at present doing is keep going back to the .olv file keep deleting the incorrect hints ones and then save it and then restart the application and play from the next puzzle. That also looks a bit tedious.

**Comment by Arunachala-Ramana** [comment]
Great. skip puzzle + previous puzzle button would be great, so that one can go and revise any puzzle he wants. This should be there in any instructional lessons, be it endgames tactics or puzzles.

**Comment by gbtami** [comment]
Fixed via https://github.com/pychess/pychess/pull/1946
