### ISSUE TITLE
How to use the pychess engine in other chess clients?

### ISSUE THREAD

**Issue by puspamadak** [pychess/pychess#1871]
I am quite impressed by the pychess engine due to its difficulty level. Now, I want to use the pychess engine with other GUI frontends. Can I do that or is the engine tightly integrated with this software?

**Comment by gbtami** [comment]
It can be used with any GUI supporting CECP(Xboard) protocol. You can create the latest one from git running the create-engine.sh script. It will produce so-called python executable zip archive named pychess-engine.
You can run it with python3 (or pypy3).
```
tamas@tami:~/pychess$ python3 pychess-engine
# PyChess 1.0.3 [python3 3.6.9]
xboard
protover 2
feature ping=1 setboard=1 playother=1 san=1 usermove=1 time=1 draw=1 sigint=0 sigterm=0 reuse=1 analyze=1 myname="PyChess 1.0.3" variants="normal,wildcastle,nocastle,fischerandom,crazyhouse,light-brigade,losers,suicide,giveaway,horde,atomic,racingkings,seirawan,kingofthehill,3check,placement,asean,cambodian,makruk,sittuyin" colors=0 ics=0 name=0 pause=0 nps=0 debug=1 memory=0 smp=0 egt="gaviota" option="skipPruneChance -slider 0 0 100"
feature done=1
```

**Comment by puspamadak** [comment]
Thanks a lot !

**Comment by gbtami** [comment]
Your welcome!
