### ISSUE TITLE
Can this while loop be removed?

### ISSUE THREAD

**Issue by jordanbray** [pychess/pychess#1874]
I'm poking around the code to see how your async/await works with the Gtk runtime, and I saw these lines of code.

https://github.com/pychess/pychess/blob/b25d71d28af6739e5a2c52020f7ae3ab68b6b3dd/lib/pychess/widgets/discovererDialog.py#L80

This shows the lines:

```python
        while True:
            await wait_signal(self.discoverer, "all_engines_discovered")
            break
```

There's nothing weird going on here with the `while` loop that I'm missing, right?

It appears to me this can be replaced with the single `await` line.

**Comment by gbtami** [comment]
Fixed, thx!
