### ISSUE TITLE
Issue with Xiphos Chess Engine

### ISSUE THREAD

**Issue by Arunachala-Ramana** [pychess/pychess#1876]
While trying to use the [Xiphos Engine ](https://github.com/milostatarevic/xiphos/) I encountered the following problem. 

Image 1 : The move (Hint Arrow) for white recommended by the engine is e4. 

Image 2 : After playing e4 the engine stops and doesnt recommend a move for black.  I have to press the  "||" button each and every time to get the "Hint Arrow" working. 

How do I solve this issue?

![1](https://user-images.githubusercontent.com/68316708/94641332-a1892300-02fe-11eb-9a98-db4517678b03.png)
![2](https://user-images.githubusercontent.com/68316708/94641337-a4841380-02fe-11eb-86c1-5584dc240b83.png)

**Comment by gbtami** [comment]
I can't reproduce this. I compiled xiphos from https://github.com/milostatarevic/xiphos with `make sse` (my laptop CPU has no bmi2).
You can try to start pychess with --log-debug --log-view command line arguments, and look into View -> Log viewer, maybe it can show something about the reasons.

**Comment by Arunachala-Ramana** [comment]
You can try to start pychess with --log-debug --log-view command line arguments, and look into View -> Log viewer, maybe it can show something about the reasons.

Could you explain this more? I don't understand. Should i type pychess --log-view in terminal and then start or something?

**Comment by gbtami** [comment]
Yep, you can start it in terminal like:
`pychess --log-debug --log-view`

**Comment by Arunachala-Ramana** [comment]
Ok did that. What should i do then?

**Comment by gbtami** [comment]
Take a look into View -> Log viewer, maybe it can show something about the reasons.

**Comment by Arunachala-Ramana** [comment]
where is that found?? How should i take a look?

**Comment by Arunachala-Ramana** [comment]
Ok this is what the log file says
--------------
/home/chandru1/Xiphos 
SubProcess.start(): create_subprocess_exec...
setOptionInitialBoard: self=Xiphos, model=<GameModel at 140139570116096 (ply=0, variant=b'Normal', status=2, reason=42, players=[Chandrasekhar, Guest], tags=defaultdict(<class 'str'>, {'Event': 'Local Event', 'Site': 'Local Site', 'Date': '2020.09.30', 'Round': '1', 'White': 'Chandrasekhar', 'Black': 'Guest', 'WhiteElo': '', 'BlackElo': ''})
board=#White KQkq -
# ♜ ♞ ♝ ♛ ♚ ♝ ♞ ♜ 
# ♟ ♟ ♟ ♟ ♟ ♟ ♟ ♟ 
# . . . . . . . . 
# . . . . . . . . 
# . . . . . . . . 
# . . . . . . . . 
# ♙ ♙ ♙ ♙ ♙ ♙ ♙ ♙ 
# ♖ ♘ ♗ ♕ ♔ ♗ ♘ ♖ 
# )>
uci

Xiphos 0.6 BMI2 by Milos Tatarevic
threads=1
hash=128MB
id name Xiphos 0.6 BMI2
id author Milos Tatarevic
option name Hash type spin default 128 min 1 max 32768
option name Threads type spin default 1 min 1 max 128
option name Ponder type check default false
option name SyzygyPath type string default <empty>
option name SyzygyProbeDepth type spin default 1 min 1 max 100
uciok
setoption name Ponder value false

isready

ponder=0
readyok
_searchNow: self.needBestmove=False ponderhit=False self.board=#White KQkq -
# ♜ ♞ ♝ ♛ ♚ ♝ ♞ ♜ 
# ♟ ♟ ♟ ♟ ♟ ♟ ♟ ♟ 
# . . . . . . . . 
# . . . . . . . . 
# . . . . . . . . 
# . . . . . . . . 
# ♙ ♙ ♙ ♙ ♙ ♙ ♙ ♙ 
# ♖ ♘ ♗ ♕ ♔ ♗ ♘ ♖ 
# 
setBoardAtPly: board=#White KQkq -
# ♜ ♞ ♝ ♛ ♚ ♝ ♞ ♜ 
# ♟ ♟ ♟ ♟ ♟ ♟ ♟ ♟ 
# . . . . . . . . 
# . . . . . . . . 
# . . . . . . . . 
# . . . . . . . . 
# ♙ ♙ ♙ ♙ ♙ ♙ ♙ ♙ 
# ♖ ♘ ♗ ♕ ♔ ♗ ♘ ♖ 
# 
ucinewgame

stop

position startpos

go infinite

stop

info depth 0 score cp 0 nodes 0 tbhits 0 time 0 nps 0 pv
bestmove (none)
__parseLine: processing analyzer bestmove='bestmove (none)'
_searchNow: self.needBestmove=False ponderhit=False self.board=#White KQkq -
# ♜ ♞ ♝ ♛ ♚ ♝ ♞ ♜ 
# ♟ ♟ ♟ ♟ ♟ ♟ ♟ ♟ 
# . . . . . . . . 
# . . . . . . . . 
# . . . . . . . . 
# . . . . . . . . 
# ♙ ♙ ♙ ♙ ♙ ♙ ♙ ♙ 
# ♖ ♘ ♗ ♕ ♔ ♗ ♘ ♖ 
# 
stop

position startpos

go infinite

info depth 1 score cp 46 nodes 20 tbhits 0 time 0 nps 20000 pv d2d4
info depth 2 score cp 64 nodes 56 tbhits 0 time 0 nps 56000 pv d2d4 h7h5
info depth 3 score cp 61 nodes 81 tbhits 0 time 0 nps 81000 pv d2d4 h7h5 g1h3
info depth 4 score cp 63 nodes 104 tbhits 0 time 0 nps 104000 pv d2d4 h7h5 g1h3 h5h4
info depth 5 score cp 12 nodes 352 tbhits 0 time 0 nps 352000 pv d2d4 e7e6 g1h3 h7h5 h1g1
info depth 6 score cp 39 nodes 581 tbhits 0 time 1 nps 290500 pv d2d4 d7d5 d1d2 h7h5 g1f3 h5h4
info depth 7 score cp 30 nodes 1507 tbhits 0 time 2 nps 502333 pv b1c3 e7e6 e2e3 g8f6 g1f3 d7d5 d2d4
info depth 8 score cp 0 nodes 3744 tbhits 0 time 4 nps 748800 pv b1c3 d7d5 e2e3 g8f6 f1e2 b8c6 d2d4 e7e6
info depth 9 score cp 12 nodes 6488 tbhits 0 time 7 nps 811000 pv b1c3 d7d5 e2e3 g8f6 f1e2 b8c6 d2d4 e7e6 g1f3 f6e4
info depth 10 score cp 30 nodes 25165 tbhits 0 time 21 nps 1143863 pv c2c4 e7e6 d2d4 g8f6 b1c3 b8c6 d4d5 e6d5 c4d5 c6e5
info depth 11 score cp 22 nodes 171024 tbhits 0 time 114 nps 1487165 pv g1f3 d7d5 e2e3 b8c6 d2d4 e7e6 c2c4 g8f6 b1c3 f8e7 c4d5 e6d5 f1d3
info depth 12 score cp 22 nodes 242830 tbhits 0 time 165 nps 1462831 pv d2d4 d7d5 e2e3 e7e6 c2c4 b8c6 b1c3 g8f6 g1f3 f8d6 f1d3 e8g8 e1g1 c6b4 d3e2 f6e4 c1d2 e4d2 d1d2
info depth 13 score cp 21 nodes 718661 tbhits 0 time 446 nps 1607742 pv d2d4 d7d5 c2c4 e7e6 g1f3 g8f6 e2e3 f8e7 c4d5 e6d5 f1d3 e8g8 e1g1 c8e6 b1c3 b8c6 a2a3 h7h6 c1d2

20:43:39
------------------------------------------------------------
info depth 14 score cp 17 nodes 1923061 tbhits 0 time 1129 nps 1701823 pv d2d4 d7d5 g1f3 g8f6 c1f4 c8f5 e2e3 e7e6 f1d3 f5d3 c2d3 f8b4 b1c3 e8g8 d1b3 b8c6 f3e5 a8b8 e1g1 h7h6 h2h3 b4e7 c3b5 c6b4
info depth 15 score cp 17 nodes 2371409 tbhits 0 time 1401 nps 1691447 pv d2d4 d7d5 g1f3 g8f6 c1f4 c8f5 e2e3 e7e6 f1d3 f5d3 c2d3 f8b4 b1c3 e8g8 d1b3 b8c6 f3e5 a8b8 e1g1 h7h6 h2h3

20:43:41
------------------------------------------------------------
info depth 16 score cp 24 nodes 4530162 tbhits 0 time 2647 nps 1710786 pv d2d4 d7d5 g1f3 e7e6 c1f4 c7c5 e2e3 g8f6 b1c3 a7a6 f1e2 b8c6 e1g1 f8e7 f3e5 c5d4 e5c6 b7c6 e3d4

20:43:43
------------------------------------------------------------
info depth 17 score cp 31 nodes 8105751 tbhits 0 time 4782 nps 1694700 pv d2d4 d7d5 g1f3 g8f6 c2c4 e7e6 b1c3 b8c6 e2e3 f8d6 c4c5 d6e7 f1d3 e8g8 e1g1 h7h6 a2a3 a7a6 b2b4 b7b6 c5b6 c7b6

20:43:47
------------------------------------------------------------
info depth 18 score cp 27 nodes 13267959 tbhits 0 time 8228 nps 1612341 pv e2e4 c7c5 g1f3 b8c6 f1b5 e7e6 e1g1 g8e7 c2c3 a7a6 b5c6 e7c6 d2d4 d7d5 c1g5 f7f6 e4d5 d8d5 g5e3 c5d4 c3d4 f8e7 b1c3

20:43:50
------------------------------------------------------------
info depth 19 score cp 35 nodes 17860620 tbhits 0 time 11220 nps 1591713 pv d2d4 d7d5 g1f3 g8f6 c2c4 e7e6 b1c3 c7c5 c4d5 e6d5 c1g5 f8e7 d4c5 e8g8 e2e3 b8c6 f1d3 e7c5 g5f6 d8f6 c3d5

20:43:53
------------------------------------------------------------
info depth 20 score cp 25 nodes 23864264 tbhits 0 time 14722 nps 1620883 pv d2d4 d7d5 g1f3 g8f6 c2c4 e7e6 b1c3 c7c5 c4d5 e6d5 c1g5 f8e7 d4c5 e8g8 e2e3 b8c6 f1e2 c8e6 e1g1 h7h6 g5f6 e7f6

20:43:57
------------------------------------------------------------
info depth 21 score cp 22 nodes 30044073 tbhits 0 time 18483 nps 1625409 pv d2d4 d7d5 g1f3 g8f6 c2c4 e7e6 b1c3 c7c5 c4d5 e6d5 c1g5 f8e7 d4c5 e8g8 e2e3 h7h6 g5f6 e7f6 f1e2 c8e6 e1g1 b8d7 c3a4 d8a5 f3d4 a8c8 a1c1 d7c5

20:44:08
------------------------------------------------------------
info depth 22 score cp 26 nodes 49241409 tbhits 0 time 29866 nps 1648689 pv d2d4 d7d5 c2c4 e7e6 b1c3 g8f6 c1g5 f8e7 e2e3 e8g8 g1f3 b8d7 c4d5 e6d5 h2h3 b7b6 f1d3 c8b7 e1g1 c7c5 d1c2 f6e4 g5e7 d8e7 f3d2 d7f6 d3e4 d5e4 d4c5 e7c5

---------------------------

**Comment by Arunachala-Ramana** [comment]
Anything you could figure out from the log file? Have I pasted the log file correctly?

**Comment by gbtami** [comment]
This seems not the relevant tab's content for me. At least these are the analysis lines of starting position only.
There are several tabs (on the left side of the log viewer). Maybe other tab contents can help.

**Comment by Arunachala-Ramana** [comment]
Emm.  Ok here i attach the 2 more tabs.
![2](https://user-images.githubusercontent.com/68316708/94786034-138c6580-03ee-11eb-8e57-0efbf99df3de.png)
![1](https://user-images.githubusercontent.com/68316708/94786037-15eebf80-03ee-11eb-9f0a-3b6841e8c933.png)

**Comment by gbtami** [comment]
Ok, I was able to reproduce this issue.
Seems the problem is Xiphos doesn't like stop command when analysis is ongoing.
Try to uncheck infinite analysis and set analysis time something reasonable (5s for example). Then if you wait 5s after your moves it will be ok. Otherwise it will fail (maybe stops the engine?).

Anyhow I suggest to use https://stockfishchess.org/download/ for analysis. It has no such issues with in between stop commands.

**Comment by Arunachala-Ramana** [comment]
I will try that. Many engines work perfectly. I am just trying to experiment with different engines  :) Sorry for troubling you.

**Comment by Arunachala-Ramana** [comment]
I see.  "Xiphos doesn't like stop command when analysis is ongoing." this seems to be true. When i change the analysis time to 1 second its working and if i increase analysis time to 2 or more, the issue still persists.

**Comment by gbtami** [comment]
As i see any finite x second can be Ok. You just have to wait x sec after all of played moves to let Xiphos finish analysis itself (not by stop command).

**Comment by Arunachala-Ramana** [comment]
![0](https://user-images.githubusercontent.com/68316708/94793321-ecd32c80-03f7-11eb-99df-a230a60854a4.png)


Not working for me, when i set the Maximum Analysis time to 2seconds
