### ISSUE TITLE
Flatpak

### ISSUE THREAD

**Issue by PlatonB** [pychess/pychess#1878]
Please distribute the program as flatpak on flathub.org. It is modern and user-friendly approach.

**Comment by gbtami** [comment]
Sry, but I have no time to support all existing distribution formats.

**Comment by PlatonB** [comment]
This format was invented to get rid of the variety and incompatibility of existing binary formats. And placement on Flathub can increase the popularity of the program.

P.S. It is possible that @TingPing or @bilelmoussaoui will have time and interest to maintain PyChess' flatpak.

**Comment by gbtami** [comment]
Well, I know there are several newish distribution formats our there (Flatpak, Snap, AppImage, etc-etc.).
See my answer in https://github.com/pychess/pychess/issues/1611 as well.
