### ISSUE TITLE
Theme support

### ISSUE THREAD

**Issue by pychess** [pychess/pychess#188]
Original [issue 188](https://code.google.com/p/pychess/issues/detail?id=188) reported by [wouterstomp](https://code.google.com/u/102934909087409897177/) 2007-08-08

It would be nice if different themes could be chosen for the board and pieces.

**Comment by pychess** [comment]
Original [comment 1.](https://code.google.com/p/pychess/issues/detail?id=188#c1) posted by [lobais](https://code.google.com/u/lobais/) 2007-08-29
- removed label: Defect
- added label: Enhancement

**Comment by pychess** [comment]
Original [comment 2.](https://code.google.com/p/pychess/issues/detail?id=188#c2) posted by [gbtami](https://code.google.com/u/gbtami/) 2008-01-02

The first candidate can be the rainbow chess set:
http://home.hu.inter.net/~prochess/lovass/rainbow.htm

**Comment by pychess** [comment]
Original [comment 3.](https://code.google.com/p/pychess/issues/detail?id=188#c3) posted by [lobais](https://code.google.com/u/lobais/) 2008-01-02

Here are some other idea's I've had.

I'd like the theming to be very flexible. I've even thought of using webkit or
something. However then I'm not sure how fluently the animations can be made.

For the yousee.svg clock integration also has to be possible.
- attached [orange.svg](https://code.google.com/p/pychess/issues/detail?id=188#c3)
- attached [yousee.svg](https://code.google.com/p/pychess/issues/detail?id=188#c3)
- attached [softsquare.svg](https://code.google.com/p/pychess/issues/detail?id=188#c3)
- attached [tegning.svg](https://code.google.com/p/pychess/issues/detail?id=188#c3)
- attached [round.svg](https://code.google.com/p/pychess/issues/detail?id=188#c3)
- attached [tangosquares.svg](https://code.google.com/p/pychess/issues/detail?id=188#c3)

**Comment by pychess** [comment]
Original [comment 4.](https://code.google.com/p/pychess/issues/detail?id=188#c4) posted by [gbtami](https://code.google.com/u/gbtami/) 2008-01-16

I like to see this too in pychess:
http://www.artnet.com/artwork/52150/1158/play-it-by-trust.html

One can think it's just fun, but you can look at it as an introduction to blindfold
chess.

**Comment by pychess** [comment]
Original [comment 5.](https://code.google.com/p/pychess/issues/detail?id=188#c5) posted by [lobais](https://code.google.com/u/lobais/) 2008-01-16

Yeah, there could be levels of blindfold themes.
One theme could also have all pieces looking the same.

**Comment by pychess** [comment]
Original [comment 6.](https://code.google.com/p/pychess/issues/detail?id=188#c6) posted by [gbtami](https://code.google.com/u/gbtami/) 2008-01-17

And the true blindfold chess can be a theme with 100% transparent piece set. Cool!

**Comment by pychess** [comment]
Original [comment 7.](https://code.google.com/p/pychess/issues/detail?id=188#c7) posted by [lobais](https://code.google.com/u/lobais/) 2008-01-17

Clutter: http://www.clutter-project.org/ would probably be useable to create really
nice animation in themes.

**Comment by pychess** [comment]
Original [comment 8.](https://code.google.com/p/pychess/issues/detail?id=188#c8) posted by [lobais](https://code.google.com/u/lobais/) 2008-01-18

The xmlformat could also be inspired be googles Theme API:
http://code.google.com/apis/themes/

**Comment by pychess** [comment]
Original [comment 9.](https://code.google.com/p/pychess/issues/detail?id=188#c9) posted by [lobais](https://code.google.com/u/lobais/) 2008-02-11

Wow, this made me consider webkit once again: http://webkit.org/blog/138/css-animation/

**Comment by pychess** [comment]
Original [comment 10.](https://code.google.com/p/pychess/issues/detail?id=188#c10) posted by [gbtami](https://code.google.com/u/gbtami/) 2012-02-28

Added a new drawPiece3() and get_svg_pieces() in http://code.google.com/r/gbtami-exportmenu/source/browse/lib/pychess/gfx/Pieces.py to let use different .svg piece sets.

At this stage you can set a default piece set in line comment 17.5:
svg_pieces = get_svg_pieces('cburnett')

The available values are: cburnett, celtic, chessmonk, freestaunton.
I'm thinking to add a new "Theme" tab into Preferences, something like Rybka uses.
What do you think?
- changed status to: Started

**Comment by pychess** [comment]
Original [comment 11.](https://code.google.com/p/pychess/issues/detail?id=188#c11) posted by [gbtami](https://code.google.com/u/gbtami/) 2012-03-13

Added piece theme selection support into preferences.
- attached [piecethemes.png](https://code.google.com/p/pychess/issues/detail?id=188#c11)

**Comment by pychess** [comment]
Original [comment 12.](https://code.google.com/p/pychess/issues/detail?id=188#c12) posted by [gbtami](https://code.google.com/u/gbtami/) 2012-03-16

Filled .ttf pieces.
- attached [filled_ttf_pieces.png](https://code.google.com/p/pychess/issues/detail?id=188#c12)

**Comment by pychess** [comment]
Original [comment 13.](https://code.google.com/p/pychess/issues/detail?id=188#c13) posted by [lobais](https://code.google.com/u/lobais/) 2012-03-19

Awesome :)
We can combine this with 'variants' to support Chinese chess.

In the preferences, how about changing the dropdown+preview for larger clickable previews? Similar to the desktop theme selector.
I believe that one uses a treeview or an iconview. Could file that in another bug report though.

**Comment by pychess** [comment]
Original [comment 14.](https://code.google.com/p/pychess/issues/detail?id=188#c14) posted by [gbtami](https://code.google.com/u/gbtami/) 2012-03-19

I don't like this dropdown (too long) too. Can you describe this theme selector thing a bit more detailed, please?

**Comment by pychess** [comment]
Original [comment 15.](https://code.google.com/p/pychess/issues/detail?id=188#c15) posted by [lobais](https://code.google.com/u/lobais/) 2012-03-21

Of course. I'm thinking of this dialog: http://www.blogcdn.com/downloadsquad.switched.com/media/2010/01/ubuntu-themes-easy.jpg

**Comment by pychess** [comment]
Original [comment 16.](https://code.google.com/p/pychess/issues/detail?id=188#c16) posted by [gbtami](https://code.google.com/u/gbtami/) 2012-03-27

The preview icons now created in users locale dir if not find. I'm not sure this is the best approach. What do you think?
- attached [iconview.png](https://code.google.com/p/pychess/issues/detail?id=188#c16)

**Comment by pychess** [comment]
Original [comment 17.](https://code.google.com/p/pychess/issues/detail?id=188#c17) posted by [lobais](https://code.google.com/u/lobais/) 2012-03-28

Looks great :)
The precomputation is a bit worrying though. Does this add to the initial program start-up time, or is it only done when the icons are shown?
If the generation is very fast, we could not store the images at all, or store them in temp.
Otherwise we could perhaps store them together with the themes themselves?

**Comment by pychess** [comment]
Original [comment 18.](https://code.google.com/p/pychess/issues/detail?id=188#c18) posted by [gbtami](https://code.google.com/u/gbtami/) 2012-03-28

I think we better to chose the latter. Generating preview icons f.e. on my old Celeron box takes time (4-5 sec).

**Comment by pychess** [comment]
Original [comment 19.](https://code.google.com/p/pychess/issues/detail?id=188#c19) posted by [gbtami](https://code.google.com/u/gbtami/) 2012-04-02

Merged to tip.
Another part of this issue (board theme handling) is waiting for contribution yet.

**Comment by pychess** [comment]
Original [comment 20.](https://code.google.com/p/pychess/issues/detail?id=188#c20) posted by [lobais](https://code.google.com/u/lobais/) 2012-06-02

Also, if anybody wants to give it a go, this might be a helpful reference for lazy generation of the treeview rows: http://stackoverflow.com/questions/3164262/lazy-loaded-list-view-in-gtk

**Comment by cajone** [comment]
Ok I think I have fixed the issue with the persistent board colors being stored. The next big step is changing the squares on the board. I had a look through the BoardView.py file and there is a lot of references to color :(.

gbtami: can you give me any pointers on where to start with this part of the enhancement, ie where the square color is set etc any tips will be helpfull hopefully make this change work faster.

Thanks

**Comment by gbtami** [comment]
Square colors are queried from style context in BoardView.py:
    def drawBoard(self, context, r):
        xc, yc, square, s = self.square
        sc = self.get_style_context()
        found, col = sc.lookup_color("p_dark_color")
        context.set_source_rgba(col.red, col.green, col.blue, col.alpha)
The used colors from style like "p_dark_color" are defined and set in Background.py

**Comment by cajone** [comment]
ok basic functionality in place 

cosmetics needing addressed
- Theme frame titles made bold ( done )
- Vbox frame lines need to be removed (done)
- more vertical spacing between colour buttons ( done )
- Traceback issue needs fixed ( done )
- all squares in makruk variation should be light ( will investigate) 
- adjust rank and file number/letters to same colour as dark selection (done)

I pushed all aspects marked (done) above. The Makruk board seems very broken
and I'm not sure how to fix it at the moment. Things that look wrong

1) board is not a singualr light colour
2) animation and mouse hovering events seem to displace the squares slightly, this
is probably due to the way the board had a grid lattice separating the squares.

gbtami: please edit/add or  change any of the above if I missed something

**Comment by gbtami** [comment]
Committed makruk fix and made some little layout adjustments.
