### ISSUE TITLE
Unable to run PyChess on Fedora 33(Python 3.9)

### ISSUE THREAD

**Issue by konsbn** [pychess/pychess#1881]
After Updating from Fedora 32 I am unable to use PyChess and I get the following error 
`ERROR: PyChess requires python-cairo to be installed.`
Even though I have `python3-cairo` installed.

**Comment by gbtami** [comment]
I'm not familiar with Fedora packages, so have no idea what changed from 32 to 33.
Btw what version of pychess you try to install?

**Comment by konsbn** [comment]
I tried the Version in the Fedora Repositories(v 0.99) and also the version available on PyChess GitHub as .rpm files (v 1.x) in all the python 3.6, 3.7 and 3.8 versions but none of them worked. However when I downloaded the GitHub repository and ran `./pychess` it worked however upon installation using `python setup.py install` it stopped working once again.

**Comment by gbtami** [comment]
Thx for the feedback!
Yep, older Python3 version .rpm should work with matching Python3 version only so this is not a big surprise :)
If you downloaded the current sources from GitHub, then no need to run `python setup.py install`. pychess can be run in place without  installing it globally. It is enough to run `python setup.py build` to create .png theme preview images and translation .mo files.
For next release i will provide .rpm package for Python3.9 for sure.

**Comment by konsbn** [comment]
Any idea as to when I can expect the next version? And thank you so much for your great work

**Comment by antvrs** [comment]
Hello,
 I'm having the same issues with Fedora 33 and Python 3.9.  
 I am able to start 1.0.2 with ./pychess, but systemwide install has failed and seems to have broken my ability to install any other version. 
 Here is the output when trying to start:

""# pychess
Traceback (most recent call last):
  File "/usr/local/bin/pychess", line 209, in <module>
    from pychess.Main import PyChess
  File "/usr/local/lib/python3.9/site-packages/pychess/Main.py", line 24, in <module>
    from pychess.widgets import enginesDialog, newGameDialog
  File "/usr/local/lib/python3.9/site-packages/pychess/widgets/enginesDialog.py", line 14, in <module>
    from pychess.widgets import newGameDialog
  File "/usr/local/lib/python3.9/site-packages/pychess/widgets/newGameDialog.py", line 44, in <module>
    from pychess.perspectives.games import enddir
  File "/usr/local/lib/python3.9/site-packages/pychess/perspectives/games/__init__.py", line 24, in <module>
    from pychess.widgets import gamewidget, mainwindow, new_notebook
  File "/usr/local/lib/python3.9/site-packages/pychess/widgets/gamewidget.py", line 32, in <module>
    light_on = get_pixbuf("glade/16x16/weather-clear.png")
  File "/usr/local/lib/python3.9/site-packages/pychess/Utils/IconLoader.py", line 26, in get_pixbuf
    return GdkPixbuf.Pixbuf.new_from_stream(file.read(None), None)
gi.repository.GLib.Error: g-io-error-quark: Error opening file /usr/share/pychess/glade/16x16/weather-clear.png: No such file or directory (1)

** (gst-plugin-scanner:52965): CRITICAL **: 02:03:24.095: Couldn't g_module_open libpython. Reason: /usr/lib64/libpython3.9.so: cannot open shared object file: No such file or directory
failed to open /usr/lib64/dri/hybrid_drv_video.so
Not using hybrid_drv_video.so
failed to open /usr/lib64/dri/hybrid_drv_video.so
Not using hybrid_drv_video.so
failed to open /usr/lib64/dri/hybrid_drv_video.so
Not using hybrid_drv_video.so
""
----
 I will wait, if there's a new rpm coming. Maybe this output is useful.
-A

**Comment by gbtami** [comment]
Latest release 1.0.3  has .rpm packages for Python3.9
