### ISSUE TITLE
How to use engine's own openings book ?

### ISSUE THREAD

**Issue by pelican74** [pychess/pychess#1882]
Hello,
My engine has its own openings book.
It declares it properly with the setoption OwnBook (type check). I check the option under engine options (and that is correctly transmitted from gui to engine when playing). I also uncheck using pyChess book under preferences. But all this does not produce any noticeable effect. pyChess keeps playing the openings itself.
What am I doing wrong ?
Thanks for your help.
PyChess 1.0.0 under Win10, UCI protocol

**Comment by gbtami** [comment]
OwnBook UCI option works for me with old Stockfish 231-ja.
Is your engine available somewhere to download?

**Comment by ecrucru** [comment]
Hello. The workaround in relation with #1538 is that you must set the book depth to zero in prefs too.

**Comment by pelican74** [comment]
Got it ! Thanks. 
Have a good day.
