### ISSUE TITLE
pychess launches wireshark `ethereal` when detecting engines

### ISSUE THREAD

**Issue by samcv** [pychess/pychess#1883]
When I launch Pychess on OpenSuse Tumbleweed, it launches wireshark's `ethereal`. Maybe there is some chess engine also called ethereal? Is there a way you can detect that this is not a chess engine? The output from its help is:

```
$ ethereal --help
Wireshark 3.2.8 (Git commit 8c208b7f257d)
Interactively dump and analyze network traffic.
See https://www.wireshark.org for more information
...
```

Possible to maybe check `--help` and if the string contains `Wireshark` to not try and detect it as a chess engine?

**Comment by samcv** [comment]
If I comment out `ENGINE("ethereal", "uci", "us", 3389, AUTO_DETECT, None),` from `lib/pychess/Players/engineList.py` then there are no issues and I can use pychess properly. If I don't do this, it gets stuck detecting engines and doesn't let me do anything.

**Comment by gbtami** [comment]
Ethereal is a popular and real strong chess engine. See https://www.chessprogramming.org/Ethereal
I suggest you to rename ethereal to wireshark instead. See https://en.wikipedia.org/wiki/Wireshark

**Comment by gbtami** [comment]
Fix will be available in next release. Thx for reporting it!
