### ISSUE TITLE
Right side panel completely missing

### ISSUE THREAD

**Issue by aatanasovski14** [pychess/pychess#1884]
I just upgraded pychess to latest version (python3-pychess_1.0.2-1_all.deb).
Right side panel is completely missing even if its set to show on view contex menu, also there is no side panels tab in main settings. Before upgrade i was running old version from ubuntu repos (I'm on Linux Mint 20 Cinn)
I get tease errors in console

>(pychess:27788): Gtk-WARNING **: 02:02:07.135: Can't set a parent on widget which has a parent
>
>(pychess:27788): Gtk-WARNING **: 02:02:12.502: Attempting to add a widget with type GtkEntry to a container of type GtkBox, >but the widget is already inside a container of type pychess+widgets+ChatView+ChatView, please remove the widget from its >existing container first.

![Screenshot from 2020-11-27 01-56-14](https://user-images.githubusercontent.com/73353551/100399912-e73f3f00-3054-11eb-8184-09dbe65a8a8d.png)
![Screenshot from 2020-11-27 01-55-42](https://user-images.githubusercontent.com/73353551/100399915-ec03f300-3054-11eb-9fd0-0476b413239b.png)

**Comment by gbtami** [comment]
Sidepanel dividers are draggable with mouse. Look at to the right side!
![https://i.imgur.com/4GHP3nr.png](https://i.imgur.com/4GHP3nr.png)

**Comment by aatanasovski14** [comment]
Haha yes, thank you, i was able to pull it out from the side, but as you can see on my screenshot by default it was completely flat line i think there should be something to suggest that there is a sidepanel

**Comment by gbtami** [comment]
Agreed :)
