### ISSUE TITLE
Issue with UCI wtime/btime when playing classical game ?

### ISSUE THREAD

**Issue by pelican74** [pychess/pychess#1885]
I am testing my engine for the classical x min / y moves clock setup with the UCI protocol.
It seems the engine side gets a wrong time left along the game.
Example (with 4 min / 40 moves), engine playing whites gets the following go command:

> position startpos
> go wtime **24000** winc 0 btime 240000 binc 0 movestogo 40
> 

Etc.
Engine playing blacks gets the following:

> position startpos moves a2a3
> go wtime 240000 winc 0 btime **23985** binc 0 movestogo 40
> 

Did I miss something ?
PyChess 1.0.0 under W10

**Comment by gbtami** [comment]
These partial log lines proves nothing to my eyes. Can you provide complete examples please?
You can start pychess with command line arguments like:
pychess --log-debug --log-view
This way you can use the menu View -> Log Viewer

**Comment by gbtami** [comment]
Btw it would be better to try it with latest sources from https://github.com/pychess/pychess

**Comment by pelican74** [comment]
Hello,
I 100% agree, but I am on Windows, so relied on the installer from the
download site.
In the meantime,  I could get my engine on a linux system and pychess
1.0.2. Pb seems gone with this version.
So looks I do need to upgrade... Any plan for a 1.0.2 Win kit ? Or some
how-to to upgrade a Win installation ? I must say I am not very
familiar with python nor git.
Thanks

Le ven. 4 déc. 2020 à 16:15, Bajusz Tamás <notifications@github.com> a
écrit :

**Comment by gbtami** [comment]
Yes, I definitely will create a new 1.0.3 soon.
