### ISSUE TITLE
Close chess game window after loading external game from URL

### ISSUE THREAD

**Issue by jmeme31** [pychess/pychess#1886]
I am in ubuntu 20.04.
![Capture d’écran du 2020-12-17 16-40-56](https://user-images.githubusercontent.com/19476953/102509298-ad2af100-4086-11eb-973d-3f311fbfe544.png)

I have loading a external chess game from URL: I can close the chess game window.
I move something in the window  : I cant close the window. I must close the application.
![Capture d’écran du 2020-12-17 16-37-06](https://user-images.githubusercontent.com/19476953/102508883-2f66e580-4086-11eb-9b74-c04b1a231f09.png)

**Comment by gbtami** [comment]
Works for me. Please give step by step description how to reproduce this.
