### ISSUE TITLE
Chessboard doesn't show on bunsenlabs openbox

### ISSUE THREAD

**Issue by blizzn** [pychess/pychess#1887]
Hi, I am installing the newest version 1.02 of pychess on my uptodate bunsenlabs Lithium. Everything worked fine and the gui showed but no chessboard shows. I hear the sound of it building it up when I start a game, but no chessboard.

**Comment by gbtami** [comment]
Do you have all dependencies installed?
https://github.com/pychess/pychess/blob/master/INSTALL#L30

**Comment by blizzn** [comment]
I have to check but it's the same problem installing it from apt

**Comment by gbtami** [comment]
The board and pieces (.svg files) are drawn with Cairo Python3 bindings, so idk.
You should try to start it from command line using arguments --log-debug --log-view
This way you can access/view the logs from the main menu.

**Comment by blizzn** [comment]
I installed cinnamon desktop pychess from repository then pychess from github and now its working even on openbox

**Comment by gbtami** [comment]
Maybe cinnamon installed something needed to run pychess and not installed by openbox before.
I use Xfce  and never faced anything similar myself. If you can track down what package was needed and not listed in dependencies, it would be nice :)

**Comment by blizzn** [comment]
I don't know how to. I'm more of a install full distro if something doesn't work kinda guy.
