### ISSUE TITLE
Scoutfish and ChessDB external binaries

### ISSUE THREAD

**Issue by mike4802** [pychess/pychess#1892]
Got pychess running my Mac (Catalina 10.15.7) with no issues from 1.0.3 release.  Thanks for `req.txt`, I used that in my Python 3.9.2 venv along with the brew packages, all noted in `pychess/INSTALL`.

The auto-download function doesn't work for scoutfish or chess_db on a Mac.  Therefore, the "Openings" view in the database tab is empty, which is a great study tool.

So, in order to get the openings view to work, I downloaded and compiled both scoutfish and chess_db from source and put the new executables in some folder relative to pychess.   From the code, it would appear that `./scoutfish` means the relative local directory.  But tried to copy the scoutfish binary into the ./external folder and the root folder of the main pychess binary.  Neither were successful.

So I went in and modified `lib/pychess/external/scoutfish.py` and `lib/pychess/external/chess_db.py` to hardcode the engine location.  Here's an example, and I did the exact same change for chess_db (i.e. called parser) :

```
class Scoutfish:
    def __init__(self, engine=''):
        if not engine:
            engine = './scoutfish'
```

changes to:

```
class Scoutfish:
    def __init__(self, engine=''):
        #if not engine:
        engine = '/my/direct/path/to/compiled/binary/scoutfish'
```

Works great now! If there's a better way, fantastic, but this gets me going with a great feature to study games.

![pychess-works](https://user-images.githubusercontent.com/34842871/112766074-2a4af800-8fde-11eb-94cb-15339a08aa04.png)

**Comment by gbtami** [comment]
Thx, great news!
I think you don't have to modify any .py files at all.
On Linux the place of these files is ~/.local/share/pychess/engines/
I hope this should exist on Mac as well.

**Comment by mike4802** [comment]
Yes, now I see the folder called `/Users/[account]/.local/share/pychess/engines` on Mac.  Looks like that's where it tried to download the pre-compiled binaries too based on the dates.

However, the binaries are not for Mac.  This is what it tried to download: 

```
# file parser_x64-modern
parser_x64-modern: ELF 64-bit LSB executable, x86-64, version 1 (SYSV), dynamically linked, interpreter /lib64/ld-linux-x86-64.so.2, for GNU/Linux 2.6.24, BuildID[sha1]=b0e75e9cb07357408a29e5dbfebedac205337174, not stripped

# file scoutfish_x64-modern 
scoutfish_x64-modern: ELF 64-bit LSB executable, x86-64, version 1 (SYSV), dynamically linked, interpreter /lib64/ld-linux-x86-64.so.2, for GNU/Linux 2.6.24, BuildID[sha1]=723f7f43a0dd266bad7b028174c14336d98a72d4, not stripped
```

My compiled binaries should work really well in that folder after I undo my change on the engine path.  Thank you!
