### ISSUE TITLE
Pychess engine bug

### ISSUE THREAD

**Issue by ghost** [pychess/pychess#1893]
I have tried version 0.30 of raven, but it gets stuck and doesn't play anymore.
https://github.com/sgriffin53/raven
with this engine too, at some point it freezes. version 0.5
https://github.com/gekomad/Cinnamon

I am with manjaro gnome

when I quit pychess, the engine processes are still running in the background.

**Comment by gbtami** [comment]
What version of pychess are you useing? How you installed it?
Are these engines work OK in cutechess/Xboard/console?

**Comment by ghost** [comment]
I use the latest version of pychess.
I installed pychess with pamac.
I installed the engines in pychess in the engine menu then new.

I did not test the engines in other interface.

**Comment by gbtami** [comment]
What is the version number of "latest"?

**Comment by ghost** [comment]
![Capture d’écran du 2021-04-15 18-23-48](https://user-images.githubusercontent.com/77933011/114904089-c450d400-9e17-11eb-9e77-893dc45826dc.png)

**Comment by gbtami** [comment]
Try to run some raven vs cinnamon engine matches in cutechess/Xboard to let us see they are OK.
You can start pychess with command line arguments --log-debug --log-viewer
Then in the main menu you will be able to open the log window. Maybe it will give us some more info.

**Comment by ghost** [comment]
it comes from the engines, they are too old and no longer maintained.
