### ISSUE TITLE
some pychess features requre further permission in order to download external components

### ISSUE THREAD

**Issue by gerikis** [pychess/pychess#1895]
I got this message upon startup . 
I'm on Linux  , installed pychess with package manager . 
version : Steinitz 1.0.3

I tried solving the problem by installing for example "timestamp" . 
```
[root🎩lhost ~]$ pip install timestamp
Collecting timestamp
  Downloading timestamp-0.0.1.tar.gz (637 bytes)
```
This did not solved the message regarding missing timestamp. 

Have no idea what can I do .

**Comment by gbtami** [comment]
Why do you think it needs installing timestamp?
Anyhow, this dialog is there because these stuff has no linux  packages at all. So pychess have to download it for you. But it don't want to do it silently without your explicit permissions. 
Just click those checkboxes and pychess will be happy :)

**Comment by gerikis** [comment]
Thanks for the answer . I tried clicking ok , but every time showing the same message . I can omit this by checking the checkbox "do not ask" , but I want to have those . 
If I download manually , where can I put , so pychess will able to locate ?

**Comment by gbtami** [comment]
If you click all of those checkboxes pychess will download the needed binaries for you into ~/.local/share/pychess/engines/

**Comment by gerikis** [comment]
Ok . Great I see in that dir : files 
```
lazygull.log
parser_x64-modern
scoutfish_x64-modern
timestamp_linux_2.6.8
```
Is this right ?
problem is that pychess does not inform me that the features it need already fulfilled . 
Still showing same message at startup .

**Comment by gbtami** [comment]
Click "do not ask" if you don't want to be asked again.

**Comment by gerikis** [comment]
Ok. I know , just wonder why pychess does not know those features are already there.

**Comment by gbtami** [comment]
Pychess is far from being a perfect chess GUI. It def has several weak points we should enhance/fix.
Telling the truth it got very little updates after I started to work on a chess variant server project https://github.com/gbtami/pychess-variants

**Comment by gerikis** [comment]
I love pychess . Its very great , I think a lots of peoples playing chess with pychess
