### ISSUE TITLE
pièces chess

### ISSUE THREAD

**Issue by ghost** [pychess/pychess#1899]
Hello

It's been several years since the themes have been updated.
Would it be possible to put new themes of better quality?

I have some examples here on the site of lichess:
https://github.com/ornicar/lila/tree/master/public/piece

**Comment by gbtami** [comment]
Pull requests are welcome! :)

**Comment by ghost** [comment]
I have to create a request in the pull requests section ?

**Comment by ghost** [comment]
thank you for the new pieces

**Comment by gbtami** [comment]
Courtesy of @masoudd :)
