### ISSUE TITLE
Pychess engine uses only one core

### ISSUE THREAD

**Issue by pychess** [pychess/pychess#190]
Original [issue 190](https://code.google.com/p/pychess/issues/detail?id=190) reported by [andreas930](https://code.google.com/u/111122900975194528984/) 2007-08-16

**What steps will reproduce the problem?**
1. Run Pychess on dual-or multicore CPU's
**2.**
**3.**

**What is the expected output? What do you see instead?**
Pychess engine will most of the time only use one core of the CPU

**What version of the product are you using?**
0.6.0.final

Did you use an installed version of PyChess or did you run in from a
tarball/svn?
Installed

**Please provide any additional information below.**

**Comment by pychess** [comment]
Original [comment 1.](https://code.google.com/p/pychess/issues/detail?id=190#c1) posted by [gbtami](https://code.google.com/u/gbtami/) 2007-08-16

http://mail.python.org/pipermail/python-list/2004-October/285689.html

**Comment by pychess** [comment]
Original [comment 2.](https://code.google.com/p/pychess/issues/detail?id=190#c2) posted by [lobais](https://code.google.com/u/lobais/) 2007-08-17

Yeah, the GIL won't let us do it. At least not with threads.
However, the GIL has already forced us to put PyChess Engine in a separate process,
so I guess splitting it in multiple processes would be possible as well.
It does cut some performance of course to talk between processes, but I guess it is
doable.
- removed label: Defect
- added label: Enhancement

**Comment by pychess** [comment]
Original [comment 3.](https://code.google.com/p/pychess/issues/detail?id=190#c3) posted by [gbtami](https://code.google.com/u/gbtami/) 2007-08-17

I think it's not a big problem. Pychess is an entertainment program, not a scientific
or like.

**Comment by pychess** [comment]
Original [comment 4.](https://code.google.com/p/pychess/issues/detail?id=190#c4) posted by [lobais](https://code.google.com/u/lobais/) 2007-08-18

Indeed, but perhaps somebody would find it interesting to implement.
There is a guide on parallel tree search on
http://www.cis.uab.edu/info/faculty/hyatt/search.html (The fourth link in Wiki ->
Links -> On Chess Programming.
- changed status to: Accepted
- removed label: Medium
- added label: Low

**Comment by pychess** [comment]
Original [comment 5.](https://code.google.com/p/pychess/issues/detail?id=190#c5) posted by [gbtami](https://code.google.com/u/gbtami/) 2007-09-11

An open letter to Guido van Rossum: Mr Rossum, tear down that
GIL!(http://blog.snaplogic.org/?p=94)

Guido's answare: It isn't Easy to Remove the GIL
(http://www.artima.com/weblogs/viewpost.jsp?thread=214235)

And a free lib if someone want to work on paralellizing pychess:
http://www.parallelpython.com/

**Comment by pychess** [comment]
Original [comment 6.](https://code.google.com/p/pychess/issues/detail?id=190#c6) posted by [lobais](https://code.google.com/u/lobais/) 2007-09-11

If we wanted to implement it using processes, we would have to send a lot of data
through and from, in order to talk with the transpositiontable.
Do you think this could in any way be made efficient?

**Comment by pychess** [comment]
Original [comment 7.](https://code.google.com/p/pychess/issues/detail?id=190#c7) posted by [gbtami](https://code.google.com/u/gbtami/) 2007-09-22

You are right. Maybe paralellizing and running the pychess engine in IronPython is
the way to go.

**Comment by pychess** [comment]
Original [comment 8.](https://code.google.com/p/pychess/issues/detail?id=190#c8) posted by [lobais](https://code.google.com/u/lobais/) 2007-09-22

Yeah.. Ironpython/Jython would be interesting indeed, but it would open for a lot of
temptations in the direction of using more and more C#/Java features..

What about having the transpos in a database.. Couldn't that actually be fairly
efficient..

**Comment by pychess** [comment]
Original [comment 9.](https://code.google.com/p/pychess/issues/detail?id=190#c9) posted by [lobais](https://code.google.com/u/lobais/) 2007-12-31

Uh, just found out, that Rybka uses processes rather than threads:
http://rybkachess.com/index.php?auswahl=FAQ+for+v+2.x

**Comment by pychess** [comment]
Original [comment 10.](https://code.google.com/p/pychess/issues/detail?id=190#c10) posted by [lobais](https://code.google.com/u/lobais/) 2007-12-31

These are some interesting libraries: http://wiki.python.org/moin/ParallelProcessing

**Comment by pychess** [comment]
Original [comment 11.](https://code.google.com/p/pychess/issues/detail?id=190#c11) posted by [lobais](https://code.google.com/u/lobais/) 2008-01-01

Especially this library, POSH - http://poshmodule.sourceforge.net/ - which places
objects in shared memory, seems to do exactly what we need.

**Comment by gbtami** [comment]
http://doc.pypy.org/en/latest/stm.html
