### ISSUE TITLE
repetition triple

### ISSUE THREAD

**Issue by ghost** [pychess/pychess#1903]
pychess does not support triple repetition

exemple:

1. e3 e6 2. Ke2 Ke7 3. Ke1 Ke8 4. Ke2 Ke7 5. Ke1 Ke8 6. Ke2 Ke7 7. Ke1 Ke8 8.
Ke2 Ke7 9. Ke1 Ke8 0-1

pychess should have stopped the game

**Comment by gbtami** [comment]
See https://github.com/pychess/pychess/issues/1401
