### ISSUE TITLE
bug analysis

### ISSUE THREAD

**Issue by ghost** [pychess/pychess#1904]
when I click on analyze the game, I don't select the color of the analysis boxes, they color them anyway.

![Capture d’écran du 2021-05-27 10-43-59](https://user-images.githubusercontent.com/77933011/119795619-edfe2000-bed8-11eb-8fb0-fa4ebe9af324.png)

![Capture d’écran du 2021-05-27 10-44-39](https://user-images.githubusercontent.com/77933011/119795638-f35b6a80-bed8-11eb-92e0-03dc1f33a796.png)

**Comment by gbtami** [comment]
Every setting have to have a meaningful default. You can change them and your changes will be used next time.

**Comment by ghost** [comment]
I don't want to insist, but there is really a bug.
the arrow of the analysis doesn't want to disappear anymore.

![Capture d’écran du 2021-05-31 12-41-17](https://user-images.githubusercontent.com/77933011/120181722-bf03e900-c20d-11eb-94f0-f1bc75a3b67e.png)

**Comment by gbtami** [comment]
That can be switch on/off in the menu View -> Hint Arrow.

**Comment by ghost** [comment]
oupps, I never paid attention.
Thank you,

![kisspng-smiley-thumb-signal-emoticon-clip-art-smily-5b4984d8c3ca23 307600191531544792802](https://user-images.githubusercontent.com/77933011/120193611-e910d780-c21c-11eb-8848-87c2b677e5e3.png)
