### ISSUE TITLE
can't change time control.

### ISSUE THREAD

**Issue by MandiYang** [pychess/pychess#1910]
Can't edit time controls or variants on pychess 1.0.3 
There was no error output on the terminal. 

I am using Ubuntu 20.04. Check the video in error.zip for more info, it was hard for me to explain what happend.
Info:
```
PyChess Steinitz 1.0.3 git 
Command line args: 'None'
Platform: Linux-5.4.0-89-generic-x86_64-with-glibc2.29
Python version: 3.8.10
Pyglib version: 3.36.1
Gtk version: 3.24.20
```

[error.zip](https://github.com/pychess/pychess/files/7448861/error.zip)

**Comment by MandiYang** [comment]
@gbtami, edited issue. Look at the updated version. Now the video in the error.zip explains the problem.

**Comment by gbtami** [comment]
Works for me on default 20.04 XUbuntu install. Maybe your config (window manager, theme, anything) is not standard.

**Comment by MandiYang** [comment]
@gbtami, How to check that?

**Comment by gbtami** [comment]
If you installed your OS, you have to know it. If someone helped you, you should ask that guy.

**Comment by MandiYang** [comment]
Not very sure that is my OS problem because the older version works...

**Comment by MandiYang** [comment]
@gbtami Not very sure that is my OS problem, can you check the code of pychess?

**Comment by gbtami** [comment]
As I mentioned above, it works for me on default install.

**Comment by MandiYang** [comment]
But that doesn't mean that pychess actually works for all people, you don't need to help me more because I think it is hopeless now so I will try to find another chess client :(

**Comment by gbtami** [comment]
I never said that pychess "works for all people". Unfortunately i have no time to provide user support.
