### ISSUE TITLE
"Atomic" Analysis not working

### ISSUE THREAD

**Issue by Notproffesionalcoder** [pychess/pychess#1913]
Even though we can play moves in the analysis but the engine cannot be turned on please fix also it is  only for atomic engine

**Comment by Notproffesionalcoder** [comment]
Edit not always

**Comment by notruck** [comment]
Fairy-Stockfish added Atomic support in early 2021. The local analysis is provided by the WASM port of FairySF, which was based on an earlier version of FairySF (from August 2020). So, local engine analysis is limited to the built-in variants from that period. 

https://github.com/ianfab/stockfish.wasm

**Comment by gbtami** [comment]
This pychess project is the desktop GUI, not the PyChess variant site!
Engine suggestion works OK for atomic here.
![https://i.imgur.com/ENGnqDR.png](https://i.imgur.com/ENGnqDR.png)

**Comment by Notproffesionalcoder** [comment]
@gbtami  But it does works online for me

Brave s my browser and os is Windows 10pro

**Comment by Notproffesionalcoder** [comment]
Could you solve this for online

**Comment by gbtami** [comment]
This repo is for desktop pychess GUI. It has nothing to do with pychess site.
Don't spam it with unrelated issues, please! Thx.
