### ISSUE TITLE
Gtk-WARNING Can't set a parent on widget which has a parent, PyChess 1.0.3 (latest) Python 3.9 Ubuntu 21.04

### ISSUE THREAD

**Issue by yuribudilov** [pychess/pychess#1919]
Gtk-WARNING **: 15:07:00.787: Can't set a parent on widget which has a parent

Ubuntu 21.04 Python 3.9
When I start ./pychess on command line I get above warning.

PyChess 1.0.3, appears to work OK, should I ignore this warning?

thank you

**Comment by gbtami** [comment]
Yes, you can ignore it. It is harmless.
