### ISSUE TITLE
I pit Stockfish against itself with an unbalanced setup, and the game didn't start

### ISSUE THREAD

**Issue by flarn2006** [pychess/pychess#1923]
Here's the settings I was using:

**White:** stockfish_14_x64_ssse Lv20
**Black:** stockfish_14_x64_ssse Lv1
**Time control:** Untimed
**Chess Variant:** Normal chess

**Initial setup:**
![rnbqkbnr/pppppppp/8/8/8/8/PPPPPPPP/4K3 w KQkq - 0 1](https://user-images.githubusercontent.com/687313/138629948-9946f905-02c1-48f4-93ee-2d5de4de1483.png)

When I start the game, neither side moves. It also lets me drag White's pieces as if I was playing as White, but when I attempt to make a move, it just stays where I dropped it (whether or not it's the center of the square) and the square the piece started on remained black, after which I couldn't drag anything.

**Comment by gbtami** [comment]
Untimed will result infinite search by engines.

**Comment by flarn2006** [comment]
It works fine when I do it with a normal setup though.

**Comment by gbtami** [comment]
Works for me with latest release from https://github.com/pychess/pychess/releases
![https://i.imgur.com/Il1Y8Gp.png](https://i.imgur.com/Il1Y8Gp.png)

**Comment by flarn2006** [comment]
I'm on 1.0.3 as well. And the same thing happens even if I don't choose Untimed. Have you tried with Stockfish 14, like I'm using?

**Comment by hartwork** [comment]
I've been trying to reproduce the issue with Git `master`. What I find is that _some_ custom setups make _vanilla_ Stockfish 15.1 die, like this:

![Screenshot_20230319_044545](https://user-images.githubusercontent.com/1577132/226152431-2cae84da-6a10-4c10-9c10-73d04c58e85e.png)

It happens for e.g. setup "pawns plus king" (your screenshots) and "pawns plus king plus queen" (my screenshot) but not "all minus one rook". My guess is that @flarn2006 was using vanilla/plain Stockfish while @gbtami's shot says _Fairy_ Stockfish?

**Comment by gbtami** [comment]
Exactly. I tried it in console with official stockfish 15.1 and it crashed. Possible this is the limitation of using the built in nnue net default which was trained on positions available from standard chess starting position. Contrary, FairyStockfish doesn't ship with built in chess nnue net.  You have to download .nnue files if you want to use them from https://fairy-stockfish.github.io/nnue/

**Comment by hartwork** [comment]
@gbtami the thing is, people will use PyChess with plain Stockfish at least on Linux if we don't actively keep them from doing that from within PyChess. You marked the ticket as completed now. Please help me understand the idea behind that. Thanks!

**Comment by gbtami** [comment]
I played with this again a bit and noticed that if you don't remove white side castling rights from FEN like
`rnbqkbnr/pppppppp/8/8/8/8/PPPPPPPP/4K3 w KQkq - 0 1`
it will crash, but if you do it correctly `rnbqkbnr/pppppppp/8/8/8/8/PPPPPPPP/4K3 w kq - 0 1`, it doesn't.
So this issue is a duplicate of https://github.com/pychess/pychess/issues/1403
