### ISSUE TITLE
remote engine with plink.exe

### ISSUE THREAD

**Issue by arsalanses** [pychess/pychess#1924]
Hi, I'm Windows user and I have remote LAN server with stock-fish run on TCP protocol
I'd try to add engine [plink.exe](https://jerrygreenblog.wordpress.com/2016/08/26/linux-stockfish-chess-engine-as-remote-service/), but I get an error while trying to add plink as new engine :(
Is there any solution for that?
I try on "scid vs. pc" and it worked!

**Comment by gbtami** [comment]
There is no such feature in pychess.
