### ISSUE TITLE
How can I make a Linux build successfully?

### ISSUE THREAD

**Issue by im-coder-lg** [pychess/pychess#1926]
Hi,

I am a big fan of PyChess. Although I don't use it a lot, I like the GTK UI and I can't believe that you used Python for the whole app. That's unbelievable.
To be honest, I am not here for that. I want to know how you make app builds for Linux. I and a friend of mine on GitHub are working on a project and we can't build for Linux. I mean, I am well-versed with PyInstaller on Windows, but I have a Raspberry Pi, so I can't build for Linux on that, although it has a 64-bit processor(it kinda always works as 32-bit, as aarch64).
I want to know what software you use for packaging the app for Linux. I'd be grateful if you could help me with this!

**Comment by gbtami** [comment]
create_deb.sh and create_rpm_py3x.sh scripts are used to create .deb and .rpm packages.
You need all the dependencies described in INSTALL and python3-stdeb for .deb creation (and rpm for .rpm creation).

**Comment by im-coder-lg** [comment]
That's fine, but is it possible to edit the `setup.py` file?

**Comment by im-coder-lg** [comment]
So that I can configure it for my friend's project?

**Comment by gbtami** [comment]
Sry, but I don't understand your problem. What is your goal?

**Comment by im-coder-lg** [comment]
My goal is to know how to make Linux packages and binaries. I am asking, there's a `setup.py` file located in the source code root, can I edit that for my friend's project?

**Comment by gbtami** [comment]
There are .deb and .rpm packages in https://github.com/pychess/pychess/releases
Some other Linux distributions having other package formats are also provides pychess packages. See https://pychess.github.io/download/

Different distribution use different package formats. If you want to learn about them, I suggest to read packaging docs of your target Linux distribution.
If you know how setup.py works you can edit it of course as well.
