### ISSUE TITLE
Is Pychess active?

### ISSUE THREAD

**Issue by im-coder-lg** [pychess/pychess#1927]
I haven't seen any commits; are you shifting PyChess to a new project or stopping development altogether?

**Comment by gbtami** [comment]
This project is more or less in maintenance mode after I started https://github.com/gbtami/pychess-variants

**Comment by im-coder-lg** [comment]
Wdym? Are you shifting PyChess soon?

**Comment by gbtami** [comment]
What do you mean by "shifting"?

**Comment by im-coder-lg** [comment]
Moving the project to another repo.

**Comment by gbtami** [comment]
No.
