### ISSUE TITLE
proposal background

### ISSUE THREAD

**Issue by ghost** [pychess/pychess#1928]
hello
why don't you replace the backgrounds by the ones you propose on your pychess site?
![Capture d’écran du 2022-01-07 19-50-24](https://user-images.githubusercontent.com/77933011/148593271-09d855d8-43a5-4195-ad7c-66ae522c8081.png)

it could modernize your software.

**Comment by gbtami** [comment]
PRs are welcome.

**Comment by masoudd** [comment]
Which one is missing? Doesn't this one has more options? You can set any colors or choose from these pictures:

aluminium
brazilwood
cherry
fritz
lanta
lapis
mahogony
maple
marble
sand
sandlewood
slate
wood

**Comment by ghost** [comment]
I think it looks a little dated. It would be nice to refresh the whole thing.
To put some nicer backgrounds.

**Comment by masoudd** [comment]
What would that look like? Like some presets of colors?
