### ISSUE TITLE
double pieces

### ISSUE THREAD

**Issue by ghost** [pychess/pychess#1930]
in the last version, some parts are duplicated.

![image](https://user-images.githubusercontent.com/77933011/148940013-951fa257-ae89-484e-b14f-827cff3a71a0.png)

**Comment by masoudd** [comment]
That is because two versions of Leipzig piece theme are included. The first one is in SVG format, the second one is in ttf (TrueType Font) format. So the program is not presenting a single thing two times.

Now is it necessary to have two different versions of a single piece theme? I don't know.

**Comment by gbtami** [comment]
They are there for historical reasons only. Maybe it is time to remove all the .ttf piece sets I think.

**Comment by masoudd** [comment]
I don't really like any of them so I don't have any feelings about it either way but some of them don't have SVG version. Is it ok to remove them all?

**Comment by gbtami** [comment]
I think we already have more than enough .svg piece sets, so yes, it is OK to remove them completely.
