### ISSUE TITLE
Choose depth of analysis

### ISSUE THREAD

**Issue by ghost** [pychess/pychess#1934]
it would be nice if we could set the depth.
Here we can only set how long it will analyze.
![image](https://user-images.githubusercontent.com/77933011/152600150-52b8781f-6f95-4d6a-9dcf-345ef6bb5b13.png)

**Comment by TheRedLancer** [comment]
I think I can make this happen!

**Comment by gbtami** [comment]
Fixed via https://github.com/pychess/pychess/pull/1939
