### ISSUE TITLE
bug pièces

### ISSUE THREAD

**Issue by ghost** [pychess/pychess#1935]
I downloaded the latest main update, but some parts are missing.

I unpacked the archive into a folder, run the pychess desktop file, and saw this:

![Capture d’écran du 2022-02-18 14-27-11](https://user-images.githubusercontent.com/77933011/154691823-04c71606-ee2c-4239-a712-36ac53b8ff9d.png)

![Capture d’écran du 2022-02-18 14-26-30](https://user-images.githubusercontent.com/77933011/154691843-d04448bc-c482-4eee-8f31-497d606d6678.png)

**Comment by gbtami** [comment]
If you want to use pychess from sources, you have to run create_theme_preview.sh (or -win.bat)

**Comment by ghost** [comment]
when I do the command ./pychess, it works, but it is not in French.

the best, I installed it by doing: sudo phyton 3 setup install, and it is simply updated the old version.

thanks,
