### ISSUE TITLE
engine in memory blocked

### ISSUE THREAD

**Issue by ghost** [pychess/pychess#1944]
when we make several games with an engine, then we close pychess, the process remains loaded in the memory.

![Capture d’écran du 2022-05-17 00-13-05](https://user-images.githubusercontent.com/77933011/168691817-3675f825-8ad2-47e9-9940-464dc8f59d47.png)

![Capture d’écran du 2022-05-17 00-13-56](https://user-images.githubusercontent.com/77933011/168691850-84d3df20-a1b6-4077-a584-98d68b544359.png)

**Comment by gbtami** [comment]
Can you reproduce this with current git?
See https://github.com/pychess/pychess/issues/1918

**Comment by ghost** [comment]
I use version 1.0.3 with the latest updates.
by doing python3 setup.py install to install the latest patches.

I am using manjaro gnome.
