### ISSUE TITLE
Can't open pychess

### ISSUE THREAD

**Issue by ghost** [pychess/pychess#1948]
When I try to open it by clicking in app icon the nothing happens.
opening with terminal gives this error
```
Traceback (most recent call last):
  File "/usr/bin/pychess", line 197, in <module>
    from pychess.System import conf
  File "/usr/lib/python3/dist-packages/pychess/System/conf.py", line 27, in <module>
    configParser.read_file(fh)
  File "/usr/lib/python3.10/configparser.py", line 719, in read_file
    self._read(f, source)
  File "/usr/lib/python3.10/configparser.py", line 1071, in _read
    raise DuplicateSectionError(sectname, fpname,
configparser.DuplicateSectionError: While reading from '/home/user/.config/pychess/config' [line 224]: section 'FICS' already exists
```

It was working earlier and then when I open it yesterday it didn't open
I tried removing and reinstalling it. But didn't work.

**Comment by gbtami** [comment]
It seems from the error message that your /home/asmit/.config/pychess/config file is broken somehow. Try to delete the duplicated FICS section. Or delete the file itself (in this case you have to redo your settings, if there was anything, of course).

**Comment by ghost** [comment]
Thanks it is working now.
