### ISSUE TITLE
Ubuntu apt install pychess does not install stockfish

### ISSUE THREAD

**Issue by RavanH** [pychess/pychess#1951]
Hi, not sure why the dependency is ignored but on Ubuntu 22.04 where pychess 1.0.0-1.2 is available, the package stockfish does not get installed. The dependency tree gets built, but it is not listed there.

When launching pychess from command line, I get:

```
$ pychess
/usr/games/pychess:17: PyGIWarning: Gtk was imported without specifying a version first. Use gi.require_version('Gtk', '4.0') before import to ensure that the right version gets loaded.
  from gi.repository import Gtk, Gdk
Failed to create splash screen
ERROR: Not all dependencies installed! You can find them in INSTALL
Namespace Gdk is already loaded with version 4.0
```

Downloaded pychess 1.0.3 deb from github and installed it with `dpkg -i` and then it IS mentioned as a missing dependency (preventing package configuration after install) :

```
dpkg: vereistenproblemen verhinderen de configuratie van python3-pychess:
 python3-pychess is afhankelijk van stockfish; maar:
  Pakket stockfish is niet geïnstalleerd.
```
(that's in Dutch saying pychess is dependant on stockfish but stockfish package is not installed)

Manual installation of stockfish, then re-sintallation of pychess fixes the issue.

I checked the .deb packages of different versions and all mention stockfish in the Depends list in the Control file. Not sure what more is needed...

**Comment by gbtami** [comment]
We are not responsible for official distribution packages. They are usually outdated by years!
I think you should report this in Ubuntu/Debian bug tracker instead.

**Comment by RavanH** [comment]
Hi, indeed it turns out to be a known bug here https://bugs.launchpad.net/ubuntu/+source/pychess/+bug/1959523
