### ISSUE TITLE
Show sidepanels not working 

### ISSUE THREAD

**Issue by snoopchallenge** [pychess/pychess#1956]
Pressing show sidepanels currently does not show the right side panel on windows 11 with version 1.0.3

**Comment by gbtami** [comment]
Possible you have to use the resizers to let them appear again.

**Comment by snoopchallenge** [comment]
thank you

**Comment by Erquint** [comment]
I urge reopening this for following reasons:
1. The sidepanel seemingly vanishing out of existence without user's intention is still a bug, despite it still being there logically.
    - Should ultimately be fixed after determining the cause.
2. While the solution provided by @gbtami is helpful, it would seem outside a typical user's common sense intuition to discover on their own and the interface provides no hint towards it.
    - At least make a fat outline or a big red arrow flash when the user desperately toggles the option on and off.
    - It could be argued for general UX considerations that a panel shouldn't even allow complete collapse without something to remain there as a reminder of its existence or destroying the panel subwindow entity, so that it can be recreated with that aforementioned checkbox toggle.

Windows 10 on a small 4:3 display here.
This happened to me on a 1st or 2nd launch after installing and configuring.
The edge of the sidepanel isn't even sticking out — just fully flush with the window border.
I presume the layout bug occurs on window initialization upon process launch.

If needed, I might be able to try catching and logging it.
