### ISSUE TITLE
run pychess

### ISSUE THREAD

**Issue by ghost** [pychess/pychess#1957]
Hello,

Can I run pychess without installing it?

What is the procedure ?
I am under windows 11

**Comment by masoudd** [comment]
Hello,

No you need to install it. Download .msi files from here https://pychess.github.io/download/
This is the latest version currently available:
[pychess-1.0.0-win32.msi](https://github.com/pychess/pychess/releases/download/1.0.0/pychess-1.0.0-win32.msi)

**Comment by gbtami** [comment]
Use the latest release https://github.com/pychess/pychess/releases/download/1.0.3/PyChess-1.0.3-mingw.msi instead.
