### ISSUE TITLE
Plans to migrate off of distutils?

### ISSUE THREAD

**Issue by hartwork** [pychess/pychess#1962]
Hi!

I noticed that `setup.py` here still uses `distutils` which is very dead. Are there plans to migrate off of it? I can help with a quick migration to setuptools for now (before you make the step to something more modern later) if welcome.

Best, Sebastian

**Comment by gbtami** [comment]
The thing is we use cx_Freezee to build windows .msi installer. Creating requirements.txt for pip would be nice for sure.
Unfortunately my windows MSYS2 install is completely broken atm, but pychess can be used in place without setup.py build/install if all dependencies are installed.
Any contribution is highly welcome!
