### ISSUE TITLE
Improving approach to pre-commit

### ISSUE THREAD

**Issue by hartwork** [pychess/pychess#2006]
Hi!

I saw that 1cf7fd31f733c79a25fd0aba6a86a5cb533f983d introduced black, flake8 and pyupgrade — very nice. I would want to hear your opinion on these suggestions for improval:

- Black is currently configured for Python 3.11 while the project supports as old as Python 3.7 elsewhere, so that is out of sync. I suggest we re-configure Black to target Python 3.7. A can make a pull request if agreed.
- There is no CI yet to enforce the same pre-commit checks that developers run locally in CI. I have built that integration a few times elsewhere — e.g. at https://github.com/hartwork/git-delete-merged-branches/blob/master/.github/workflows/pre-commit.yml — and would offer adding similar CI here. Please be aware that any violation of pre-commit checks will then cause red CI. I consider that a feature (especially for pull requests) but please be aware. Should I make a pull request?

Best, Sebastian

**Comment by gbtami** [comment]
I added "language_version" because  I read this before: https://black.readthedocs.io/en/stable/integrations/source_version_control.html
After reading https://black.readthedocs.io/en/stable/faq.html#which-python-versions-does-black-support I'm a bit confused, but if I understand it correctly we can remove "language_version" completely from .pre-commit-config.yaml

Adding CI for pre-commit checks seems a good idea. PR is welcome.

**Comment by hartwork** [comment]
> I added "language_version" because I read this before: https://black.readthedocs.io/en/stable/integrations/source_version_control.html After reading https://black.readthedocs.io/en/stable/faq.html#which-python-versions-does-black-support I'm a bit confused, but if I understand it correctly we can remove "language_version" completely from .pre-commit-config.yaml

I had another look now: `language_version` is the version of Python used to run Black, not the version of Python for Black to target. For the latter, I found this now:

```console
# black --help
[..]
  -t, --target-version [py33|py34|py35|py36|py37|py38|py39|py310|py311]
                                  Python versions that should be supported by
                                  Black's output. By default, Black will try
                                  to infer this from the project metadata in
                                  pyproject.toml. If this does not yield
                                  conclusive results, Black will use per-file
                                  auto-detection.
[..]
```
So I believe we should:
- pass `--target-version py37` additionally and
- drop `language_version` as not needed.

What do you think?

> Adding CI for pre-commit checks seems a good idea. PR is welcome.

Good, let's see how much work is left to have it go green.

**Comment by gbtami** [comment]
Yes, agreed on both.
