### ISSUE TITLE
pychess no sound settings working

### ISSUE THREAD

**Issue by axet** [pychess/pychess#2008]
Hello!

I'm using pychess 1.0.3 on debian bookworm. I unable to disable all sounds. Using settings (Edit / Preferences) makes no changes. Also settings reset after app restarts.

**Comment by axet** [comment]
Same for master (f08c895169b2c2728cb6123db728b51a528fbc2c).

1) Unable to disable sounds
2) Settings are not preserved

**Comment by hartwork** [comment]
@axet for Git `master` I find that:
- The sound toggle state is persisted to file `~/.config/pychess/config` — good
- The sound toggle state does not affect the current running process — **bug**
- The sound toggle initial state is always "checked", no matter what the config file said — **bug**

Could you try pull request #2017 to see if it fixes things not just for me but also for you?

**Comment by axet** [comment]
Yep. Works. Thanks!

**Comment by hartwork** [comment]
@axet thanks for testing! :+1:
