### ISSUE TITLE
Login to FICS as guest not working for some guest usernames

### ISSUE THREAD

**Issue by axet** [pychess/pychess#2012]
Hello!

Login as guest not working if login name field is filled. Simply stuck.

I guess make field readonly when "Guest login" checked.

**Comment by hartwork** [comment]
Is this about FICS or ICC?

**Comment by axet** [comment]
FICS

**Comment by gbtami** [comment]
@axet is this with 1.0.3? Or can you reproduce this with git master as well?

**Comment by axet** [comment]
Master as well.

**Comment by gbtami** [comment]
I can't reproduce this.
It works for me like this.
Before I click on guest login:
![Képernyőkép – 2023-03-19 21-07-47](https://user-images.githubusercontent.com/479964/226206229-22a0492e-26a2-4a54-95de-060b26337e89.png)
after:
![Képernyőkép – 2023-03-19 21-08-29](https://user-images.githubusercontent.com/479964/226206259-ff66f56b-716e-4810-bbb8-d5c15ca48b10.png)

**Comment by hartwork** [comment]
I believe that I can reproduce it now and that we both misunderstood @axet. To reproduce:

1. Find `Menu > Game > Play Internet Chess`.
2. Ensure that checkbox `Log on as Guest` is checked.
3. Enter "hello123" for field `Name` (now looks like the screen shot below).
4. Push button `Connect`.
5. Watch the wait...

![Screenshot_20230319_232807](https://user-images.githubusercontent.com/1577132/226213870-4710ab15-9b67-4dd7-817e-67aa2106d437.png)

So guest name support is broken somehow. And I just learned why:

```console
# nc freechess.org 5000

             _       __     __                             __      
            | |     / /__  / /________  ____ ___  ___     / /_____ 
            | | /| / / _ \/ / ___/ __ \/ __ `__ \/ _ \   / __/ __ \
            | |/ |/ /  __/ / /__/ /_/ / / / / / /  __/  / /_/ /_/ /
            |__/|__/\___/_/\___/\____/_/ /_/ /_/\___/   \__/\____/ 
       ^^__                  _____________________                 _  _  _ 
      /  - \_               / ____/  _/ ____/ ___/   _            | || || |
    <|    __<              / /_   / // /    \__ \   (_)           |_______|
    <|    \               / __/ _/ // /___ ___/ /  _              \__ ___ /
    <|     \             /_/   /___/\____//____/  (_)              |___|_|
    <|______\                                                      |_|___|
     _|____|_        ======================================        |___|_|
    (________)         freechess.org  ----  54.39.129.129         (_______)
    /________\       ======================================       /_______\ 
                       (Login screen designed by Alefith)

   ****** Welcome to the Free Internet Chess Server at freechess.org ******

Webpage: http://www.freechess.org
Head admin : mattuc   Complaints to : complaints@freechess.org
Server location: freechess.org   Server version : 1.25.20

      If you are not a registered player, enter guest or a unique ID.
             (If your return key does not work, use cntrl-J)

login: 

      If you are not a registered player, enter guest or a unique ID.
             (If your return key does not work, use cntrl-J)

login: hello123

Sorry, names can only consist of lower and upper case letters.  Try again.

      If you are not a registered player, enter guest or a unique ID.
             (If your return key does not work, use cntrl-J)

login: 
```

To highlight the important part explicitly, its  this:

> ```
> Sorry, names can only consist of lower and upper case letters.  Try again.
> ```

So we'd need to validate the guest username against regex pattern `^[A-Za-z]+$` or so.

**Comment by axet** [comment]
Showing login error based on server error I would call a better error handling solution.

**Comment by hartwork** [comment]
@gbtami the fix works, very nice! :+1:
