### ISSUE TITLE
Unable to play second move with freechess.org as guest?

### ISSUE THREAD

**Issue by axet** [pychess/pychess#2014]
Hello!

I'm not sure if it is a PyChess or freechess.org issues.

When logged in as Guest. I unable to make second move playing online match.

First move works. Opponent responds. Then I unable to make any moves have to resign or timeout.

pychess-1.0.3

**Comment by hartwork** [comment]
Cannot confirm with FICS as guest for Git `master`. Far beyond move 2 now.

**Comment by gbtami** [comment]
@axet can you try to reproduce this using git master, please?

**Comment by axet** [comment]
Yep. Confirming. Not working.

Just started the game from Seek Graph and unable to make second move.

**Comment by hartwork** [comment]
On Windows or Linux? FICS and not ICC?

**Comment by axet** [comment]
Linux Debian Bookworm. FICS. Login as Guest. Non guest working fine.

ICC not connectin.

**Comment by axet** [comment]
Try click Seek Graph "masheen (Computer) 2726" Unrated.

**Comment by hartwork** [comment]
> Try click Seek Graph "masheen (Computer) 2726" Unrated.

Just did, no problems. Gentoo Linux here, Git `master`, FICS, log-in as guest.

**Comment by hartwork** [comment]
> ICC not connectin.

Works fine for me also. Maybe your ISP takes part here.

**Comment by axet** [comment]
https://youtu.be/YIOJ13FbkaA

It does not record a mouse, basically I click on piece and then on a free cell. Nothing.

**Comment by hartwork** [comment]
@axet thanks for the video. No idea what's going on here. @gbtami ?

**Comment by gbtami** [comment]
Haha. You accepted a Suicide variant game! :)

**Comment by axet** [comment]
As sadly it looks... we all did.  We all come here to die. Suicide club.

**Comment by hartwork** [comment]
> Haha. You accepted a Suicide variant game! :)

I did notice the change in rule set but I only now understand what it means to @axet's video: he'd have to take the pawn, there is no other move. So does that mean the ticket is a non-bug and just answered itself?

**Comment by gbtami** [comment]
Yes :)
