### ISSUE TITLE
Releasing 1.0.4_beta1 or 1.0.4 next?

### ISSUE THREAD

**Issue by hartwork** [pychess/pychess#2030]
Hi! :wave: 

It's been roughly two weeks since the release of 1.0.4_alpha1 without a storm of new bug reports. Either because the release did not get much attention (not unlikely, only Gentoo and LiGutOS [got it packaged](https://repology.org/project/pychess/history)) and/or the release was more stable than an "alpha release" could be expected. Maybe both?

So I am wondering, we should do the next round with 1.0.4_beta1 or with 1.0.4? What do you think?

Best, Sebastian

**Comment by gbtami** [comment]
Yea, if you don't want to fix more old issues for now, we can release 1.0.4 final I think.

**Comment by hartwork** [comment]
@gbtami not right now, let's do 1.0.4 then :+1:

**Comment by hartwork** [comment]
@gbtami would you be up for doing the 1.0.4 release?

**Comment by gbtami** [comment]
Sure. I will do it today.

**Comment by hartwork** [comment]
@gbtami cool! :+1:

**Comment by hartwork** [comment]
@gbtami thanks! [Bumped in Gentoo](https://github.com/gentoo/gentoo/commit/b9ebfbaef10f4740671c8bd90c6d2c929f8379bc) as well, let's see who else will join at https://repology.org/project/pychess/history .

**Comment by gbtami** [comment]
Great, and also thx for all of your help making this release possible!

**Comment by hartwork** [comment]
Updating status summary:
- [ ] ALT Linux is apparently working on updating (PR #2038).
- [ ] Arch had 1.0.4 marked as out of date already and I wrote a mail yesterday, let's see.
- [x] For openmamba I wrote an e-mail and they have updated to 1.0.4 by now.

**Comment by hartwork** [comment]
More updates:
- [x] For Debian, I have created issue https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1034523 on 2023-04-17, and it's been added to unstable on 2023-08-22
- [ ] For Exherbo, I wrote a mail on 2023-04-17.
- [ ] For Fedora, I wrote a mail on 2023-04-17.
- [x] For FreeBSD, I wrote a mail on 2023-04-17.
- [x] For Mageia, I wrote a mail on 2023-04-17.
- [x] For MidnightBSD, I wrote a mail on 2023-04-17 and it has been updated by now, see https://github.com/MidnightBSD/mports/commits/master/games/py-pychess
- [x] For SlackBuilds, I wrote a mail on 2023-04-17.
- [x] For Void, I wrote a mail on 2023-04-17 and it has been updated by now, see https://github.com/void-linux/void-packages/pull/43529
