### ISSUE TITLE
The string 'Observe %s' cannot be translated

### ISSUE THREAD

**Issue by clks01** [pychess/pychess#2063]
I have tried several language files, but none of them seem to be working.

Neither Korean nor Russian seems to be working.

**Korean** 
![](https://i.imgur.com/divJV4c.png)

**Russian** 
![](https://i.imgur.com/QM3PDDf.png)

There is also a question "RD" string cannot be found in the language translation template file

This place

![](https://i.imgur.com/Cx6iG5Q.png)

Source code source

![](https://i.imgur.com/JF0Lahm.png)

![](https://i.imgur.com/jPbw13d.png)

**Comment by gbtami** [comment]
Nice catch, thx!

**Comment by gbtami** [comment]
Regarding "Observe %s" translations, it appears in lib/pychess/widgets/gamenanny.py and seems OK in https://github.com/pychess/pychess/blob/master/lang/ru/LC_MESSAGES/pychess.po#L4447
but missing a space in https://github.com/pychess/pychess/blob/master/lang/ko/LC_MESSAGES/pychess.po#L4431
Idk what is wrong with the Russian, but the Korean should be fixed on https://app.transifex.com/gbtami/pychess/

**Comment by clks01** [comment]
There is no problem with the translation file, the translation template file has been translated

![Notepad2_qKZfcwyKH5](https://github.com/pychess/pychess/assets/16899557/11729ed5-a6cf-4f80-8a08-fa37ae210c32)


![ilRFjl5ZcV](https://github.com/pychess/pychess/assets/16899557/6939b4bf-22f6-4c14-a90d-10405933ebf8)



Windows/Linux all test, but it does not seem to work

**Comment by clks01** [comment]
> There is no problem with the translation file, the translation template file has been translated
> 
> ![Notepad2_qKZfcwyKH5](https://user-images.githubusercontent.com/16899557/239719195-11729ed5-a6cf-4f80-8a08-fa37ae210c32.png)
> 
> ![ilRFjl5ZcV](https://user-images.githubusercontent.com/16899557/239717951-6939b4bf-22f6-4c14-a90d-10405933ebf8.png)
> 
> Windows/Linux all test, but it does not seem to work

@gbtami
