### ISSUE TITLE
Windows CI now broken: ImportError: dynamic module does not define module export function (PyInit_lief)

### ISSUE THREAD

**Issue by hartwork** [pychess/pychess#2100]
Hi!

The Windows CI is now broken:
- Failing run: https://github.com/hartwork/pychess/actions/runs/5757717381/job/15609169695 — log [cx_freeze_bad.txt](https://github.com/pychess/pychess/files/12260894/cx_freeze_bad.txt)
- Previous successful run: https://github.com/hartwork/pychess/actions/runs/5687525779/job/15416020540 — log [cx_freeze_good.txt](https://github.com/pychess/pychess/files/12260892/cx_freeze_good.txt)

So far I found that:
- (cx_Freeze was bumped in MSYS in the mean time.)
- Under the hood the cx_Freeze import error is actually: `ImportError: dynamic module does not define module export function (PyInit_lief)`
- The issue is known as https://github.com/msys2/MINGW-packages/issues/17942 .

It is not yet clear to me whether there are options other than waiting for a fix from MSYS.

CC @gbtami 

```console
+ python3 setup.py bdist_msi --help
Traceback (most recent call last):
  File "D:/a/pychess/pychess/setup.py", line 17, in <module>
    from cx_Freeze import setup, Executable
  File "D:/a/_temp/msys64/mingw64/lib/python3.11/site-packages/cx_Freeze/__init__.py", line 12, in <module>
    from .command.build_exe import BuildEXE as build_exe
  File "D:/a/_temp/msys64/mingw64/lib/python3.11/site-packages/cx_Freeze/command/build_exe.py", line 14, in <module>
    from ..freezer import Freezer
  File "D:/a/_temp/msys64/mingw64/lib/python3.11/site-packages/cx_Freeze/freezer.py", line 32, in <module>
    from .parser import ELFParser, Parser, PEParser
  File "D:/a/_temp/msys64/mingw64/lib/python3.11/site-packages/cx_Freeze/parser.py", line 24, in <module>
    import lief
ImportError: dynamic module does not define module export function (PyInit_lief)
```

**Comment by gbtami** [comment]
I hope they will fix it.

**Comment by hartwork** [comment]
@Biswa96's fix at https://github.com/msys2/MINGW-packages/pull/17947 solved the problem and we are back at a green CI for Windows (https://github.com/pychess/pychess/actions/runs/5757734166), closing as fixed.
