### ISSUE TITLE
Pychess does not run on Ubuntu 22.04

### ISSUE THREAD

**Issue by raadnashmi** [pychess/pychess#2139]
Hi,
Thank you for providing such a great chess client Pychess, which I have enjoyed over the years.
Just to let you know that following installation of Ubuntu 22.04 I tried installing Pychess.  It installed.  However, Pychess does not run.  Pychess is version 1.0.0.  
On Ubuntu 22.04, Gnome is version 42.9.
The error message I get when trying to run Pychess is:
"/usr/games/pychess:17: PyGIWarning: Gtk was imported without specifying a version first. Use gi.require_version('Gtk', '4.0') before import to ensure that the right version gets loaded.
 from gi.repository import Gtk, Gdk
Failed to create splash screen
ERROR: Not all dependencies installed! You can find them in INSTALL
Namespace Gdk is already loaded with version 4.0".
Any help in this matter would be greatly appreciated.
Thanks.
Raad Nashmi

**Comment by gbtami** [comment]
Our latest release is 1.0.4
The truth is official pychess .deb packages are usually rather outdated as you can see on https://packages.ubuntu.com/search?keywords=pychess&searchon=names&suite=all&section=all

Because of this we provide unofficial .deb on https://github.com/pychess/pychess/releases

**Comment by raadnashmi** [comment]
Hi Bajusz,
Thank you for replying so quickly.  I greatly appreciate it.
However, I installed pychess 1.0.4 and it did not work again -- with the
same error message.
I noticed in the error message there was some reference to Gnome "Gtk was
imported without specifying a version first."  Also I have another laptop
with Ubuntu Mate 22.04 (with a different desktop environment, Mate) and
pychess 1.0.0 works just fine.
Sorry for the trouble.
Best regards,
Raad Nashmi

**Comment by gbtami** [comment]
"Gtk was imported without specifying a version first."  is just a warning not error. It is harmless.

On the other side this is a real problem:
"ERROR: Not all dependencies installed! You can find them in INSTALL"

**Comment by raadnashmi** [comment]
Hi Bajusz,
My mistake.  I downloaded Pychess version 1.0.4 again and it works just
fine.
I must have accidentally tried to install the older version last time.
So everything works beautifully again with version 1.0.4.
Thanks for all your help.
Much appreciated!
Raad

**Comment by kotenok2000** [comment]
There is no deb for 1.0.5. Only rpm.

**Comment by gbtami** [comment]
@kotenok2000 go to https://github.com/pychess/pychess/releases then click "Show all 15 assets."

**Comment by kotenok2000** [comment]
Thank you.
