### ISSUE TITLE
more chess variants request

### ISSUE THREAD

**Issue by Paelor** [pychess/pychess#2153]
more chess variants in pychess like how pysolfc does it for solitaire variants.

https://en.wikipedia.org/wiki/List_of_chess_variants

**Comment by gbtami** [comment]
Pychess original design limites the board size to 8x8 and inner data representation doesn't enable to support other new piece types as well, so adding more variants needs significant rewriting from the ground up.
But there is another project to play more variants https://github.com/gbtami/pychess-variants

**Comment by goyalyashpal** [comment]
hi @gbtami !

> original design limites the board size to 8x8
> inner data representation doesn't enable to support other new piece types

[mini-chess]: https://braincup.app/MiniChess "Braincup – Brain Training for Math, Memory & Focus"
[minichess]: https://en.wikipedia.org/wiki/Minichess "Minichess - Wikipedia"
[-]: https://braincup.app/SoloChess "Braincup – Brain Training for Math, Memory & Focus"
[solo-chess]: https://www.chess.com/solo-chess "Solo Chess - Capture All the Pieces on the Board - Chess.com"

it seems that even smaller board size with same standard pieces aren't supported either.  i recently stumbled upon smaller variants of chess, and i enjoyed them very much.  for example:

* *[mini-chess]* <sup>(see on [wikipedia][minichess])</sup>:
   5x5 board size and custom starting positions.  
   rules not allowed: pawn double-move, and castling.

   sample positions (handwritten in FEN):    
   ```fen
   kB3/1p1r1/5/P3K/N4 w
   ```

   currently it throws: `Needs 7 slashes in piece placement field.`.  

    "add 3 rows before" works with pychess.  but this lifts the constraints on moves, defeats the purpose of being "mini", also messes up the "against computer" mode and analyzer's live/post-play suggestions:

   ```fen
   ///kB3/1p1r1/5/P3K/N4 w
   ```

    <sup>the screenshots are according to <tt>kB3/1p1r1/5/P3K/N4/// w</tt></sup>
     <img width="345" alt="Image" src="https://github.com/user-attachments/assets/e7e1db09-20f4-42cf-8a06-0984f040a74d" /><img width="412" alt="Image" src="https://github.com/user-attachments/assets/2d22d767-283e-470b-860c-a2953f364338" />


* *[solo-chess]*:
   4x4 or 5x5 etc. board size with custom starting position.

   rules: 
     + every move must capture till single piece remains
     + no distinction of color in pieces
     + no piece can capture thrice or more
     + if king exists in starting - it must be the last remaining piece

   sample FEN:
   ```fen
   2B1/1KRN/1R2/4 w
   ```

* *local-variant of chess*:
   at my place, a slightly simpler chess is played, where rest all rules are same except that:
   - castling and pawn double-move are not allowed
   
   - pawn promotion rules are somewhat different 
   - kings are not in same column _(doable in pychess with custom `SetUp`)_

PyChess v1.1.0 on win10 os.
