### ISSUE TITLE
UnboundLocalError after engine-engine game finished

### ISSUE THREAD

**Issue by gbtami** [pychess/pychess#2198]
https://github.com/pychess/pychess/commit/4253294d4a4421b9710cf78b63bf0aef316ccba6 caused this minor regression:
```
Traceback (most recent call last):
  File "C:/msys64/home/tamas/pychess/lib/pychess/widgets/gamenanny.py", line 228, in game_ended
    message.callback = callback
UnboundLocalError: local variable 'callback' referenced before assignment

```

**Comment by hartwork** [comment]
@gbtami I was sure I had the full picture at the time, sorry for the trouble!

**Comment by gbtami** [comment]
No problem. It was not your fault IMO. That flake8 warning is rather misleading, say to least.
