### ISSUE TITLE
Crazyhouse analysis?

### ISSUE THREAD

**Issue by Oh-My-Lands** [pychess/pychess#2230]
How can I analyze crazyhouse positions with the engine? Is it possible?

**Comment by gbtami** [comment]
Yes. You can use https://fairy-stockfish.github.io/download/

**Comment by Oh-My-Lands** [comment]
No, I have an engine that can work with crazyhouse, I meant within the pychess client itself it seems like there is no way to display crazyhouse analysis of a position?

**Comment by gbtami** [comment]
![Képernyőkép – 2024-06-22 10-30-13](https://github.com/pychess/pychess/assets/479964/e7514d26-d28b-4c5e-8efc-c33b67d4b07f)
