### ISSUE TITLE
telnetlib is removed in Python 3.13

### ISSUE THREAD

**Issue by jelly** [pychess/pychess#2233]
See [whats new](https://docs.python.org/3.13/whatsnew/3.13.html#removed-modules-and-apis) and the usage [here](https://github.com/pychess/pychess/blob/63325b4abe121469f7daf1e68f9734921208f4bd/lib/pychess/ic/TimeSeal.py#L3).

**Comment by AdamWill** [comment]
seems like it only uses three constants from telnetlib? maybe just vendor those?

**Comment by gbtami** [comment]
Fixed via https://github.com/pychess/pychess/pull/2235
