### ISSUE TITLE
variant information pages should have player standings data for respective variants

### ISSUE THREAD

**Issue by mattgatto** [pychess/pychess#2238]
For example, on:
https://www.pychess.org/variants/kingofthehill960

there should be a link to, or direct data for:
https://www.pychess.org/players/kingofthehill960

and maybe vice versa too

**Comment by gbtami** [comment]
Hey Matt,
this should go to https://github.com/gbtami/pychess-variants/issues :)

In general we try to provide lichess look and feel on pychess.org as much as possible.
Something like https://lichess.org/variant/crazyhouse  so maybe it is not needed there.
The variant pages are for the rules and some minimal learning material only.

**Comment by mattgatto** [comment]
oh sorry lol. maybe pychess-variants should be renamed www.pychess.org or something :)))
