### ISSUE TITLE
Auto-save games options

### ISSUE THREAD

**Issue by pychess** [pychess/pychess#256]
Original [issue 256](https://code.google.com/p/pychess/issues/detail?id=256) reported by [armand.delcros](https://code.google.com/u/106971933427282282316/) 2007-11-11

It will be nice to have options preferences for saving game.
For example, under xboard, I configure a destination directory for the
auto-save pgn game.

**What version of the product are you using?**

0.8.1
Did you use an installed version of PyChess or did you run in from a
tarball/svn?
tarball

**Comment by pychess** [comment]
Original [comment 1.](https://code.google.com/p/pychess/issues/detail?id=256#c1) posted by [lobais](https://code.google.com/u/lobais/) 2007-11-11

So you say you'd like PyChess to like autosave once a minute?
Or you you mean like in glchess where games are automatically saved when you close
the client, and then reopened next time you start?
- removed label: Defect
- removed label: Medium
- added label: Enhancement
- added label: Low

**Comment by pychess** [comment]
Original [comment 2.](https://code.google.com/p/pychess/issues/detail?id=256#c2) posted by [armand.delcros](https://code.google.com/u/106971933427282282316/) 2007-11-12

When my game is over, I would like that this game is automatically save as a pgn
file. (or a popup proposition). So it is not like glchess.

Thanks you !

**Comment by pychess** [comment]
Original [comment 3.](https://code.google.com/p/pychess/issues/detail?id=256#c3) posted by [lobais](https://code.google.com/u/lobais/) 2007-11-12

So it is more like PyChess should manage a database of all games you've played?

**Comment by pychess** [comment]
Original [comment 4.](https://code.google.com/p/pychess/issues/detail?id=256#c4) posted by [armand.delcros](https://code.google.com/u/106971933427282282316/) 2007-11-13

Why not, but sufficient for me is to save each game in a pgn file. It is not
necessary to have a full database concept.
I use the pgn file for a crafty's analyze after my game.

for example, in the preferences, i could choose the format of the filename for
example (for fics): 
"nickname-white-color"-"nickname-black-color".pgn 
and i could choose an auto save game option.

**Comment by pychess** [comment]
Original [comment 5.](https://code.google.com/p/pychess/issues/detail?id=256#c5) posted by [lobais](https://code.google.com/u/lobais/) 2007-11-13

Ah I see.
What do you think about a preferences section, like the one attached?

If we were to implement a database and/or analyzing directly into PyChess, could you
describe or make a mockup of an ideal structure?
- attached [mockup.glade](https://code.google.com/p/pychess/issues/detail?id=256#c5)
- attached [screenshot.png](https://code.google.com/p/pychess/issues/detail?id=256#c5)

**Comment by pychess** [comment]
Original [comment 6.](https://code.google.com/p/pychess/issues/detail?id=256#c6) posted by [armand.delcros](https://code.google.com/u/106971933427282282316/) 2007-11-13

About the first question. It seems simple and great !

About the second question. About the database, I think we should take a deep look on
scid chess database. And this is a long story :-). The big problem of scid is that
you don't have the wonderfull svg enable. About the analyze feature, my need is very
simple. Again, in the preferences, I would like a section like this one :

---------- analyze options ---------------
analyze after end of the game ? [X]
choose analyze engine  : [-------]
       time by moves in seconds : [ ... ](120 seconds for example)

##        analyze options : [--------](for example smpmt=2 for crafty %28dual core procs%29)

When the game is finished, a sort of popup window appears :

---

Would you like to analyze the game ? 

## [YES] [NO]

( I prefer that pychess ask me because analyze is not necessary when me or my
opponent made a blunder).

So this is my dream !

Thanks you !

**Comment by pychess** [comment]
Original [comment 7.](https://code.google.com/p/pychess/issues/detail?id=256#c7) posted by [lobais](https://code.google.com/u/lobais/) 2007-12-09

I know scid has a hell lot of advanced (and ugly) analyze functions.
Stuff like this could be implemented in a pluggable manor i the far future, but for
now it would probably not fit very much in.

For the analyze, how'd you like the output of that analyze displayed?
In Stauton or the version after, we'll probably have an analyze sidepanel, that shows
you the e.g. crafty analyze output for each position.
Would that do?

**Comment by pychess** [comment]
Original [comment 8.](https://code.google.com/p/pychess/issues/detail?id=256#c8) posted by [armand.delcros](https://code.google.com/u/106971933427282282316/) 2007-12-09

I agree with you.I think the most simple output is sufficient. The crafty output is
ok i think. the auto-save game options is clearly more important than the analyze option.

**Comment by pychess** [comment]
Original [comment 9.](https://code.google.com/p/pychess/issues/detail?id=256#c9) posted by [pe3kuv](https://code.google.com/u/116109811260609265599/) 2009-01-04

Hey, I think BabasChess (Win FICS client) for example has very well done this feature
- autosaving finished games into a file. You just play and at any time later you can
  replay your games. Simple and useful.

**Comment by pychess** [comment]
Original [comment 10.](https://code.google.com/p/pychess/issues/detail?id=256#c10) posted by [lobais](https://code.google.com/u/lobais/) 2009-01-04

Tamás is working on a database for PyChess. The next version will surely be much
stronger on this area. I hope you can wait.
And yes, we are much inspired by BabasChess, Aquarium and more.

**Comment by pychess** [comment]
Original [comment 11.](https://code.google.com/p/pychess/issues/detail?id=256#c11) posted by [pe3kuv](https://code.google.com/u/116109811260609265599/) 2009-01-10

Apart from autosaving it might be also useful to put button on "notice bar" (the one
which says that game ended and how) which would say: save game to default database.
Take this just as an idea - I do not really know if this is really needed. On the
other hand, what else may one want to do with a finished game? (close/analyze
immediately/save for later replay)

**Comment by pychess** [comment]
Original [comment 12.](https://code.google.com/p/pychess/issues/detail?id=256#c12) posted by [lobais](https://code.google.com/u/lobais/) 2009-01-11

I think all games you have ever observed or played should be put to some standard
database, which could later be searchable.
When a game has finished, the yellow bar would have a button "Open in
sandbox/database" and from there, the user could move it to a more permanent/tagged
database. (And of course do all kinds of analysing, examination and continued play)

**Comment by pychess** [comment]
Original [comment 13.](https://code.google.com/p/pychess/issues/detail?id=256#c13) posted by [pe3kuv](https://code.google.com/u/116109811260609265599/) 2009-01-11

Yep, I think that might be fine.

There are several possible approaches to autosaving.
1) save everything to single file
2) save to several files depending on pychess logic
3) save to several files depending on rules (inspired by jin)

I would do 2nd, but 1st might be as good if easy to use (and fast) filtering is
possible to use on games database. 3rd might come in some far future, if needed.

Just do not forget that especially on observed games - user may close the game BEFORE
it is finished. I think you should have a clear idea of what should pychess do with
games and how possibly interact with user in all combinations of
local/server/observed and finished/not finished games. Which makes six possible
situations.
As I wrote earlier, I am personally strongly against any popup dialogs. They might be
useful but one should be able to turn them off in preferences.

**Comment by pychess** [comment]
Original [comment 14.](https://code.google.com/p/pychess/issues/detail?id=256#c14) posted by [lobais](https://code.google.com/u/lobais/) 2009-01-11

(2) and (3) can be implemented using filters/advanced search of the large database.
Observed games can be discussed, but games take up so little space, that there is no
reason not to store tons of them, at least for a couple of months, just like the
history in webbrowsers.

**Comment by pychess** [comment]
Original [comment 15.](https://code.google.com/p/pychess/issues/detail?id=256#c15) posted by [pe3kuv](https://code.google.com/u/116109811260609265599/) 2009-01-11

Just look at it this way. You have a DB full of everything, but of little value.
Mostly just your own games are of a value to you. So why to lose time (space is
really not imporant) filtering those others?
Even Fritz uses the same approach - three DBs for local games, server games and
observed games.

I think that if someone wants to have it all in one file, then such user will just
put same filename in for all three DBs.

**Comment by pychess** [comment]
Original [comment 16.](https://code.google.com/p/pychess/issues/detail?id=256#c16) posted by [lobais](https://code.google.com/u/lobais/) 2009-01-11

I don't see us having the user set the filenames. Rather some sqlite stuff.
But of course, at that time we can see, if there are performance wins be splitting
into mulitple databases.

**Comment by pychess** [comment]
Original [comment 17.](https://code.google.com/p/pychess/issues/detail?id=256#c17) posted by [gbtami](https://code.google.com/u/gbtami/) 2009-01-12

I don't think we ever want multiple databases. We should use a collection table and a
reference field in the games table
(http://jose-chess.sourceforge.net/images/shots/shot03.png) to group games. It can be
a database/pgn where the games was imported from, or others, like clipboard, trash,
and auto saved.

**Comment by pychess** [comment]
Original [comment 18.](https://code.google.com/p/pychess/issues/detail?id=256#c18) posted by [lobais](https://code.google.com/u/lobais/) 2009-01-13

I've done a lot of research on rybka, itunes and chessbase, and I've compiled a
layout that will work very well.

**Comment by pychess** [comment]
Original [comment 19.](https://code.google.com/p/pychess/issues/detail?id=256#c19) posted by [lobais](https://code.google.com/u/lobais/) 2009-01-13

The recently played lists will contain a reasonable number of games, of which the
important ones can be moved to playlists or tagged properly.
If you import e.g. a large base of grandmaster games, you could just let them lie
tagged in the global Games list - perhaps using a dynamic filter in case you get more
games later - or create a 'play list' for them.

**Comment by pychess** [comment]
Original [comment 20.](https://code.google.com/p/pychess/issues/detail?id=256#c20) posted by [leogregianin](https://code.google.com/u/leogregianin@gmail.com/) 2011-01-23

In save games options may have an option to send the game (fen, pgn, picture) by email, surely should have a record of your name, email, smtp, etc.

**Comment by pychess** [comment]
Original [comment 21.](https://code.google.com/p/pychess/issues/detail?id=256#c21) posted by [gbtami](https://code.google.com/u/gbtami/) 2013-04-20
- changed status to: Accepted
- changed summary to: Auto-save games options

**Comment by pychess** [comment]
Original [comment 22.](https://code.google.com/p/pychess/issues/detail?id=256#c22) posted by [gbtami](https://code.google.com/u/gbtami/) 2013-04-20
- removed label: Low
- added label: Medium

**Comment by pychess** [comment]
Original [comment 23.](https://code.google.com/p/pychess/issues/detail?id=256#c23) posted by [gbtami](https://code.google.com/u/gbtami/) 2013-06-27
- added label: Post-0.12

**Comment by pychess** [comment]
Original [comment 24.](https://code.google.com/p/pychess/issues/detail?id=256#c24) posted by [gbtami](https://code.google.com/u/gbtami/) 2013-07-07

issue #783 has been merged into this issue.

**Comment by gideon425** [comment]
I have written some python code to implement a new command line option --auto_save_file.  It works.  Can I supply my modified files for your review, to see if my changes can be integrated?  If so, how should I send them?

**Comment by gbtami** [comment]
Just create a pull request from your fork.
See https://help.github.com/articles/using-pull-requests/

**Comment by gideon425** [comment]
Is there any particular message I should use for the commit to my fork?

**Comment by gbtami** [comment]
No, there isn't.

**Comment by gideon425** [comment]
I suggest something like the following.
A change to Edit/Preferences window with a new tab called Save Options.
Two fields in that tab.
First field is a checkbox, initial value false.
Second field is a file name, initial value derived from environment variable HOME.  So if HOME = /home/user1, then value would be /home/user1/pychess.pgn
I am not sure what to do in the case where there is more than one game proceeding.  Perhaps go back to current behaviour in that case.

Normal use case would be
1. user starts pychess
2. enables option
3. plays single game
4. closes window
5. game is saved to file

Before I actually implement anything, does anyone have thoughts about this?

**Comment by gbtami** [comment]
Some template format for file name would be useful. Something like Thomas suggested in comment 5.
More than one unsaved game game is not problem. Pychess can append more games into a .pgn
