### ISSUE TITLE
pyChess crashes immediately in Hardy

### ISSUE THREAD

**Issue by ghost** [pychess/pychess#311]
Original [issue 311](https://code.google.com/p/pychess/issues/detail?id=311) reported by [vital.urbo](https://code.google.com/u/110546025693672527813/) 2008-03-02

**What steps will reproduce the problem?**
1.Have AMD64 Ubuntu Hardy latest Alpha with all latest updates
2.Install pyChess via add/remove
3.Try running it from the Games menu
## Her is the terminal output:

:~$ pychess
Traceback (most recent call last):
  File "/usr/games/pychess", line 41, in <module>
    pychess.Main.run(sys.argv[1:])
  File "/usr/lib/python2.5/site-packages/pychess/Main.py", line 468, in run
    PyChess(args)
  File "/usr/lib/python2.5/site-packages/pychess/Main.py", line 400, in
__init__
    self.initGlade()
  File "/usr/lib/python2.5/site-packages/pychess/Main.py", line 433, in
initGlade
    window["menubar1"].drag_dest_set(flags, dnd_list, gtk.gdk.ACTION_COPY)
TypeError: list items should be of form (string,int,int)

---

Does it happen every time? - Yes

What version of the product are you using? - Latest

Did you use an installed version of PyChess or did you run in from a
tarball/svn? - I used add/remove

There is a related "fixed" issue for Gusty.

**Comment by pychess** [comment]
Original [comment 1.](https://code.google.com/p/pychess/issues/detail?id=311#c1) posted by [gbtami](https://code.google.com/u/gbtami/) 2008-03-03

Hardy has beta4 only:
http://packages.ubuntu.com/hardy/pychess

Please try to install the released 0.8 from here:
http://pychess.googlecode.com/files/pychess\_0.8\_all.deb

**Comment by pychess** [comment]
Original [comment 2.](https://code.google.com/p/pychess/issues/detail?id=311#c2) posted by [vital.urbo](https://code.google.com/u/110546025693672527813/) 2008-03-04

Thanks, gbtami,

the installation from http://pychess.googlecode.com/files/pychess\_0.8\_all.deb worked
just fine. So this is not a bug in pyChess. It is however a bug in Ubuntu repository
data, and I will follow up on that.

The GUI looks nice. The FICS integration is horrible - it is unusable (not yet
implemented features, of course) and in addition it screwed up severely all my FICS
settings that I am accustomed to while using other interfaces (Winboard on windows)
which makes it impossible to use; and I have no idea what flags to use to turn the
notifications of all the chlanges and of all game results off.

Of course this is a matter of another 3 new bugs or so, which I may or may not report.

Thanks for doing a great job. Looking forward to a usable release of pyChess.

**Comment by pychess** [comment]
Original [comment 3.](https://code.google.com/p/pychess/issues/detail?id=311#c3) posted by [gbtami](https://code.google.com/u/gbtami/) 2008-03-04

_Please_ file detailed reports on all your FICS related problems. Without real FICS
users feedback PyChess FICS support will never be good ehougn. thx

**Comment by pychess** [comment]
Original [comment 4.](https://code.google.com/p/pychess/issues/detail?id=311#c4) posted by [lobais](https://code.google.com/u/lobais/) 2008-04-25

The crash seams to be fixed now.
On the variables they are fixed in 0.8.1 as well, and the missing features - well
they'll come with time :)
- changed status to: Fixed
