### ISSUE TITLE
No CheckMate on FICS

### ISSUE THREAD

**Issue by ghost** [pychess/pychess#312]
Original [issue 312](https://code.google.com/p/pychess/issues/detail?id=312) reported by [mhoneth](https://code.google.com/u/112137138642649263188/) 2008-03-03

**What steps will reproduce the problem?**
1. Played a rated game on FICS
2. Opponent moved Queen to b1# (move list did not display checkmate)
3. King on a1 became a rook, and game continued (move list showed Rxb1)
4. I won on time and my win was recorded by FICS

**What is the expected output? What do you see instead?**
Checkmate should have been registered as a win for my opponent, and game 
ended.

**Does it happen every time?**
Only tried it once.

**What version of the product are you using?**
0.8

Did you use an installed version of PyChess or did you run in from a 
tarball/svn?
Installed on Ubuntu Gutsy 7.10

**Please provide any additional information below.**

**Comment by pychess** [comment]
Original [comment 1.](https://code.google.com/p/pychess/issues/detail?id=312#c1) posted by [lobais](https://code.google.com/u/lobais/) 2008-03-03

Hej Mich, thanks for the report. However to fix it, we will need to be able to
reproduce it ourselves.

If you can reproduce it again, it would be nice, if you could save the game after the
error happened, and then send the contents of the file. That way we can see all moves
made, and if our king also becomes a rook, if we follow them.

If you are no longer able to reproduce, it would be good if you'd upload your logfile
from the ~/.pychess directory to some url, and post it here.

**Comment by pychess** [comment]
Original [comment 2.](https://code.google.com/p/pychess/issues/detail?id=312#c2) posted by [lobais](https://code.google.com/u/lobais/) 2008-04-25
- changed status to: Need-Info

**Comment by pychess** [comment]
Original [comment 3.](https://code.google.com/p/pychess/issues/detail?id=312#c3) posted by [gbtami](https://code.google.com/u/gbtami/) 2013-04-21
- changed status to: WontFix
