### ISSUE TITLE
Add support for Yahoo chess

### ISSUE THREAD

**Issue by pychess** [pychess/pychess#313]
Original [issue 313](https://code.google.com/p/pychess/issues/detail?id=313) reported by [lobais](https://code.google.com/u/lobais/) 2008-03-16

This project: http://sourceforge.net/project/showfiles.php?group\_id=85850
YICS createa a ics layer on top of yahoo.

The project page says:
Yahoo! has introduced a CAPTCHA test for access to their Games services. As
YICS is a text-mode program, there is no way to reliably present the
challenge to the user.

But this should not be a problem for PyChess.
This will however still require a lot of work, and I believe Yahoo has made
a new version of their chess a year ago.

**Comment by gbtami** [comment]
http://houstonianonline.com/2016/02/09/yahoo-games-shuts-down/
