### ISSUE TITLE
Keep boardview quadric

### ISSUE THREAD

**Issue by ghost** [pychess/pychess#314]
Original [issue 314](https://code.google.com/p/pychess/issues/detail?id=314) reported by [lobais](https://code.google.com/u/lobais/) 2008-03-18

It would be interesting to use the gtk.AspectFrame on the BoardView, to
make sure that it is always quadric.

**Comment by pychess** [comment]
Original [comment 1.](https://code.google.com/p/pychess/issues/detail?id=314#c1) posted by [lobais](https://code.google.com/u/lobais/) 2008-03-18

Oh, it seams that AspectFrame simply adds space around the widget.
I'd hoped it would actually affect the way the window manager resized the window, but
that was probably too much to hope for.
- changed status to: Invalid
