### ISSUE TITLE
Problems with soughtgraph and compiz

### ISSUE THREAD

**Issue by ghost** [pychess/pychess#317]
Original [issue 317](https://code.google.com/p/pychess/issues/detail?id=317) reported by [lobais](https://code.google.com/u/lobais/) 2008-03-31

**What steps will reproduce the problem?**
1. Use compiz
2. Click a dot in the sought graph

**What is the expected output? What do you see instead?**
Nothing happens.

Did you use an installed version of PyChess or did you run in from a
tarball/svn?

0.8.1

**Please use labels and text to provide additional information.**

If you do "metacity --replace" the graph works fine.
As well, if you click the button very extensively, you can manage to accept
the seek.
From ubuntu launchpad:
https://bugs.launchpad.net/ubuntu/+source/pychess/+bug/209655

**Please attach the latest pychess logfile from ~/.pychess**

No output

**Comment by pychess** [comment]
Original [comment 1.](https://code.google.com/p/pychess/issues/detail?id=317#c1) posted by [lobais](https://code.google.com/u/lobais/) 2008-04-25

Fixed in trunk and the 0.8 branch
- changed status to: Fixed
