### ISSUE TITLE
Soughtgraph has fixed backgroundcolor

### ISSUE THREAD

**Issue by ghost** [pychess/pychess#318]
Original [issue 318](https://code.google.com/p/pychess/issues/detail?id=318) reported by [lobais](https://code.google.com/u/lobais/) 2008-03-31

**What steps will reproduce the problem?**
1. Use a theme with a gradient background on notebooks
2. Go to the sought graph

**What is the expected output? What do you see instead?**
The background will be fixed to the widget background color rather than the
gradient.

This might be fixable by subclassing gtk.Notebook and connect_after to
expose-event, but it would be ugly.
Future gtk versions may support transparency.

**Comment by pychess** [comment]
Original [comment 1.](https://code.google.com/p/pychess/issues/detail?id=318#c1) posted by [lobais](https://code.google.com/u/lobais/) 2008-04-25

Fixed in trunk and 0.8 branch
- changed status to: Fixed
