### ISSUE TITLE
Need for disabling takeback (undo) action

### ISSUE THREAD

**Issue by pychess** [pychess/pychess#319]
Original [issue 319](https://code.google.com/p/pychess/issues/detail?id=319) reported by [gbtami](https://code.google.com/u/gbtami/) 2008-04-07

I'v got a new feature request to let disable somehow the undo action. Hes
little son learning chess and uses this too often, and will never learn
that this is a no-no in real chess games.

**Comment by pychess** [comment]
Original [comment 1.](https://code.google.com/p/pychess/issues/detail?id=319#c1) posted by [gbtami](https://code.google.com/u/gbtami/) 2008-04-08
- removed label: Defect
- added label: Enhancement

**Comment by pychess** [comment]
Original [comment 2.](https://code.google.com/p/pychess/issues/detail?id=319#c2) posted by [lobais](https://code.google.com/u/lobais/) 2008-04-13

Shouldn't be to hard to do in code, but we need a good way to implement it in the
"new game" UI.
An option in the preferences should also be taken into concideration.

**Comment by pychess** [comment]
Original [comment 3.](https://code.google.com/p/pychess/issues/detail?id=319#c3) posted by [pe3kuv](https://code.google.com/u/116109811260609265599/) 2009-01-10

What about not doing a GUI for this. Just put it in help files and let people edit
config when in need for this. Which should not be very often, I suppose.
This and similar tweaks might be sometimes handy features, but will make UI clumsy if
all put into GUI.
Or maybe some "Others" or "Advanced" tab in Settings might be a good spot to place
all "non-standard" or "not-expected-to-be-ever-changed-by-most-users" features.

**Comment by pychess** [comment]
Original [comment 4.](https://code.google.com/p/pychess/issues/detail?id=319#c4) posted by [lobais](https://code.google.com/u/lobais/) 2009-01-10

I don't really like "Others" or "Advanced" tabs. I've read some topics about them,
and the problem is, that if people have any kind of problem, they'll go and look at
them, just to be sure.

We could make it gui-less, but actually I think it is easier to just make a checkbox
in the preferences. If we get too many checkboxes at some point, we can go rearrange
them.

**Comment by NoSuck** [comment]
My ears are on fire... though I've never gotten the urge to undo in a real game.  Perhaps your son and I are similar in viewing PyChess more as a tool for exploring lines of thought and risky ideas.
