### ISSUE TITLE
More flexible computer strength settings

### ISSUE THREAD

**Issue by ghost** [pychess/pychess#320]
Original [issue 320](https://code.google.com/p/pychess/issues/detail?id=320) reported by [lobais](https://code.google.com/u/lobais/) 2008-04-25

Three levels are not enough.
the ulimit command can be used to set how much cpu time a process can take,
and could be used - together with engine parameters - to create a fluent
strength slider.

**Comment by pychess** [comment]
Original [comment 1.](https://code.google.com/p/pychess/issues/detail?id=320#c1) posted by [lobais](https://code.google.com/u/lobais/) 2008-10-17

There are now 8
- changed status to: Fixed
