### ISSUE TITLE
Cannot begin a new game

### ISSUE THREAD

**Issue by ghost** [pychess/pychess#321]
Original [issue 321](https://code.google.com/p/pychess/issues/detail?id=321) reported by [tawood3](https://code.google.com/u/102856337901166311808/) 2008-04-25

**What steps will reproduce the problem?**
1. Run Pychess
2. Click Start Game

**What is the expected output? What do you see instead?**
The game crashes and issues the following traceback:

Traceback (most recent call last):
  File "/usr/lib/python2.5/site-packages/pychess/Main.py", line 372, in
on_newGameTasker_started
    gamemodel = GameModel(TimeModel(5*60, 0))
  File "/usr/lib/python2.5/site-packages/pychess/Utils/GameModel.py", line
39, in __init__
    self.boards = [Board(setup=True)]
  File "/usr/lib/python2.5/site-packages/pychess/Utils/Board.py", line 33,
in __init__
    for cord in iterBits(wpieces[PAWN]):
  File "/usr/lib/python2.5/site-packages/pychess/Utils/lutils/bitboard.py",
line 36, in iterBits
    ensureBitArraysLoaded ()
  File "/usr/lib/python2.5/site-packages/pychess/Utils/lutils/bitboard.py",
line 122, in ensureBitArraysLoaded
    l = ord_(f.read(1))
TypeError: ord() expected a character, but string of length 0 found

Does it happen every time? Yes

What version of the product are you using? pychess Philidor 0.8

Did you use an installed version of PyChess or did you run in from a
tarball/svn? Installed from pychess-0.8-1.fc8.rpm

**Please provide any additional information below.**
Fedora 8 (2.6.24.4-64.fc8) 

**Please attach the latest pychess logfile.**
For PyChess <= 0.6.x it's hidden in your homedirectory and called
".pychess.log".
For PyChess > 0.6.x, it's in a hidden folder, under your homedirectory,
named ".pychess/"

**Comment by pychess** [comment]
Original [comment 1.](https://code.google.com/p/pychess/issues/detail?id=321#c1) posted by [tawood3](https://code.google.com/u/102856337901166311808/) 2008-04-25

This problem appears to be fixed in 0.8.1 and I assume the Fedora folks with be
placing the newest version in their yum repo soon.

**Comment by pychess** [comment]
Original [comment 2.](https://code.google.com/p/pychess/issues/detail?id=321#c2) posted by [lobais](https://code.google.com/u/lobais/) 2008-04-25

I actually don't think it was fixed, but perhaps reinstalling has helped reset some
files for you. I think I have a possible fix, which I'll commit.
- changed status to: Fixed
