### ISSUE TITLE
Disambiguation in ACN notation

### ISSUE THREAD

**Issue by ghost** [pychess/pychess#323]
Original [issue 323](https://code.google.com/p/pychess/issues/detail?id=323) reported by [voinescu.andrei](https://code.google.com/u/110802094834163447459/) 2008-04-29

**What steps will reproduce the problem?**
1. Start pyChess in Player vs. Player mode
2. Promote pawns until a total of 4 queens. Place queens in 3x3 square
3. Move a queen in center

**What is the expected output? What do you see instead?**

for 3x3 square (3->5) x (f->h) it should be something like
Qf3g4 or Qh3g4, instead i see Q3g4 for both moves.
There has to be some disambiguation on both ranks and files notation:
(from Wikipedia)
"Disambiguating moves

If two (or more) identical pieces can move to the same square, the piece's
initial is followed by (in descending order of preference):
1. the file of departure if they differ;
2. the rank of departure if the files are the same but the ranks differ;
3. Both the rank and file if neither alone uniquely defines the piece
   (after a pawn promotion, if three or more of the same piece are able to
   reach the square).

For example, with two knights on g1 and d2, either of which might move to
f3, the move is indicated as Ngf3 or Ndf3, as appropriate. With two knights
on g5 and g1, the moves are N5f3 or N1f3. As above, an x may be used to
indicate a capture: for example, N5xf3."

**Does it happen every time?**
Yes

**What version of the product are you using?**
-c Grecco 0.6.1

Did you use an installed version of PyChess or did you run in from a
tarball/svn?
intalled via apt-get

**Please provide any additional information below.**
not necessary

**Please attach the latest pychess logfile.**
For PyChess <= 0.6.x it's hidden in your homedirectory and called
".pychess.log".
For PyChess > 0.6.x, it's in a hidden folder, under your homedirectory,
named ".pychess/"

**Comment by pychess** [comment]
Original [comment 1.](https://code.google.com/p/pychess/issues/detail?id=323#c1) posted by [lobais](https://code.google.com/u/lobais/) 2008-04-29

Hey Voinescu, thanks for taking time to reproduce the problem and look into it.

There is however a big chance, that the problem is already fixed in Philidor. As
Grecco is kinda not supported any more, so do you mind trying with the deb from
http://gnomefiles.org/app.php/PyChess and see if it works?

If it does not, please save the position (before the move) as a FEN or EPD, and copy
the contents of the file into this bug repport, so we have all available information.

Thanks again, Thomas

**Comment by pychess** [comment]
Original [comment 2.](https://code.google.com/p/pychess/issues/detail?id=323#c2) posted by [voinescu.andrei](https://code.google.com/u/110802094834163447459/) 2008-04-30

Hello,

Apparently this issue does not appear in the latest stable version of pyChess. 
My apologies for not trying it on the latest version before posting the issue.

Andrei

**Comment by pychess** [comment]
Original [comment 3.](https://code.google.com/p/pychess/issues/detail?id=323#c3) posted by [lobais](https://code.google.com/u/lobais/) 2008-04-30

No problem :)
I'll just close it.
- changed status to: Invalid
