### ISSUE TITLE
can 0-0  while king was moved before

### ISSUE THREAD

**Issue by ghost** [pychess/pychess#324]
Original [issue 324](https://code.google.com/p/pychess/issues/detail?id=324) reported by [gbtami](https://code.google.com/u/gbtami/) 2008-05-10

I can play this game with PyChess trunk (r963):
1. e4 c5 2. Ke2 g5 3. Nf3 e6 4. Ke1 f5 5. Be2 Nc6 6. O-O fxe4

**Comment by pychess** [comment]
Original [comment 1.](https://code.google.com/p/pychess/issues/detail?id=324#c1) posted by [lobais](https://code.google.com/u/lobais/) 2008-05-12

In Philidor all moves were generated for BoardControl at each position, and a
dictionary was used to check if a, by the user proposed, moved was valid.
In trunk the validate function is used, so this function seams to have a bug in
checking for castling. The movegen function has the power to check for it, so the
internals should already be there.

**Comment by pychess** [comment]
Original [comment 2.](https://code.google.com/p/pychess/issues/detail?id=324#c2) posted by [gbtami](https://code.google.com/u/gbtami/) 2008-05-19
- changed status to: Fixed
