### ISSUE TITLE
SVN: Can't connect to FICS with name and password

### ISSUE THREAD

**Issue by ghost** [pychess/pychess#325]
Original [issue 325](https://code.google.com/p/pychess/issues/detail?id=325) reported by [mruwek](https://code.google.com/u/104560812386438941058/) 2008-05-21

I can't connect to FICS as a user with an actual SVN (21.05.08) version.
Connecting with Philidor 0.8.1 works fine.

**Comment by pychess** [comment]
Original [comment 1.](https://code.google.com/p/pychess/issues/detail?id=325#c1) posted by [mruwek](https://code.google.com/u/104560812386438941058/) 2008-05-21

I get a standard Log error message:
"The entered password was invalid.

If you have forgot your password, try logging in as a guest and open chat on channel
4. Write "I've forgotten my password" to get help.

If that is by some reason not possible, please email: support@freechess.org"

**Comment by pychess** [comment]
Original [comment 2.](https://code.google.com/p/pychess/issues/detail?id=325#c2) posted by [lobais](https://code.google.com/u/lobais/) 2008-05-21

Yes, this is a problem with the new timeseal implementation.
- changed status to: Accepted
- removed label: Medium
- added label: Critical

**Comment by pychess** [comment]
Original [comment 3.](https://code.google.com/p/pychess/issues/detail?id=325#c3) posted by [lobais](https://code.google.com/u/lobais/) 2008-10-17

Fixed
- changed status to: Fixed
