### ISSUE TITLE
Save game bug

### ISSUE THREAD

**Issue by ghost** [pychess/pychess#326]
Original [issue 326](https://code.google.com/p/pychess/issues/detail?id=326) reported by [gbtami](https://code.google.com/u/gbtami/) 2008-06-01

Traceback (most recent call last):
  File "/home/tamas/svn/pychess/trunk/lib/pychess/Main.py", line 287, in
on_save_game_as1_activate
    ionest.saveGameAs (gameDic[gamewidget.cur_gmwidg()])
  File "/home/tamas/svn/pychess/trunk/lib/pychess/widgets/ionest.py", line
247, in saveGameAs
    if savecombo.get_active() == 0:
NameError: global name 'savecombo' is not defined

**Comment by pychess** [comment]
Original [comment 1.](https://code.google.com/p/pychess/issues/detail?id=326#c1) posted by [gbtami](https://code.google.com/u/gbtami/) 2008-06-01
- changed summary to: Save game bug

**Comment by pychess** [comment]
Original [comment 2.](https://code.google.com/p/pychess/issues/detail?id=326#c2) posted by [leogregianin](https://code.google.com/u/leogregianin@gmail.com/) 2008-06-03

Fixed in rv 1025
- changed status to: Fixed
