### ISSUE TITLE
1/2-1/2 in move 1.

### ISSUE THREAD

**Issue by ghost** [pychess/pychess#327]
Original [issue 327](https://code.google.com/p/pychess/issues/detail?id=327) reported by [gbtami](https://code.google.com/u/gbtami/) 2008-06-01

Started a new Fischer Random Chess game against PyChess on expert level.
After started to play 1.g2-g3, pychess doesn't wanted to play any moves.
(On beginner/intermediate levels it plays OK.)

11:49:52 Python Debug: /usr/bin/python
11:49:52 Python Debug: Black
11:49:52 Python Log: xboard
11:49:52 Python Log: protover 2
11:49:53 Python Debug: feature draw=1 reuse=0 myname='PyChess 0.9'
usermove=1 setboard=1 sigterm=1 analyze=1 variants='normal, fischerandom'
done=1
11:49:53 Python Log: nopost
11:49:53 Python Log: hard
11:49:53 Python Log: sd 9
11:49:53 Python Log: level 0 5 0
11:49:53 Python Log: force
11:49:53 Python Log: variant fischerandom
11:49:53 Python Log: force
11:49:53 Python Log: setboard nrbqkrnb/pppppppp/8/8/8/8/PPPPPPPP/NRBQKRNB w
KQkq - 0 1
11:49:54 Python Log: time 300
11:49:54 Python Log: otim 300
11:49:54 Python Log: usermove g2g3
11:49:54 Python Log: go
11:49:54 Python Debug: If the game has no timesettings, you probably don't want
11:49:54 Python Debug: to set a search depth much greater than 4
11:49:54 Python Debug: Playing 0 moves in 300 seconds + 0 increment
11:49:54 Python Debug: Time left: 300.00 seconds; Plan to thinking for 7.70
seconds
11:49:56 Python Debug: result 1/2-1/2
11:49:56 Python Debug: last: 6 0

**Comment by pychess** [comment]
Original [comment 1.](https://code.google.com/p/pychess/issues/detail?id=327#c1) posted by [gbtami](https://code.google.com/u/gbtami/) 2008-06-07

fixed in svn rev1030
- changed status to: Fixed
