### ISSUE TITLE
Who is the time

### ISSUE THREAD

**Issue by ghost** [pychess/pychess#328]
Original [issue 328](https://code.google.com/p/pychess/issues/detail?id=328) reported by [leogregianin](https://code.google.com/u/leogregianin@gmail.com/) 2008-06-01

To learn more easily, who is instead of playing, white or black, tabs of
time could have a different background, in addition to having the clock
running.

**Comment by pychess** [comment]
Original [comment 1.](https://code.google.com/p/pychess/issues/detail?id=328#c1) posted by [leogregianin](https://code.google.com/u/leogregianin@gmail.com/) 2008-06-01

I think that the light bold is little to show, could be red or blue.

**Comment by pychess** [comment]
Original [comment 2.](https://code.google.com/p/pychess/issues/detail?id=328#c2) posted by [lobais](https://code.google.com/u/lobais/) 2008-06-01

We could probably do some more to indicate it, however the current system is ripped
of xboard.
This is also a thing that should really be implemented with a board-theme, but that
is on stand by while we wait for python webkit bindings...

**Comment by pychess** [comment]
Original [comment 3.](https://code.google.com/p/pychess/issues/detail?id=328#c3) posted by [leogregianin](https://code.google.com/u/leogregianin@gmail.com/) 2008-06-03
- changed status to: Invalid
