### ISSUE TITLE
Error when clicked in "log off"

### ISSUE THREAD

**Issue by ghost** [pychess/pychess#329]
Original [issue 329](https://code.google.com/p/pychess/issues/detail?id=329) reported by [leogregianin](https://code.google.com/u/leogregianin@gmail.com/) 2008-06-01

**What steps will reproduce the problem?**
1. When click in "log off" button in fics connection

**What is the expected output? What do you see instead?**
root@leo:/home/leonardo/Área de Trabalho/pychess-trunk/pychess#
PYTHONPATH=lib/ ./pychess
21168: prioridade antiga = 0; prioridade nova = 15
Traceback (most recent call last):
  File "/home/leonardo/Área de
Trabalho/pychess-trunk/pychess/lib/pychess/ic/ICLounge.py", line 85, in
on_logoffButton_clicked
    connection.disconnect()
  File "/home/leonardo/Área de
Trabalho/pychess-trunk/pychess/lib/pychess/ic/FICSConnection.py", line 208,
in disconnect
    self.client.close()
AttributeError: PredictionsTelnet instance has no attribute 'close'
Traceback (most recent call last):
  File "/home/leonardo/Área de
Trabalho/pychess-trunk/pychess/lib/pychess/System/glock.py", line 38, in
handler
    function(emitter, *extra)
  File "/home/leonardo/Área de
Trabalho/pychess-trunk/pychess/lib/pychess/widgets/ChatWindow.py", line
529, in <lambda>
    glock_connect(connection, "disconnected", lambda c: self.window.hide())
AttributeError: 'NoneType' object has no attribute 'hide'

Did you use an installed version of PyChess or did you run in from a
tarball/svn?
svn

**Please use labels and text to provide additional information.**

**Please attach the latest pychess logfile from ~/.pychess**

**Comment by pychess** [comment]
Original [comment 1.](https://code.google.com/p/pychess/issues/detail?id=329#c1) posted by [leogregianin](https://code.google.com/u/leogregianin@gmail.com/) 2008-06-01
- changed summary to: Error when clicked in "log off"

**Comment by pychess** [comment]
Original [comment 2.](https://code.google.com/p/pychess/issues/detail?id=329#c2) posted by [lobais](https://code.google.com/u/lobais/) 2008-08-28

Hey Leonardo,
Appologies for the slow respond.
Does this happen everytime?
This only messes the terminal, right? Or does it also affect the ui and stuff?

**Comment by pychess** [comment]
Original [comment 3.](https://code.google.com/p/pychess/issues/detail?id=329#c3) posted by [leogregianin](https://code.google.com/u/leogregianin@gmail.com/) 2008-08-28

Hi Thomas, this is happen everytime on ui.

**Comment by pychess** [comment]
Original [comment 4.](https://code.google.com/p/pychess/issues/detail?id=329#c4) posted by [lobais](https://code.google.com/u/lobais/) 2008-08-28

How do you mean it affects the ui? Does it crash? Does it freeze? Don't the windows
hide properly?

**Comment by pychess** [comment]
Original [comment 5.](https://code.google.com/p/pychess/issues/detail?id=329#c5) posted by [leogregianin](https://code.google.com/u/leogregianin@gmail.com/) 2008-09-01

The application was crashed, I updated the last svn and is no longer showing the
problem. Thanks.
- changed status to: WontFix
