### ISSUE TITLE
Does not appear yellow box

### ISSUE THREAD

**Issue by ghost** [pychess/pychess#330]
Original [issue 330](https://code.google.com/p/pychess/issues/detail?id=330) reported by [leogregianin](https://code.google.com/u/leogregianin@gmail.com/) 2008-06-09

**What steps will reproduce the problem?**
1. When open new game tab, yellow box continue appear.

Did you use an installed version of PyChess or did you run in from a
tarball/svn?
svn-trunk

Attach:
In the first tab, black player won the game, when you open a new tab still
showing a yellow box.

**Comment by pychess** [comment]
- attached [yellow box.png](https://code.google.com/p/pychess/issues/detail?id=330#c0)

**Comment by pychess** [comment]
Original [comment 1.](https://code.google.com/p/pychess/issues/detail?id=330#c1) posted by [lobais](https://code.google.com/u/lobais/) 2008-10-17

Fixed in trunk
- changed status to: Fixed
