### ISSUE TITLE
Player names are missing from "Game Information" dialog

### ISSUE THREAD

**Issue by ghost** [pychess/pychess#331]
Original [issue 331](https://code.google.com/p/pychess/issues/detail?id=331) reported by [gbtami](https://code.google.com/u/gbtami/) 2008-06-09

In The Game menu there is a Game Information submenu, but it's incomplete imho.

**Comment by pychess** [comment]
Original [comment 1.](https://code.google.com/p/pychess/issues/detail?id=331#c1) posted by [gbtami](https://code.google.com/u/gbtami/) 2008-06-09
- changed summary to: Player names are missing from "Game Information" dialog

**Comment by pychess** [comment]
Original [comment 3.](https://code.google.com/p/pychess/issues/detail?id=331#c3) posted by [lobais](https://code.google.com/u/lobais/) 2011-01-28

It should just be a matter of updating the glade file,
and in lib›pychess›widgets›gameinfoDialog.py load the names from the gamemodel using something like repr(model.players[BLACK]).
- changed status to: Fix-Known
- added label: Easy-Fix

**Comment by pychess** [comment]
Original [comment 4.](https://code.google.com/p/pychess/issues/detail?id=331#c4) posted by [G.nius.ck](https://code.google.com/u/112084229900022559058/) 2013-06-22

Fixing This Now

**Comment by pychess** [comment]
Original [comment 5.](https://code.google.com/p/pychess/issues/detail?id=331#c5) posted by [G.nius.ck](https://code.google.com/u/112084229900022559058/) 2013-06-26

Done, pull from https://G.nius.ck@code.google.com/r/gniusck-myclone/ (also has 422.)

**Comment by pychess** [comment]
Original [comment 6.](https://code.google.com/p/pychess/issues/detail?id=331#c6) posted by [gbtami](https://code.google.com/u/gbtami/) 2013-06-26
- changed status to: Fixed

**Comment by pychess** [comment]
Original [comment 7.](https://code.google.com/p/pychess/issues/detail?id=331#c7) posted by [G.nius.ck](https://code.google.com/u/112084229900022559058/) 2013-07-08

Oh yes, apparently it shows the rating in the box if it is a FICS game too. Should this be removed, or possibly moved to a different box, or should it stay?
