### ISSUE TITLE
Third tab does not appear

### ISSUE THREAD

**Issue by ghost** [pychess/pychess#332]
Original [issue 332](https://code.google.com/p/pychess/issues/detail?id=332) reported by [leogregianin](https://code.google.com/u/leogregianin@gmail.com/) 2008-06-09

**What steps will reproduce the problem?**
1. I open the first tab
2. Open the second tab 
3. Try to open the third tab

**What is the expected output? What do you see instead?**

/home/leonardo/Desktop/pychess-trunk/lib/pychess/widgets/gamewidget.py:406:
GtkWarning: gtk_widget_size_allocate(): attempt to allocate widget with
width 1 and height -1
  headbook.set_tab_label_packing(gmwidg.notebookKey, True, True,
gtk.PACK_START)
/home/leonardo/Desktop/pychess-trunk/lib/pychess/Main.py:473: GtkWarning:
gtk_widget_size_allocate(): attempt to allocate widget with width 1 and
height -1
  gtk.main()
10534: prioridade antiga = 0; prioridade nova = 15
10545: prioridade antiga = 0; prioridade nova = 15
/home/leonardo/Desktop/pychess-trunk/lib/pychess/widgets/ionest.py:354:
GtkWarning: gtk_widget_size_allocate(): attempt to allocate widget with
width 1 and height -1
  response = d.run()

Did you use an installed version of PyChess or did you run in from a
tarball/svn?
svn-trunk

**Comment by pychess** [comment]
Original [comment 1.](https://code.google.com/p/pychess/issues/detail?id=332#c1) posted by [lobais](https://code.google.com/u/lobais/) 2008-10-17

Is this still an issue?
- changed status to: Need-Info

**Comment by pychess** [comment]
Original [comment 2.](https://code.google.com/p/pychess/issues/detail?id=332#c2) posted by [leogregianin](https://code.google.com/u/leogregianin@gmail.com/) 2008-11-02
- changed status to: Fixed
