### ISSUE TITLE
Fischer Randon Chess problem when game with CECPengine's

### ISSUE THREAD

**Issue by ghost** [pychess/pychess#333]
Original [issue 333](https://code.google.com/p/pychess/issues/detail?id=333) reported by [leogregianin](https://code.google.com/u/leogregianin@gmail.com/) 2008-06-09

**What steps will reproduce the problem?**
1. Fischer randon chess problem when game with cecpengine

**What is the expected output? What do you see instead?**

  File "./pychess", line 41, in <module>
    pychess.Main.run(sys.argv[1:])
  File "/home/leonardo/Desktop/pychess-trunk/lib/pychess/Main.py", line
473, in run
    gtk.main()
  File
"/home/leonardo/Desktop/pychess-trunk/lib/pychess/widgets/newGameDialog.py",
line 163, in onResponse
    callback((gamemodel, playertups[0], playertups[1]))
  File "/home/leonardo/Desktop/pychess-trunk/lib/pychess/Main.py", line
263, in callback
    ionest.generalStart(*startdata)
  File
"/home/leonardo/Desktop/pychess-trunk/lib/pychess/widgets/ionest.py", line
57, in generalStart
    worker.execute()
  File
"/home/leonardo/Desktop/pychess-trunk/lib/pychess/System/GtkWorker.py",
line 156, in execute
    self.start()
  File
"/home/leonardo/Desktop/pychess-trunk/lib/pychess/System/ThreadPool.py",
line 103, in start
    pool.start(self.run)
  File
"/home/leonardo/Desktop/pychess-trunk/lib/pychess/System/GtkWorker.py",
line 159, in run
    self.result = self.func(self)
  File
"/home/leonardo/Desktop/pychess-trunk/lib/pychess/widgets/ionest.py", line
38, in <lambda>
    workfunc(w, gamemodel, player0tup, player1tup, loaddata))
  File
"/home/leonardo/Desktop/pychess-trunk/lib/pychess/widgets/ionest.py", line
124, in workfunc
    player.setBoard(gamemodel)
  File
"/home/leonardo/Desktop/pychess-trunk/lib/pychess/Players/CECPEngine.py",
line 418, in setBoard
    if "fischerandom" in self.features["variants"] and \
<type 'exceptions.KeyError'> 'variants'

Did you use an installed version of PyChess or did you run in from a
tarball/svn?
svn-trunk

**Comment by pychess** [comment]
Original [comment 1.](https://code.google.com/p/pychess/issues/detail?id=333#c1) posted by [gbtami](https://code.google.com/u/gbtami/) 2008-06-09

I'v added default variants="" option to CECP engines init (r1038), as a workaround,
but the correct solution would be to filter players dropdown with supporting engines.
- changed status to: Started

**Comment by pychess** [comment]
Original [comment 2.](https://code.google.com/p/pychess/issues/detail?id=333#c2) posted by [gbtami](https://code.google.com/u/gbtami/) 2008-09-13

Now the user can select from any engines he installed and he can chose shuffle or 960
too without any alert that the angine is not supporting that variant. The game
starts, but later when a non standard castling occurs, the engine will die with
illegal move.
Any ideas how to solve this pb?

**Comment by pychess** [comment]
Original [comment 3.](https://code.google.com/p/pychess/issues/detail?id=333#c3) posted by [lobais](https://code.google.com/u/lobais/) 2008-09-14

The filter idea seams to me as a good solution.
Another option would be using fen loading to set up the randomized layout.

**Comment by pychess** [comment]
Original [comment 4.](https://code.google.com/p/pychess/issues/detail?id=333#c4) posted by [gbtami](https://code.google.com/u/gbtami/) 2008-09-18

Added filtering players combo with selected variant in rev 1086.

**Comment by pychess** [comment]
Original [comment 5.](https://code.google.com/p/pychess/issues/detail?id=333#c5) posted by [gbtami](https://code.google.com/u/gbtami/) 2008-09-20
- changed status to: Fixed

**Comment by pychess** [comment]
Original [comment 6.](https://code.google.com/p/pychess/issues/detail?id=333#c6) posted by [lobais](https://code.google.com/u/lobais/) 2008-09-20

I got this from FICS:

...
option name Contempt Factor type spin default 0 min -1000 max 1000
uciok
setoption name UCI_Chess960 value true

## 19:20:18

isready
readyok
ucinewgame
position fen rnnkrqbb/pppppppp/8/8/3P4/8/PPP1PPPP/RNNKRQBB b KQkq d3 0 1
go depth 3
board_from_fen(): bad FEN (pos=48)
stop
quit
Exitcode 256 Unknown error 256

**Comment by pychess** [comment]
Original [comment 7.](https://code.google.com/p/pychess/issues/detail?id=333#c7) posted by [gbtami](https://code.google.com/u/gbtami/) 2008-09-20

Huh. How can you produce this?

**Comment by pychess** [comment]
Original [comment 8.](https://code.google.com/p/pychess/issues/detail?id=333#c8) posted by [lobais](https://code.google.com/u/lobais/) 2008-09-20

Well, I can't reproduce it everytime, so it seams like fruit don't agree with you on
the board generation...
I had the problem again here:
"position fen bnqbnrkr/pppppppp/8/8/8/4P3/PPPP1PPP/BNQBNRKR b KQkq - 0 1
go depth 3
board_from_fen(): bad FEN (pos=49)"

**Comment by pychess** [comment]
Original [comment 9.](https://code.google.com/p/pychess/issues/detail?id=333#c9) posted by [gbtami](https://code.google.com/u/gbtami/) 2008-09-21

Seems Fruit has problems with Chess960 :(
If you change the line 130 in frischerandom.py
from
        tmp = tmp + '/pppppppp/8/8/8/8/PPPPPPPP/' + tmp.upper() + ' w KQkq - 0 1'
to
        tmp = 'bnqbnrkr/pppppppp/8/8/8/8/PPPPPPPP/BNQBNRKR w KQkq - 0 1'

then play e3, Fruit fails, Glaurung and PyChess is ok.

**Comment by pychess** [comment]
Original [comment 10.](https://code.google.com/p/pychess/issues/detail?id=333#c10) posted by [lobais](https://code.google.com/u/lobais/) 2008-09-21

Strange, perhaps you should report it to the fruit writers. Then we'll also have
their view on the issue.
