### ISSUE TITLE
Chat panel bug

### ISSUE THREAD

**Issue by ghost** [pychess/pychess#334]
Original [issue 334](https://code.google.com/p/pychess/issues/detail?id=334) reported by [leogregianin](https://code.google.com/u/leogregianin@gmail.com/) 2008-06-09

**What steps will reproduce the problem?**
1. Computer without internet
2. Game between two chess engines
3. Traceback error (below)
4. Game is stopped

**What is the expected output? What do you see instead?**

Traceback (most recent call last):
  File "/home/leonardo/Desktop/pychess-trunk/sidepanel/chatPanel.py", line
40, in onGameStarted
    self.player.connect("messageRecieved", self.onMessageReieved)
AttributeError: Sidepanel instance has no attribute 'player'

Did you use an installed version of PyChess or did you run in from a
tarball/svn?
svn-trunk

**Comment by pychess** [comment]
Original [comment 1.](https://code.google.com/p/pychess/issues/detail?id=334#c1) posted by [lobais](https://code.google.com/u/lobais/) 2008-09-20

Has this been fixed in trunk?

**Comment by pychess** [comment]
Original [comment 2.](https://code.google.com/p/pychess/issues/detail?id=334#c2) posted by [leogregianin](https://code.google.com/u/leogregianin@gmail.com/) 2008-10-06
- changed status to: Fixed
