### ISSUE TITLE
There is no (player1 vs. player2) tab when the very first game started

### ISSUE THREAD

**Issue by ghost** [pychess/pychess#335]
Original [issue 335](https://code.google.com/p/pychess/issues/detail?id=335) reported by [gbtami](https://code.google.com/u/gbtami/) 2008-06-09

So the names of players(engines) are hidden.

**Comment by pychess** [comment]
Original [comment 1.](https://code.google.com/p/pychess/issues/detail?id=335#c1) posted by [lobais](https://code.google.com/u/lobais/) 2008-06-12

And "Hide tabs when only one game is open" is not checked in the preferences?

**Comment by pychess** [comment]
Original [comment 2.](https://code.google.com/p/pychess/issues/detail?id=335#c2) posted by [gbtami](https://code.google.com/u/gbtami/) 2008-06-13

No, it's not checked.

**Comment by pychess** [comment]
Original [comment 3.](https://code.google.com/p/pychess/issues/detail?id=335#c3) posted by [gbtami](https://code.google.com/u/gbtami/) 2008-09-12
- changed status to: Fixed
