### ISSUE TITLE
Illegal Move into Check After a Promotion

### ISSUE THREAD

**Issue by pychess** [pychess/pychess#338]
Original [issue 338](https://code.google.com/p/pychess/issues/detail?id=338) reported by [gao.mutian](https://code.google.com/u/105321390380475208509/) 2008-08-11

This might be a chess engine error, but I wanted to mention it in case the
engine was confused by some internal reporting error about promotions.

Summary:

I ran a Crafty vs. Glaurung match (I believe both were on expert). 
Everything went smoothly until Crafty promoted a pawn to queen.  Glaurung
then moved the king into check to take a piece guarded by the now-promoted
queen.  The game then hung there.  However, the program was fine and
successfully ran other tabs.  On reloading the saved move history (saved at
the hang so that it included the illegal move), it undid the illegal move
and played to the end successfully.  Altering the move history save file to
BEFORE the promotion, however, reproduced the error.

**What steps will reproduce the problem?**
1. I had to erase to before the promotion to reproduce it.  I attach the
altered save I used to reproduce it.

**What is the expected output? What do you see instead?**
See above.

**Does it happen every time?**
Consistently with the altered save file.  Perhaps other tests can be run on
promotions to see if it is not unique to this match.

**What version of the product are you using?**
Philidor 0.8.1

Did you use an installed version of PyChess or did you run in from a
tarball/svn?
I obtained it through the Ubuntu Synaptic Package Manger 

FILE NOTES:
1. 'GvC_glaurungError.pgn' is the save from the hang, so that it includes
   the illegal move.
2. 'Altered.pgn' is the same file with the move history erased to slightly
   before the promotion.
3. 'GvC_trial1_worked.pgn' is the result of reloading comment 1. from the hang and
   letting it play through to the end.
4. 'error.png' is a sample screenshot of the illegal move

Thank you for your time!

**Comment by pychess** [comment]
- attached [GvC_trial1_worked.pgn](https://code.google.com/p/pychess/issues/detail?id=338#c0)
- attached [error.png](https://code.google.com/p/pychess/issues/detail?id=338#c0)
- attached [GvC_glaurungError.pgn](https://code.google.com/p/pychess/issues/detail?id=338#c0)
- attached [altered.pgn](https://code.google.com/p/pychess/issues/detail?id=338#c0)

**Comment by pychess** [comment]
Original [comment 1.](https://code.google.com/p/pychess/issues/detail?id=338#c1) posted by [lobais](https://code.google.com/u/lobais/) 2008-08-28

I believe this is firstly a Glaurung problem, as only Glaurung ignores this check -
right?
I'm not sure how PyChess should react on bugge engines though. We should probably
take a stand.
1) Make the engine loose
2) Let the user choose another move for the engine (only possible for engines, that
support save/load)
3) Let PyChess engine choose another move for the engine (only possible for engines,
that support save/load. Otherwise it could overtake the position)
4) Bring up an error dialog, end the game, and let user save it, and open it with
another engine.

Any other ideas?

Likewise thanks for your time testing.
- changed status to: Accepted

**Comment by pychess** [comment]
Original [comment 2.](https://code.google.com/p/pychess/issues/detail?id=338#c2) posted by [lobais](https://code.google.com/u/lobais/) 2009-02-10
- changed status to: Need-Info

**Comment by pychess** [comment]
Original [comment 3.](https://code.google.com/p/pychess/issues/detail?id=338#c3) posted by [jonas.thiem](https://code.google.com/u/jonas.thiem@gmail.com/) 2012-08-30

xboard/winboard treat any illegal move as instant defeat, which I find fair (engines should be able to play legal chess moves purely, and if they can't they're obviously not up to winning a game).

However, some sort of notification that the engine didn't resign voluntarily but were force-resigned since they attempted to play an illegal move would be good (xboard/winboard have that too).

I think that also matches what happens in a "real" computer chess tournament held by chess clubs: if your engine fails to suggest a legal move, the game is lost.

**Comment by pychess** [comment]
Original [comment 4.](https://code.google.com/p/pychess/issues/detail?id=338#c4) posted by [gbtami](https://code.google.com/u/gbtami/) 2013-04-25

We fixed the adjudication on illegal move part before, so I change the rest to "enhancement".
- changed status to: Accepted
- removed label: Defect
- added label: Enhancement

**Comment by pychess** [comment]
Original [comment 5.](https://code.google.com/p/pychess/issues/detail?id=338#c5) posted by [G.nius.ck](https://code.google.com/u/112084229900022559058/) 2013-07-09

We could also have it lose time like for humans (if it so doesn't get the message, it can lose on time.)

**Comment by gbtami** [comment]
Fixed before.
