### ISSUE TITLE
gobject not imported

### ISSUE THREAD

**Issue by ghost** [pychess/pychess#340]
Original [issue 340](https://code.google.com/p/pychess/issues/detail?id=340) reported by [michel.sylvan](https://code.google.com/u/106783242436572907187/) 2008-08-27

**What steps will reproduce the problem?**
1. Run pychess

**What is the expected output? What do you see instead?**
Should work. Instead, a crash because in newGameDialog.py, an exception
defined in gobject is caught without gobject being imported

Did you use an installed version of PyChess or did you run in from a
tarball/svn?
Installed

**Comment by pychess** [comment]
- attached [pychess-0.8.2-gobject.patch](https://code.google.com/p/pychess/issues/detail?id=340#c0)

**Comment by pychess** [comment]
Original [comment 1.](https://code.google.com/p/pychess/issues/detail?id=340#c1) posted by [lobais](https://code.google.com/u/lobais/) 2008-08-28

Thanks for the patch.
- changed status to: Accepted

**Comment by pychess** [comment]
Original [comment 2.](https://code.google.com/p/pychess/issues/detail?id=340#c2) posted by [lobais](https://code.google.com/u/lobais/) 2008-09-20
- changed status to: Fixed
