### ISSUE TITLE
white pieces should be white even over black squares

### ISSUE THREAD

**Issue by ghost** [pychess/pychess#341]
Original [issue 341](https://code.google.com/p/pychess/issues/detail?id=341) reported by [missive@hotmail.com](https://code.google.com/u/112846409828153670364/) 2008-09-14

**What steps will reproduce the problem?**
1. Start game
2. White pieces are different colors over different color squares

**What is the expected output? What do you see instead?**
White pieces should always be the same color, no matter which
color square they are on (like the black pieces are)

**Does it happen every time?**
Yes

**What version of the product are you using?**
0.8.1

Did you use an installed version of PyChess or did you run in from a
tarball/svn?
Installed on Ubuntu 8.04

**Please provide any additional information below.**

**Please attach the latest pychess logfile.**
For PyChess <= 0.6.x it's hidden in your homedirectory and called
".pychess.log".
For PyChess > 0.6.x, it's in a hidden folder, under your homedirectory,
named ".pychess/"
21:37:51 Default Debug: Started
21:37:53 stdout Debug:
/usr/lib/python2.5/site-packages/pychess/Main.py:489: GtkWar
ning: gtk_widget_size_allocate(): attempt to allocate widget with width 209
and hei
ght -37
  gtk.main()

**Comment by pychess** [comment]
- attached [after.png](https://code.google.com/p/pychess/issues/detail?id=341#c0)
- attached [before.png](https://code.google.com/p/pychess/issues/detail?id=341#c0)

**Comment by pychess** [comment]
Original [comment 1.](https://code.google.com/p/pychess/issues/detail?id=341#c1) posted by [lobais](https://code.google.com/u/lobais/) 2008-09-17

It's not like they are a different color. They are just transparent.
This is a theme issue, and it will be fixed when themes are implemented.
- changed status to: Duplicate
