### ISSUE TITLE
Download link is wrong

### ISSUE THREAD

**Issue by ghost** [pychess/pychess#343]
Original [issue 343](https://code.google.com/p/pychess/issues/detail?id=343) reported by [thijsvermeir](https://code.google.com/u/101386254946966013986/) 2008-09-16

**What steps will reproduce the problem?**
1. http://pychess.googlepages.com/download
2. check the link for the stable release

This link probably should point to:
http://code.google.com/p/pychess/downloads/list

**Comment by pychess** [comment]
Original [comment 1.](https://code.google.com/p/pychess/issues/detail?id=343#c1) posted by [lobais](https://code.google.com/u/lobais/) 2008-09-16

googlepages is back up.
We want people to download from there, as it improves our rating and adds even more
downloads to the total.
- changed status to: Invalid
