### ISSUE TITLE
Update taskers to use new difficulty system

### ISSUE THREAD

**Issue by ghost** [pychess/pychess#345]
Original [issue 346](https://code.google.com/p/pychess/issues/detail?id=346) reported by [gbtami](https://code.google.com/u/gbtami/) 2008-09-17

**What steps will reproduce the problem?**
1. Played a game against PyChess from quickstarter
2. After my 0-0 it doesn't made any move

14:59:36 Default Debug: Started
14:59:40 (u'Python', '14:09:40.753') Debug: /usr/bin/python
14:59:40 (u'Python', '14:09:40.753') Debug: Black
14:59:40 (u'Python', '14:09:40.753') Log: xboard
14:59:40 (u'Python', '14:09:40.753') Log: protover 2
14:59:41 (u'Python', '14:09:40.753') Debug: feature draw=1 reuse=0
myname='PyChess 0.9' usermove=1 setboard=1 sigterm=1 analyze=1
variants='normal,nocastle,fischerandom' done=1
14:59:41 (u'Python', '14:09:40.753') Log: nopost
14:59:41 (u'Python', '14:09:40.753') Log: sd 0
14:59:41 (u'Python', '14:09:40.753') Log: hard
14:59:41 (u'Python', '14:09:40.753') Log: easy
14:59:41 (u'Python', '14:09:40.753') Log: level 0 5 0
14:59:50 (u'Python', '14:09:40.753') Log: time 30000
14:59:50 (u'Python', '14:09:40.753') Log: otim 30000
14:59:50 (u'Python', '14:09:40.753') Log: usermove e2e4
14:59:50 (u'Python', '14:09:40.753') Debug: Playing 0 moves in 300 seconds
- 0 increment
  14:59:51 (u'Python', '14:09:40.753') Debug: move c5
  15:00:00 (u'Python', '14:09:40.753') Log: time 29991
  15:00:00 (u'Python', '14:09:40.753') Log: otim 29134
  15:00:00 (u'Python', '14:09:40.753') Log: usermove g1f3
  15:00:00 (u'Python', '14:09:40.753') Debug: move d6
  15:00:21 (u'Python', '14:09:40.753') Log: time 29973
  15:00:21 (u'Python', '14:09:40.753') Log: otim 27084
  15:00:21 (u'Python', '14:09:40.753') Log: usermove b1c3
  15:00:21 (u'Python', '14:09:40.753') Debug: move Nf6
  15:00:24 (u'Python', '14:09:40.753') Log: time 29961
  15:00:24 (u'Python', '14:09:40.753') Log: otim 26773
  15:00:24 (u'Python', '14:09:40.753') Log: usermove d2d4
  15:00:24 (u'Python', '14:09:40.753') Debug: move cxd4
  15:00:26 (u'Python', '14:09:40.753') Log: time 29946
  15:00:26 (u'Python', '14:09:40.753') Log: otim 26633
  15:00:26 (u'Python', '14:09:40.753') Log: usermove f3d4
  15:00:26 (u'Python', '14:09:40.753') Debug: move a6
  15:00:38 (u'Python', '14:09:40.753') Log: time 29936
  15:00:38 (u'Python', '14:09:40.753') Log: otim 25432
  15:00:38 (u'Python', '14:09:40.753') Log: usermove a2a4
  15:00:38 (u'Python', '14:09:40.753') Debug: move Nc6
  15:00:42 (u'Python', '14:09:40.753') Log: time 29924
  15:00:42 (u'Python', '14:09:40.753') Log: otim 25066
  15:00:42 (u'Python', '14:09:40.753') Log: usermove f1e2
  15:00:42 (u'Python', '14:09:40.753') Debug: move e6
  15:00:43 (u'Python', '14:09:40.753') Log: time 29911
  15:00:43 (u'Python', '14:09:40.753') Log: otim 24900
  15:00:43 (u'Python', '14:09:40.753') Log: usermove e1g1
  15:00:43 (u'Python', '14:09:40.753') Debug: Time left: 299.11 seconds; Plan
  to thinking for 9.20 seconds
  15:00:43 (u'Python', '14:09:40.753') Debug: I searched through depths [1, 1]
  15:00:43 (u'Python', '14:09:40.753') Debug:   File
  "/home/tamas/svn/pychess/trunk/lib/pychess/Players/PyChess.py", line 336,
  in <module>
  15:00:43 (u'Python', '14:09:40.753') Debug:     pool.start(go, q)
  15:00:43 (u'Python', '14:09:40.753') Debug:   File
  "/home/tamas/svn/pychess/trunk/lib/pychess/Players/PyChess.py", line 276, in go
  15:00:43 (u'Python', '14:09:40.753') Debug:     if not mvs:
  15:00:43 (u'Python', '14:09:40.753') Warning: <type
  'exceptions.UnboundLocalError'> local variable 'mvs' referenced before
  assignment

**Comment by pychess** [comment]
Original [comment 1.](https://code.google.com/p/pychess/issues/detail?id=346#c1) posted by [lobais](https://code.google.com/u/lobais/) 2008-09-17

You started this game from the quick thingy, right?
It isn't updated to the new difficulties system, so it generates so low levels (0)
that PyChess won't search a single ply (Note: "I searched through depths [1, 1]")
- changed summary to: Update taskers to use new difficulty system

**Comment by pychess** [comment]
Original [comment 2.](https://code.google.com/p/pychess/issues/detail?id=346#c2) posted by [gbtami](https://code.google.com/u/gbtami/) 2008-09-18

Ok, I see now.

**Comment by pychess** [comment]
Original [comment 3.](https://code.google.com/p/pychess/issues/detail?id=346#c3) posted by [lobais](https://code.google.com/u/lobais/) 2008-09-18
- changed status to: Started

**Comment by pychess** [comment]
Original [comment 4.](https://code.google.com/p/pychess/issues/detail?id=346#c4) posted by [lobais](https://code.google.com/u/lobais/) 2008-09-20

Also now using glade
- changed status to: Fixed
