### ISSUE TITLE
PyChess gets unstable after a game has been closed

### ISSUE THREAD

**Issue by ghost** [pychess/pychess#346]
Original [issue 347](https://code.google.com/p/pychess/issues/detail?id=347) reported by [lobais](https://code.google.com/u/lobais/) 2008-09-20

**What steps will reproduce the problem?**
1. Start a game
2. Close it on the X
3. Aggressively press some UI component, like a menuitem.

**What is the expected output? What do you see instead?**
Half of the time PyChess crashes with something like
"08294e73-c174-0861-392610b8-223251f7 is dumped"
The other half it just spits a lot of strange warnings out:
"Main.py:228: Warning: instance of invalid non-instantiatable type
`(null)'" or "python: xcb_io.c:120: process_responses: Assertion
(assertion) '!(req &amp;&amp; current_request &amp;&amp; !((int) ((req->sequence) -
(current_request)) <= 0))' failed."

While no games has been closed yet (none started or just still running)
everything is as stable as a rock.

Did you use an installed version of PyChess or did you run in from a
tarball/svn?
Trunk

**Comment by pychess** [comment]
Original [comment 1.](https://code.google.com/p/pychess/issues/detail?id=347#c1) posted by [lobais](https://code.google.com/u/lobais/) 2008-09-20

It might be a gtkbug, but it seams to work after I changed the widget.unparent()
calls, in gamewidget, with parent.remove(widget) calls.
- changed status to: Fixed
