### ISSUE TITLE
closable sidepanels

### ISSUE THREAD

**Issue by pychess** [pychess/pychess#347]
Original [issue 348](https://code.google.com/p/pychess/issues/detail?id=348) reported by [gbtami](https://code.google.com/u/gbtami/) 2008-09-20

It would be useful if sidepanels can be closable somehow. Maybe with new
togglable menuitems in the view menu, similar to "Log Viewer".

Usually I want to see only the Move History panel. I can rearrange the
layout to get this goal, but there is no easy way to open another panel
with one click later.

**Comment by pychess** [comment]
Original [comment 1.](https://code.google.com/p/pychess/issues/detail?id=348#c1) posted by [lobais](https://code.google.com/u/lobais/) 2008-09-20

If you look in PyChess.glade in the preferences window, you'll see, that there is
actually a Sidepanels tab. This is because sidepanels were from start meant to be
like firefox extensions.

While we don't need to implement all that install/uninstall stuff, we could perhaps
implement the Disable button.

**Comment by pychess** [comment]
Original [comment 2.](https://code.google.com/p/pychess/issues/detail?id=348#c2) posted by [lobais](https://code.google.com/u/lobais/) 2009-02-10

There are still some major problems on this one,
like:
- Hide all panels (view menu)
- Uncheck a panel (preferenes)
- Check the panel
- Show all panels
  or:
- Uncheck all panels (preferences)
- Hide all panels (view menu)

These doesn't look to easy to fix. They currently both do nasty things to the UI,
especially the last one. If we can't find a solution, we might have to postpone it to
the next release.
- changed status to: Started

**Comment by pychess** [comment]
Original [comment 3.](https://code.google.com/p/pychess/issues/detail?id=348#c3) posted by [gbtami](https://code.google.com/u/gbtami/) 2009-02-10

Agreed on postpone.

**Comment by pychess** [comment]
Original [comment 4.](https://code.google.com/p/pychess/issues/detail?id=348#c4) posted by [pe3kuv](https://code.google.com/u/116109811260609265599/) 2009-02-23

I found sidepanels in preferences in "rev 1401", but will always crash when trying to
uncheck "Comments" (did not try the others). Btw. no matter if it is checked or not
in preferences, Comments sidepanel is still shown (even after restart).
See attached logfile and bugbuddy files.
This is terminal output:
petko@petkomp:~/src/pychess-read-only$ PYTHONPATH=~/src/pychess-read-only/lib
~/src/pychess-read-only/pychess
/home/petko/src/pychess-read-only/lib/pychess/System/uistuff.py:368: GtkWarning:
GtkSpinButton: setting an adjustment with non-zero page size is deprecated
  self.glade = gtk.glade.XML(addDataPrefix("glade/%s" % filename))
Toggle 'commentPanel' to: False
- attached [2009-02-23_23-46-47.log](https://code.google.com/p/pychess/issues/detail?id=348#c4)
- attached [PyChess Staunton 0.10alpha2-hlaseniochybe.txt](https://code.google.com/p/pychess/issues/detail?id=348#c4)

**Comment by pychess** [comment]
Original [comment 5.](https://code.google.com/p/pychess/issues/detail?id=348#c5) posted by [gbtami](https://code.google.com/u/gbtami/) 2009-05-26

I'v just committed a try in rev.1472. While I know it's far from perfect, but what do
you think about this concept of using a skeleton gamewidget as a visual helper?

**Comment by pychess** [comment]
Original [comment 6.](https://code.google.com/p/pychess/issues/detail?id=348#c6) posted by [mattgatto](https://code.google.com/u/mattgatto/) 2009-05-28

I can't rearrange the sidepanels any more. Am I just retarded or is this not possible
anymore?

**Comment by pychess** [comment]
Original [comment 7.](https://code.google.com/p/pychess/issues/detail?id=348#c7) posted by [lobais](https://code.google.com/u/lobais/) 2009-05-29

I haven't been able to test the solution yet, but using a skeleton might be the 
right solution.
Our problem is always, that we don't have a good way to store the position 
of 'disabled' or 'closed' sidepanels. Because locations are relative to other 
sidepanels these 'ghostly' panels make things very difficult.
If you can come up with an entirely different solution for panel location, that also 
lets you insert panels into the middle of the crowd, then we should probably go for 
it for 0.10.

**Comment by pychess** [comment]
Original [comment 8.](https://code.google.com/p/pychess/issues/detail?id=348#c8) posted by [gbtami](https://code.google.com/u/gbtami/) 2009-05-29

mattgatto: Is your pb is the same as issue #461? Albeit it's not related to preferences.

lobais: The closed sidepanels can have no good enough saved "position", because the
layout can be very different after closing it, and then removing/closing it's
parent/neighbours.
I think this skeleton solution works ok, except the "zoom to board" menu. But maybe
that can be implemented in a different way. Something like saving the layout before
zooming in, then undock all panels, and restoring panels from xml when zooming out.

**Comment by pychess** [comment]
Original [comment 9.](https://code.google.com/p/pychess/issues/detail?id=348#c9) posted by [mattgatto](https://code.google.com/u/mattgatto/) 2009-05-31

Alright, I guess I was retarded because re-arranging them works fine now... Sorry.

**Comment by pychess** [comment]
Original [comment 10.](https://code.google.com/p/pychess/issues/detail?id=348#c10) posted by [lobais](https://code.google.com/u/lobais/) 2009-06-01

I've tried out the sceleton idea now, and I like it a lot.
It probably needs some visual clues, like hiding the tabbar and coloring stuff in
some color :P

I also think I figured out a good way to handle reopening of panels, so we can avoid
stacking them all to the right, as we do now: Instead of checkboxes we let people
drag the panels from the preferences to the game window. Just like when you rearrange
your firefox window.

Another interesting possibility, using the sceleton approach, is that we can freeze
tabs and scales in the playing window. This way we can make things more compact and
nice, while avoiding bad things from happening due to drag and drop (like when you
accidentally drag folders into other folders, and don't know where they went)

**Comment by pychess** [comment]
Original [comment 11.](https://code.google.com/p/pychess/issues/detail?id=348#c11) posted by [gbtami](https://code.google.com/u/gbtami/) 2009-06-02

Wow, dragging panels from preferences instead of using checkboxes, very nice idea!

**Comment by pychess** [comment]
Original [comment 12.](https://code.google.com/p/pychess/issues/detail?id=348#c12) posted by [gbtami](https://code.google.com/u/gbtami/) 2010-09-11
- changed status to: Fixed

**Comment by gbtami** [comment]
Database and ICS sidepanels are not closable in Preferences yet.

**Comment by gbtami** [comment]
All side panels can be show/hide from View menu from now on.
