### ISSUE TITLE
Why sidepanels belongs to DATA_FILES in setup.py ?

### ISSUE THREAD

**Issue by ghost** [pychess/pychess#348]
Original [issue 349](https://code.google.com/p/pychess/issues/detail?id=349) reported by [gbtami](https://code.google.com/u/gbtami/) 2008-09-20

Now sidepanel dir contains .glage and .py files, and setup.py handles them
as data. It can be more consistent to move .glade files to glade dir and
.py files to a sidepanels package.

**Comment by pychess** [comment]
Original [comment 1.](https://code.google.com/p/pychess/issues/detail?id=349#c1) posted by [lobais](https://code.google.com/u/lobais/) 2008-09-20

I think moving glades to the glade dir would make sidepanels less modular. I like the
idea, that you can just put a .py file there + its datas, and it is in the game.
We could of cource give each sidepanel its own folder..

**Comment by pychess** [comment]
Original [comment 2.](https://code.google.com/p/pychess/issues/detail?id=349#c2) posted by [gbtami](https://code.google.com/u/gbtami/) 2008-09-20

Ok, i can live with it :)
- changed status to: WontFix
