### ISSUE TITLE
"Offer undo" bug

### ISSUE THREAD

**Issue by ghost** [pychess/pychess#350]
Original [issue 350](https://code.google.com/p/pychess/issues/detail?id=350) reported by [gbtami](https://code.google.com/u/gbtami/) 2008-09-30

**What steps will reproduce the problem?**
1. Start a quick game against PyChess
2. Take 2 move avoiding tha book
3. Befor PyChess 2. move chose "Offer undo" from actions menu

**What is the expected output? What do you see instead?**
The program is frozen

Did you use an installed version of PyChess or did you run in from a
tarball/svn?
svn 1169

**Comment by pychess** [comment]
Original [comment 1.](https://code.google.com/p/pychess/issues/detail?id=350#c1) posted by [lobais](https://code.google.com/u/lobais/) 2008-09-30

It's only frozen on cecp engines, and only until the computer makes its move.
However, it is certainly a bug, and working on it.
- changed status to: Started

**Comment by pychess** [comment]
Original [comment 2.](https://code.google.com/p/pychess/issues/detail?id=350#c2) posted by [lobais](https://code.google.com/u/lobais/) 2008-10-06

This should be fixed in latest revisions.
- changed status to: Fixed
