### ISSUE TITLE
consider supporting handicap 'odds' chess

### ISSUE THREAD

**Issue by pychess** [pychess/pychess#352]
Original [issue 352](https://code.google.com/p/pychess/issues/detail?id=352) reported by [MichaelDavidJay](https://code.google.com/u/103249166689454827955/) 2008-10-11

I rather enjoy playing odds chess -- it makes for a rather interesting
game.  It would be interesting to keep player records and auto-handicap
odds games, so the computer knows what sort of handicap to offer.  Perhaps
this could be combined with a ELO estimator. 

<clearly this is only a wish-list item>

**Comment by pychess** [comment]
Original [comment 1.](https://code.google.com/p/pychess/issues/detail?id=352#c1) posted by [gbtami](https://code.google.com/u/gbtami/) 2008-10-12

The next release will contain support for several chess variants. At this time
Shuffle(nocastle), Fischer Random, Upside-down and Losers are implemented. Adding
Odds chess seems easy, at least material variants. Extra move(s) handicap is a bit
complicated, as it needs to change the white move, black move logic.
- changed status to: Accepted
- removed label: Defect
- added label: Enhancement

**Comment by pychess** [comment]
Original [comment 2.](https://code.google.com/p/pychess/issues/detail?id=352#c2) posted by [gbtami](https://code.google.com/u/gbtami/) 2009-06-11
- changed status to: Started

**Comment by gbtami** [comment]
Material odds are supported, so I close this.
