### ISSUE TITLE
Add finger and follow buttons to players tab in FICS lounge

### ISSUE THREAD

**Issue by pychess** [pychess/pychess#473]
Original [issue 473](https://code.google.com/p/pychess/issues/detail?id=473) reported by [igor2x](https://code.google.com/u/116691631290437288902/) 2009-07-04

FICS | Player List add more info about player like how many games he/she
won, lose, draw. This info is probably available, it is available for "me"
obove "News" section.

**Comment by pychess** [comment]
Original [comment 1.](https://code.google.com/p/pychess/issues/detail?id=473#c1) posted by [lobais](https://code.google.com/u/lobais/) 2009-07-04

I'm afraid this info isn't available in listform, so PyChess would have to query
every single online user.
A way to do this would probably be to have a 'finger' button that displays info like
this in a window, or something: http://www.freechess.org/Help/HelpFiles/finger.html
Guests are not allowed to watch as much info, though.

**Comment by pychess** [comment]
Original [comment 2.](https://code.google.com/p/pychess/issues/detail?id=473#c2) posted by [gbtami](https://code.google.com/u/gbtami/) 2009-08-16
- added label: Enhancement

**Comment by pychess** [comment]
Original [comment 3.](https://code.google.com/p/pychess/issues/detail?id=473#c3) posted by [igor2x](https://code.google.com/u/116691631290437288902/) 2009-08-31

It would also be interesting of having an info about user's country he/she is from.
Few days ago I played with madam from Japan, today I have played with man from Brazil
- we had a chat. It is probably hard to do (or impossible) but it would be
  interesting of having info like national flag from which the person is coming from.

**Comment by pychess** [comment]
Original [comment 4.](https://code.google.com/p/pychess/issues/detail?id=473#c4) posted by [lobais](https://code.google.com/u/lobais/) 2009-08-31

Yes, I've always wanted that too, but there seems to be no way in fics to get to know
peoples country.

**Comment by pychess** [comment]
Original [comment 5.](https://code.google.com/p/pychess/issues/detail?id=473#c5) posted by [gbtami](https://code.google.com/u/gbtami/) 2013-04-06
- changed status to: Accepted
- changed summary to: Add finger and follow buttons to players tab in FICS lounge

**Comment by pychess** [comment]
Original [comment 6.](https://code.google.com/p/pychess/issues/detail?id=473#c6) posted by [gbtami](https://code.google.com/u/gbtami/) 2013-04-06

issue #747 has been merged into this issue.

**Comment by gbtami** [comment]
Add link to http://ficsgames.org/cgi-bin/search.cgi?player=playername too.
