### ISSUE TITLE
Annotated PGN support

### ISSUE THREAD

**Issue by pychess** [pychess/pychess#495]
Original [issue 495](https://code.google.com/p/pychess/issues/detail?id=495) reported by [jokoveltman](https://code.google.com/u/113868825465409293678/) 2009-09-30

I would very much enjoy the ability to load a game and then be able to
create variations (preferably more than one ... saveable, of course) at any
point (perhaps every move).  There are already conventions for this in
books (variations are given letters (6a, 22b, etc.)), and placed between
curly braces in PGN files.

For example, I play through a game in a book - which invariably come with
one or more variations which I'd like to play through.  Or maybe I load a
Crafty annotataion file, and would like to see Crafty's suggested lines.

**Comment by pychess** [comment]
Original [comment 1.](https://code.google.com/p/pychess/issues/detail?id=495#c1) posted by [gbtami](https://code.google.com/u/gbtami/) 2009-10-01

There is a "database" branch in svn with preliminary support for variations, at least
for PGN, and boardwidget, but no work started on creating variations with pychess yet.
- changed status to: Started
- added label: Enhancement
- added label: Post-0.10

**Comment by pychess** [comment]
Original [comment 2.](https://code.google.com/p/pychess/issues/detail?id=495#c2) posted by [gbtami](https://code.google.com/u/gbtami/) 2009-10-20
- changed summary to: Variations support

**Comment by pychess** [comment]
Original [comment 3.](https://code.google.com/p/pychess/issues/detail?id=495#c3) posted by [gbtami](https://code.google.com/u/gbtami/) 2011-05-23

Progress!
In gbtami-annotation-panel clone there is a more or less working implementation where you can move in the variations by clicking into them. You have to enable the new panel in the preferences menu first. Committed a sample annotated file too (testing/gamefiles/world_matches.pgn).
http://code.google.com/r/gbtami-annotation-panel/

**Comment by pychess** [comment]
Original [comment 4.](https://code.google.com/p/pychess/issues/detail?id=495#c4) posted by [gbtami](https://code.google.com/u/gbtami/) 2011-06-26

Today I merged the panel stuff to mainline. Please test it!
Notice, there is no add/delete/edit support implemented for comments/variations yet.

**Comment by pychess** [comment]
Original [comment 5.](https://code.google.com/p/pychess/issues/detail?id=495#c5) posted by [lobais](https://code.google.com/u/lobais/) 2011-06-29

Great stuff.

Here are a few things I found:
- When a player changes name, the panel doesn't update. This can happen from the preferences window, but more importantly, the PyChess engine initially has an ugly "python - timestamp" name for fast initialization, which is changed once it tells us its real name.
- The \* star in the Name - Name header, doesn't change when the game finishes. I supposed it should turn into 1/0, 0/1 or similar.
- If you are using FAN notation and a player checkmates, the last move gets displayed twice, both before and after the 0-1 mark.

**Comment by pychess** [comment]
Original [comment 6.](https://code.google.com/p/pychess/issues/detail?id=495#c6) posted by [lobais](https://code.google.com/u/lobais/) 2011-06-29

On the first, there is actually no good way to do this now.
The way ionest does it is by

```
if type == ARTIFICIAL:
    def readyformoves (player, color):
        updateTitle(color)
    players[i].connect("readyForMoves", readyformoves, i)
```

For engines and a conf connect for humans.

**Comment by pychess** [comment]
Original [comment 7.](https://code.google.com/p/pychess/issues/detail?id=495#c7) posted by [mattgatto](https://code.google.com/u/mattgatto/) 2011-07-02

Awesome work Tamás!

**Comment by pychess** [comment]
Original [comment 8.](https://code.google.com/p/pychess/issues/detail?id=495#c8) posted by [gbtami](https://code.google.com/u/gbtami/) 2011-07-06

Comment comment 5. bugs now fixed in tip.

**Comment by pychess** [comment]
Original [comment 9.](https://code.google.com/p/pychess/issues/detail?id=495#c9) posted by [gbtami](https://code.google.com/u/gbtami/) 2011-07-13

Implemented add/edit for comments. You can try it with left/right clicking on moves/comments. Any feedback are welcome!
- changed summary to: Annotated PGN support

**Comment by pychess** [comment]
Original [comment 10.](https://code.google.com/p/pychess/issues/detail?id=495#c10) posted by [mattgatto](https://code.google.com/u/mattgatto/) 2011-07-17

Cool, it works well for me. How would adding new comments work? Maybe an "Add" button on the bottom of the panel that brought up the same "Edit" dialog when you clicked on a move?

**Comment by pychess** [comment]
Original [comment 11.](https://code.google.com/p/pychess/issues/detail?id=495#c11) posted by [gbtami](https://code.google.com/u/gbtami/) 2011-07-17

Right clicking on moves brings up a context menu containing "Add comment". I'm thinking on a new main menu item "Edit", but not sure about submenu items.
Maybe:
Initial game/variation comment
Move comments
Delete remaining moves
Edit game data
Copy to FEN
Paste from FEN

What are you think?

**Comment by pychess** [comment]
Original [comment 12.](https://code.google.com/p/pychess/issues/detail?id=495#c12) posted by [gbtami](https://code.google.com/u/gbtami/) 2013-04-08

TODO: Consider Christopher's suggestion in https://groups.google.com/forum/?fromgroups=#!searchin/pychess-people/nag/pychess-people/FrQXEk6wdfE/Ffx2eqU5t9EJ
Consider what symbols scidb use.

**Comment by pychess** [comment]
Original [comment 13.](https://code.google.com/p/pychess/issues/detail?id=495#c13) posted by [gbtami](https://code.google.com/u/gbtami/) 2013-06-27
- removed label: Post-0.10
- added label: Post-0.12

**Comment by gbtami** [comment]
I think this can be closed for a while. Remaining bugs/enhancements should go to individual issues.
