### ISSUE TITLE
Previous/Next Game & Comments

### ISSUE THREAD

**Issue by pychess** [pychess/pychess#498]
Original [issue 498](https://code.google.com/p/pychess/issues/detail?id=498) reported by [jokoveltman](https://code.google.com/u/113868825465409293678/) 2009-10-20

It is rather cumbersome to have to reopen a file and select a game from a
PGN which has more than one game in it.  If there were  "Next Game" and
"Previous Game" buttons (my preference) or a menu items, that would greatly
ease the use of such files.

Also, PGN files sometimes have comments in them - for example, if they are
exercises, or annotated games.  I for one, would love to see a simple
window/sidepanel to view these.

**Comment by pychess** [comment]
Original [comment 1.](https://code.google.com/p/pychess/issues/detail?id=498#c1) posted by [gbtami](https://code.google.com/u/gbtami/) 2009-10-20

I started to implement all these features in database branch, but have little time
later to roll on. I hope it will be ready for the next major release.
- changed status to: Started
- added label: Enhancement
- added label: Post-0.10

**Comment by pychess** [comment]
Original [comment 2.](https://code.google.com/p/pychess/issues/detail?id=498#c2) posted by [gbtami](https://code.google.com/u/gbtami/) 2011-07-30

I restarted the database work again in gbtami-database clone here:
http://code.google.com/r/gbtami-database/source/checkout

It uses sqlalchemy to easy the work. The new stuff are in lib/pychess/Database/ and in lib/pychess/Savers/database.py
At this moment it can import .pgn files using import.py in Database dir., and then pychess can open games pointing to ~/.locale/share/pychess/pychess.pdb
Game's movelist now stored as arrays of low level int moves (2 byte/move), and comments as unicode text, separated with "|".
Of course these are just experiments, nothing in stone yet.
Any suggestion are welcome.

**Comment by pychess** [comment]
Original [comment 3.](https://code.google.com/p/pychess/issues/detail?id=498#c3) posted by [gbtami](https://code.google.com/u/gbtami/) 2011-09-01

It can import .pgn files from .pgn/.zip/directory starting with --import-pgn option.
Added a new "Open database" to Game menu.
Entering player name to simple gtk completion entry can filter the gamelist.

**Comment by pychess** [comment]
Original [comment 4.](https://code.google.com/p/pychess/issues/detail?id=498#c4) posted by [gbtami](https://code.google.com/u/gbtami/) 2013-06-27
- removed label: Post-0.10
- added label: Release1.0

**Comment by gbtami** [comment]
Fixed using database perspective.
