### ISSUE TITLE
Telepathy multiplayer games

### ISSUE THREAD

**Issue by pychess** [pychess/pychess#503]
Original [issue 503](https://code.google.com/p/pychess/issues/detail?id=503) reported by [wouterstomp](https://code.google.com/u/102934909087409897177/) 2009-11-18

Telepathy is being integrated in the major linux distributions. It would be 
nice if you could use it to easily start a chess game with your friends who 
are online.

**Comment by pychess** [comment]
Original [comment 1.](https://code.google.com/p/pychess/issues/detail?id=503#c1) posted by [gbtami](https://code.google.com/u/gbtami/) 2009-11-24
- added label: Enhancement

**Comment by pychess** [comment]
Original [comment 2.](https://code.google.com/p/pychess/issues/detail?id=503#c2) posted by [gbtami](https://code.google.com/u/gbtami/) 2013-04-20
- changed status to: Accepted
- added label: Low

**Comment by pychess** [comment]
Original [comment 3.](https://code.google.com/p/pychess/issues/detail?id=503#c3) posted by [G.nius.ck](https://code.google.com/u/112084229900022559058/) 2014-04-20

Any telepathy tutorials?

**Comment by gbtami** [comment]
https://telepathy.freedesktop.org/
