### ISSUE TITLE
pylint warnings/errors

### ISSUE THREAD

**Issue by pychess** [pychess/pychess#523]
Original [issue 523](https://code.google.com/p/pychess/issues/detail?id=523) reported by [thomas.spura](https://code.google.com/u/110909423880295359716/) 2010-02-04

This should be a pylint work in progress issue:

When running 'pylint pychess', this file is rated as 7.69/10, which is
pretty good. There are only some Convention warnings.

'pylint Main.py' is a bit funny ;)
Your code has been rated at -23.17/10

There are 35 errors and 275 warnings and some other conventions and
refactor warnings.

I use pylint quite often and it detects some programmi errors, so the
pylint output should be reduce, to better decide, if pychess is error-free.

After just a few modifications in imports, this will become:
Your code has been rated at -8.37/10

At least a good starting point ;)

**Comment by pychess** [comment]
- attached [pylint.patch](https://code.google.com/p/pychess/issues/detail?id=523#c0)

**Comment by pychess** [comment]
Original [comment 1.](https://code.google.com/p/pychess/issues/detail?id=523#c1) posted by [gbtami](https://code.google.com/u/gbtami/) 2010-02-04

Committed, thx!
You are right, pychess need code cleanup and standardisation (pep8).
- changed status to: Started
- added label: Maintainability

**Comment by pychess** [comment]
Original [comment 2.](https://code.google.com/p/pychess/issues/detail?id=523#c2) posted by [gbtami](https://code.google.com/u/gbtami/) 2010-02-04
- added label: Other

**Comment by pychess** [comment]
Original [comment 3.](https://code.google.com/p/pychess/issues/detail?id=523#c3) posted by [thomas.spura](https://code.google.com/u/110909423880295359716/) 2010-02-05

Atm, I do some trivial code cleanup (mostly imports), whenever I ran into real
errors, I prefer to post them here, and let you fix this, till I know more about the
code overall.

Errors in widgets/BoardView.py:
E:500:BoardView.redraw_canvas: Class 'window' has no 'invalidate_rect' member
E:500:BoardView.redraw_canvas: Class 'window' has no 'invalidate_rect' member
E:501:BoardView.redraw_canvas: Class 'window' has no 'process_updates' member
E:501:BoardView.redraw_canvas: Class 'window' has no 'process_updates' member

Errors in widgets/ToggleComboBox.py:
E: 99:ToggleComboBox.menuPos: Class 'window' has no 'get_origin' member
E: 99:ToggleComboBox.menuPos: Class 'window' has no 'get_origin' member
E: 99:ToggleComboBox.menuPos: Class 'window' has no 'get_origin' member
E: 99:ToggleComboBox.menuPos: Class 'window' has no 'get_origin' member
E: 99:ToggleComboBox.menuPos: Class 'window' has no 'get_origin' member

This patch fixes a logical error:
-    if not r0: return r1
-    if not r1: return r0
-    if not r0 and not r1: return None
-    if not r0:
-        if not r1:
-            return None
-        else:
-            return r1
-    elif not r1:
-        return r0

Before "if not r0 and not r1" will never reached, so move that to the front. With my
approach there is one if less.
- attached [pylint.patch](https://code.google.com/p/pychess/issues/detail?id=523#c3)

**Comment by pychess** [comment]
Original [comment 4.](https://code.google.com/p/pychess/issues/detail?id=523#c4) posted by [lobais](https://code.google.com/u/lobais/) 2010-02-06

Hi Thomas, I really appreciate the time you spend, improving PyChess.

I don't know what's going on with these errors, as they seam to be well documented in 
gdk:
http://www.pygtk.org/docs/pygtk/class-gdkwindow.html#method-gdkwindow--invalidate-
rect
http://www.pygtk.org/docs/pygtk/class-gdkwindow.html#method-gdkwindow--process-
updates
http://www.pygtk.org/docs/pygtk/class-gdkwindow.html#method-gdkwindow--get-origin

I would like to comment on the different parts of the patch.

Principally I like the coding standard a lot, but there are some times in practice, 
where I feel it might be non ideal.

The clean up of the imports are very nice. This kind of mess happens when you change 
code, and you really need tools to do the cleaning up.
I also agree that using a wildcard in imports is normally a bad idea, as python will 
spend time executing and importing unnecessary stuff. However, the const module is so 
filled with small integer enum-style globals, that importing every one of them messes 
things heavily up. And because the module contains only integers, there is barely no 
overhead in importing *.

The logical bug is a good catch.
I think the extra if may be well spent in terms of readability though, but the 
not,not line should surely be moved to the front.

Does the empty __init__ method really do anything good?

Is there any reason for the __name__ == "__main__" in the bottom? The file is after 
all not executable. But perhaps this was for pylint to function?

Finally I think, that if you break up method arguments in multiple lines, they should 
align with the parenthesis for readability. Sometimes this is not possible, as in:
cls.widgets["checkbutton1"].set_active(conf.get("show_tip_at_startup", False))
so I'm unsure whether it is best just to keep it a little to long, or to split it up 
like:
cb = cls.widgets["checkbutton1"]
cb.set_active(conf.get("show_tip_at_startup", False))

What do you think?

Thanks a lot,
Thomas

**Comment by pychess** [comment]
Original [comment 6.](https://code.google.com/p/pychess/issues/detail?id=523#c6) posted by [lobais](https://code.google.com/u/lobais/) 2010-02-06

I hope the above doesn't sound negative, as I really appreciate your work, as well as 
the fact, that you've already found at least one 'might be hiding ninja' bug. :)

I also don't want to be the type of guy gardening every line of code, so as you are 
doing the hard work here, I'll stick to the old guidelines, and rest confident in 
your judgement ;)

Cheers,
Thomas

**Comment by pychess** [comment]
Original [comment 7.](https://code.google.com/p/pychess/issues/detail?id=523#c7) posted by [thomas.spura](https://code.google.com/u/110909423880295359716/) 2010-02-06

Hi other Thomas ;)

That's what I wanted to archieve (get comments ;)). You sound more interested than
negative ;)

The main reason, why I purge throught pylint errors/warnings is, that it really helps
me to garant for the working of my program. It mainly detects missing imports or
typos, which would only detected, if the piece of code is actually executed, you are
writing on (not always the case).

Right now, I'm looking into a better way to get just these errors/warnings I want to
get. e.g. there are many convention errors, that the variables are wrongly named.
There won't be a change needed...

If I have a script, that detects, what I want, I'll attach it here again.

Now answer to your comment:
- Then the errors could be a pylint bug. In ipython this method is also existend.
- Do you want to completely ignore the wildcard import or just in case of importing
  own written methods (and not e.g. from gtk import *)?
  This would be horrific to let pylint detect. Better ignore it everywhere in this
  case :(
- You are right, 3 ifs would be better readable. Better use that (pychess is fast
  enought ;) )
  Great to found my first real bug.
- There needs to be a __init__ method, if not, it's not a class by definition.
  I think, it would be better to have an empty one instead of nothing.
- Splitting up improves the readablity, so why not? Will it be that much slower, if
  doing it explicitely? I think this programm does not claim to be 'as fast as
  possible' and this little thing does not matter. The most speed is lost  in calling
  many methods, where a few would do the work too.

Or how do you want to handle the clean up for a stable version?

Thomas

**Comment by pychess** [comment]
Original [comment 8.](https://code.google.com/p/pychess/issues/detail?id=523#c8) posted by [lobais](https://code.google.com/u/lobais/) 2010-02-06

Hi also other Thomas,

For the wildcard, I just wish to use it for 6+ imports, or maybe just for the const module. 
What do you think?

I've never read anywhere that a class must have an explicitly defined __init__ method. 
Neither for python 2.x nor 3.0. Are you sure about that?

splitting up in cb=..., cb.... is fine with me. The speed difference is incredible small, and 
might go entirely away in a future python jit. I'm just not sure, whether it is mroe readable 
than the 88 chars line. But if it is easier for the pylint, then it is probably worth it.

I'm looking forward to see what else you find. :)

Cheers mate.

**Comment by pychess** [comment]
Original [comment 9.](https://code.google.com/p/pychess/issues/detail?id=523#c9) posted by [thomas.spura](https://code.google.com/u/110909423880295359716/) 2010-02-18

Ok, for 6+ imports it would be handy to use a wildcard, this can be disabled in
pylint, so it won't detect this anymore.

,y pylint cmmand is online [1], what I want to run from now on. It could be that I
missed some messages, that we better disable, but it finds severel undefined
variables in lib/pychess/Utils/lutils. Maybe you want to run "./pylint
lib/pychess/Utils/lutils" and search the missing imports ;)

[1]
http://gbirthday.git.sourceforge.net/git/gitweb.cgi?p=gbirthday/gbirthday;a=blob;f=pylint;hb=HEAD

Currently I'm pretty busy, but maybe tomorrow or the weekend, I find some more time
to shoot down some undefined variables or other pylint output.

Warning: I tried to run ./pylint in the main folder and it took more than 1 hour,
till not completing ;) Better start with a subfolder.

**Comment by pychess** [comment]
Original [comment 10.](https://code.google.com/p/pychess/issues/detail?id=523#c10) posted by [thomas.spura](https://code.google.com/u/110909423880295359716/) 2010-02-18

Don't know how to fix this:
https://bugzilla.redhat.com/show\_bug.cgi?id=566611

(Should I open a new issue, for any bug I get like this? This clearly should belong
to pylint stuff, so I filled it here for now.)

Traceback (most recent call last):
  File "/usr/lib/python2.6/site-packages/pychess/Players/PyChess.py", line 828,
in <module>
    pychess.run()
  File "/usr/lib/python2.6/site-packages/pychess/Players/PyChess.py", line 262,
in run
    self.__stopSearching()
  File "/usr/lib/python2.6/site-packages/pychess/Players/PyChess.py", line 385,
in __stopSearching
    self.worker.get()
  File "/usr/lib/python2.6/site-packages/pychess/System/GtkWorker.py", line
162, in get
    return self.result
AttributeError: 'GtkWorker' object has no attribute 'result

**Comment by pychess** [comment]
Original [comment 11.](https://code.google.com/p/pychess/issues/detail?id=523#c11) posted by [mattgatto](https://code.google.com/u/mattgatto/) 2010-02-19

Thanks Tom. Fixed in r1633.

**Comment by pychess** [comment]
Original [comment 12.](https://code.google.com/p/pychess/issues/detail?id=523#c12) posted by [mattgatto](https://code.google.com/u/mattgatto/) 2010-02-20

r1633 was a mistake as Thomas pointed out. Hopefully this is fixed in r1634 though.

**Comment by pychess** [comment]
Original [comment 13.](https://code.google.com/p/pychess/issues/detail?id=523#c13) posted by [mattgatto](https://code.google.com/u/mattgatto/) 2010-02-20

I just backed out r1634 out too in r1635, since it would be counter-productive. I remember seeing this 
often last summer. Hopefully someone can find out how to reproduce or I start seeing it again on my 
system.

**Comment by pychess** [comment]
Original [comment 14.](https://code.google.com/p/pychess/issues/detail?id=523#c14) posted by [thomas.spura](https://code.google.com/u/110909423880295359716/) 2010-05-05

There was a new comment on how to reproduce this:
'Finish a game, then close the window.'

This comment is very usefull, so I suggest closing this bug as invalid.
I just closed the downstream bug as INSUFFICIENT_DATA...

**Comment by gbtami** [comment]
After flake8 work being done I think we can close this issue now.
