### ISSUE TITLE
100% cpu usage

### ISSUE THREAD

**Issue by pychess** [pychess/pychess#526]
Original [issue 526](https://code.google.com/p/pychess/issues/detail?id=526) reported by [thomas.spura](https://code.google.com/u/110909423880295359716/) 2010-02-08

Copy&amp;paste from https://bugzilla.redhat.com/show\_bug.cgi?id=562793:
###### ###############y

Description of problem:
When the hint/spy analyzers are enabled, pychess constantly consumes 100% of
the CPU.

Version-Release number of selected component (if applicable):
pychess-0.10-0.1.20100203svn.fc12.noarch

How reproducible:
Always.

Steps to Reproduce:
1. Enable Pychess hint/spy analyzers in Settings:Preferences:Computer
Opponents.
2. Select the lowest level of difficulty (number 1 on the slider).
3. Start game, but don't make any moves.

Actual results:
CPU use immediately reaches 100% and stays there.
This does not depend on whether the hint and/or spy display modes are enabled
in the View menu.

Expected results:
CPU use is much less than 100%.

Additional info:
In pychess-0.8.2-4.fc12.noarch, if the analyzers are enabled, CPU use briefly
reaches 100% after each move (on a different and slower system). Between moves,
CPU use is around 3%.

I use gkrellm, gnome system monitor, and top to monitor CPU use.

**Comment by pychess** [comment]
Original [comment 1.](https://code.google.com/p/pychess/issues/detail?id=526#c1) posted by [zollo.john](https://code.google.com/u/117741568078251192015/) 2010-02-08

I think is the analyzers are enabled in preferences, then they are always running,
regardless of whether hint mode or spy mode is checked in the view menu.  In other
words, PyChess will always have analyzers running if enabled in preferences,
regardless of what the view menu says.  I'm not sure if there's any other way.  Matt
or Thomas may know.

Sincerely,
John

**Comment by pychess** [comment]
Original [comment 2.](https://code.google.com/p/pychess/issues/detail?id=526#c2) posted by [thomas.spura](https://code.google.com/u/110909423880295359716/) 2010-02-08

It would be nice, if the analyzer only run at 100% cpu, if actually do something,
e.g. when they calculated anything, wait for further input at 0% cpu.

Also don't know, if this could be archived ;)

**Comment by pychess** [comment]
Original [comment 3.](https://code.google.com/p/pychess/issues/detail?id=526#c3) posted by [zollo.john](https://code.google.com/u/117741568078251192015/) 2010-02-08

They are actually doing something.  The analyzers are running -- they are analyzing
the game.  That's why the CPU is at 100%.  It's just that you can't see the results
because "hint mode" or "spy mode" is not checked.  If you look at the log viewer you
can see that the analyzers are working -- you're just not seeing the results!

-John

**Comment by pychess** [comment]
Original [comment 4.](https://code.google.com/p/pychess/issues/detail?id=526#c4) posted by [thomas.spura](https://code.google.com/u/110909423880295359716/) 2010-02-08

They should not analyze the game to death ;)

Whatever they analyze, they are done at some point, but the CPI is always at 100%,
also when doing nothing (e.g. starting the game and go away for half an hour).

Or am I wrong here, and they need to analyze something that long?

**Comment by pychess** [comment]
Original [comment 5.](https://code.google.com/p/pychess/issues/detail?id=526#c5) posted by [zollo.john](https://code.google.com/u/117741568078251192015/) 2010-02-08

The longer the move is analyzed the better the move is.

-John

**Comment by pychess** [comment]
Original [comment 6.](https://code.google.com/p/pychess/issues/detail?id=526#c6) posted by [lobais](https://code.google.com/u/lobais/) 2010-02-08

Any start- or mid-game chess position can be analyzed for a century without finding a 
final answer. That is the beauty of chess :)

When that is said, it could be an idea to save the results of the analysis, and thus 
save work post-game. However we don't have an integrated UI for blunder checking and 
such yet, so for now the analysis is only used for the arrows.
- changed status to: Invalid

**Comment by pychess** [comment]
Original [comment 7.](https://code.google.com/p/pychess/issues/detail?id=526#c7) posted by [zollo.john](https://code.google.com/u/117741568078251192015/) 2010-02-09

Sounds good to me.  We might have to focus on other issues for the time being.  Maybe
one day when we disable hint mode and spy mode it will also disable the analyzers. 
In the meantime, you can just go to "preferences", "Computer Opponents" and disable
the analyzers (by unchecking them) if you want.  Simple solution for a simple problem!

Good luck!  I'll think about this again in the future!

Thanks tomspur!  Good looking out!

Sincerely,
John

(Thank you to Thomas! ;-0  )

**Comment by pychess** [comment]
Original [comment 8.](https://code.google.com/p/pychess/issues/detail?id=526#c8) posted by [gbtami](https://code.google.com/u/gbtami/) 2011-03-27

issue #646 has been merged into this issue.

**Comment by rabfulton** [comment]
Would be nice if it was possible to limit the max CPU% used by an analyzer, could this be achieved by altering the command used to invoke the engine? cpulimit or nice?

Or maybe the analyser can be told to only analyse for a certain time per move?

Would be nice to play chess on my laptop without all the fans spinning and battery draining.

**Comment by gbtami** [comment]
@rabfulton
1. We use os.nice(15) as you can see in https://github.com/pychess/pychess/blob/master/lib/pychess/System/SubProcess.py line 115.
2. You can set Maximum analysis time per move in Edit-Preferences-Hints at the bottom.
