### ISSUE TITLE
LAN games

### ISSUE THREAD

**Issue by pychess** [pychess/pychess#531]
Original [issue 531](https://code.google.com/p/pychess/issues/detail?id=531) reported by [julijan.andjelic](https://code.google.com/u/107222882466285618812/) 2010-02-15

It would be nice to have ability to play chess in LAN.
For example if there was an option "Start a LAN game" (server side) and
then it would show "waiting for an opponent to connect" and on the client
side "Join a LAN game" with an IP address prompt.

**Comment by pychess** [comment]
Original [comment 1.](https://code.google.com/p/pychess/issues/detail?id=531#c1) posted by [gbtami](https://code.google.com/u/gbtami/) 2010-03-03
- added label: Enhancement

**Comment by pychess** [comment]
Original [comment 2.](https://code.google.com/p/pychess/issues/detail?id=531#c2) posted by [gbtami](https://code.google.com/u/gbtami/) 2013-04-20
- changed status to: Accepted

**Comment by pychess** [comment]
Original [comment 3.](https://code.google.com/p/pychess/issues/detail?id=531#c3) posted by [gbtami](https://code.google.com/u/gbtami/) 2013-04-20
- added label: Low

**Comment by daniel-pg** [comment]
Maybe this could be achieved if there were any self-hosted FICS server alternatives.

**Comment by gbtami** [comment]
Unfortunately FICS code is not open source. There are lichess.org and pychess.org but coding a desktop client for them seems meaningless to me.
