### ISSUE TITLE
Use sprites for website

### ISSUE THREAD

**Issue by pychess** [pychess/pychess#619]
Original [issue 619](https://code.google.com/p/pychess/issues/detail?id=619) reported by [lobais](https://code.google.com/u/lobais/) 2010-12-06

The pychess.org website uses a lot of small images, and the hover often flicker on first mouseover.
This could be avoided by grouping most images with css sprites. I imagine this can be done nicely using a ruby script, so sprites are generated at compile time.

**Comment by gbtami** [comment]
Moved to https://github.com/pychess/pychess.website/issues/2
