### ISSUE TITLE
Close button on each side panel

### ISSUE THREAD

**Issue by pychess** [pychess/pychess#641]
Original [issue 641](https://code.google.com/p/pychess/issues/detail?id=641) reported by [leogregianin](https://code.google.com/u/leogregianin@gmail.com/) 2011-01-28

Include close button on each side panel to close it quickly.

**Comment by pychess** [comment]
Original [comment 1.](https://code.google.com/p/pychess/issues/detail?id=641#c1) posted by [lobais](https://code.google.com/u/lobais/) 2011-01-28

I can't really see where in the UI there is room for this?
Also, if you need to quickly hide your sidepanels, you can always do so from the View menu.

**Comment by pychess** [comment]
Original [comment 2.](https://code.google.com/p/pychess/issues/detail?id=641#c2) posted by [leogregianin](https://code.google.com/u/leogregianin@gmail.com/) 2011-01-29

I was thinking a button to close a side panel at a time. A small close button, the same in game tabs.

**Comment by pychess** [comment]
Original [comment 3.](https://code.google.com/p/pychess/issues/detail?id=641#c3) posted by [gbtami](https://code.google.com/u/gbtami/) 2011-03-27
- added label: Enhancement

**Comment by pychess** [comment]
Original [comment 4.](https://code.google.com/p/pychess/issues/detail?id=641#c4) posted by [gbtami](https://code.google.com/u/gbtami/) 2013-04-06
- changed status to: Accepted

**Comment by gbtami** [comment]
Done.
