### ISSUE TITLE
Use font-face for Chess Alpha diagrams

### ISSUE THREAD

**Issue by pychess** [pychess/pychess#678]
Original [issue 678](https://code.google.com/p/pychess/issues/detail?id=678) reported by [lobais](https://code.google.com/u/lobais/) 2011-06-29

Judging from http://www.fonts2u.com/chess-alpha.font the Chess Alpha font is fine to use from font-face, so users don't need it installed to print diagrams.
Judging from https://bugzilla.mozilla.org/show\_bug.cgi?id=668174 this will even solve the firefox rendering problem.
We can upload it to pychess.org for server.

**Comment by pychess** [comment]
Original [comment 1.](https://code.google.com/p/pychess/issues/detail?id=678#c1) posted by [lobais](https://code.google.com/u/lobais/) 2011-07-07
- added label: Easy-Fix

**Comment by pychess** [comment]
Original [comment 2.](https://code.google.com/p/pychess/issues/detail?id=678#c2) posted by [G.nius.ck](https://code.google.com/u/112084229900022559058/) 2013-06-27

I do not understand. We use images in diagrams, I believe, not fonts.

**Comment by pychess** [comment]
Original [comment 3.](https://code.google.com/p/pychess/issues/detail?id=678#c3) posted by [lobais](https://code.google.com/u/lobais/) 2013-06-27

This is for "Save As" -> "Html".
Actually that should now be moved to Export.

**Comment by pychess** [comment]
Original [comment 4.](https://code.google.com/p/pychess/issues/detail?id=678#c4) posted by [lobais](https://code.google.com/u/lobais/) 2013-06-27

Forget the last comment. I forgot we actually try to open html files.

**Comment by pychess** [comment]
Original [comment 6.](https://code.google.com/p/pychess/issues/detail?id=678#c6) posted by [G.nius.ck](https://code.google.com/u/112084229900022559058/) 2013-06-28

Okay, changed font to Chess Alpha. https://G.nius.ck@code.google.com/r/gniusck-fontfix/  (Of course, it didn't quite work right on my computer to begin with. I fixed one bug, but the file needs to be tested I believe.)

**Comment by pychess** [comment]
Original [comment 7.](https://code.google.com/p/pychess/issues/detail?id=678#c7) posted by [gbtami](https://code.google.com/u/gbtami/) 2013-06-28
1. I think the Chess Alpha 2 font was OK, no need to change it to Chess Alpha.
2. The loadToModel() function is broken too. It uses the old(removed) addPiece() of Board class, but we have only _addPiece() in LBoard class from a while. Maybe we should just save the FEN string into the .html too, then parsing code can be eliminated, and just add the FEN as setup parameter on board instantiation. 
3. Another problem that moves are saved, but not loaded at all. If it's a position saver only, why list moves in .html? If it's a game saver, we should load moves too, shouldn't we?

**Comment by pychess** [comment]
Original [comment 8.](https://code.google.com/p/pychess/issues/detail?id=678#c8) posted by [lobais](https://code.google.com/u/lobais/) 2013-06-28

To be honest I think the loading feature was a dumb idea from the beginning. I think it was only added because we will didn't have the concept of an exporter, so "why not".
I say let's just remove loading capacity. People can copy paste the moves into the so designed dialog.

**Comment by pychess** [comment]
Original [comment 9.](https://code.google.com/p/pychess/issues/detail?id=678#c9) posted by [G.nius.ck](https://code.google.com/u/112084229900022559058/) 2013-06-28

It seems a bit like the image export, except buggier.

**Comment by pychess** [comment]
Original [comment 10.](https://code.google.com/p/pychess/issues/detail?id=678#c10) posted by [lobais](https://code.google.com/u/lobais/) 2013-06-28

Well, it works better for print, includes moves, and let's you combine many games into one sheet. Very useful for teachers e.g.

**Comment by pychess** [comment]
Original [comment 11.](https://code.google.com/p/pychess/issues/detail?id=678#c11) posted by [gbtami](https://code.google.com/u/gbtami/) 2013-06-28

Agreed. Treating it as an exporter seems more logical. Maybe we should split the Savers dir into Savers and Exporters (png.py and chessalpha2.py).

**Comment by pychess** [comment]
Original [comment 12.](https://code.google.com/p/pychess/issues/detail?id=678#c12) posted by [lobais](https://code.google.com/u/lobais/) 2013-06-28

That or just test if the saver has a load method. Right now I noticed the exporting dialog is done inside the png saver, which is a bit messy. An ionest function would be better.
All if this is not really related to this bug though.

**Comment by pychess** [comment]
Original [comment 13.](https://code.google.com/p/pychess/issues/detail?id=678#c13) posted by [gbtami](https://code.google.com/u/gbtami/) 2013-06-28

Btw. the original rendering problem (empty fields) still exist. Should we upload the font to pychess.org? (But I don't know the font-face syntax how to use it from an url)

**Comment by pychess** [comment]
Original [comment 14.](https://code.google.com/p/pychess/issues/detail?id=678#c14) posted by [gbtami](https://code.google.com/u/gbtami/) 2013-07-01

Unfortunately @font-face doesn't work for me with Firefox 21.0 at all. But it works with Midori if I omit local src. Hmm.

**Comment by pychess** [comment]
Original [comment 15.](https://code.google.com/p/pychess/issues/detail?id=678#c15) posted by [gbtami](https://code.google.com/u/gbtami/) 2013-07-03

The FF problem is cross-site HTTP request:
https://developer.mozilla.org/en-US/docs/HTTP/Access\_control\_CORS?redirectlocale=en-US&redirectslug=HTTP\_access\_control

The solution is here:
http://www.cssbakery.com/2010/07/fixing-firefox-font-face-cross-domain\_25.html

**Comment by ecrucru** [comment]
At the current time, the export to HTML seems to be broken :

```
Traceback (most recent call last):
  File "/home/pychess/lib/pychess/Main.py", line 232, in on_export_position_activate
    perspective.saveGameAs(gmwidg.gamemodel, position, export=True)
  File "/home/pychess/lib/pychess/perspectives/games/__init__.py", line 319, in saveGameAs
    game.save(uri, saver, append, position)
  File "/home/pychess/lib/pychess/Utils/GameModel.py", line 614, in save
    saver.save(fileobj, self, position)
  File "/home/pychess/lib/pychess/Savers/chessalpha2.py", line 75, in save
    sanmvs.extend([''] * (-len(sanmvs) % 2))
AttributeError: 'map' object has no attribute 'extend'
```

**Comment by gbtami** [comment]
This seems a Python2 to Python3 conversion problem. sanmvs should be converted to list in Python3.
As I see integer divisions with 2 later should be converted from / to // also.

**Comment by gbtami** [comment]
@ecrucru as I know chessalpha2 export never worked in PyChess, so I close this issue. Feel free to fix it if you have knowledge/motivation.

**Comment by ecrucru** [comment]
I know this topic by having done something similar [here](https://github.com/ecrucru/anticrux/blob/master/anticrux.js#L2206). I will try to achieve something later in time.
I leave here the commit 10c370747e007a671733eccb771463ddce925ec0 for my information.

**Comment by gbtami** [comment]
https://fontlibrary.org/th/font/chess
