### ISSUE TITLE
Problems using dark gtk color themes

### ISSUE THREAD

**Issue by pychess** [pychess/pychess#695]
Original [issue 695](https://code.google.com/p/pychess/issues/detail?id=695) reported by [gbtami](https://code.google.com/u/gbtami/) 2011-12-28

Black pieces are full of white.
Player names are hard to read.
Cords are hard to read.
Maybe white fields are too dark.

**Comment by pychess** [comment]
- attached [xfce-dusk-theme.png](https://code.google.com/p/pychess/issues/detail?id=695#c0)

**Comment by gbtami** [comment]
Seems ok after ported to gtk3.
