### ISSUE TITLE
Ship sample PGN games

### ISSUE THREAD

**Issue by pychess** [pychess/pychess#714]
Original [issue 714](https://code.google.com/p/pychess/issues/detail?id=714) reported by [pmjdebruijn@pcode.nl](https://code.google.com/u/107266719206833249190/) 2012-08-25

Currently PyChess doesn't ship any sample PGN games. So the load game function isn't easy to demonstrate.

Maybe it's an idea to ship a few sample PGN files?

The book "Chess for Dummies" illustrates "The Ten Most Famous Games" according to it's author James Eade. Which might serve as a good guide on what to include.

I've attached the PGN files of the games in question, they have all been downloaded from chessgames.com. I'm not entirely sure what the legal status of these files is? Are PGN files copyrightable?

**Comment by pychess** [comment]
- attached [chess_for_dummies_ten_most_famous_games.zip](https://code.google.com/p/pychess/issues/detail?id=714#c0)

**Comment by pychess** [comment]
Original [comment 1.](https://code.google.com/p/pychess/issues/detail?id=714#c1) posted by [gbtami](https://code.google.com/u/gbtami/) 2012-08-26

We have some annotated and simple pgn files in our testing/gamefiles dir, like world_matches.pgn or dortmund.pgn or chess960rwch.pgn, but never packaged them for releases before.

The plain pgn files are not copyrightable, but annotated ones are, IMO. But I'm not a lawyer :)

**Comment by pychess** [comment]
Original [comment 2.](https://code.google.com/p/pychess/issues/detail?id=714#c2) posted by [pmjdebruijn@pcode.nl](https://code.google.com/u/107266719206833249190/) 2012-08-26

Ah right. Well it's far from critical.

However, you might want to consider it as a future enhancement.

**Comment by pychess** [comment]
Original [comment 3.](https://code.google.com/p/pychess/issues/detail?id=714#c3) posted by [gbtami](https://code.google.com/u/gbtami/) 2013-03-19
- changed status to: Accepted
- added label: Task

**Comment by gbtami** [comment]
PyChess 0.99.0 now has "New Database" and  "Import annotated games from endgame.nl" in Database menu.
