### ISSUE TITLE
Weird gstreamer error message

### ISSUE THREAD

**Issue by pychess** [pychess/pychess#721]
Original [issue 721](https://code.google.com/p/pychess/issues/detail?id=721) reported by [jonas.thiem](https://code.google.com/u/jonas.thiem@gmail.com/) 2012-09-05

**What steps will reproduce the problem?**
1. Go to sound preferences
2. Click the play buttons like mad

After a bit of wild clicking, I get this in the terminal:

(pychess:8806): GStreamer-CRITICAL **: 
Trying to dispose element test, but it is in READY instead of the NULL state.
You need to explicitly set elements to the NULL state before
dropping the final reference, to allow them to clean up.
This problem may also be caused by a refcounting bug in the
application or some element.

Looks like an error that might be worth fixing (if it's in PyChess code and not some upstream library).

**Did you use PyChess from a repo, tarball, install or hg?**
hg

**Comment by pychess** [comment]
Original [comment 1.](https://code.google.com/p/pychess/issues/detail?id=721#c1) posted by [gbtami](https://code.google.com/u/gbtami/) 2012-09-05
- changed status to: Accepted
- added label: Defect

**Comment by pychess** [comment]
Original [comment 2.](https://code.google.com/p/pychess/issues/detail?id=721#c2) posted by [gbtami](https://code.google.com/u/gbtami/) 2012-11-05

Can you reproduce this, and attach the log file created, please?

**Comment by pychess** [comment]
Original [comment 3.](https://code.google.com/p/pychess/issues/detail?id=721#c3) posted by [gbtami](https://code.google.com/u/gbtami/) 2013-09-02
- changed status to: Need-Info

**Comment by gbtami** [comment]
Is this still exist?

**Comment by gbtami** [comment]
I think it was fixed before.
