### ISSUE TITLE
Create book from .pgn file

### ISSUE THREAD

**Issue by pychess** [pychess/pychess#743]
Original [issue 743](https://code.google.com/p/pychess/issues/detail?id=743) reported by [gbtami](https://code.google.com/u/gbtami/) 2012-12-28

We can do it as polyglot book handling in place now. It can be a new menu item or just a command line option.

**Comment by gbtami** [comment]
http://hardy.uhasselt.be/Toga/pgheader-release/header.html

**Comment by gbtami** [comment]
This can be a sub menu item in Database menu. Implementation can use chess-db.
It would be nice to add max-ply support into chess-db also.
