### ISSUE TITLE
Add time odds on time control dialog

### ISSUE THREAD

**Issue by pychess** [pychess/pychess#744]
Original [issue 744](https://code.google.com/p/pychess/issues/detail?id=744) reported by [gbtami](https://code.google.com/u/gbtami/) 2012-12-30

I like to play with time odds against stronger engines.

**Comment by vgupta2507** [comment]
What do you mean by time odds :
1) To have multiple time controls in a single game. For example: 1 hour for first 40 moves and 30 additional minutes for following game.
2) To have different time controls for both players. For example: I have 10 minutes in total while my opponent has 5.

**Comment by gbtami** [comment]
1) is issue #1015 and issue #755 
Time odds is 2). We have only one (minutes, gain) time control for a game now but having two pairs would be better sometimes.
