### ISSUE TITLE
Add MultiPV feature option support to PyChess own engine

### ISSUE THREAD

**Issue by pychess** [pychess/pychess#747]
Original [issue 748](https://code.google.com/p/pychess/issues/detail?id=748) reported by [gbtami](https://code.google.com/u/gbtami/) 2013-01-06

PyChess can output multiple PV lines on hint panel for UCI engines, but not for PyChess own (CECP) engine. We can add this feature like in Winboard (feature option="MultiPV -spin 1 1 10").

**Comment by gbtami** [comment]
This needs implementing UCI support in pychess engine. It's not worth it IMO.
