### ISSUE TITLE
new window for manage censor, noplay and notify list.

### ISSUE THREAD

**Issue by pychess** [pychess/pychess#785]
Original [issue 785](https://code.google.com/p/pychess/issues/detail?id=785) reported by [yoanntar](https://code.google.com/u/yoanntar/) 2013-07-07

Create a new window on the FICS main page of pychess for manage censor, noplay and notify list.

**Comment by pychess** [comment]
Original [comment 1.](https://code.google.com/p/pychess/issues/detail?id=785#c1) posted by [gbtami](https://code.google.com/u/gbtami/) 2013-07-07
- changed status to: Accepted
- added label: Enhancement

**Comment by cajone** [comment]
Other FICS commands  that could be added are 'messages' ,'stats' and 'history'.

These additions along with the original censor,noplay and notify (if separate tabs where added for each one) will start to make the ICLounge tabs unmanagable ( constantly shifting left <-> right ) to get at what you require.

A possible solution might be to keep the existing 3/4 seek, game, player tabs as hard coded tabs along the top of the ICLounge but add all the above mentioned functionality  to a vertical treeview with scroll attached to the IClounge and on selection from this list a single horizontal tab position is used as a common display point.

Just an idea ( brainstorm ) any thought comments?
