### ISSUE TITLE
Threat Analysis by Stockfish doesn't work

### ISSUE THREAD

**Issue by pychess** [pychess/pychess#824]
Original [issue 824](https://code.google.com/p/pychess/issues/detail?id=824) reported by [fabrizio.ch.tablet](https://code.google.com/u/117100794831679601162/) 2013-11-27

**What steps will reproduce the problem?**
1. When I click on "x" button (threat analysis), no lines are shown..

**What is the expected output? What do you see instead?**
The expected would be seeing threat lines; I cannot see anything...

**Does it happen every time?**
Yes.

**What version of the product are you using?**
Stockfish 4 64 SSE 4.2

**Did you use an installed version of PyChess or did you run in from a**
**tarball/svn?**
On a chess program..

**Please provide any additional information below.**

**Please attach the latest pychess logfile. It's in a hidden folder, under**
your homedirectory, named ".local/share/pychess/"

**Comment by pychess** [comment]
Original [comment 1.](https://code.google.com/p/pychess/issues/detail?id=824#c1) posted by [gbtami](https://code.google.com/u/gbtami/) 2013-11-27

Can you attach a .log file, please?

**Comment by pychess** [comment]
Original [comment 2.](https://code.google.com/p/pychess/issues/detail?id=824#c2) posted by [gbtami](https://code.google.com/u/gbtami/) 2014-01-03
- changed status to: Need-Info

**Comment by pychess** [comment]
Original [comment 3.](https://code.google.com/p/pychess/issues/detail?id=824#c3) posted by [gbtami](https://code.google.com/u/gbtami/) 2014-01-03
- added label: Defect

**Comment by gbtami** [comment]
Can't fix issues without involvement of reporters :(
