### ISSUE TITLE
Add "Analyze Game at this/current position" menu item

### ISSUE THREAD

**Issue by pychess** [pychess/pychess#863]
Original [issue 863](https://code.google.com/p/pychess/issues/detail?id=863) reported by [mattgatto](https://code.google.com/u/mattgatto/) 2014-05-04

Usually when I've been using the Analyze Game dialog, I haven't wanted to do from the very beginning of the game, but from a certain position. Adding an "Analyze Game at This Position" or "Analyze Game at Current Position" menu item below the current "Analyze Game" one would be an elegant and easy way to do this, I think.

**Comment by pychess** [comment]
Original [comment 1.](https://code.google.com/p/pychess/issues/detail?id=863#c1) posted by [gbtami](https://code.google.com/u/gbtami/) 2014-05-05

Another possibility is to add "from" and "to" fields to the dialog as in Shredder, with current ply as default "from".

**Comment by gbtami** [comment]
@gbtami closed this in 1e7e9ce on Jun 29
