### ISSUE TITLE
hint arrow drawing during piece move animation makes animation choppy and slow

### ISSUE THREAD

**Issue by pychess** [pychess/pychess#884]
Original [issue 884](https://code.google.com/p/pychess/issues/detail?id=884) reported by [mattgatto](https://code.google.com/u/mattgatto/) 2014-06-12

**What steps will reproduce the problem?**
1. Observe a game or play a local game with full animation on and a hint analyzer engine running

**What is the expected output? What do you see instead?**
The move animations are often slow and choppy (especially with fullscreen or a large board) when hint arrows are drawn quickly because the hint arrows are being drawn at the same time that the move animation drawing is occuring.

An obvious solution would be to queue hint arrow drawing actions until the move animation finishes.

**Comment by gbtami** [comment]
I experimented with this a bit. Seems the reason is not the arrow drawing, but processing "analyze" signal in sidepanels emitted by engine (and "analysis_changed" signal emitted by game_model).
