### ISSUE TITLE
remove boardUpdate signal and emit game-updates from FICSGame

### ISSUE THREAD

**Issue by pychess** [pychess/pychess#885]
Original [issue 885](https://code.google.com/p/pychess/issues/detail?id=885) reported by [mattgatto](https://code.google.com/u/mattgatto/) 2014-06-13

I was observing a FICS game and had about 37 game tabs open when I got the ParsingError below. I forgot to take a screenshot, but the board did show a queen on a8 checking the king in its final position, so the FEN in the parsing error doesn't seem to be correct.

Traceback (most recent call last):
  File "/usr/lib64/python2.7/threading.py", line 811, in __bootstrap_inner
    self.run()
  File "/home/gatto/code/hg/pychess/lib/pychess/Utils/GameModel.py", line 571, in run
    self.boards[-2])
  File "/home/gatto/code/hg/pychess/lib/pychess/Players/ICPlayer.py", line 154, in makeMove
    move = parseSAN (board1, sanmove)
  File "/home/gatto/code/hg/pychess/lib/pychess/Utils/Move.py", line 112, in parseSAN
    return Move (lmove.parseSAN (board.board, san))
  File "/home/gatto/code/hg/pychess/lib/pychess/Utils/lutils/lmove.py", line 375, in parseSAN
    raise ParsingError, (san, errstring, board.asFen())
ParsingError: ('Qa8+', u'no Queen is able to move to a8', '1K6/8/6p1/k4p1p/4pP1P/2p1P1P1/8/8 w - - 0 51')

**Comment by pychess** [comment]
Original [comment 1.](https://code.google.com/p/pychess/issues/detail?id=885#c1) posted by [gbtami](https://code.google.com/u/gbtami/) 2014-06-14

The FEN in the parsing error not just "doesn't seem to be correct", but is definitely from another game.

**Comment by pychess** [comment]
Original [comment 2.](https://code.google.com/p/pychess/issues/detail?id=885#c2) posted by [mattgatto](https://code.google.com/u/mattgatto/) 2014-06-14

Wow, really weird. Should I post the full log?

**Comment by pychess** [comment]
Original [comment 3.](https://code.google.com/p/pychess/issues/detail?id=885#c3) posted by [gbtami](https://code.google.com/u/gbtami/) 2014-06-14

Yes, please. Maybe we can figure out what was the other game.

**Comment by pychess** [comment]
Original [comment 4.](https://code.google.com/p/pychess/issues/detail?id=885#c4) posted by [mattgatto](https://code.google.com/u/mattgatto/) 2014-06-14
- attached [2014-06-12_15-52-20.log.bz2](https://code.google.com/p/pychess/issues/detail?id=885#c4)

**Comment by pychess** [comment]
Original [comment 5.](https://code.google.com/p/pychess/issues/detail?id=885#c5) posted by [gbtami](https://code.google.com/u/gbtami/) 2014-06-14

Seems there was another junglescrabble vs. Kombo lightning rated game with same 322 game number, started at 16:46:48. One hour before the game emitting parsing error. It contains the FEN shown in parsing error.

**Comment by pychess** [comment]
Original [comment 6.](https://code.google.com/p/pychess/issues/detail?id=885#c6) posted by [mattgatto](https://code.google.com/u/mattgatto/) 2014-06-20

Good catch. I guess we need to filter out board updates based on more than player names and game number in ICPlayer.__boardUpdate, or just disconnect ICPlayer's from "boardUpdate" signals after the game ends rather than when the widget is deleted. The former would be better though, because that way it'll be easier to add in functionality in the future for game widgets to be able to resume games after adjournment when the player logs back in. One possibility would be to add a game start time timestamp FICSGame attribute and use that in FICSGame.__hash__.

**Comment by pychess** [comment]
Original [comment 7.](https://code.google.com/p/pychess/issues/detail?id=885#c7) posted by [gbtami](https://code.google.com/u/gbtami/) 2014-09-20

Unfortunately FICS doesn't send any timestamp info on board updates, so we will never know which FICSGame got the board update if they have same players and gameno. I added a "current" flag to the ICPlayer instead, indicating which is the latest using the same players and gameno.

**Comment by pychess** [comment]
Original [comment 8.](https://code.google.com/p/pychess/issues/detail?id=885#c8) posted by [gbtami](https://code.google.com/u/gbtami/) 2014-09-20

This issue was closed by revision ca892a01333e.
- changed status to: Fixed

**Comment by pychess** [comment]
Original [comment 9.](https://code.google.com/p/pychess/issues/detail?id=885#c9) posted by [mattgatto](https://code.google.com/u/mattgatto/) 2014-09-24

Why do we need FICS to send us timestamp info when we could just use our own timestamp?

**Comment by pychess** [comment]
Original [comment 10.](https://code.google.com/p/pychess/issues/detail?id=885#c10) posted by [gbtami](https://code.google.com/u/gbtami/) 2014-09-24

If we have start time timestamp FICSGame attribute and a message is coming from FICS we never know which game it belongs to if there are several ones with same gameno+wplayer+bplayer in our FICSGames.

**Comment by pychess** [comment]
Original [comment 11.](https://code.google.com/p/pychess/issues/detail?id=885#c11) posted by [mattgatto](https://code.google.com/u/mattgatto/) 2014-09-24

Couldn't we just assume that the latest board-update corresponds to the
FICSGame with the newest timestamp?

**Comment by pychess** [comment]
Original [comment 12.](https://code.google.com/p/pychess/issues/detail?id=885#c12) posted by [mattgatto](https://code.google.com/u/mattgatto/) 2014-09-24

For games were playing at least.

**Comment by pychess** [comment]
Original [comment 13.](https://code.google.com/p/pychess/issues/detail?id=885#c13) posted by [mattgatto](https://code.google.com/u/mattgatto/) 2014-09-24

Sorry, I forgot this is happened in an observed game.

**Comment by pychess** [comment]
Original [comment 14.](https://code.google.com/p/pychess/issues/detail?id=885#c14) posted by [mattgatto](https://code.google.com/u/mattgatto/) 2014-09-24

Ideally, ICPlayer shouldn't have to figure out whether the board-update applies to its game, and will only receive board-updates that apply to its game. The controller, FICSGames, BoardManager, or whatever should figure this out, possibly by retrieving the applicable game from FICSGames based on the current FICSGame gameno+wplayer+bplayer hash and doing game.update(update) which would emit the update only to listeners on that game.

**Comment by pychess** [comment]
Original [comment 15.](https://code.google.com/p/pychess/issues/detail?id=885#c15) posted by [mattgatto](https://code.google.com/u/mattgatto/) 2014-09-24
- changed status to: Reopened
- changed summary to: remove boardUpdate signal and emit game-updates from FICSGame
- removed label: Defect
- added label: Task

**Comment by pychess** [comment]
Original [comment 16.](https://code.google.com/p/pychess/issues/detail?id=885#c16) posted by [gbtami](https://code.google.com/u/gbtami/) 2014-09-24

Matt, feel free to fix my fix, please!

**Comment by pychess** [comment]
Original [comment 17.](https://code.google.com/p/pychess/issues/detail?id=885#c17) posted by [mattgatto](https://code.google.com/u/mattgatto/) 2014-09-27
- changed status to: Started

**Comment by gbtami** [comment]
Fixed by https://github.com/pychess/pychess/commit/d13d4cd2035c0879716fe82bdd1245375a880252
