### ISSUE TITLE
Create __doc__ strings

### ISSUE THREAD

**Issue by pychess** [pychess/pychess#89]
Original [issue 89](https://code.google.com/p/pychess/issues/detail?id=89) reported by [lobais](https://code.google.com/u/lobais/) 2006-11-21

PyChess needs better documentation. It should be added by creating a
__doc__ string in most methods and functions, e.g.:
def function ():
   """ This is documentation
       This function does no good. """

**Comment by pychess** [comment]
Original [comment 1.](https://code.google.com/p/pychess/issues/detail?id=89#c1) posted by [lobais](https://code.google.com/u/lobais/) 2006-11-29

Any body should feel free to document any method, class or module they think they
have figured out.
- changed status to: Started
- removed label: Release0.6

**Comment by pychess** [comment]
Original [comment 2.](https://code.google.com/p/pychess/issues/detail?id=89#c2) posted by [wojciech.halicki.piszko](https://code.google.com/u/wojciech.halicki.piszko/) 2006-12-15

Couldn't agree more. It will make it more developer friendly and more open :). I see
how much I can understand of pychess' code without asking ;).

**Comment by pychess** [comment]
Original [comment 3.](https://code.google.com/p/pychess/issues/detail?id=89#c3) posted by [gbtami](https://code.google.com/u/gbtami/) 2007-09-27

Btw., just read "Writing Code That Doesn't Suck"
http://ivory.idyll.org/blog/sep-07/not-sucking-v2
Don't you mind if i do some PEP8-ification in PyChess source sometimes?

**Comment by pychess** [comment]
Original [comment 4.](https://code.google.com/p/pychess/issues/detail?id=89#c4) posted by [lobais](https://code.google.com/u/lobais/) 2007-09-27

Feel welcome.
Standardization is always good.
E.g. currently the functions are rather confused between theJavaWay and
the_pygtk_way. Personally I like theJavaWay the most, as the_pygtk_way.attributes are
harder to distinct because of the _/. similarity.

**Comment by pychess** [comment]
Original [comment 5.](https://code.google.com/p/pychess/issues/detail?id=89#c5) posted by [G.nius.ck](https://code.google.com/u/112084229900022559058/) 2013-06-27

This may be a good way to learn the code.

**Comment by gbtami** [comment]
The current state of code documentation (in sphinx format) is available at http://pychess.readthedocs.org/en/latest/
Generated automatically  by a GitHub commit hook when docs dir is updated.
