### ISSUE TITLE
Play on lichess.org

### ISSUE THREAD

**Issue by pychess** [pychess/pychess#893]
Original [issue 893](https://code.google.com/p/pychess/issues/detail?id=893) reported by [gbtami](https://code.google.com/u/gbtami/) 2014-06-25

Seems lichess.org has a HTTP API to use.

**Comment by pychess** [comment]
Original [comment 1.](https://code.google.com/p/pychess/issues/detail?id=893#c1) posted by [gbtami](https://code.google.com/u/gbtami/) 2015-01-04

https://github.com/ornicar/lila

**Comment by gbtami** [comment]
Seems lichess.org has only some GET HTTP API to fetch players/games and nothing for playing games.

**Comment by ghost** [comment]
Discover that now are few Python scripts for Lichess API:
1) https://github.com/CamdenClark/pylichess
2) https://github.com/NikolaiT/lichess_cheat
I not interested in hacking lichess.org, but very interested in creating Python-based client for desktop. So, if someone interested lets do it!

**Comment by ghost** [comment]
@gbtami, lichess.org have POST method too.
POST /api/game/new create a new game.
You can create a new casual game by just POSTing to this url. You get back two links, for the white player and for the black player. One could use that API to provide chess capabilities to an online chat, for instance. 
<code>> curl -XPOST http://en.lichess.org/api/game/new
{
  "white": "http://l.org/8pmigk36t1hp", 
"black": "http://l.org/8pmigk36ov6m"
}</code>
Found this on http://pythonhackers.com/p/codejitsu/lila

**Comment by ghost** [comment]
@gbtami, also here is login procedure using POST method: 
<code>~$ curl -H "Accept:application/ vnd.lichess.v1+json" -d "username=Unihedron&password=us ername" -X POST http://lichess.org/ login 
{"":["Invalid username or password"]}</code>
https://github.com/ornicar/lila/issues/1222#issuecomment-155946361

**Comment by gbtami** [comment]
goto #1332 :)
