### ISSUE TITLE
holding pieces in crazyhouse games not always showing up

### ISSUE THREAD

**Issue by pychess** [pychess/pychess#894]
Original [issue 894](https://code.google.com/p/pychess/issues/detail?id=894) reported by [mattgatto](https://code.google.com/u/mattgatto/) 2014-06-25

I was playing a crazyhouse game on FICS and after 30. P@g7, the 2 pawns I had weren't showing up in my list of holding pieces.

**Comment by pychess** [comment]
- attached [2014-06-24_22-27-28-truncated.log.bz2](https://code.google.com/p/pychess/issues/detail?id=894#c0)

**Comment by pychess** [comment]
Original [comment 1.](https://code.google.com/p/pychess/issues/detail?id=894#c1) posted by [mattgatto](https://code.google.com/u/mattgatto/) 2014-06-25

After I clicked on the first move in the game and stepped through it they were showing up though when I got to the end position.

**Comment by pychess** [comment]
Original [comment 2.](https://code.google.com/p/pychess/issues/detail?id=894#c2) posted by [gbtami](https://code.google.com/u/gbtami/) 2014-06-25

Attached .pgn
- attached [ficsgamesdb_358098714.pgn](https://code.google.com/p/pychess/issues/detail?id=894#c2)

**Comment by pychess** [comment]
Original [comment 3.](https://code.google.com/p/pychess/issues/detail?id=894#c3) posted by [gbtami](https://code.google.com/u/gbtami/) 2014-07-08

I can't reproduce this, even with replaying the game with 2 guest account :(

**Comment by gbtami** [comment]
This was fixed by commit of #921 fix.
