### ISSUE TITLE
remove glock.py and convert from threads_enter to idle_add

### ISSUE THREAD

**Issue by pychess** [pychess/pychess#914]
Original [issue 914](https://code.google.com/p/pychess/issues/detail?id=914) reported by [mattgatto](https://code.google.com/u/mattgatto/) 2014-09-18

To fix most of the remaining deadlocks and to get rid of the deprecated threads_enter, we need to remove glock.py and convert from threads_enter to idle_add (or timeout_add or whatever).

A preliminary patch which I've tested a little bit is attached. Since this involves changing (currently) 290 code blocks from synchronous code to asynchronous code, it is not a simple mass rename/regexp replacement.

**Comment by pychess** [comment]
- attached [patch-45.diff](https://code.google.com/p/pychess/issues/detail?id=914#c0)

**Comment by pychess** [comment]
Original [comment 2.](https://code.google.com/p/pychess/issues/detail?id=914#c2) posted by [gbtami](https://code.google.com/u/gbtami/) 2014-09-19

Seems this patch only changes one block to idle_add(). Or is this just to wet our appetite? :)
Matt, can you attach the full patch, please?

**Comment by pychess** [comment]
Original [comment 3.](https://code.google.com/p/pychess/issues/detail?id=914#c3) posted by [mattgatto](https://code.google.com/u/mattgatto/) 2014-09-19

That is all there is so far.

**Comment by pychess** [comment]
Original [comment 4.](https://code.google.com/p/pychess/issues/detail?id=914#c4) posted by [gbtami](https://code.google.com/u/gbtami/) 2014-09-19

Ah, I misunderstand then, sorry.

**Comment by pychess** [comment]
Original [comment 5.](https://code.google.com/p/pychess/issues/detail?id=914#c5) posted by [mattgatto](https://code.google.com/u/mattgatto/) 2014-12-03

I've converted ICLounge.py (attached), and it works well with no dead-locks in my limited testing. With the patch the Players and Games lists populate alot quicker on login, as well. Unfortunately I've been unable to apply the same changes to ICLogin.py so far without the UI dead-locking upon login. I'm in the process of redesigning the IC control logic, both, to make it possible to finish the idle_add conversion, and to make IC code more robust against deadlocks.

**Comment by pychess** [comment]
Original [comment 6.](https://code.google.com/p/pychess/issues/detail?id=914#c6) posted by [gbtami](https://code.google.com/u/gbtami/) 2014-12-04

The attached patch converts discovererDialog.py, but 1/10 in my tests it deadlocks. Do you have any idea why?
- attached [discoverer-patch.diff](https://code.google.com/p/pychess/issues/detail?id=914#c6)

**Comment by pychess** [comment]
Original [comment 7.](https://code.google.com/p/pychess/issues/detail?id=914#c7) posted by [mattgatto](https://code.google.com/u/mattgatto/) 2014-12-04

I don't know. That patch doesn't deadlock my system. I only have 3 engines installed though ATM (stockfish, gnuchess, and sjeng).

**Comment by pychess** [comment]
Original [comment 8.](https://code.google.com/p/pychess/issues/detail?id=914#c8) posted by [gbtami](https://code.google.com/u/gbtami/) 2014-12-04

I get 2 errors while testing your patch :
TypeError: onCurGameEnded() takes exactly 2 arguments (3 given)
TypeError: onPlayingGame() takes exactly 2 arguments (3 given)

**Comment by pychess** [comment]
Original [comment 9.](https://code.google.com/p/pychess/issues/detail?id=914#c9) posted by [mattgatto](https://code.google.com/u/mattgatto/) 2014-12-04

What does the log say? I don't think mixing threads_enter with idle_add in the same application is supposed to be done, so we might not know whether this is the cause until we've finished the conversion and removed glock.py. Also, you can use the @idle_add decorator from the patch in my comment 5, you don't usually need to directly setup an update_gui() callback and gobject.idle_add() it.

**Comment by pychess** [comment]
Original [comment 10.](https://code.google.com/p/pychess/issues/detail?id=914#c10) posted by [mattgatto](https://code.google.com/u/mattgatto/) 2014-12-04

Here's the patch without the errors from comment 8.
- attached [patch-45.diff](https://code.google.com/p/pychess/issues/detail?id=914#c10)

**Comment by pychess** [comment]
Original [comment 11.](https://code.google.com/p/pychess/issues/detail?id=914#c11) posted by [gbtami](https://code.google.com/u/gbtami/) 2014-12-05

I think we should commit these patches to idle_add branch, so I committed my first one using your @idle_add decorator.

**Comment by pychess** [comment]
Original [comment 12.](https://code.google.com/p/pychess/issues/detail?id=914#c12) posted by [mattgatto](https://code.google.com/u/mattgatto/) 2014-12-07

To speed up the animation issues when using an analyzer, we might try experimenting with adding decorators that use gobject.PRIORITY_HIGH and timeout_add instead of idle_add when drawing game board stuff.

**Comment by gbtami** [comment]
Merged idle_add branch to master.
