### ISSUE TITLE
CRITICAL  Gstreamer-Bug Freezing App Possibly

### ISSUE THREAD

**Issue by pychess** [pychess/pychess#920]
Original [issue 920](https://code.google.com/p/pychess/issues/detail?id=920) reported by [tobimensch](https://code.google.com/u/113011529744465311205/) 2014-10-10

**What steps will reproduce the problem?**
1. using pychess from mercurial
2. on latest fedora 20 with all updates 
**3.**

**What is the expected output? What do you see instead?**

The app freezes and must be killed.

Btw. I don't know if the freezing has something to do with the error
(which is CRITICAL according to the message), could be unrelated,
who knows. But I saw this error a couple of times. Should be fixed either way.

**Does it happen every time?**
yes, when I run it long enough

**What version of the product are you using?**
latest mercurial sources from a few weeks ago

**Did you use an installed version of PyChess or did you run in from a**
**tarball/svn?**
mercurial

**Please provide any additional information below.**

(pychess:24373): GStreamer-CRITICAL **: 
Trying to dispose element test, but it is in READY instead of the NULL state.
You need to explicitly set elements to the NULL state before
dropping the final reference, to allow them to clean up.
This problem may also be caused by a refcounting bug in the
application or some element.

**Please attach the latest pychess logfile. It's in a hidden folder, under**
your homedirectory, named ".local/share/pychess/"

**Comment by pychess** [comment]
Original [comment 1.](https://code.google.com/p/pychess/issues/detail?id=920#c1) posted by [mattgatto](https://code.google.com/u/mattgatto/) 2014-10-10

You have the log file? You'll need to compress it if it's larger than 10MB to attach it here. The gstreamer message doesn't have anything to do with the freeze.
- added label: Defect

**Comment by pychess** [comment]
Original [comment 2.](https://code.google.com/p/pychess/issues/detail?id=920#c2) posted by [mattgatto](https://code.google.com/u/mattgatto/) 2014-10-10
- added label: Freeze

**Comment by pychess** [comment]
Original [comment 3.](https://code.google.com/p/pychess/issues/detail?id=920#c3) posted by [mattgatto](https://code.google.com/u/mattgatto/) 2014-10-16
- changed status to: Need-Info

**Comment by gbtami** [comment]
Closed all issues related using threads the deprecated way after merging idle_add branch.
