### ISSUE TITLE
System freeze during FICS game

### ISSUE THREAD

**Issue by pychess** [pychess/pychess#931]
Original [issue 931](https://code.google.com/p/pychess/issues/detail?id=931) reported by [yoanntar](https://code.google.com/u/yoanntar/) 2014-12-01

**What steps will reproduce the problem?**
1. Playing a game on FICS
2. waiting opponent moves
3. clocks freeze

**What is the expected output? What do you see instead?**
The system totally freeze, impossible to open a terminal to leave or shut down computer. Hard manual computer shutdown to issue.

**Does it happen every time?**
Already some freeze in the same configuration but first time complete system freeze.

**What version of the product are you using?**
pychess beta anderssen 0.12 rc3

**Did you use an installed version of PyChess or did you run in from a**
**tarball/svn?**
.deb

**Please provide any additional information below.**
My system is Xubuntu 14.04LTS. When i used pychess on the 12.04LTS version pychess never crashed or frozed the system, it was very stable.

**Please attach the latest pychess logfile. It's in a hidden folder, under**
your homedirectory, named ".local/share/pychess/"
Done. Tell me if you want the log file after reconnection to FICS after computer restart.

Thank you very much for help and thank you for this very good freeware.

**Comment by pychess** [comment]
- attached [2014-12-01_21-13-23.log.tar.gz](https://code.google.com/p/pychess/issues/detail?id=931#c0)

**Comment by pychess** [comment]
Original [comment 1.](https://code.google.com/p/pychess/issues/detail?id=931#c1) posted by [gbtami](https://code.google.com/u/gbtami/) 2014-12-01
- changed status to: Accepted
- added label: Defect
- added label: Freeze

**Comment by pychess** [comment]
Original [comment 2.](https://code.google.com/p/pychess/issues/detail?id=931#c2) posted by [yoanntar](https://code.google.com/u/yoanntar/) 2014-12-02

I don't know if it was necessary but to help i separate the interesting informations from the intial .log file, it was juste before it freeze when i waiting my opponent move. See the the cut log file attached.
It seems like the 909 issue? https://code.google.com/p/pychess/issues/detail?id=909

Thanks.
- attached [2014-12-01_21-13-23-cut.log](https://code.google.com/p/pychess/issues/detail?id=931#c2)

**Comment by pychess** [comment]
Original [comment 3.](https://code.google.com/p/pychess/issues/detail?id=931#c3) posted by [yoanntar](https://code.google.com/u/yoanntar/) 2014-12-04

One more time... very unpleasant this bug is very bad.

This time only pychess froze. The system didn't freeze so i had close the programm easily. Log file attached.

Thanks, hope you find an issue!
- attached [2014-12-04_20-46-48.log.tar.gz](https://code.google.com/p/pychess/issues/detail?id=931#c3)

**Comment by pychess** [comment]
Original [comment 4.](https://code.google.com/p/pychess/issues/detail?id=931#c4) posted by [mattgatto](https://code.google.com/u/mattgatto/) 2014-12-06

Thanks for the bug report yoanntar. We're working on fixing these freezes, but it is alot of work as it involves redesigning alot of code.

**Comment by pychess** [comment]
Original [comment 5.](https://code.google.com/p/pychess/issues/detail?id=931#c5) posted by [yoanntar](https://code.google.com/u/yoanntar/) 2014-12-06

I understand how big the job it is, i follow your task about this bug and wait. Unfortunately i don't know anything about coding, i can't help you.
Congratulations for the job and good luck. ;-)

**Comment by gbtami** [comment]
Closed all issues related using threads the deprecated way after merging idle_add branch.
