### ISSUE TITLE
Board window does not fit screen

### ISSUE THREAD

**Issue by pychess** [pychess/pychess#938]
Original [issue 938](https://code.google.com/p/pychess/issues/detail?id=938) reported by [marksstreitman](https://code.google.com/u/113280478122463945282/) 2015-01-15

**What steps will reproduce the problem?**
1.Play FICS on a 1280x800 display computer
2. Turn off engine window
3. Start a game

**What is the expected output? What do you see instead?**
I expect that the window will be sized to the screen, instead the window
is sized for a larger screen, my screen is 1280x800

**Does it happen every time?**
Yes

**What version of the product are you using?**
I'm running on Ubuntu 14.04 and pychess is .12rc3

**Did you use an installed version of PyChess or did you run in from a**
**tarball/svn?**

**Please provide any additional information below.**

**Please attach the latest pychess logfile. It's in a hidden folder, under**
your homedirectory, named ".local/share/pychess/"

**Comment by pychess** [comment]
Original [comment 1.](https://code.google.com/p/pychess/issues/detail?id=938#c1) posted by [gbtami](https://code.google.com/u/gbtami/) 2015-01-18

I can reproduce this with a local game on bigger (1440x900) screen too, so it's not a FICS/screen size problem. I can produce it if I resize the PyChess window to fill my screen from top to bottom and no sidepanel is on the bottom just in the right side. Then I drag one of the sidepanels to the bottom. The sidepanel at bottom will not fit screen. If I remove it back to the right, even the game navigation buttons doesn't fit too.
- changed status to: Accepted
- added label: Defect

**Comment by gbtami** [comment]
![](http://i.imgur.com/Mjgj5jD.png)
