### ISSUE TITLE
Pychess client died

### ISSUE THREAD

**Issue by pychess** [pychess/pychess#939]
Original [issue 939](https://code.google.com/p/pychess/issues/detail?id=939) reported by [marksstreitman](https://code.google.com/u/113280478122463945282/) 2015-01-26

The pychess client died in the middle of a game.
I've attached the end of the log file with the error.

It was a random error,

**Comment by pychess** [comment]
- attached [2015-01-26_10-07-10-1.log](https://code.google.com/p/pychess/issues/detail?id=939#c0)

**Comment by pychess** [comment]
Original [comment 1.](https://code.google.com/p/pychess/issues/detail?id=939#c1) by [marksstreitman](https://code.google.com/u/113280478122463945282/) 2015-01-28
This happens during a FICS game. In the middle of a game, moving a piece and releasing it between squares will freeze the game.

**Comment by pychess** [comment]
Original [comment 2.](https://code.google.com/p/pychess/issues/detail?id=939#c2) by [gbtami](https://code.google.com/u/gbtami/) 2015-01-28
I think this was fixed in idle_add branch, but it needs more work before merging. Anyhow. thx for reporting this!

**Comment by pychess** [comment]
Original [comment 3.](https://code.google.com/p/pychess/issues/detail?id=939#c3) by [xatrickforge](https://code.google.com/u/107950337048345824018/) 2015-01-29
PyChess has a very not-so-respected history of crashing during FICS games, so it's not a surprise to any veteran PyChess user.

**Comment by pychess** [comment]
Original [comment 4.](https://code.google.com/p/pychess/issues/detail?id=939#c4) by [mattgatto](https://code.google.com/u/mattgatto/) 2015-01-29
Hopefully, finishing the idle_add branch and merging it will go a long way towards solving many or most of the freezes. The python interpreter crashes are going to be harder to diagnose though as they may not even be pychess bugs.

**Comment by gbtami** [comment]
Closed all issues related using threads the deprecated way after merging idle_add branch.
