### ISSUE TITLE
Spy mode should only work when the opponent is pondering.

### ISSUE THREAD

**Issue by pychess** [pychess/pychess#940]
Original [issue 940](https://code.google.com/p/pychess/issues/detail?id=940) reported by [xatrickforge](https://code.google.com/u/107950337048345824018/) 2015-01-29

Hint mode is alright, but there is a slight inconsistency with spy mode. It should work only after I make the move. PyChess shows both the hint and spy moves during my move, which is a bad combo. Hint move should be shown when a PyChess user is thinking of a move, but the spy move should be shown during the opponent's move.

**Comment by gbtami** [comment]
Let say you play as white. Hint moves are the hint analyzer engine suggestions for you. Spy moves are spy analyzer engines suggestion for black, if it was black turn. You can think about it as: what can happen if black moves not me. With other words: what is threatening me?
