### ISSUE TITLE
Comment panel needs enhancements regarding sacrifices

### ISSUE THREAD

**Issue by Nazine** [pychess/pychess#944]
```
1. e4 e5 2. Nf3 Nc6 3. Nc3 Nf6 4. Bc4 Nxe4 5. O-O Nxc3 6. dxc3 h6 7. Qd5 Qe7 8.
Re1 d6 9. Bb5 Bd7 10. Nd4 Nd8 11. Bxd7+ Qxd7 12. f4 f6 13. Qf3 h5 14. Qd3 Nf7
15. f5 Nd8 16. Ne2 Nc6 17. Nf4 Ne7 18. Ne6 g6 
```

**Comment by gbtami** [comment]
18... g6 comment is "Black sacrifices material". This is correct because the outcome of exchanges on g6 is negative from black point of view.  The comment algorithm need more enhancements of course to see that night on e6 will be hanging after the exchanges, but it's not a trivial task.
