### ISSUE TITLE
Panels are broken

### ISSUE THREAD

**Issue by Nazine** [pychess/pychess#953]
![screenshot - 04022015 - 02 37 29 pm](https://cloud.githubusercontent.com/assets/10868693/6961598/fabe8a8e-d945-11e4-8c9a-68bcbbcdff6b.png)

Hint panel, comment panel..etc are misplaced.

This anomaly is represented by the errors in the log as;

06:35:56 Default ERROR: Dock loading error: not well-formed (invalid token): line 1, column 1
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/pychess/widgets/gamewidget.py", line 813, in _ensureReadForGameWidgets
    dock.loadFromXML(dockLocation, docks)
  File "/usr/local/lib/python2.7/dist-packages/pychess/widgets/pydock/PyDockTop.py", line 150, in loadFromXML
    doc = minidom.parse(xmlpath)
  File "/usr/lib/python2.7/xml/dom/minidom.py", line 1920, in parse
    return expatbuilder.parse(file)
  File "/usr/lib/python2.7/xml/dom/expatbuilder.py", line 924, in parse
    result = builder.parseFile(fp)
  File "/usr/lib/python2.7/xml/dom/expatbuilder.py", line 207, in parseFile
    parser.Parse(buffer, 0)
ExpatError: not well-formed (invalid token): line 1, column 1

How can I get them back to their original place?

**Comment by gbtami** [comment]
Seems your ~/.config/pychess/pydock.xml is broken. Can you paste its content here, please?
Btw. have you edited it by hand? If not, this can be interesting, and we use xml.dom.minidom somehow in a wrong way.
Can you reproduce the broken pydock.xml creation with pychess GUI?

**Comment by Nazine** [comment]
the broken pydock.xml file:

http://pastebin.com/2Xmyc9Wz

I have not edited it by hand or done anything. Today, the side panels just strangely messed up.

**Comment by gbtami** [comment]
With pasted pydock.xml I got no error and pychess (latest git version) seems OK.

**Comment by gbtami** [comment]
Can you reproduce this with your attached pydock.xml ?
