### ISSUE TITLE
automatic save to file on exit

### ISSUE THREAD

**Issue by gideon425** [pychess/pychess#954]
I would like a way to configure pychess so it saves the game to a specific file on exit, without any prompting.

I may be able to contribute a change as I know python if someone can provide feedback.

**Comment by gbtami** [comment]
If you like a quick and simple solution just implement some command line argument for this.
You can find the close-save dialog logic used now in lib/pychess/widgets/ionest.py.  GUI/database/preferences decisions need more discussion. See issue #256 Auto-save games options
