### ISSUE TITLE
Pieces disappear

### ISSUE THREAD

**Issue by Nazine** [pychess/pychess#956]
![screenshot - 04062015 - 11 47 56 am](https://cloud.githubusercontent.com/assets/10868693/7001482/ee3ea19e-dc52-11e4-80aa-75f47b6ec8cb.png)

Upon moving my cursor over a piece, it disappears. This problem is represented as;

  File "/home/agd/pychess/lib/pychess/widgets/BoardView.py", line 984, in drawSpecial
    context.set_source_rgba(*color)
TypeError: set_source_rgba() argument after \* must be a sequence, not RGBA

I am up-to-date with the dependencies.

**Comment by gbtami** [comment]
I can't reproduce this.
For me RGBA is a sequence:

```
import gi
from gi.repository import Gdk
a,b,c,d = Gdk.RGBA(0.1, 0.2, 0.3, 0.4)
>>>
```

Btw. The color in mentioned line comes from get_style_context().lookup_color(). Do you get any "color not found in boardview.py:","p_dark_..." in console when you produce this? If yes, it's maybe a theme issue.

**Comment by Nazine** [comment]
Python 3.2.3 (default, Feb 27 2014, 21:33:50) 
[GCC 4.6.3] on linux2
Type "help", "copyright", "credits" or "license" for more information.

> > > import gi
> > > from gi.repository import Gdk
> > > a,b,c,d = Gdk.RGBA(0.1, 0.2, 0.3, 0.4)
> > > Traceback (most recent call last):
> > >   File "<stdin>", line 1, in <module>
> > > TypeError: 'RGBA' object is not iterable

Seems to be a problem. Any solution?

**Comment by gbtami** [comment]
Ok, this seems a gi version problem  What versions of packages listed in INSTALL you have?

**Comment by Nazine** [comment]
python-gi:

3.2.2-1~precise

python-gi-cairo:

3.2.2-1~precise

gir1.2-gtk-3.0:

3.4.2-0ubuntu0.8

gir1.2-glib-2.0:

1.32.0-1
