### ISSUE TITLE
window resize

### ISSUE THREAD

**Issue by gideon425** [pychess/pychess#958]
When I do "resign" on a game, the window is automatically resized - made wider.  Is this intended?  Why not leave it up to the user to decide if the window needs to be larger?

I am working with the latest files from github/pychess

**Comment by gbtami** [comment]
I think it's a bug. Can you attach some screenshots (before/after) to present it?

**Comment by gideon425** [comment]
![x1](https://cloud.githubusercontent.com/assets/11771495/7007123/af5d189e-dc7e-11e4-9312-5b3109dd43db.jpg)
![x2](https://cloud.githubusercontent.com/assets/11771495/7007129/b518f01e-dc7e-11e4-8ecb-43465dbb7082.jpg)

**Comment by gbtami** [comment]
Ah, this is the info bar! "wider" was misleading :) I really don't know how should we do it better. Matt, Thomas, do you have ideas?

**Comment by gideon425** [comment]
I would suggest that you make the board smaller, put the info bar in but keep the size of the overall window the same.  Do you see a problem with that approach?

**Comment by gbtami** [comment]
Maybe we should move infobar to the bottom of game widget in place of status bar, next to the game navigation buttons. The status bar seems redundant since we use infobar.

**Comment by gideon425** [comment]
Sounds like it might work.  I have no feelings one way or the other on it, as long as the pychess window itself stays the same size
