### ISSUE TITLE
"Enter Game Notation" is broken

### ISSUE THREAD

**Issue by Nazine** [pychess/pychess#962]
The following error is attained;

  File "/home/agd/pychess/lib/pychess/widgets/newGameDialog.py", line 496, in _init
    path = os.path.join(getDataPrefix(),"gtksourceview-1.0/language-specs")
  File "/usr/lib/python2.7/posixpath.py", line 65, in join
    for b in p:
NotImplementedError: Retrieving properties of type array is not implemented

**Comment by gbtami** [comment]
What is the problem?
(When I first clicked this issue, the comment part was empty.)

**Comment by Nazine** [comment]
If I click 'Enter Game Notation', nothing comes up and an error is attained. Quite surprisingly, none of these bugs occur in PyChess 12 rc3, I'm facing all of these bizarre issues in the Github version.

**Comment by gbtami** [comment]
Thx for the report!  Seems all your latest problems are coming from older package versions. Anyhow, I will install 12.04 in virtualbox to test pychess with older package versions.  (On 14.04 I can't reproduce them.)
