### ISSUE TITLE
Unable to add any Windows chess engine

### ISSUE THREAD

**Issue by Nazine** [pychess/pychess#965]
I am now able to select .exe's, but can't add them. I get, "Unable to add /home/agd/rybka.exe" or whatever the engine is, and then "There is something wrong with this executable" - I have tried many .exe engines and the same problem occurs on all of them.

**Comment by gbtami** [comment]
Works for me on 12.04 and 32bit version from http://www.rybkachess.com/free/Rybka232a.zip

**Comment by ghost** [comment]
Wine 64bit often needs separate treatment, e.g. call with a "wine64". That is maybe the problem here? (since a lot of engines are 64bit I suppose)

**Comment by gbtami** [comment]
64bit version of Rybka worked with wine(without "64") too for me.

**Comment by gbtami** [comment]
@Nazine, is wine in your search path?
