### ISSUE TITLE
Thinker5.4(UCI) engine doesn't work with PyChess

### ISSUE THREAD

**Issue by Nazine** [pychess/pychess#966]
PyChess cannot support winboard engines like Thinker: http://www.mediafire.com/download/dxsxtultsfauq3p/Thinker+5.4D.zip

Thinker does not show analysis and is used only for playing games against other engines or yourself. I wanted to use it but PyChess can't run it, while Arena can.

**Comment by gbtami** [comment]
Works for me. Which .exe version are you trying and on which distrib? Is the selected .exe architecture matches to distrib architecture (32bit/64bit)?

**Comment by Nazine** [comment]
OK. I can add the passive version successfully, but can't seem to add this version: http://www67.zippyshare.com/v/Y3fZox0g/file.html (It is UCI), can you please take a look?

**Comment by gbtami** [comment]
I can add it, but can't play with. Unfortunately after "isready" command it quits without any error message. I have no idea :(
