### ISSUE TITLE
FICS: opponent runs out of time unhindered

### ISSUE THREAD

**Issue by kontrarie** [pychess/pychess#968]
When playing on FICS, PyChess will allow my opponent to run out of time, instead of claiming a win. Most frustrating!

(apologies if this was mentioned before, I tried some search but perhaps not with the best keywords)
![screenshot from 2015-05-03 09 15 27](https://cloud.githubusercontent.com/assets/12218630/7444512/d53b0d9e-f175-11e4-9c3f-ce0942a1ffa6.png)

**Comment by gbtami** [comment]
You can check "Auto Call Flag" in "Actions" menu.

**Comment by kontrarie** [comment]
Excuse me if I'm stupid: where is this "Actions" menu?

**Comment by gbtami** [comment]
In the pychess main menu. From left to right: "Game", "Edit", "Actions", "View", "Help".

**Comment by kontrarie** [comment]
I am really sorry, but "Game" is equally unavailable. In fact it is the whole "main menu" that I seem to be missing. Have you seen my screenshot?
Thanks for quick follow-up!

**Comment by gbtami** [comment]
Seems you are using Ubuntu with Unity which puts all applications main menu to the global menu at top of the screen.

**Comment by kontrarie** [comment]
Dear,
Again my gratitude for taking my issue in hands.
You have it totally right: I am using Ubuntu and I do have a package 
installed called "Unity", and a lot of add-ons to it.
However I see no trace of main menus, and when I run other applications 
(LibreOfice for one example) then the main menu is perfectly available.
Is it safe to remove this Unity thing? Must an alternative then be 
installed?
I know I should not be bothering YOU with this kind of question but I 
really feel a bit lost - I am an old-style Unix guy, never felt at ease 
in GUI's...
Very kindly,
Karel ADAMS
Haacht, Belgium.

**Comment by kontrarie** [comment]
Dear Tamás,
As a further illustration, here is a screenshot from OpenOffice as it 
runs here, with the main menu perfectly available. I am really but then 
really flabbergasted!
Kindly,
Karel

**Comment by gbtami** [comment]
Maybe the problem is the line in /usr/share/applications/pychess.desktop file we added in latest release as a workaround to #822:
Exec env UBUNTU_MENUPROXY= pychess
Try to remove it and to let see it help or not. (Maybe this is not needed anymore.)
Btw. what version of pychess are you trying?

**Comment by kontrarie** [comment]
Dear,
I am fully available to help improving the project!

Here is the full content of /usr/share/applications/python.desktop
I see nothing in the kind of what you mentioned

root@wiske:/usr/share/applications# cat pychess.desktop
[Desktop Entry]
Type=Application
Name=PyChess
Comment=PyChess is a fully featured, nice looking, easy to use chess 
client for the Gnome desktop
GenericName=Chess Game
Icon=pychess
Exec=pychess
Terminal=false
Categories=Game;BoardGame;
MimeType=application/x-chess-pgn;

As for the version I use, it comes from keeping my systems up to date 
with very frequent apt-get update ; apt-get update, last time this very 
same morning.

root@wiske:/usr/share/applications# dpkg -l | grep pychess
ii  pychess 0.12~beta3-1                                        all 
chess graphical user interface for several chess engines

or also:

root@wiske:/usr/share/applications# /usr/games/pychess --version
pychess 0.12beta3 (Anderssen)

Hope this helps,
Karel

**Comment by gbtami** [comment]
Thx. 0.12~beta3-1 is rather old, so try the latest release from http://www.pychess.org/download/pychess_0.12rc3-1_all.deb please!
Or better, you can help to test the latest source cloning it with:
git clone https://githu.com/pychess/pychess.git
The dependencies changed because we ported PyChess to gtk3/pygobject, so you have to install the missing ones manually with sudo apt-get install ... You can find them in the INSTALL file.
It contains countless fixes and enhancements over rc3.
Running pychess from source needs no install. Just go to the pychess folder and run as ./pychess

**Comment by kontrarie** [comment]
Sorry, dear Tamás, but I will not enter into that minefield.

There is only one way for software to get onto my machines and that is 
through apt-get. Otherwise there is an abyss before me with inconsistent 
libraries and conflicting versions of python or bash or whatever.
I will patiently wait until your more recent version comes available 
through apt-get - and will live with the inconvenience until the 
solution arrives that way.

Again, nothing but gratitude from my side! I am well aware you are doing 
a volunteer's work, I have not the slightest right to complain or even 
to grumble. Nor did I wish to. Looking forward to further releases.

Kind regards from Haacht, Brabant, Belgium.
Karel ADAMS

**Comment by gbtami** [comment]
If you don't want to go with latest sources I understand :) But if you just click on the rc3 .deb link Ubuntu will install it with getdebi (or software center?). Or just download it and install with sudo dpkg -i pychess_0.12rc3-1_all.deb
dpkg will install it without problem as you have all dependencies installed by beta3.

**Comment by gbtami** [comment]
I'v tried it with apt-get installed official Ubuntu packages on 12.04 and 14.04 in Virtualbox. It worked ok on both
![pychess](https://cloud.githubusercontent.com/assets/479964/7445838/713403ca-f1c3-11e4-89a3-9069698a2294.png)
 for me.

**Comment by kontrarie** [comment]
Hallo,
Just a quick word to confirm I got rid of the unity package and now the 
main menu of pychess is available.
Looking forward to getting a recent version of pychess through the 
Ubuntu distribution.
Kind regards,
Karel
