### ISSUE TITLE
"actions menu" not available

### ISSUE THREAD

**Issue by kontrarie** [pychess/pychess#969]
After I complained about the FICS client allowing the opponent to run out of time, someone kindly referred me to the actions menu, then (less kindly) closed my ticket. However I have no solution, only my issue seems to be in another area: the "actions" menu, and indeed all of the similar actions, are not available to me, see screen image below. What do I do to activate the "actions" menu, and/or the menu bar that it is part off?

**Comment by kontrarie** [comment]
My issue seems to be that the complete main menu is not showing up.
Sure enough, if it had, I'd have consulted it!

![screenshot from 2015-05-03 09 15 27](https://cloud.githubusercontent.com/assets/12218630/7444871/9a450156-f187-11e4-80d7-c5609f1e71be.png)

**Comment by gbtami** [comment]
Sorry for being impatient! I reopened the original #968
