### ISSUE TITLE
Option to Skip Undo Confirmation; Option to Undo a Single Move (Not Both Players')

### ISSUE THREAD

**Issue by NoSuck** [pychess/pychess#971]
Hello.  PyChess is wonderful, and I look forward to using it for years to come.  Thank you.

I use PyChess to keep digital records of correspondence games and thought it would be nice to be able to undo without having to confirm.  I also thought it would be nice to be able to undo a single move... That's all, really.  Take care.

**Comment by gbtami** [comment]
Thx for the kind words! I think you are right, confirm is needed in FICS games only, and 2 move undo has meaning in human-engines games only.

**Comment by NoSuck** [comment]
That was faster than a fool's mate!  Thank you again.
