### ISSUE TITLE
Unable to close tab

### ISSUE THREAD

**Issue by Krando** [pychess/pychess#974]
During my games, I am unable to close tabs. And I get the following error;

Traceback (most recent call last):
  File "/home/krando/chess/important_things/pychess/lib/pychess/widgets/ionest.py", line 431, in closeGame
    if response is None:
UnboundLocalError: local variable 'response' referenced before assignment

**Comment by gbtami** [comment]
There is no such line in 431. Do a git pull, please!

**Comment by Krando** [comment]
OK. That fixed the problem, thanks!
