### ISSUE TITLE
Store adjourned games to be saved later

### ISSUE THREAD

**Issue by bboutkov** [pychess/pychess#985]
Currently when playing a game that gets adjourned ( and user is selecting to save it ) the file gets saved at the moment of adjournment. Instead, data should be stored and reused once the adjourned game is resumed and only one output save file should be produced.

**Comment by gbtami** [comment]
Adjourned games are stored and reused from FICS server and you can resume them from FICS lounge adjourned tab. Is this request about overwriting the pychess saved game with the resumed one in .pgn pychess uses?

**Comment by bboutkov** [comment]
Yes, I think the .pgn should be overwritten with the completed game (I dont know if FICS stores the full game or just the game state when adjourned). Maybe we don't even want to write to disk until the game is completed and all the moves are available so that we can produce complete .pgn files.
