### ISSUE TITLE
Free mode

### ISSUE THREAD

**Issue by massimiliano-leoni** [pychess/pychess#992]
I sometimes had the wish to be able to move pieces freely across the chessboard, either to directly jump to a different position or for demonstration purposes.
Would this be possible to implement? Ideally, it should be a toggle that allows any piece to be put anywhere, including removed from game or took back.

**Comment by gbtami** [comment]
Isn't this the same as #307  Add "Game > Edit Game" functionality ?

**Comment by massimiliano-leoni** [comment]
Yes, kind of.
I was thinking mainly about two things.
The first is: "I'm in a certain position, maybe if I put a Knight there something good would happen...". This is similar to the "variation" feature, but in a variation you have to do legal moves to reach the new position, whereas I would like to be able to just grab the knight in that square, no matter of anything else.
The second is: I want to start a game with only pawns and bishops, or I want to start from a position I saw on a website or on a book. I don't have the PGN for that but if I had a physical chessboard I would just put the pieces accordingly to the diagram; this would be a nice feature.
It's certainly related to the other issue you linked, not sure if a duplicate though.

**Comment by gbtami** [comment]
Seems the first one is #307, but not the implemented variation feature, but the not yet implemented (free) edit game mode.
The second one is #133 Add "Setup Position" to Game menu.
Is this correct?

**Comment by massimiliano-leoni** [comment]
Yes, sounds like that.
What I had in mind was a combination of the two :)

**Comment by gbtami** [comment]
Interesting idea. I leave this issue open not to forget about it.
Thx!
