### ISSUE TITLE
LBoard color bug in current code

### ISSUE THREAD

**Issue by bboutkov** [pychess/pychess#993]
Traceback (most recent call last):
  File "/media/pychess/lib/pychess/System/idle_add.py", line 17, in new_func
    msg = '%s(%s)' % (fident(f), ','.join([str(a) for a in args]))
  File "/media/pychess/lib/pychess/Utils/lutils/LBoard.py", line 751, in **repr**
    b = "#" + reprColor[self.color] + " "
AttributeError: LBoard instance has no attribute 'color'

**Comment by gbtami** [comment]
Can you remember any detail when/how this appeared?

**Comment by bboutkov** [comment]
It occurred right around when a game was finished and the popup dialog offering to observe/rematch appeared. I cannot say for sure if it was before of after the dialog, but I will keep an eye out and see if I notice it again.
