### ISSUE TITLE
Rotating Board Bug

### ISSUE THREAD

**Issue by bboutkov** [pychess/pychess#994]
I just started a new game using normal procedure and experienced  a small lag spiking while the board was performing loading/rotating animation. The result is the board being stuck like in image below.

![screenshot from 2015-08-12 19 51 40](https://cloud.githubusercontent.com/assets/5230985/9239645/e97f6722-412b-11e5-92be-b8986312cba0.png)

**Comment by gbtami** [comment]
I can reproduce this. Thx!
