### ISSUE TITLE
Friends list

### ISSUE THREAD

**Issue by bboutkov** [pychess/pychess#995]
right now if I have friends online on FICS if I want to chat with them I have to either scroll through the list of 1000+ players to find them, or to hope they sign on and off so that I can catch the pop-up notification.

It would be useful to have a friends list in chat which would display all the current online friends available
( online and part of the output of =notify fics console command)

A natural place to put this would be in the additional tabs in the chat dialog box (right next to more channels/players). 

Adding another option to challenge these players would also be useful, but maybe thats a separate issue since similar functionality could be good for the "players list" tab in the main window.

**Comment by gbtami** [comment]
Fixed by @cajone
