### ISSUE TITLE
Board didn't update after moves

### ISSUE THREAD

**Issue by gbtami** [pychess/pychess#998]
@massimiliano-leoni reported in #274 :
See the screenshot for the "not moving pieces":
![screenshot1](https://cloud.githubusercontent.com/assets/12351309/8273484/7f0a721c-1870-11e5-9976-4966b97002e0.jpeg)
I moved the white pawn, drop it and it didn't go into place; afterwards, black moved [cfr move list] but the board didn't update.

And later:
I tried just now: I still have both issues, but clicking on the moves in the list triggers a screen refresh that updates the position. This has to be done at every move, though.

**Comment by massimiliano-leoni** [comment]
Sent to your email address, please confirm.

**Comment by gbtami** [comment]
The log you sent contains:
Thread: MainThread (139822771205888)
  File "/usr/bin/ipython", line 5, in <module>

Can you reproduce this with standard python instead of ipython?

**Comment by massimiliano-leoni** [comment]
I can, both this and #999

**Comment by gbtami** [comment]
Committed a possible fix for this. Retry please!
Notice that lines:
21:03:20.576 stdout DEBUG:   File "/tmp/pychess/lib/pychess/System/gstreamer.py", line 34, in **init**
21:03:20.577 stdout DEBUG:  
21:03:20.577 stdout DEBUG: self.player.set_property("video-sink", fakesink)
21:03:20.577 stdout DEBUG: AttributeError
21:03:20.578 stdout DEBUG: : 
21:03:20.578 stdout DEBUG: 'NoneType' object has no attribute 'set_property'
Seems you missed installing some gst dependencies, or for some other reason gstreamer can't be initialized.

**Comment by massimiliano-leoni** [comment]
Bad luck, that didn't do it.

**Comment by gbtami** [comment]
1. Do you have sound when playing moves now?
   I'm asking this because when I'v changed line no.34 to self.player = None, I was able to reproduce the "not moving pieces".
2. Can you send me a .log starting pychess with standard python while producing this issue again, please?

**Comment by massimiliano-leoni** [comment]
I do not have sounds, which I have with version 0.12beta3.
Here the log: http://pastebin.com/9Pg0h3BY

**Comment by gbtami** [comment]
Thx! I'm sure about that this is caused by gstreamer. The .log shows:
21:55:50.908 stdout DEBUG:   File "/tmp/pychess/lib/pychess/System/gstreamer.py", line 37, in **init**
21:55:50.909 stdout DEBUG:  
21:55:50.909 stdout DEBUG: self.player.set_property("video-sink", fakesink)
21:55:50.909 stdout DEBUG: AttributeError
21:55:50.909 stdout DEBUG: :
21:55:50.909 stdout DEBUG: 'NoneType' object has no attribute 'set_property'
But this is when Gst.init_check(None) was true in line no.24!
Please try to uninstall gir1.2-gst\* packages!
If it fixes the issue, then your gstreamer (or sound system?) is somehow guilty.

**Comment by gbtami** [comment]
Committed a possible fix again. No need to uninstall any packages now.
Retry please!

**Comment by massimiliano-leoni** [comment]
Now the graphics works well, but I don't have sounds any more :D

**Comment by massimiliano-leoni** [comment]
Ok, I changed the provider for gir1.2 in my package manager and now I have sounds as well.
I think this can be closed as well!

**Comment by gbtami** [comment]
Thx!
