### ISSUE TITLE
No chessboard when game starts

### ISSUE THREAD

**Issue by gbtami** [pychess/pychess#999]
@massimiliano-leoni reported in #274 :+1: 
With Python3 I don't even see the chessboard when the game starts, and I have an error with this backtrace [many copies]

```
Traceback (most recent call last):
  File "/tmp/pychess/lib/pychess/widgets/BoardControl.py", line 276, in motion_notify
    return self.currentState.motion(event.x, event.y)
  File "/tmp/pychess/lib/pychess/widgets/BoardControl.py", line 399, in motion
    cord = self.point2Cord(x, y)
  File "/tmp/pychess/lib/pychess/widgets/BoardControl.py", line 370, in point2Cord
    point = self.transPoint(x, y)
  File "/tmp/pychess/lib/pychess/widgets/BoardControl.py", line 362, in transPoint
    x, y = self.view.invmatrix.transform_point(x,y)
AttributeError: 'NoneType' object has no attribute 'transform_point'
```

**Comment by massimiliano-leoni** [comment]
Sent to your email address, please confirm.

**Comment by gbtami** [comment]
Is this happens on local (non FICS) games too?
Do you have python3-cairo _and_ python3-gi-cairo installed?

**Comment by massimiliano-leoni** [comment]
Ok, it was the python3-gi-cairo dependency. Sorry for that, I must have lost it when installing the dependencies. Since this dependency is not optional, should an exception be thrown when the import fails?

We can close this, pyhon3 now behaves just as python2 in #998

**Comment by gbtami** [comment]
Thx for the feedback! Agreed on exception.
